### ISSUE TITLE
bug: Revanced Manager keeps aborting

### ISSUE THREAD

**Issue by Someguy1519** [ReVanced/revanced-manager#1048]
### Type

Error while running the manager

### Bug description

Whenever I try to patch YouTube Music, ReVanced Manager keeps aborting.

### Steps to reproduce

Step 1: Download and Patch YouTube Music 6.11.52 with ReVanced Manager 1.4.3

Step 2: Watch it abort after "Compiling resources"

### Android version

13

### Manager version

1.4.3

### Target package name

com.google.android.apps.youtube.music

### Target package version.

6.11.52

### Installation type

Non-root

### Patches selected.

![Screenshot_20230723_213221](https://github.com/ReVanced/revanced-manager/assets/27980228/0b2ae2a5-d833-4d5d-8954-05f98b832aec)

### Device logs (exported using Manager settings).

```shell
07-23 21:08:38.272 16880 16880 I manager.flutter: Using CollectorTypeCC GC.
07-23 21:08:38.277 16880 16880 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
07-23 21:08:38.280 16880 16880 D ActivityThread: setConscryptValidator
07-23 21:08:38.280 16880 16880 D ActivityThread: setConscryptValidator - put
07-23 21:08:38.289 16880 16880 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 11608; state: ENABLED
07-23 21:08:38.291 16880 16880 W ziparchive: Unable to open '/data/app/~~pk3H621XkrEqjwUwM5vqIQ==/app.revanced.manager.flutter-39jT0wLOo0kAZn_AFoux1Q==/base.dm': No such file or directory
07-23 21:08:38.291 16880 16880 W ziparchive: Unable to open '/data/app/~~pk3H621XkrEqjwUwM5vqIQ==/app.revanced.manager.flutter-39jT0wLOo0kAZn_AFoux1Q==/base.dm': No such file or directory
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Compact header
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~da6eBcxOA0P3JewTlyAxjg==/app.revanced.manager.flutter-tsM7_6kQ9pnrmjRXUtvPIg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5915625528378321944.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~da6eBcxOA0P3JewTlyAxjg==/app.revanced.manager.flutter-tsM7_6kQ9pnrmjRXUtvPIg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5915625528378321944.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEPACI/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Screenshots or video

![Screenshot_20230723_214043](https://github.com/ReVanced/revanced-manager/assets/27980228/adf3ddbe-c15c-416e-9816-52d85c7bc9dd)
[revanced-manager_patcher_20230723213841022400.log.txt](https://github.com/ReVanced/revanced-manager/files/12141796/revanced-manager_patcher_20230723213841022400.log.txt)
[revanced-manager_logcat_20230723212134242465.log.txt](https://github.com/ReVanced/revanced-manager/files/12141797/revanced-manager_logcat_20230723212134242465.log.txt)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-patcher/issues/206
