### ISSUE TITLE
bug: Patching error using latest Revanced, recommended YT, latest YT Music

### ISSUE THREAD

**Issue by DoulosTrieste** [ReVanced/revanced-manager#1051]
### Type

Error at runtime

### Bug description

Upon selecting any number of patches for YT or YT Music, and pressing Patch button, Aborted error appears with references to NoSuchFileException for Kotlin.
YT and YT Music were installed first, by obtaining their APKs (not bundles) from APKMirror.

### Steps to reproduce

Steps to reproduce the behaviour:

1    Select patches for YT or YT Music
2    Click on Patch
3    Wait a couple of seconds
4    See error

### Android version

13

### Manager version

1.4.3

### Target package name

YouTube 
YT Music

### Target package version.

YT: 18.23.35
YTM: 6.11.52

### Installation type

Root

### Patches selected.

1 patch: Copy video URL
(fails with any number of patches)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
07-24 23:48:04.799  2378  2378 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
07-24 23:48:04.897  2378  2378 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
07-24 23:48:04.898  2378  2378 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
07-24 23:48:04.898  2378  2378 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
07-24 23:48:05.234  2378  2378 W manager.flutter: type=1400 audit(0.0:41898): avc: denied { read } for name="max_map_count" dev="proc" ino=4566689 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: QUALCOMM build                   : 324ce1b, If2c1c1f9f5
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: Build Date                       : 07/23/21
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.12
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: Local Branch                     : mybranchebeb7532-538f-f1b0-a55f-1458d0b52ae8
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r135-rel
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: Remote Branch                    : NONE
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
07-24 23:48:05.248  2378  2378 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-24 23:48:05.251  2378  2378 I AdrenoGLES-0: PFP: 0x016ee187, ME: 0x00000000
07-24 23:48:05.414  2495  2495 W sh      : type=1400 audit(0.0:41899): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:05.424  2495  2495 W sh      : type=1400 audit(0.0:41900): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:05.434  2495  2495 W sh      : type=1400 audit(0.0:41901): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:05.444  2495  2495 W sh      : type=1400 audit(0.0:41902): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:05.454  2495  2495 W sh      : type=1400 audit(0.0:41903): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:06.104  2378  2441 I flutter : dynamic_color: Core palette detected.
07-24 23:48:06.157  2378  2443 I Gralloc4: mapper 4.x is not supported
07-24 23:48:06.158  2378  2443 W Gralloc3: mapper 3.x is not supported
07-24 23:48:06.165  2378  2443 W Gralloc4: allocator 4.x is not supported
07-24 23:48:06.166  2378  2443 W Gralloc3: allocator 3.x is not supported
07-24 23:48:06.184  2378  2443 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2246, requested_size=1080x2246 buffer{size=1080x2114 transform=0}
07-24 23:48:06.186  2378  2378 E SurfaceSyncer: Failed to find sync for id=0
07-24 23:48:06.186  2378  2378 E SurfaceSyncer: Failed to find sync for id=1
07-24 23:48:06.194  2378  2435 W Parcel  : Expecting binder but got null!
07-24 23:48:06.424  2495  2495 W sh      : type=1400 audit(0.0:41907): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:06.434  2495  2495 W sh      : type=1400 audit(0.0:41908): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:06.444  2495  2495 W sh      : type=1400 audit(0.0:41909): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:06.454  2495  2495 W sh      : type=1400 audit(0.0:41910): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:06.464  2495  2495 W sh      : type=1400 audit(0.0:41911): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:09.904  2495  2495 W sh      : type=1400 audit(0.0:41915): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:09.914  2495  2495 W sh      : type=1400 audit(0.0:41916): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:09.924  2495  2495 W sh      : type=1400 audit(0.0:41917): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:09.934  2495  2495 W sh      : type=1400 audit(0.0:41918): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:09.944  2495  2495 W sh      : type=1400 audit(0.0:41919): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:48:38.585  2378  2391 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
07-24 23:50:33.441  2378  2378 E SurfaceSyncer: Failed to find sync for id=0
07-24 23:50:33.442  2378  2378 E SurfaceSyncer: Failed to find sync for id=1
07-24 23:50:33.442  2378  2378 E SurfaceSyncer: Failed to find sync for id=2
07-24 23:52:10.744  2495  2495 W sh      : type=1400 audit(0.0:41940): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:52:10.764  2495  2495 W sh      : type=1400 audit(0.0:41941): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:52:10.774  2495  2495 W sh      : type=1400 audit(0.0:41942): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:52:10.784  2495  2495 W sh      : type=1400 audit(0.0:41943): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:52:10.794  2495  2495 W sh      : type=1400 audit(0.0:41944): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-24 23:52:10.804  2495  2495 W sh      : type=1400 audit(0.0:41945): avc: denied { read } for name="/" dev="sde48" ino=2 scontext=u:r:untrusted_app:s0:c121,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborted
Error:
kotlin.io.NoSuchFileException: /data/adb/revanced/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:114)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgments

- [ ] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/975
