### ISSUE TITLE
YouTube patch aborded caused by:  java.lang.ClassNotFoundException: com. android.tools.smali.dexlib2.AccessFlag

### ISSUE THREAD

**Issue by GeekndGamer** [ReVanced/revanced-manager#1064]
### Type

Error while running the manager

### Bug description

Here below the errors messages that I'm getting after the patch is aborded. 

erator.hasNext(SequenceBuilder.kt:129) at app.revanced.manager. flutter.MainA

ctivity.runPatcher$lambda-20 (MainActiv

ity.kt:326)

at app.revanced.manager.flutter.MainA ctivity.$r8$lambda$Rd-

IpIH jmxD15EWmBEFM-jtGsk (Unknown

Source:0)

at app.revanced.manager. flutter.MainA ctivity$

$ExternalSyntheticLambda13.run(Unknown

Source:24)

at

java.lang.Thread.run(Thread.java:1012)

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/tools/

smali/dexlib2/AccessFlags;

at app.revanced.patches.youtube.utils . integrations. fingerprints. RemoteEmbed dedPlayerFingerprint.<init>(RemoteEmbe

ddedPlayerFingerprint.kt:11) at app.revanced.patches.youtube.utils

.integrations.fingerprints.RemoteEmbed dedPlayerFingerprint.<clinit>(Unknown Source:2)

at app.revanced.patches.youtube.utils

. integrations.patch.IntegrationsPatch. <init>(IntegrationsPatch.kt:20)

13 more

Caused by:

java.lang.ClassNotFoundException: com. android.tools.smali.dexlib2.AccessFlag

### Steps to reproduce

Use whatever version of YouTube android trying to patch it with whatever patch on the revanced manager.

### Android version

Android 13

### Manager version

1.4.3

### Target package name

Youtube

### Target package version.

YouTube 18.2.3.35

### Installation type

Non-root

### Patches selected.

I try every
one individually and still the same error message 

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
An error occurred! Aborted
Error:
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:319)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/tools/smali/dexlib2/AccessFlags;
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<init>(RemoteEmbeddedPlayerFingerprint.kt:11)
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<clinit>(Unknown Source:2)
	at app.revanced.patches.youtube.utils.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:20)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
	... 16 more
```

### Screenshots or video

![Screenshot_20230729-220802216](https://github.com/ReVanced/revanced-manager/assets/26921152/2a2f4c5f-bcc5-4224-aa77-bfc70904cb81)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
Update ReVanced Manager
