### ISSUE TITLE
bug: patch hide shorts components

### ISSUE THREAD

**Issue by amod0990** [ReVanced/revanced-manager#1065]
### Type

Error at runtime

### Bug description

build error, patch not applied hide shorts Components 

### Steps to reproduce

Choosed from storage, choosed 18.29.38, choosed needed to me patches, path, then I have some error on patch hide shorts Components

### Android version

11

### Manager version

1.4.3-2

### Target package name

Youtube

### Target package version.

18.29.38

### Installation type

Non-root

### Patches selected.

![Screenshot_20230730-122725](https://github.com/ReVanced/revanced-manager/assets/130699795/c648b65a-57d9-4594-ba85-9382e8848787)

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Custom branding icon MMT
Applied Default video quality
Applied Disable pip notification
Applied Enable minimized playback
Applied Hide mix playlists
Failed to apply Hide shorts components: 'Hide shorts components' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'ComponentParserPatch' but the following error was raised: java.lang.ClassCastException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction12x cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.ReferenceInstruction
	at app.revanced.patches.shared.patch.litho.ComponentParserPatch.execute(ComponentParserPatch.kt:43)
	at app.revanced.patches.shared.patch.litho.ComponentParserPatch.execute(ComponentParserPatch.kt:30)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:337)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:313)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:313)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:42)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:363)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Applied MicroG support
Applied Sponsorblock
Applied Spoof player parameters
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Additional context

`Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Custom branding icon MMT
Applied Default video quality
Applied Disable pip notification
Applied Enable minimized playback
Applied Hide mix playlists
Failed to apply Hide shorts components: 'Hide shorts components' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'ComponentParserPatch' but the following error was raised: java.lang.ClassCastException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction12x cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.ReferenceInstruction
	at app.revanced.patches.shared.patch.litho.ComponentParserPatch.execute(ComponentParserPatch.kt:43)
	at app.revanced.patches.shared.patch.litho.ComponentParserPatch.execute(ComponentParserPatch.kt:30)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:337)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:313)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:313)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:42)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:363)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Applied MicroG support
Applied Sponsorblock
Applied Spoof player parameters
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!`

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Julius8900** [comment]
Please use suggested vetsion.

**Comment by amod0990** [comment]
Is it suggested version hello😄

**Comment by Julius8900** [comment]
You're using Extended sources. Please switch to the ReVanced sources.
