### ISSUE TITLE
Aborts during compiling (manager v1.5.0/patches v2.187.0) 

### ISSUE THREAD

**Issue by Shazzkid** [ReVanced/revanced-manager#1075]
### Type

Error while running the manager

### Bug description

Latest patches/manager (1.5.0/2.187.0) aborts at the end when compiling ANY app, even with recommended app version and recommended patches. 
Clearing manager cache didn't resolve issue. 

### Steps to reproduce

Using manager v1.5.0, and patches v2.187.0, patch YT v18.23.35. 

### Android version

13

### Manager version

1.5.0 

### Target package name

Youtube
Reddit
Infinity

### Target package version.

v18.23.35 

### Installation type

Non-root

### Patches selected.

Client Spoof
Comments
Copy Video Url
Custom Branding
Disable Shorts On Startup
Disable Fullscreen Panels
Disable Player Popup Panels
Disable Zoom Haptics
Enable Debugging
External Downloads
Hdr Auto Brightness
Hide Shorts Components
Hide Ads
Hide Album Cards
Hide Autoplay Buttor
Hide Breaking News Shelf
Hide Captions Button
Hide Cast Button
Hide Crowdfunding Box
Hide Email Address
Hide Floating Microphone Button
Hide Layout Components
Hide Player Buttons
Hide Player Overlay
Hide Video Action Buttons
Hide Watermark
Minimized Playback
Navigation Buttons
old Video Quality Menu
Premium Heading
Remember Video Quality
Remove Player Controls
Background
Return Youtube Dislike
Sponsorblock
Tablet Mini Player
Theme
Vanced MicroG Support
Video Ads

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Client spoof
Applied Comments
Applied Copy video url
Applied Custom branding
Applied Disable Shorts on startup
Applied Disable fullscreen panels
Applied Disable player popup panels
Applied Disable zoom haptics
Applied Enable debugging
Applied External downloads
Applied HDR auto brightness
Applied Hide Shorts components
Applied Hide ads
Applied Hide album cards
Applied Hide autoplay button
Applied Hide breaking news shelf
Applied Hide captions button
Applied Hide cast button
Applied Hide crowdfunding box
Applied Hide email address
Applied Hide floating microphone button
Applied Hide layout components
Applied Hide player buttons
Applied Hide player overlay
Applied Hide video action buttons
Applied Hide watermark
Applied Minimized playback
Applied Navigation buttons
Applied Old video quality menu
Applied Premium heading
Applied Remember video quality
Applied Remove player controls background
Applied Return YouTube Dislike
Applied SponsorBlock
Applied Tablet mini player
Applied Theme
Applied Vanced MicroG support
Applied Video ads
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec: [aapt2, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KVOZSX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KVOZSX/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:126)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:382)
	at app.revanced.patcher.Patcher.save(Patcher.kt:100)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec: [aapt2, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KVOZSX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KVOZSX/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:107)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:122)
	... 6 more
Caused by: java.io.IOException: Cannot run program "aapt2": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at brut.util.OS.exec(OS.java:97)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
```

### Acknowledgments

- [x] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
Looking into it

**Comment by ego-lay-atman-bay** [comment]
I got this same issue when I tried to patch tasker

**Comment by Ushie** [comment]
ReVanced Manager v1.5.0 has been pulled due to upstream issues, please downgrade to v1.4.3 for the time being or wait for the next release within the next few days
