### ISSUE TITLE
bug: aborted patching YouTube music after "compiling resources"

### ISSUE THREAD

**Issue by Gilgul46** [ReVanced/revanced-manager#1078]
### Type

Error while running the manager

### Bug description

It will not repack the apk successfully. 
It doesn't happen with Normal YouTube.
I tried to delete youtube music and install an older version, but it didn't work. I tried to patchclike normal, and even for MicroG, but it keeps aborting

### Steps to reproduce

I'm using Samsung A52 with the latest LineageOS20 version. 

### Android version

13

### Manager version

1.4.3

### Target package name

com.google.android.apps.youtube.music

### Target package version.

6.12.53

### Installation type

Root

### Patches selected.

Background Play (v0.0.0)

• Bypass Certificate Checks (v0.0.0) Codecs Unlock (v0.0.0)

Exclusive Audio Playback (v0.0.0) Hide Get Premium (v0.0.0)

Minimized Playback Music (v0.0.0)

Music Video Ads (v0.0.0)

Predictive Back Gesture (v0.0.0)

Remove Screen Capture Restriction (v0.0.0)

Remove Screenshot Restriction (v0.0.0)

Upgrade Button Remover (v0.0.0)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
08-03 21:25:47.942 29881 29905 E OpenGLRenderer: Unable to match the desired swap behavior.
08-03 21:25:47.970 29881 29881 E SurfaceSyncer: Failed to find sync for id=0
08-03 21:25:47.970 29881 29881 E SurfaceSyncer: Failed to find sync for id=1
08-03 21:25:47.970 29881 29881 E SurfaceSyncer: Failed to find sync for id=2
08-03 21:25:50.286 29881 29895 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
08-03 21:26:04.817 29881 29905 E OpenGLRenderer: Unable to match the desired swap behavior.
08-03 21:26:04.823 29881 29881 E SurfaceSyncer: Failed to find sync for id=0
08-03 21:26:04.824 29881 29881 E SurfaceSyncer: Failed to find sync for id=1
08-03 21:26:04.824 29881 29881 E SurfaceSyncer: Failed to find sync for id=2
08-03 21:26:04.824 29881 29881 E SurfaceSyncer: Failed to find sync for id=3
08-03 21:26:11.249 29881 29895 W manager.flutter: Suspending all threads took: 5.061ms
08-03 21:26:11.258 29881 29895 I manager.flutter: Background young concurrent copying GC freed 4022(521KB) AllocSpace objects, 87(2728KB) LOS objects, 51% free, 3205KB/6600KB, paused 209us,5.369ms total 37.009ms
08-03 21:26:23.458 29926 29926 W sh      : type=1400 audit(0.0:296103): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c113,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-03 21:26:23.478 29926 29926 W sh      : type=1400 audit(0.0:296104): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c113,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-03 21:26:23.486 29926 29926 W sh      : type=1400 audit(0.0:296105): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c113,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-03 21:26:23.494 29926 29926 W sh      : type=1400 audit(0.0:296106): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c113,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-03 21:26:23.506 29926 29926 W sh      : type=1400 audit(0.0:296107): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c113,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-03 21:26:26.610 29881 29895 I manager.flutter: Background concurrent copying GC freed 413634(15MB) AllocSpace objects, 1(68KB) LOS objects, 21% free, 86MB/110MB, paused 44us,28us total 144.687ms
08-03 21:26:46.099 29881 29898 W System  : A resource failed to call close. 
08-03 21:26:47.088 29881 29895 I manager.flutter: Background concurrent copying GC freed 1012503(23MB) AllocSpace objects, 2(132KB) LOS objects, 26% free, 65MB/89MB, paused 51us,28us total 167.926ms
08-03 21:26:48.290 29881 29895 I manager.flutter: Background concurrent copying GC freed 545767(21MB) AllocSpace objects, 5(560KB) LOS objects, 19% free, 97MB/121MB, paused 50us,29us total 184.017ms
08-03 21:26:49.692 29881 29895 I manager.flutter: Background concurrent copying GC freed 858324(32MB) AllocSpace objects, 0(0B) LOS objects, 15% free, 134MB/158MB, paused 47us,28us total 280.445ms
08-03 21:27:05.563 29881 29895 I manager.flutter: Background concurrent copying GC freed 2711680(87MB) AllocSpace objects, 14(10MB) LOS objects, 25% free, 70MB/94MB, paused 61us,31us total 136.665ms
08-03 21:27:05.564 29881 29898 W System  : A resource failed to call close. 
08-03 21:27:05.959 29881 29895 I manager.flutter: Background young concurrent copying GC freed 2833306(55MB) AllocSpace objects, 0(0B) LOS objects, 26% free, 65MB/89MB, paused 287us,31us total 158.896ms
08-03 21:27:06.192 29881 29895 I manager.flutter: Background concurrent copying GC freed 1919607(40MB) AllocSpace objects, 2(132KB) LOS objects, 25% free, 68MB/92MB, paused 51us,30us total 125.047ms
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6262: error: resource android:color/bright_foreground_dark_disabled is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6276: error: resource android:color/btn_default_material_dark is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6277: error: resource android:color/btn_leanback_color is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6278: error: resource android:color/bright_foreground_dark_inverse is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6279: error: resource android:color/btn_default_material_light is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6280: error: resource android:color/btn_leanback_focused is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6281: error: resource android:color/background_floating_device_default_light is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6282: error: resource android:color/background_device_default_light is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6283: error: resource android:color/car_action1 is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6284: error: resource android:color/car_action1_dark is private.
08-03 21:27:16.095 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6285: error: resource android:color/background_holo_light is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6286: error: resource android:color/background_floating_material_light is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6287: error: resource android:color/car_blue_100 is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6288: error: resource android:color/car_blue_200 is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6289: error: resource android:color/bright_foreground_disabled_holo_light is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6290: error: resource android:color/accent_device_default_700 is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6291: error: resource android:color/btn_colored_borderless_text_material is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6292: error: resource android:color/bright_foreground_dark is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6293: error: resource android:color/background_material_dark is private.
08-03 21:27:16.096 29881 32699 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/res/values/styles.xml:6294: error: resource android:color/car_blue_50 is private.
08-03 21:27:25.019 29881 29881 E BLASTBufferQueue: [VRI[MainActivity]#4](f:0,a:1) Applying pending transactions on dtor 1
08-03 21:27:33.249 29881 29905 E OpenGLRenderer: Unable to match the desired swap behavior.
08-03 21:27:33.271 29881 29881 E SurfaceSyncer: Failed to find sync for id=0
08-03 21:27:33.271 29881 29881 E SurfaceSyncer: Failed to find sync for id=1
08-03 21:27:33.271 29881 29881 E SurfaceSyncer: Failed to find sync for id=2
08-03 21:27:33.271 29881 29881 E SurfaceSyncer: Failed to find sync for id=3
08-03 21:27:33.271 29881 29881 E SurfaceSyncer: Failed to find sync for id=4
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Predictive back gesture
Applied Remove screen capture restriction
Applied Remove screenshot restriction
Applied Upgrade button remover
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~gto-9eo889eTsIh8GzyoDg==/app.revanced.manager.flutter-hrCnKG2GKcLGEZ3fomZjgQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61253240, --version-name, 6.12.53, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL989362852027859215.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~gto-9eo889eTsIh8GzyoDg==/app.revanced.manager.flutter-hrCnKG2GKcLGEZ3fomZjgQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61253240, --version-name, 6.12.53, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL989362852027859215.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IWVFGB/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
#988
