### ISSUE TITLE
bug: No applications found

### ISSUE THREAD

**Issue by xiao-mantou** [ReVanced/revanced-manager#1083]
### Type

Error while running the manager

### Bug description

In new version, manager cannot detect installed youtube, not sure other applications.

### Steps to reproduce

1 install youtube
2 open manager - pacher - select an application

### Android version

12

### Manager version

1.6.1 1.6.0

### Target package name

com.google.android.youtube

### Target package version.

18.23.35

### Installation type

Root

### Patches selected.

/

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
08-04 14:28:15.132  8132  8132 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
08-04 14:28:15.133  8132  8132 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
08-04 14:28:15.177  8132  8132 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10260; state: ENABLED
08-04 14:28:15.194  8132  8147 D AppScoutStateMachine: 8132-ScoutStateMachinecreated
08-04 14:28:15.416  8132  8132 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
08-04 14:28:15.416  8132  8132 V GraphicsEnvironment: Updatable production driver is not supported on the device.
--------- beginning of system
08-04 14:28:15.418  8132  8132 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
08-04 14:28:15.419  8132  8132 D OpenGLRenderer: JNI_OnLoad success
08-04 14:28:15.419  8132  8132 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
08-04 14:28:15.420  8132  8132 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-04 14:28:15.420  8132  8132 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-04 14:28:15.514  8132  8132 W manager.flutter: type=1400 audit(0.0:7296): avc: denied { read } for name="max_map_count" dev="proc" ino=1553258 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: QUALCOMM build                   : 16c8186230, I159ae7f0bb
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: Build Date                       : 04/05/21
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.10
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: Local Branch                     : 
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: Remote Branch                    : 
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: Remote Branch                    : 
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: Reconstruct Branch               : 
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
08-04 14:28:15.520  8132  8132 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
08-04 14:28:15.526  8132  8132 I AdrenoGLES-0: PFP: 0x016ee197, ME: 0x00000000
08-04 14:28:15.577  8132  8132 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
08-04 14:28:15.611  8132  8132 D IS_CTS_MODE: false
08-04 14:28:15.611  8132  8132 D MULTI_WINDOW_SWITCH_ENABLED: false
08-04 14:28:15.611  8132  8132 D IS_CTS_MODE: false
08-04 14:28:15.611  8132  8132 D MULTI_WINDOW_SWITCH_ENABLED: false
08-04 14:28:15.614  8132  8132 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-04 14:28:15.636  8132  8132 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-04 14:28:15.636  8132  8132 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
08-04 14:28:15.644  8132  8132 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=475ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=277ms seq=2 late=10ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=189ms seq=3 late=285ms h=android.app.ActivityThread$H w=159)
08-04 14:28:15.750  8132  8132 D SurfaceView: UPDATE null, mIsCastMode = false
08-04 14:28:15.752  8132  8153 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
08-04 14:28:15.778  8176  8176 W sh      : type=1400 audit(0.0:7297): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:15.790  8176  8176 W sh      : type=1400 audit(0.0:7298): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:15.794  8176  8176 W sh      : type=1400 audit(0.0:7299): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:15.798  8176  8176 W sh      : type=1400 audit(0.0:7300): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:15.806  8176  8176 W sh      : type=1400 audit(0.0:7301): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:15.839  8132  8132 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x267c9e2, mIsProjectionMode = false
08-04 14:28:15.840  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:15.840  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:15.841  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:15.851  8132  8158 I flutter : dynamic_color: Core palette detected.
08-04 14:28:15.954  8132  8158 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)
08-04 14:28:15.954  8132  8158 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
08-04 14:28:15.954  8132  8158 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
08-04 14:28:15.954  8132  8158 E flutter : <asynchronous suspension>
08-04 14:28:15.954  8132  8158 E flutter : #2      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:79)
08-04 14:28:15.954  8132  8158 E flutter : <asynchronous suspension>
08-04 14:28:15.954  8132  8158 E flutter : #3      PermissionActions.request (package:permission_handler/permission_handler.dart:52)
08-04 14:28:15.954  8132  8158 E flutter : <asynchronous suspension>
08-04 14:28:15.954  8132  8158 E flutter : #4      NavigationViewModel.requestManageExternalStorage (package:revanced_manager/ui/views/navigation/navigation_viewmodel.dart:56)
08-04 14:28:15.954  8132  8158 E flutter : <asynchronous suspension>
08-04 14:28:15.954  8132  8158 E flutter : 
08-04 14:28:16.093  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 14:28:16.272  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 14:28:18.236  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 14:28:18.274  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 14:28:23.422  8132  8132 I InstallPlugin: handleActivityResult(210,0,null)
08-04 14:28:23.423  8132  8175 D AppScoutStateMachine: 8132-ScoutStateMachinecreated
08-04 14:28:23.466  8132  8132 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x90fe5db, mIsProjectionMode = false
08-04 14:28:23.466  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:23.468  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:23.474  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:23.501  8132  8175 I OpenGLRenderer: Davey! duration=7486ms; Flags=1, FrameTimelineVsyncId=850419, IntendedVsync=12117933168685, Vsync=12117933168685, InputEventId=0, HandleInputStart=12117934485792, AnimationStart=12117934492980, PerformTraversalsStart=12117934496000, DrawStart=12117941285271, FrameDeadline=12117966502017, FrameInterval=12117934429750, FrameStartTime=16666666, SyncQueued=12117946507198, SyncStart=12117946721209, IssueDrawCommandsStart=12117954917198, SwapBuffers=12117981712563, FrameCompleted=12125419791414, DequeueBufferDuration=1245782, QueueBufferDuration=1318854, GpuCompleted=12125419791414, SwapBuffersCompleted=12117984192459, DisplayPresentTime=385511, 
08-04 14:28:23.518  8176  8176 W sh      : type=1400 audit(0.0:7307): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:23.546  8176  8176 W sh      : type=1400 audit(0.0:7308): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:23.558  8176  8176 W sh      : type=1400 audit(0.0:7309): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:23.578  8176  8176 W sh      : type=1400 audit(0.0:7310): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:23.655  8132  8132 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-04 14:28:23.655  8132  8132 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
08-04 14:28:23.674  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 14:28:23.684  8132  8175 I OpenGLRenderer: Davey! duration=5538ms; Flags=0, FrameTimelineVsyncId=850655, IntendedVsync=12120063173252, Vsync=12120096506584, InputEventId=0, HandleInputStart=12120106789697, AnimationStart=12120106798864, PerformTraversalsStart=12120106801625, DrawStart=12120126197666, FrameDeadline=12120096506584, FrameInterval=12120106711937, FrameStartTime=16666666, SyncQueued=12120126610218, SyncStart=12120126748031, IssueDrawCommandsStart=12120126779072, SwapBuffers=12120128400010, FrameCompleted=12125601722039, DequeueBufferDuration=1183698, QueueBufferDuration=884740, GpuCompleted=12125601722039, SwapBuffersCompleted=12120129686104, DisplayPresentTime=385768, 
08-04 14:28:26.791  8132  8132 W Looper  : PerfMonitor longMsg : seq=75 plan=14:28:23.653 late=25ms wall=3109ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
08-04 14:28:26.813  8132  8132 I Choreographer: Skipped 189 frames!  The application may be doing too much work on its main thread.
08-04 14:28:26.883  8132  8132 W Looper  : PerfMonitor doFrame : time=69ms vsyncFrame=0 latency=3155ms procState=-1 historyMsgCount=6 (msgIndex=6 wall=3109ms seq=75 late=25ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
08-04 14:28:26.902  8132  8132 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=8ms latency=2215ms running=0ms  procState=-1  historyMsgCount=9 (msgIndex=1 wall=3109ms seq=75 late=25ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=69ms seq=76 late=3155ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
08-04 14:28:26.911  8132  8132 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=8ms latency=2221ms running=0ms  procState=-1  historyMsgCount=10 (msgIndex=1 wall=3109ms seq=75 late=25ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=69ms seq=76 late=3155ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
08-04 14:28:27.019  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 14:28:27.105  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 14:28:28.406  8176  8176 W sh      : type=1400 audit(0.0:7319): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:28.430  8176  8176 W sh      : type=1400 audit(0.0:7320): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:28.438  8176  8176 W sh      : type=1400 audit(0.0:7321): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:28.458  8176  8176 W sh      : type=1400 audit(0.0:7322): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:28.474  8176  8176 W sh      : type=1400 audit(0.0:7323): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c4,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 14:28:40.771  8132  8146 D AppScoutStateMachine: 8132-ScoutStateMachinecreated
08-04 14:28:40.792  8132  8132 I InstallPlugin: handleActivityResult(212,-1,null)
08-04 14:28:40.885  8132  8132 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x713ebc6, mIsProjectionMode = false
08-04 14:28:40.885  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:40.885  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:40.885  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:40.910  8132  8146 I OpenGLRenderer: Davey! duration=17466ms; Flags=1, FrameTimelineVsyncId=850954, IntendedVsync=12125355103664, Vsync=12125355103664, InputEventId=0, HandleInputStart=12125365770529, AnimationStart=12125365772664, PerformTraversalsStart=12125365773654, DrawStart=12125404612195, FrameDeadline=12125388436996, FrameInterval=12125365749800, FrameStartTime=16666666, SyncQueued=12125406763341, SyncStart=12125406988133, IssueDrawCommandsStart=12125407194591, SwapBuffers=12125417774227, FrameCompleted=12142821776824, DequeueBufferDuration=8747813, QueueBufferDuration=958177, GpuCompleted=12142821776824, SwapBuffersCompleted=12125419491206, DisplayPresentTime=386040, 
08-04 14:28:43.022  8132  8146 D AppScoutStateMachine: 8132-ScoutStateMachinecreated
08-04 14:28:43.038  8132  8132 I InstallPlugin: handleActivityResult(209,-1,null)
08-04 14:28:43.068  8132  8132 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x5a70111, mIsProjectionMode = false
08-04 14:28:43.068  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:43.069  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:43.069  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:28:43.085  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 14:28:43.089  8132  8146 I OpenGLRenderer: Davey! duration=2265ms; Flags=1, FrameTimelineVsyncId=852133, IntendedVsync=12142737117285, Vsync=12142770450617, InputEventId=0, HandleInputStart=12142776351772, AnimationStart=12142776353908, PerformTraversalsStart=12142776355001, DrawStart=12142815468960, FrameDeadline=12142770450617, FrameInterval=12142776328751, FrameStartTime=16666666, SyncQueued=12142816594012, SyncStart=12142816959741, IssueDrawCommandsStart=12142817205001, SwapBuffers=12142820648543, FrameCompleted=12145003281563, DequeueBufferDuration=1478907, QueueBufferDuration=9007552, GpuCompleted=12145003281563, SwapBuffersCompleted=12142830818595, DisplayPresentTime=387040, 
08-04 14:28:50.300  8132  8132 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=12152222, downTime=12152222, deviceId=-1, source=0x101, displayId=0 }
08-04 14:28:50.304  8132  8132 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=12152222, downTime=12152222, deviceId=-1, source=0x101, displayId=0 }
08-04 14:28:51.408  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 14:29:51.773  8132  8147 D AppScoutStateMachine: 8132-ScoutStateMachinecreated
08-04 14:29:51.829  8132  8132 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xeb3d468, mIsProjectionMode = false
08-04 14:29:51.830  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:29:51.830  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:29:51.830  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:29:51.844  8132  8147 I OpenGLRenderer: Davey! duration=71028ms; Flags=1, FrameTimelineVsyncId=852133, IntendedVsync=12142737117285, Vsync=12142770450617, InputEventId=0, HandleInputStart=12142776351772, AnimationStart=12142776353908, PerformTraversalsStart=12142776355001, DrawStart=12142815468960, FrameDeadline=12142787117283, FrameInterval=12142776328751, FrameStartTime=16666666, SyncQueued=12142816594012, SyncStart=12142816959741, IssueDrawCommandsStart=12142817205001, SwapBuffers=12142820648543, FrameCompleted=12213765648933, DequeueBufferDuration=1478907, QueueBufferDuration=9007552, GpuCompleted=12213765648933, SwapBuffersCompleted=12142830818595, DisplayPresentTime=387040, 
08-04 14:29:51.858  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 14:29:56.470  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 14:32:13.920  8132  8175 D AppScoutStateMachine: 8132-ScoutStateMachinecreated
08-04 14:32:13.977  8132  8132 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x9b92798, mIsProjectionMode = false
08-04 14:32:13.978  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:32:13.978  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:32:13.981  8132  8132 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-04 14:32:14.019  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 14:32:14.022  8132  8175 I OpenGLRenderer: Davey! duration=213202ms; Flags=1, FrameTimelineVsyncId=852133, IntendedVsync=12142737117285, Vsync=12142770450617, InputEventId=0, HandleInputStart=12142776351772, AnimationStart=12142776353908, PerformTraversalsStart=12142776355001, DrawStart=12142815468960, FrameDeadline=12142803783949, FrameInterval=12142776328751, FrameStartTime=16666666, SyncQueued=12142816594012, SyncStart=12142816959741, IssueDrawCommandsStart=12142817205001, SwapBuffers=12142820648543, FrameCompleted=12355940379764, DequeueBufferDuration=1478907, QueueBufferDuration=9007552, GpuCompleted=12355940379764, SwapBuffersCompleted=12142830818595, DisplayPresentTime=387040, 
08-04 14:32:14.385  8132  8132 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=12356305, downTime=12356305, deviceId=-1, source=0x101, displayId=0 }
08-04 14:32:14.387  8132  8132 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=12356305, downTime=12356305, deviceId=-1, source=0x101, displayId=0 }
08-04 14:32:21.537  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 14:32:21.918  8132  8132 D DecorView[]: onWindowFocusChanged hasWindowFocus true
```

### Screenshots or video

![IMG_20230804_143453](https://github.com/ReVanced/revanced-manager/assets/25640395/d6fa523c-24e3-4ce7-9081-a66241f5ff59)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
Ways to troubleshoot this issue:

1. Make sure you have an active internet connection.
2. Make sure you are using valid sources.

**Comment by xiao-mantou** [comment]
confirmed, internet connection issue.

**Comment by piknockyou** [comment]
I have found out that disabling AdGuard solved the problem for me.
