### ISSUE TITLE
bug: patcher aborted with all versions of youtube

### ISSUE THREAD

**Issue by nmally** [ReVanced/revanced-manager#1089]
### Type

Error while running the manager

### Bug description

I started getting a playback timeout after about a minute so I tried updating the youtu.be app with the newest revanced. I Cannot patch anything with the new updates and as well as the last known working source/target. No software updates occurred on this android. I followed all search engine related sites to help troubleshoot. 

### Steps to reproduce

Followed the instructions from the official source website github 

### Android version

11

### Manager version

1.6.1
1.6.0
1.4.3

### Target package name

YouTube

### Target package version.

18.29.38
18.23.35
18.16.39

### Installation type

Non-root

### Patches selected.

Default

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
An error occurred! Aborted
Error:
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:295)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:285)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:285)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:39)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:334)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:395)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/tools/smali/dexlib2/AccessFlags;
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<init>(RemoteEmbeddedPlayerFingerprint.kt:11)
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<clinit>(Unknown Source:2)
	at app.revanced.patches.youtube.utils.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:20)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
	... 16 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
Use 1.6.1

**Comment by nmally** [comment]
> Use 1.6.1

I have!

**Comment by nmally** [comment]
Why did you close it? I have tried numerous versions all to which they abort!

**Comment by alrahman** [comment]
I am receiving the same error with v1.6.1. Tried to patch various YouTube versions, including one that I patched and installed previously. This should be reopened

**Comment by Mcofir** [comment]
having the same issue

**Comment by JmKopecky** [comment]
Same issue with 1.7.0
