### ISSUE TITLE
bug: $DexFileNotFoundException when patching YouTube

### ISSUE THREAD

**Issue by 8bit-coder** [ReVanced/revanced-manager#1093]
### Type

Error while running the manager

### Bug description

I found the bug while attempting to patch the suggest 18.23.35 version of YouTube. I tried clearing the manager's data and cache and that didn't help either. I tried uninstalling all the original YouTube updates and installing 18.23.35 fresh and that didn't do anything either.

### Steps to reproduce

1. Download ReVanced Manager
2. Have YouTube 18.23.35 installed
3. Attempt to patch
4. Encounter the error

### Android version

13

### Manager version

1.6.1

### Target package name

YouTube

### Target package version.

18.23.35

### Installation type

Non-root

### Patches selected.

- Client Spoof
- Copy Video URL
- Disable Shorts on Startup
- Disable Auto Captions
- Disable Fullscreen Panels
- Disable Player Popup Panels
- Enable Android Debugging
- Enable Debugging
- Export All Activities
- External Downloads
- Hdr Auto Brightness
- Hide Shorts Components
- Hide Ads
- Hide Album Cards
- Hide Breaking News Shelf
- Hide Crowdfunding Box
- Hide Endscreen Cards
- Hide Filter Bar
- Hide Watermark
- Minimized Playback
- Old Video Quality Menu
- Open Links Externally
- Playback Speed
- Predictive Back Gesture
- Premium Heading
- Remember Video Quality
- Remove Player Controls Backgrund
- Remove Screen Capture Restriction
- Remove Screenshot Restriction
- Return YouTube Dislike
- Seekbar Tapping
- Sponsorblock
- Spoof App Version
- Spoof Wifi Connection
- Vanced MicroG Support
- Video Ads
- Wide Searchbar

### Device logs (exported using Manager settings).

```shell
https://pastebin.com/GeKP9f44 since it's too long for GitHub
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborted
Error:
org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: 99131cf0-33c3-11ee-a2c8-83f86a99f7cf.bin does not exist
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:83)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:61)
	at app.revanced.patcher.util.patch.PatchBundle$Dex.loadPatches(PatchBundle.kt:71)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Additional context

I'm patching on a Samsung Galaxy A32 5G.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by ILoveOpenSourceApplications** [comment]
Can you try patching again but this time excluding the below mentioned patches.
`Enable Android Debugging`
`Export All Activities`
`Remove Screen Capture Restriction`
`Remove Screenshot Restriction`
`Spoof Wifi Connection`
Report back if the issue is still there or not after doing so.

**Comment by michalpl7** [comment]
I had the same issue on Oneplus 11 and Xiaomi Mi11 devices, I used v1.4.3 version without any issue.
Also why 1.6.1 requires access to Internet and ability to download additional content?

**Comment by 8bit-coder** [comment]
I deselected the patches you mentioned and it got farther, but now it gives a different error:

Here's the log:

`Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: Could not generate: values-land/dimens.xml
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:744)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
	at app.revanced.patcher.Patcher.decodeResources(Patcher.kt:220)
	at app.revanced.patcher.Patcher.access$decodeResources(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:351)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:395)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.directory.DirectoryException: file must be a directory: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MZQHJI/cache/res/values-land
	at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
	at brut.directory.FileDirectory.createDirLocal(FileDirectory.java:63)
	at brut.directory.AbstractDirectory.createDir(AbstractDirectory.java:149)
	at brut.directory.AbstractDirectory.getFileOutput(AbstractDirectory.java:122)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:726)
	... 11 more`

**Comment by ILoveOpenSourceApplications** [comment]
> Also why 1.6.1 requires access to Internet and ability to download additional content?

The manager was already doing that in the previous version. But now the user is given the flexibility to chose whether they want to update their patches version or not. That's it.

**Comment by 8bit-coder** [comment]
Bump, any progress?

**Comment by 8bit-coder** [comment]
Has this issue been fixed?

**Comment by Ushie** [comment]
You can try to recreate the issue with the [latest release of ReVanced Manager](https://github.com/revanced/revanced-manager/releases/latest)
