### ISSUE TITLE
bug: Aborted while Repacking

### ISSUE THREAD

**Issue by BrokenLimbs** [ReVanced/revanced-manager#1105]
### Type

Error at runtime

### Bug description

It keeps aborting the Repacking of YouTube unsure of what the issue is. 

### Steps to reproduce

Step 1: Select Patcher
Step 2: Select an Application
Step 3: Select YouTube current: 18.23.35 Recommended: 18.23.35
Step 4: Select Default Patches
Step 5: Patch

### Android version

13 TQ3A.230605.012

### Manager version

1.7.0

### Target package name

com.google.android.youtube

### Target package version.

18.23.35

### Installation type

Root

### Patches selected.

Always Autorepeat
Client Spoof
Comments
Copy Video Url
Custom Branding
Disable Shorts On Startup 
Disable Auto Captions
Disable Fullscreen Panels
Disable Player Popup Panels
Disable Zoom Haptics
Enable Debugging
External Downloads
Hdr Auto Brightness
Hide Shorts Components
Hide Ads
Hide Album Cards
Hide Autoplay Button
Hide Breaking News Shelf
Hide Captions Button
Hide Cast Button
Hide Crowdfunding Box
Hide Email Address
Hide Endscreen Cards
Hide Filter Bar
Hide Floating Microphone Button
Hide Info Cards
Hide Layout Components
Hide Load More Button
Hide Player Buttons
Hide Player Overlay
Hide Seekbar
Hide Timestamp
Hide Video Action Buttons
Hide Watermark
Minimized Playback
Navigation Buttons
Old Video Quality Menu
Open Links Externally
Playback Speed
Player Flyout Menu
Premium Heading
Remember Video Quality
Return Youtube Dislike
Seekbar Tapping 
Sponsorblock
Spoof App Version
Swipe Controls
Tablet Mini Player
Theme
Vanced MicroG Support
Video Ads
Wide Searchbar

### Device logs (exported using Manager settings).

```shell
--------- beginning of main                                                                                          │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=0                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=1                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=2                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=3                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=4                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=5                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=6                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=7                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=8                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=9                                         │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=10                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=11                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=12                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=13                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=14                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=15                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=16                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=17                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=18                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=19                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=20                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=21                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=22                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=23                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=24                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=25                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=26                                        │08-08 05:43:13.888 18379 18379 E SurfaceSyncer: Failed to find sync for id=27                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=0                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=1                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=2                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=3                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=4                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=5                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=6                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=7                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=8                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=9                                         │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=10                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=11                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=12                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=13                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=14                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=15                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=16                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=17                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=18                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=19                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=20                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=21                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=22                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=23                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=24                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=25                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=26                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=27                                        │08-08 05:43:31.684 18379 18379 E SurfaceSyncer: Failed to find sync for id=28                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=0                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=1                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=2                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=3                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=4                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=5                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=6                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=7                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=8                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=9                                         │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=10                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=11                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=12                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=13                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=14                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=15                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=16                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=17                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=18                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=19                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=20                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=21                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=22                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=23                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=24                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=25                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=26                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=27                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=28                                        │08-08 05:43:38.310 18379 18379 E SurfaceSyncer: Failed to find sync for id=29
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Repacking patched apk                                          │
Compiling resources                                            │
An error occurred! Aborted                                     │
Error:                                                         │
brut.androlib.AndrolibException: brut.common.BrutException: cou│
        at brut.androlib.res.AndrolibResources.aapt2Package(And│
        at brut.androlib.res.AndrolibResources.aaptPackage(Andr│
        at app.revanced.patcher.Patcher.save(Patcher.kt:128)   │
        at app.revanced.manager.flutter.MainActivity.runPatcher│
        at app.revanced.manager.flutter.MainActivity.$r8$lambda│
        at app.revanced.manager.flutter.MainActivity$$ExternalS│
        at java.lang.Thread.run(Thread.java:1012)              │
Caused by: brut.common.BrutException: could not exec (exit code│
        at brut.util.OS.exec(OS.java:99)                       │
        at brut.androlib.res.AndrolibResources.aapt2Package(And│
        ... 6 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
Include the foll logs, not half of it.

**Comment by BrokenLimbs** [comment]
```Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Always autorepeat
Applied Client spoof
Applied Comments
Applied Copy video url
Applied Custom branding
Applied Disable Shorts on startup
Applied Disable auto captions
Applied Disable fullscreen panels
Applied Disable player popup panels
Applied Disable zoom haptics
Applied Enable debugging
Applied External downloads
Applied HDR auto brightness
Applied Hide Shorts components
Applied Hide ads
Applied Hide album cards
Applied Hide autoplay button
Applied Hide breaking news shelf
Applied Hide captions button
Applied Hide cast button
Applied Hide crowdfunding box
Applied Hide email address
Applied Hide endscreen cards
Applied Hide filter bar
Applied Hide floating microphone button
Applied Hide info cards
Applied Hide layout components
Applied Hide load more button
Applied Hide player buttons
Applied Hide player overlay
Applied Hide seekbar
Applied Hide timestamp
Applied Hide video action buttons
Applied Hide watermark
Applied Minimized playback
Applied Navigation buttons
Applied Old video quality menu
Applied Open links externally
Applied Playback speed
Applied Player flyout menu
Applied Remember video quality
Applied Return YouTube Dislike
Applied Seekbar tapping
Applied SponsorBlock
Applied Spoof app version
Applied Swipe controls
Applied Tablet mini player
Applied Theme
Applied Vanced MicroG support
Applied Video ads
Applied Wide searchbar
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~fafhOJg9Fl28BQYzUuaG1w==/app.revanced.manager.flutter-fBPVW2a2cUi_foNvPtovjQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1538252224, --version-name, 18.23.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL1791073527982914536.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~fafhOJg9Fl28BQYzUuaG1w==/app.revanced.manager.flutter-fBPVW2a2cUi_foNvPtovjQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1538252224, --version-name, 18.23.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL1791073527982914536.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CEJILN/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more```
