### ISSUE TITLE
bug: Patching YouTube fails 

### ISSUE THREAD

**Issue by skifli** [ReVanced/revanced-manager#1109]
### Type

Error while running the manager

### Bug description

My phone is not rooted. Due to this I tried to patch a YouTube apk I downloaded. The patching fails with an error I believe is unrelated to the origin of the APK.

### Steps to reproduce

1

### Android version

11

### Manager version

1.7.0

### Target package name

com.google.android.youtube

### Target package version.

18.31.36

### Installation type

Non-root

### Patches selected.

The default except hide cast, however it happened previously with all the default patches.

### Device logs (exported using Manager settings).

```shell
None
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Disable zoom haptics
Applied Enable debugging
Failed to apply Hide player overlay: Failed to resolve CreatePlayerOverviewFingerprint
Applied Premium heading
Applied Theme
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~X2H04YauNka76oWL-Z7YGQ==/app.revanced.manager.flutter-VNQSr1ffVg69Oz8E6Bti8w==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1539302848, --version-name, 18.31.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5223466190871212229.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~X2H04YauNka76oWL-Z7YGQ==/app.revanced.manager.flutter-VNQSr1ffVg69Oz8E6Bti8w==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1539302848, --version-name, 18.31.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5223466190871212229.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WGMLKC/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Additional context

This is the link to where I downloaded the APK from: https://m.apkpure.com/youtube/com.google.android.youtube

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
![SmartSelect_20230808_194745](https://github.com/ReVanced/revanced-manager/assets/79272171/aca8bf2a-6575-4f17-962b-d72584f8eabf)

**Comment by skifli** [comment]
> ![SmartSelect_20230808_194745](https://user-images.githubusercontent.com/79272171/259171015-aca8bf2a-6575-4f17-962b-d72584f8eabf.jpg)

Thank you, it works now. However I am unable to use my main account on YouTube. Only my alt is working. Should I create a separate issue, as it may be related to microG?

![image](https://github.com/ReVanced/revanced-manager/assets/121291719/ea182226-d8d3-4b4c-b93e-955d261e05f3)

**Comment by xDARKxDEVILx** [comment]
> > ![SmartSelect_20230808_194745](https://user-images.githubusercontent.com/79272171/259171015-aca8bf2a-6575-4f17-962b-d72584f8eabf.jpg)
> 
> Thank you, it works now. However I am unable to use my main account on YouTube. Only my alt is working. Should I create a separate issue, as it may be related to microG?
> 
> ![image](https://user-images.githubusercontent.com/121291719/259193503-ea182226-d8d3-4b4c-b93e-955d261e05f3.png)

Remove that account in device settings then accounts then login with it again

**Comment by LiphiTC** [comment]
I have the same error with suggested version downloaded from official play store

**Comment by skifli** [comment]
> 

Try making another issue since it worked fine when I did it on the suggested version.
