### ISSUE TITLE
Youtube Music 

### ISSUE THREAD

**Issue by pratikranjan2212** [ReVanced/revanced-manager#1130]
### Type

Error while running the manager

### Bug description

Whenever I try to apply the patch for Youtube Music it always gets aborted. Please fix this. 
![Screenshot_20230812_200225](https://github.com/ReVanced/revanced-manager/assets/128955674/0408567d-f2b0-470e-a532-0b4b416c769b)

### Steps to reproduce

Select any Youtube Music apk
Select the patches provided in the screenshot
Click on Patch

### Android version

13

### Manager version

1.8.0

### Target package name

Youtube Music

### Target package version.

v6.11.52

### Installation type

Non-root

### Patches selected.

![Screenshot_20230812_200707](https://github.com/ReVanced/revanced-manager/assets/128955674/37ee6a9c-d10d-4193-8637-53c841fb5321)

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~lDNrtlV9DErbRHTlxxEIhw==/app.revanced.manager.flutter-SxKTHwfu_8sTmB8CA9Zszw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL826644287560213399.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~lDNrtlV9DErbRHTlxxEIhw==/app.revanced.manager.flutter-SxKTHwfu_8sTmB8CA9Zszw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL826644287560213399.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WQMPBW/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
This is an issue with ReVanced Patcher and will be resolved soon.

**Comment by KobeW50** [comment]
@pratikranjan2212 use v6.10.52 until the issue is resolved.

**Comment by aayushrautela** [comment]
Any progress?
