### ISSUE TITLE
bug: Build aborted, caused by java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by lflad** [ReVanced/revanced-manager#1133]
### Type

Error while running the manager

### Bug description

I'm trying to update revanced as it seems like youtube has again done something to mess with its API. However, when I try to patch the latest working APK (v18.30.37) with the 92 default patches, it fails like this:

```
java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
```

Seems like it's having a problem finding something with dexlib2? I'm not sure what's happening here.

I've tried reinstalling vanced manager and microg, but nothing seems to resolve the issue.

### Steps to reproduce

1. Download the 18.30.37 APK from APKmirror
2. Try to patch it using the default patches as of 14 Aug 2023
3. Wait until it's aborted.

### Android version

5.10.157-android13-4-00001-g914e947b041d-ab10144456
#1 Tue May 16 08:47:42 UTC 2023

### Manager version

1.8.0

### Target package name

com.google.android.youtube_18.30.37-1539173824_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk

### Target package version.

v18.30.37

### Installation type

Non-root

### Patches selected.

Default Patches. There's 92 of them.

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
08-14 13:57:40.312  9596  9596 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.mgoogle.android.gms_0.2.24.220220-220220001_minAPI23(arm64-v8a,armeabi-v7a,x86)(nodpi)_apkmirror.com.apk Binary XML file line #80
--------- beginning of main
08-14 13:57:43.036  9596  9596 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
08-14 13:57:43.036  9596  9596 D FilePickerDelegate: Selected type */*
08-14 13:57:44.654  9596  9596 I InstallPlugin: handleActivityResult(720,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x1 })
08-14 13:57:44.655  9596 11933 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A1000004484
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=0
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=1
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=2
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=3
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=4
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=5
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=6
08-14 13:57:44.672  9596  9596 E SurfaceSyncer: Failed to find sync for id=7
08-14 13:57:45.449  9596 11933 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.30.37-1539173824_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
08-14 13:57:45.449  9596 11933 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@feb5ac7]
08-14 13:57:45.459  9596  9596 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.30.37-1539173824_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
08-14 13:57:45.460  9596  9596 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.30.37-1539173824_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
08-14 13:58:05.343 11972 11972 W sh      : type=1400 audit(0.0:27132): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.363 11972 11972 W sh      : type=1400 audit(0.0:27133): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.379 11972 11972 W sh      : type=1400 audit(0.0:27134): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.399 11972 11972 W sh      : type=1400 audit(0.0:27135): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.419 11972 11972 W sh      : type=1400 audit(0.0:27136): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.435 11972 11972 W sh      : type=1400 audit(0.0:27137): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.451 11972 11972 W sh      : type=1400 audit(0.0:27138): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.471 11972 11972 W sh      : type=1400 audit(0.0:27139): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:05.588  9596  9606 W System  : A resource failed to call close. 
08-14 13:58:05.590  9596  9606 W System  : A resource failed to call close. 
08-14 13:58:08.045  9596  9604 I manager.flutter: Background young concurrent copying GC freed 1467960(46MB) AllocSpace objects, 10(192KB) LOS objects, 0% free, 106MB/106MB, paused 109us,23us total 103.557ms
08-14 13:58:08.967  9596  9604 I manager.flutter: Background concurrent copying GC freed 2596222(89MB) AllocSpace objects, 29(516KB) LOS objects, 48% free, 100MB/196MB, paused 51us,14us total 108.244ms
08-14 13:58:10.343  9596  9604 I manager.flutter: Background concurrent copying GC freed 2318698(86MB) AllocSpace objects, 7(9928KB) LOS objects, 39% free, 148MB/244MB, paused 37us,16us total 184.973ms
08-14 13:58:18.563  9596  9604 I manager.flutter: Background young concurrent copying GC freed 3956903(83MB) AllocSpace objects, 0(0B) LOS objects, 30% free, 170MB/244MB, paused 39us,75us total 101.185ms
08-14 13:58:19.071  9596  9604 I manager.flutter: Background concurrent copying GC freed 7274236(202MB) AllocSpace objects, 9(10MB) LOS objects, 48% free, 100MB/196MB, paused 67us,56us total 252.010ms
08-14 13:58:19.071  9596  9606 W System  : A resource failed to call close. 
08-14 13:58:19.490  9596  9604 I manager.flutter: Background young concurrent copying GC freed 5423811(117MB) AllocSpace objects, 1(28KB) LOS objects, 42% free, 112MB/196MB, paused 49us,28us total 134.591ms
08-14 13:58:19.903  9596  9604 I manager.flutter: Background concurrent copying GC freed 4792207(135MB) AllocSpace objects, 28(712KB) LOS objects, 41% free, 133MB/229MB, paused 97us,16us total 151.355ms
08-14 13:58:21.066  9596  9604 I manager.flutter: Background concurrent copying GC freed 2833116(97MB) AllocSpace objects, 30(480KB) LOS objects, 39% free, 146MB/242MB, paused 43us,13us total 182.339ms
08-14 13:58:22.328  9596  9604 I manager.flutter: Background concurrent copying GC freed 2998601(112MB) AllocSpace objects, 8(9944KB) LOS objects, 33% free, 193MB/289MB, paused 48us,12us total 263.517ms
08-14 13:58:28.016  9596  9604 I manager.flutter: Background concurrent copying GC freed 1876778(100MB) AllocSpace objects, 7(10MB) LOS objects, 33% free, 191MB/287MB, paused 33us,13us total 277.205ms
08-14 13:58:33.556  9596  9604 I manager.flutter: Background concurrent copying GC freed 2721591(107MB) AllocSpace objects, 14(640KB) LOS objects, 32% free, 199MB/295MB, paused 45us,18us total 265.726ms
08-14 13:58:50.398  9596  9596 I InstallPlugin: handleActivityResult(2,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x43 })
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=0
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=1
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=2
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=3
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=4
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=5
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=6
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=7
08-14 13:58:50.428  9596  9596 E SurfaceSyncer: Failed to find sync for id=8
--------- beginning of crash
08-14 13:58:50.441  9596  9596 E AndroidRuntime: FATAL EXCEPTION: main
08-14 13:58:50.441  9596  9596 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 9596
08-14 13:58:50.441  9596  9596 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HSFKUQ/out.apk: open failed: ENOENT (No such file or directory)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:574)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at com.cleveroad.cr_file_saver.utils.FileKt$saveFileInBackground$1$file$1.invokeSuspend(File.kt:71)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at libcore.io.Linux.open(Native Method)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7804)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:560)
08-14 13:58:50.441  9596  9596 E AndroidRuntime: 	... 8 more
08-14 13:58:50.449  9596  9596 I Process : Sending signal. PID: 9596 SIG: 9
08-14 13:58:52.970 14174 14174 I manager.flutter: Using CollectorTypeCC GC.
08-14 13:58:52.972 14174 14174 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
08-14 13:58:52.979 14174 14174 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10362; state: ENABLED
08-14 13:58:52.992 14174 14174 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~c3xx3XVuwJMPlHeEzo9hpw==/app.revanced.manager.flutter-ic8kHfXmbrNMTGuaqBnJIA==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~c3xx3XVuwJMPlHeEzo9hpw==/app.revanced.manager.flutter-ic8kHfXmbrNMTGuaqBnJIA==/lib/arm64:/data/app/~~c3xx3XVuwJMPlHeEzo9hpw==/app.revanced.manager.flutter-ic8kHfXmbrNMTGuaqBnJIA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
08-14 13:58:52.999 14174 14174 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
08-14 13:58:52.999 14174 14174 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
08-14 13:58:53.000 14174 14174 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
08-14 13:58:53.000 14174 14174 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-14 13:58:53.000 14174 14174 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-14 13:58:53.010 14174 14192 D vulkan  : searching for layers in '/data/app/~~c3xx3XVuwJMPlHeEzo9hpw==/app.revanced.manager.flutter-ic8kHfXmbrNMTGuaqBnJIA==/lib/arm64'
08-14 13:58:53.011 14174 14192 D vulkan  : searching for layers in '/data/app/~~c3xx3XVuwJMPlHeEzo9hpw==/app.revanced.manager.flutter-ic8kHfXmbrNMTGuaqBnJIA==/base.apk!/lib/arm64-v8a'
08-14 13:58:53.031 14174 14174 W manager.flutter: type=1400 audit(0.0:27170): avc: denied { read } for name="max_map_count" dev="proc" ino=7455659 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
08-14 13:58:53.041 14174 14174 D libEGL  : loaded /vendor/lib64/egl/libGLES_mali.so
08-14 13:58:53.105 14174 14174 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10362; state: DISABLED
08-14 13:58:53.147 14231 14231 W sh      : type=1400 audit(0.0:27171): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:53.155 14231 14231 W sh      : type=1400 audit(0.0:27172): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:53.159 14231 14231 W sh      : type=1400 audit(0.0:27173): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:53.171 14231 14231 W sh      : type=1400 audit(0.0:27174): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:53.179 14231 14231 W sh      : type=1400 audit(0.0:27175): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:53.187 14231 14231 W sh      : type=1400 audit(0.0:27176): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:53.755 14174 14174 I Choreographer: Skipped 57 frames!  The application may be doing too much work on its main thread.
08-14 13:58:53.819 14174 14206 I flutter : dynamic_color: Core palette detected.
08-14 13:58:53.945 14174 14174 E SurfaceSyncer: Failed to find sync for id=0
08-14 13:58:53.945 14174 14174 E SurfaceSyncer: Failed to find sync for id=1
08-14 13:58:54.431 14573 14573 W sh      : type=1400 audit(0.0:27196): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:54.439 14573 14573 W sh      : type=1400 audit(0.0:27197): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:54.459 14573 14573 W sh      : type=1400 audit(0.0:27198): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:54.475 14573 14573 W sh      : type=1400 audit(0.0:27199): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:58:54.495 14573 14573 W sh      : type=1400 audit(0.0:27200): avc: denied { read } for name="/" dev="dm-10" ino=2 scontext=u:r:untrusted_app:s0:c106,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-14 13:59:22.113 14174 14174 E SurfaceSyncer: Failed to find sync for id=0
08-14 13:59:22.113 14174 14174 E SurfaceSyncer: Failed to find sync for id=1
08-14 13:59:22.113 14174 14174 E SurfaceSyncer: Failed to find sync for id=2
08-14 13:59:22.128 14174 14174 E SurfaceSyncer: Failed to find sync for id=0
08-14 13:59:22.128 14174 14174 E SurfaceSyncer: Failed to find sync for id=1
08-14 13:59:22.128 14174 14174 E SurfaceSyncer: Failed to find sync for id=2
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
An error occurred! Aborted
Error:
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:319)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:395)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/tools/smali/dexlib2/AccessFlags;
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<init>(RemoteEmbeddedPlayerFingerprint.kt:11)
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<clinit>(Unknown Source:2)
	at app.revanced.patches.youtube.utils.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:20)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
	... 16 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
> v18.30.37

not recommended version

**Comment by pnavfrost** [comment]
> > v18.30.37
> 
> not recommended version, reset your custom sources

![Screenshot_20230815-233539~2.png](https://github.com/ReVanced/revanced-manager/assets/82537585/fa85747f-6586-43d2-99ee-6537f0e8cf85)

wait what's the suggested one then?

**Comment by Ushie** [comment]
It's very likely that you have custom sources set to inotia00, please reset them

The suggested version for official ReVanced should be v18.23.35

**Comment by pnavfrost** [comment]
> It's very likely that you have custom sources set to inotia00, please reset them
> 
> The suggested version for official ReVanced should be v18.23.35

That fixed it, but I wonder why it defaults to Inotia's ones on a clean install...

(I kept getting this error and uninstalling-reinstalling both microg and Revanced Manager and it *still* defaulted to Inotia)
