### ISSUE TITLE
bug: Integrations error

### ISSUE THREAD

**Issue by skad22** [ReVanced/revanced-manager#1135]
### Type

Error while running the manager

### Bug description

Every time i try to patch YouTube im prompted with the same error message even though i tried different versions of the apk ,deleted and reinstalled all required programs and delted the cache and logs 

### Steps to reproduce

Simply trying to patch the app with any patch and automatically merging integrations 

### Android version

13

### Manager version

V 1.8.0

### Target package name

Youtube 

### Target package version.

The recommend version v18.23.35

### Installation type

Non-root

### Patches selected.

Mainly the default selection and even when tweaking the selection still the same error

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Failed to apply Always autorepeat: 'Always autorepeat' depends on 'Integrations' but the following error was raised: java.lang.IllegalStateException: Encountered 1 parser syntax errors and 0 lexer syntax errors!
	at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compile(InlineSmaliCompiler.kt:49)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:72)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstruction(InlineSmaliCompiler.kt:84)
	at app.revanced.patcher.extensions.InstructionExtensions.addInstruction(InstructionExtensions.kt:93)
	at app.revanced.patches.shared.integrations.patch.AbstractIntegrationsPatch$IntegrationsFingerprint.invoke(AbstractIntegrationsPatch.kt:47)
	at app.revanced.patches.shared.integrations.patch.AbstractIntegrationsPatch.execute(AbstractIntegrationsPatch.kt:65)
	at app.revanced.patches.shared.integrations.patch.AbstractIntegrationsPatch.execute(AbstractIntegrationsPatch.kt:16)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:395)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Failed to apply Client spoof: 'Client spoof' depends on 'Spoof signature verification' but the following error was raised: 'Spoof signature verification' depends on 'SpoofSignatureVerificationResourcePatch' but the following error was raised: 'SpoofSignatureVerificationResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Comments: 'Comments' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Applied Custom branding
Failed to apply Disable Shorts on startup: 'Disable Shorts on startup' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable auto captions: 'Disable auto captions' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable fullscreen panels: 'Disable fullscreen panels' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable player popup panels: 'Disable player popup panels' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable zoom haptics: 'Disable zoom haptics' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Enable debugging: 'Enable debugging' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply External downloads: 'External downloads' depends on 'ExternalDownloadsResourcePatch' but the following error was raised: 'ExternalDownloadsResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply HDR auto brightness: 'HDR auto brightness' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide Shorts components: 'Hide Shorts components' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide ads: 'Hide ads' depends on 'Hide get premium' but the following error was raised: 'Hide get premium' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide album cards: 'Hide album cards' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide autoplay button: 'Hide autoplay button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide breaking news shelf: 'Hide breaking news shelf' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide captions button: 'Hide captions button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide cast button: 'Hide cast button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide crowdfunding box: 'Hide crowdfunding box' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide email address: 'Hide email address' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide endscreen cards: 'Hide endscreen cards' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide filter bar: 'Hide filter bar' depends on 'HideFilterBarResourcePatch' but the following error was raised: 'HideFilterBarResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide floating microphone button: 'Hide floating microphone button' depends on 'HideFloatingMicrophoneButtonResourcePatch' but the following error was raised: 'HideFloatingMicrophoneButtonResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide info cards: 'Hide info cards' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide layout components: 'Hide layout components' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide load more button: 'Hide load more button' depends on 'HideLoadMoreButtonResourcePatch' but the following error was raised: 'HideLoadMoreButtonResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide player buttons: 'Hide player buttons' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide player overlay: 'Hide player overlay' depends on 'HidePlayerOverlayResourcePatch' but the following error was raised: 'HidePlayerOverlayResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide seekbar: 'Hide seekbar' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide timestamp: 'Hide timestamp' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide video action buttons: 'Hide video action buttons' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide watermark: 'Hide watermark' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Minimized playback: 'Minimized playback' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Navigation buttons: 'Navigation buttons' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Old video quality menu: 'Old video quality menu' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Open links externally: Encountered 1 parser syntax errors and 0 lexer syntax errors!
Failed to apply Playback speed: 'Playback speed' depends on 'Custom playback speed' but the following error was raised: 'Custom playback speed' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Player flyout menu: 'Player flyout menu' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Applied Premium heading
Failed to apply Remember video quality: 'Remember video quality' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Return YouTube Dislike: 'Return YouTube Dislike' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Seekbar tapping: 'Seekbar tapping' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply SponsorBlock: 'SponsorBlock' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Spoof app version: 'Spoof app version' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Swipe controls: 'Swipe controls' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Tablet mini player: 'Tablet mini player' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Theme: 'Theme' depends on 'SeekbarColorBytecodePatch' but the following error was raised: 'SeekbarColorBytecodePatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Vanced MicroG support: 'Vanced MicroG support' depends on 'Hide cast button' but the following error was raised: 'Hide cast button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Video ads: 'Video ads' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Wide searchbar: 'Wide searchbar' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
Check whether you are using a custom source for integrations. Open manager, go to settings, tap on sources and reset the sources to `revanced` if not there already.

**Comment by skad22** [comment]
I didn't mess with the sources and tried to set them to the default sources but didn't work.

**Comment by skad22** [comment]
#

**Comment by TheAabedKhan** [comment]
> I didn't mess with the sources and tried to set them to the default sources but didn't work.

Can you clean install the manager and send a screen recording of patching please?

**Comment by skad22** [comment]
> > I didn't mess with the sources and tried to set them to the default sources but didn't work.
> 
> Can you clean install the manager and send a screen recording of patching please?

I tried that couple of times and had the exact same log as the one i posted even when i change the patches it still gives me the same error.

**Comment by pnavfrost** [comment]
https://github.com/ReVanced/revanced-manager/assets/82537585/c5fffd02-9212-423e-bf65-575411346b83

I don't know if it's the exact same error, but seems pretty much the same so I did a recording of my issue

**Comment by skad22** [comment]
https://github.com/ReVanced/revanced-manager/assets/142052098/f79e0a9b-c052-434a-aa74-cc92369e3efc

**Comment by KobeW50** [comment]
@pnavfrost reset your sources from the Manager settings.

@skad22 start the screen recording from before you select the apk

**Comment by IASAH** [comment]
Same error with me

**Comment by IASAH** [comment]
I just found that latest version of  YT Music that the patch applied to is 6.10.52 nothing newer works

**Comment by skad22** [comment]
A late Update but I was finally able to get it to work.
Changing the phone's language to English UK worked in resolving the issue  and the app is working normally even after sitting the language back to the original.

**Comment by KobeW50** [comment]
@TheAabedKhan should a new issue be made regarding the device language causing errors?

**Comment by TheAabedKhan** [comment]
> should a new issue be made regarding the device language causing errors?

If you can reproduce the bug, then open one.

**Comment by zymawy** [comment]
thank you @skad22 I changed system language from Arabic to English and patches applied successfully
