### ISSUE TITLE
bug: Crash after patching

### ISSUE THREAD

**Issue by OmegaSunkey** [revanced/revanced-manager#114]
### Type

Error at runtime

### Branch

Flutter

### Bug description

Patched app: YouTube
Is version supported by ReVanced: Yes
When does it happen?: At patch

### Steps to reproduce

Step 1. Choose YouTube
Step 2. Wait.

### Relevant log output

```shell
FATAL EXCEPTION: Thread-19
Process: app.revanced.manager.flutter, PID: 5288
java.lang.NullPointerException: Attempt to invoke interface method 'org.w3c.dom.Node org.w3c.dom.NamedNodeMap.getNamedItem(java.lang.String)' on a null object reference
	at app.revanced.patches.youtube.misc.settings.resource.patch.SettingsResourcePatch.close(SettingsResourcePatch.kt:272)
	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:363)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by Sculas** [comment]
Probably due to missing split support. I think you have to use the file picker for now, @Aunali321 please correct me if I'm wrong.

**Comment by OmegaSunkey** [comment]
file picker doesnt work either

**Comment by Aunali321** [comment]
Uninstall youtube updates. Go to apkmirror and download 17.29.34. make sure to download the full apk and not bundle (should be 130mb+). Use that apl inside the manager to patch.

**Comment by Aunali321** [comment]
> Probably due to missing split support. I think you have to use the file picker for now, @Aunali321 please correct me if I'm wrong.
File picker is broken for alot of people. And it doesn't have any useful logs. Can you take a look? #93. Ping me on discord if you want to discuss.
