### ISSUE TITLE
Scrolling with mouse and keyboard is agonizingly slow.

### ISSUE THREAD

**Issue by userse31** [ReVanced/revanced-manager#1140]
### Type

Other

### Bug description

The speed for scrolling is extremely slow when using a mouse. Also, clicking and dragging and the keyboard's arrow key's don't work.

Evidence: https://youtu.be/NfOHp9TQ3c8

### Steps to reproduce

Step 1: Obtain a Stratus C5 Elite with a dead digitizer.

Step 2: Use the phone with otg/bluetooth keyboard and mouse because replacing the screen is beyond reasonable repair (sourcing a new digitizer would cost way more then what the phone is worth).

Step 3: Install ReVanced Manager 1.8.0.

Step 4: Find out that trying to scroll with the keyboard's arrow keys or by clicking and dragging the mouse (to simulate scrolling via touch) doesn't work and that the ONLY way to scroll in the program is to use the mouse's scroll wheel and ascend/descend through the menus at 3 pixels/millennia. (Is this tung-in-cheek enough?)

### Android version

Android 11 (ARMv7 on ARM64 SOC [Yes, I am mad at this]).

### Manager version

1.8.0

### Target package name

Not applicable

### Target package version.

Not applicable

### Installation type

Root

### Patches selected.

Not applicable.

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
08-18 16:37:27.066  4603  4603 E AndroidRuntime: FATAL EXCEPTION: main
08-18 16:37:27.066  4603  4603 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 4603
08-18 16:37:27.066  4603  4603 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4480)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4512)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7703)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5051)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4467)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	... 11 more
08-18 16:37:27.066  4603  4603 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5044)
08-18 16:37:27.066  4603  4603 E AndroidRuntime: 	... 12 more
--------- beginning of main
08-18 16:56:15.115  5599  5599 W logcat  : type=1400 audit(0.0:9919): avc: denied { search } for name="mm" dev="sysfs" ino=4012 scontext=u:r:untrusted_app:s0:c190,c256,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
```

### Screenshots or video

https://youtu.be/NfOHp9TQ3c8

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by validcube** [comment]
Should be fixed in Flutter 3.16
