### ISSUE TITLE
bug: abort yt music

### ISSUE THREAD

**Issue by CrisAhr** [ReVanced/revanced-manager#1144]
### Type

Error while running the manager

### Bug description

always aborts when packing the apk

### Steps to reproduce

the same as always? I mean, download the recommended apk and patch it

### Android version

11

### Manager version

1.8.0

### Target package name

com.google.android.apps.youtube.music

### Target package version.

all versions

### Installation type

Non-root

### Patches selected.

all

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~J7X5QN_gSEABjdcBTl5BKQ==/app.revanced.manager.flutter-cbOZR83EQmgCUNtYpPoBdQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61551240, --version-name, 6.15.51, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL8769772337414271971.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~J7X5QN_gSEABjdcBTl5BKQ==/app.revanced.manager.flutter-cbOZR83EQmgCUNtYpPoBdQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61551240, --version-name, 6.15.51, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL8769772337414271971.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWASDU/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Screenshots or video

![Screenshot_20230820-131327](https://github.com/ReVanced/revanced-manager/assets/81647749/9c2c4345-f74b-4704-88e0-0e9592b15c96)

### Solution

none

### Additional context

none

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
#1130
