### ISSUE TITLE
bug: Revanced Manager crashes when exporting patched apk

### ISSUE THREAD

**Issue by Sam101011** [ReVanced/revanced-manager#1173]
### Type

Error while running the manager

### Bug description

After patching youtube, attempting to export it crashes the manager.

### Steps to reproduce

Open Revanced Manager
Patch the latest recommended youtube apk
Export the patched apk

### Android version

10

### Manager version

1.9.4

### Target package name

com.google.android.youtube

### Target package version.

18.32.39

### Installation type

Non-root

### Patches selected.

![Screenshot_20230828_050338_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/90930406/939dac8f-f07a-4245-a9d0-2f03a9c5c917)
![Screenshot_20230828_050343_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/90930406/504a191a-690d-4e29-b1a5-697b251cd186)

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
08-28 04:30:34.208  2827  2827 E AndroidRuntime: FATAL EXCEPTION: main
08-28 04:30:34.208  2827  2827 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 2827
08-28 04:30:34.208  2827  2827 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VQKDFH/out.apk: open failed: ENOENT (No such file or directory)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at com.cleveroad.cr_file_saver.utils.FileKt$saveFileInBackground$1$file$1.invokeSuspend(File.kt:71)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a75af69, Dispatchers.Main]
08-28 04:30:34.208  2827  2827 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at libcore.io.Linux.open(Native Method)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-28 04:30:34.208  2827  2827 E AndroidRuntime: 	... 10 more
08-28 04:34:45.586  4780  4780 E AndroidRuntime: FATAL EXCEPTION: main
08-28 04:34:45.586  4780  4780 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 4780
08-28 04:34:45.586  4780  4780 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LQOGOP/out.apk: open failed: ENOENT (No such file or directory)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at com.cleveroad.cr_file_saver.utils.FileKt$saveFileInBackground$1$file$1.invokeSuspend(File.kt:71)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f2e061f, Dispatchers.Main]
08-28 04:34:45.586  4780  4780 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at libcore.io.Linux.open(Native Method)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-28 04:34:45.586  4780  4780 E AndroidRuntime: 	... 10 more
08-28 04:39:42.796  5994  5994 E AndroidRuntime: FATAL EXCEPTION: main
08-28 04:39:42.796  5994  5994 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 5994
08-28 04:39:42.796  5994  5994 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYOFPS/out.apk: open failed: ENOENT (No such file or directory)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at com.cleveroad.cr_file_saver.utils.FileKt$saveFileInBackground$1$file$1.invokeSuspend(File.kt:71)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cb3c040, Dispatchers.Main]
08-28 04:39:42.796  5994  5994 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at libcore.io.Linux.open(Native Method)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-28 04:39:42.796  5994  5994 E AndroidRuntime: 	... 10 more
08-28 04:48:22.623  9962  9962 E AndroidRuntime: FATAL EXCEPTION: main
08-28 04:48:22.623  9962  9962 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 9962
08-28 04:48:22.623  9962  9962 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HQWKMA/out.apk: open failed: ENOENT (No such file or directory)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at com.cleveroad.cr_file_saver.utils.FileKt$saveFileInBackground$1$file$1.invokeSuspend(File.kt:71)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bb9413a, Dispatchers.Main]
08-28 04:48:22.623  9962  9962 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at libcore.io.Linux.open(Native Method)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-28 04:48:22.623  9962  9962 E AndroidRuntime: 	... 10 more
--------- beginning of system
08-28 04:59:31.945 13644 13644 D ActivityThread: Attach thread to application
08-28 04:59:31.965 13644 15271 I ActivityThread: Init compatible state: true
08-28 04:59:32.012 13644 13644 I ActivityThread: finishPreloaded preloadStatus 0
08-28 04:59:32.038 13644 13644 V ActivityThread: callActivityOnCreate
08-28 04:59:32.147 13644 13644 D ActivityThread: add activity client record, r= ActivityRecord{b4423bc token=android.os.BinderProxy@c959459 {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} token= android.os.BinderProxy@c959459
08-28 04:59:33.944 13644 13644 W HwApsManager: HwApsManagerService, registerCallback, start !
08-28 04:59:34.766 13644 13644 D HwCustConnectivityManagerImpl: isBlockNetworkRequestByNonAis, INVALID_SUBSCRIPTION_ID
08-28 04:59:51.284 13644 13644 D ActivityThread: Won't deliver top position change in state=5
08-28 04:59:54.903 13644 13644 I ViewRootImpl: dispatchDetachedFromWindow in doDie
08-28 05:02:34.035 13644 13644 D ActivityThread: Won't deliver top position change in state=5
08-28 05:03:08.982 13644 13644 D ActivityThread: Won't deliver top position change in state=5
08-28 05:03:17.248 13644 13644 D ActivityThread: Won't deliver top position change in state=5
08-28 05:03:17.405 13644 13644 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com_arm64-v8a.apk Binary XML file line #41
08-28 05:03:17.410 13644 13644 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com_arm64-v8a.apk Binary XML file line #418
08-28 05:03:17.461 13644 13644 D SystemConfig: Removed unavailable feature android.hardware.sensor.barometer
08-28 05:03:17.461 13644 13644 D SystemConfig: Removed unavailable feature android.hardware.sensor.gyroscope
08-28 05:03:17.464 13644 13644 W SystemConfig: No directory /product_services/etc/sysconfig, skipping
08-28 05:03:17.464 13644 13644 W SystemConfig: No directory /product_services/etc/permissions, skipping
08-28 05:03:17.467 13644 13644 W SystemConfig: No directory /system/emui/base/sysconfig, skipping
08-28 05:03:17.468 13644 13644 W SystemConfig: No directory /system/emui/oversea/sysconfig, skipping
08-28 05:03:17.470 13644 13644 W SystemConfig: No directory /vendor/etc/sysconfig, skipping
08-28 05:03:17.472 13644 13644 D SystemConfig: Removed unavailable feature android.hardware.sensor.barometer
08-28 05:03:17.472 13644 13644 D SystemConfig: Removed unavailable feature android.hardware.sensor.gyroscope
08-28 05:03:17.477 13644 13644 W SystemConfig: No directory /odm/etc/sysconfig, skipping
08-28 05:03:17.478 13644 13644 W SystemConfig: No directory /odm/etc/carrier/28403/sysconfig, skipping
08-28 05:03:17.478 13644 13644 W SystemConfig: No directory /odm/etc/carrier/28403/permissions, skipping
08-28 05:03:17.478 13644 13644 W SystemConfig: No directory /odm/hw_odm/JNY-L21/sysconfig, skipping
08-28 05:03:17.479 13644 13644 W SystemConfig: No directory /odm/hw_odm/JNY-L21/permissions, skipping
08-28 05:03:17.479 13644 13644 W SystemConfig: No directory /hw_product/etc/sysconfig, skipping
08-28 05:03:17.483 13644 13644 W SystemConfig: No directory /hw_product/etc/carrier/28403/sysconfig, skipping
08-28 05:03:17.483 13644 13644 W SystemConfig: No directory /hw_product/etc/carrier/28403/permissions, skipping
08-28 05:03:17.483 13644 13644 W SystemConfig: No directory /hw_product/region_comm/oversea/sysconfig, skipping
08-28 05:03:17.485 13644 13644 W SystemConfig: No directory /hw_product/hw_oem/JNY-L21/sysconfig, skipping
08-28 05:03:17.485 13644 13644 W SystemConfig: No directory /preload/JNY-L21/hw/eu/sysconfig, skipping
08-28 05:03:17.485 13644 13644 W SystemConfig: No directory /cust/global/sysconfig, skipping
08-28 05:03:17.485 13644 13644 W SystemConfig: No directory /cust/global/permissions, skipping
08-28 05:03:17.486 13644 13644 W SystemConfig: No directory /cust/global/carrier/28403/sysconfig, skipping
08-28 05:03:17.487 13644 13644 W SystemConfig: No directory /cust/global/carrier/28403/permissions, skipping
08-28 05:03:17.487 13644 13644 W SystemConfig: No directory /cust/hw/eu/permissions, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /cust/hw/eu/carrier/28403/sysconfig, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /cust/hw/eu/carrier/28403/permissions, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /hw_product/special_cust/JNY-L21/hw/eu/sysconfig, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /hw_product/special_cust/JNY-L21/hw/eu/permissions, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /cust/cotalite/sysconfig, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /cust/cotalite/permissions, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /cust/ecota/sysconfig, skipping
08-28 05:03:17.488 13644 13644 W SystemConfig: No directory /cust/ecota/permissions, skipping
08-28 05:03:22.714 13644 13644 D ActivityThread: Won't deliver top position change in state=4
--------- beginning of main
08-28 05:03:29.050 13644 13644 D DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-28 05:03:29.050 13644 13644 W HwRemoteInputMethodManager: isCasting false because IHwDistributedWindowManager is invalid.
08-28 05:03:46.656 13644 15290 W libEGL  : EGLNativeWindowType 0x795e0d3010 disconnect failed
08-28 05:03:46.662 13644 15283 W libEGL  : EGLNativeWindowType 0x79d100da10 disconnect failed
08-28 05:03:46.676 13644 13644 D DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
08-28 05:03:47.292 13644 15281 D ZrHung.AppEyeUiProbe: not watching, wait.
08-28 05:03:51.627 13644 13644 I AwareBitmapCacher: handleReleaseCache: pid=13644
08-28 05:03:51.627 13644 13644 I AwareBitmapCacher: init lrucache size: 2097152 pid=13644
08-28 05:04:45.172 13644 13644 D ActivityThread: Won't deliver top position change in state=5
08-28 05:04:45.176 13644 15281 D ZrHung.AppEyeUiProbe: restart watching
08-28 05:04:45.196 13644 15283 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-28 05:04:45.198 13644 15290 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-28 05:04:45.209 13644 13644 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
08-28 05:04:45.210 13644 13644 D DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-28 05:04:45.210 13644 13644 W InputMethodManager: startInputReason = 1
08-28 05:04:45.210 13644 13644 W HwRemoteInputMethodManager: isCasting false because IHwDistributedWindowManager is invalid.
08-28 05:04:46.560 13644 13644 V AudioManager: querySoundEffectsEnabled...
08-28 05:04:51.410 13644 13644 V AudioManager: querySoundEffectsEnabled...
```

### Screenshots or video

https://github.com/ReVanced/revanced-manager/assets/90930406/cb8b2820-a334-443a-b728-68c6725cd5bd

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by furopi** [comment]
For me its crashing when i click on save

**Comment by zakiben21** [comment]
Do "clear data" for the revanced manager app, and try patching and exporting again, it worked for me

**Comment by Sam101011** [comment]
It turns out it wasn't a good idea to use revancify's keystore

**Comment by furopi** [comment]
> Do "clear data" for the revanced manager app, and try patching and exporting again, it worked for me

Thank you, Sir! Will try ASAP! 👍

**Comment by Ushie** [comment]
> It turns out it wasn't a good idea to use revancify's keystore

What does that mean? is it failing because of revancify's keystore?

**Comment by Sam101011** [comment]
> > It turns out it wasn't a good idea to use revancify's keystore
> 
> What does that mean? is it failing because of revancify's keystore?

It looks like that's the case. When using revancify's keystore I get the abovementioned error but after clearing the manager's data, it worked just fine.

**Comment by furopi** [comment]
For me it was all about clearing the app data. I use standard keystore.
