### ISSUE TITLE
bug: TikTok fails to patch one patch and then has an OutOfMemory error

### ISSUE THREAD

**Issue by prossberg** [ReVanced/revanced-manager#1179]
### Type

Error while running the manager

### Bug description

I tried to patch a newer TikTok version to update to a newer version than the one I was using. When I tried to patch the APK one of the patches (Hide Ads) failed and then later the compiling of dex files takes very long and then also fails with an OutOfMemory Error.
Note: Merging Integrations takes quite a bit longer than for other apps.

### Steps to reproduce

Step 1: Download the APK
Step 2: Try to patch the APK with default patches

### Android version

13

### Manager version

1.9.4

### Target package name

TikTok (com.zhiliaoapp.musically)

### Target package version.

31.0.1

### Installation type

Non-root

### Patches selected.

Default:
- Disable Login Requirement
- Downloads
- Feed Filter
- Fix Google Login
- Hide Ads
- Playback Speed
- Settings
- Show Seekbar

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
08-30 11:26:15.449 10341 10341 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #5
08-30 11:26:15.451 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #353
08-30 11:26:15.451 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #375
08-30 11:26:15.451 10341 10341 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_NETWORK_STATE in package: com.zhiliaoapp.musically at: Binary XML file line #377
08-30 11:26:15.470 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1645
08-30 11:26:15.470 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1647
08-30 11:26:15.470 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1649
08-30 11:26:15.470 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1651
08-30 11:26:15.470 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1653
08-30 11:26:15.470 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1655
08-30 11:26:15.477 10341 10341 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #2423
08-30 11:27:06.776 10341 10341 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #5
08-30 11:27:06.777 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #353
08-30 11:27:06.777 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #375
08-30 11:27:06.777 10341 10341 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_NETWORK_STATE in package: com.zhiliaoapp.musically at: Binary XML file line #377
08-30 11:27:06.780 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1645
08-30 11:27:06.780 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1647
08-30 11:27:06.780 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1649
08-30 11:27:06.780 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1651
08-30 11:27:06.780 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1653
08-30 11:27:06.780 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1655
08-30 11:27:06.782 10341 10341 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.5-2023100050_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #2423
08-30 11:27:34.205 10341 10341 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #5
08-30 11:27:34.206 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #353
08-30 11:27:34.206 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #375
08-30 11:27:34.206 10341 10341 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_NETWORK_STATE in package: com.zhiliaoapp.musically at: Binary XML file line #377
08-30 11:27:34.210 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1645
08-30 11:27:34.210 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1647
08-30 11:27:34.210 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1649
08-30 11:27:34.210 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1651
08-30 11:27:34.210 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1653
08-30 11:27:34.210 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1655
08-30 11:27:34.212 10341 10341 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #2423
--------- beginning of main
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=0
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=1
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=2
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=3
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=4
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=5
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=6
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=7
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=8
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=9
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=10
08-30 11:33:51.734 10341 10341 E SurfaceSyncer: Failed to find sync for id=11
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=0
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=1
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=2
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=3
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=4
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=5
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=6
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=7
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=8
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=9
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=10
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=11
08-30 11:34:49.180 10341 10341 E SurfaceSyncer: Failed to find sync for id=12
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=0
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=1
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=2
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=3
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=4
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=5
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=6
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=7
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=8
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=9
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=10
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=11
08-30 11:34:49.197 10341 10341 E SurfaceSyncer: Failed to find sync for id=12
08-30 11:34:54.261 10341 10341 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
08-30 11:34:54.262 10341 10341 D FilePickerDelegate: Selected type */*
08-30 11:34:55.976 10341 10341 I InstallPlugin: handleActivityResult(23432,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x1 })
08-30 11:34:55.977 10341 15637 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A1000011804
08-30 11:34:55.987 10341 15637 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk
08-30 11:34:55.987 10341 15637 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@dc69788]
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=0
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=1
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=2
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=3
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=4
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=5
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=6
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=7
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=8
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=9
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=10
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=11
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=12
08-30 11:34:55.997 10341 10341 E SurfaceSyncer: Failed to find sync for id=13
08-30 11:34:56.023 10341 10341 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #5
08-30 11:34:56.024 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #353
08-30 11:34:56.025 10341 10341 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #375
08-30 11:34:56.025 10341 10341 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_NETWORK_STATE in package: com.zhiliaoapp.musically at: Binary XML file line #377
08-30 11:34:56.028 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1645
08-30 11:34:56.028 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1647
08-30 11:34:56.028 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1649
08-30 11:34:56.028 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1651
08-30 11:34:56.028 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1653
08-30 11:34:56.028 10341 10341 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1655
08-30 11:34:56.029 10341 10341 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_31.0.1-2023100010_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #2423
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=0
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=1
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=2
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=3
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=4
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=5
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=6
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=7
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=8
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=9
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=10
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=11
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=12
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=13
08-30 11:36:30.625 10341 10341 E SurfaceSyncer: Failed to find sync for id=14
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=0
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=1
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=2
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=3
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=4
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=5
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=6
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=7
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=8
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=9
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=10
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=11
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=12
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=13
08-30 11:36:30.634 10341 10341 E SurfaceSyncer: Failed to find sync for id=14
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Disable login requirement succeeded
Downloads succeeded
Feed filter succeeded
Fix google login succeeded
Hide ads failed: app.revanced.patcher.patch.PatchException
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:153)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:214)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:213)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException
	at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:33)
	at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:18)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	... 18 more
Playback speed succeeded
Settings succeeded
Show seekbar succeeded
Compiling modified dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 4957680 free bytes and 4841KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.google.common.collect.ImmutableList.listIterator(ImmutableList.java:373)
	at com.google.common.collect.ImmutableList.listIterator(ImmutableList.java:363)
	at com.google.common.collect.ImmutableList.iterator(ImmutableList.java:358)
	at com.google.common.collect.ImmutableList.iterator(ImmutableList.java:58)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeAnnotations(DexWriter.java:908)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:411)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:158)
	at lanchon.multidexlib2.DexIO.access$000(DexIO.java:38)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:99)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Additional context

I have encountered TikTok errors before which is why I stayed on version 29.9.4 of the app so far.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by cameronmgj** [comment]
I've experienced this bug too and came to see if anyone else had run into it. I am on android 12. i have attempted many different apks from different sources, in different formats (dpi, architecture, etc.), and different tiktok releases. None work. I have tried to identify the patch causing the bug by only adding one patch at a time, but this still gave the same result. The apks were able to install directly without patching, but revanced manager always said outofmemory when attempting any number of patches.

**Comment by alphapuggle** [comment]
Having the same issue. Trying to patch 29.9.3 which I had patched previously yields the same results. This is on a Pixel 7 Pro with 12GB of RAM, it should not be running out of memory in normal circumstances. It does this even on a fresh boot. Something is definitely bugged.

**Comment by cameronmgj** [comment]
yeah, i forgot to mention i ran into this on the mi 10 lite 5G (has 6+2gb of memory). i tried multiple tiktok versions from releases 29, 30, and 31.

**Comment by LegendSound** [comment]
Maybe it is because Tiktok is over 256 Mb and since few ReVanced Patches update, even with older and less heavy versions, we can't patch
