### ISSUE TITLE
bug: Entering client ID doesn't work

### ISSUE THREAD

**Issue by leskal** [ReVanced/revanced-manager#1185]
After Pull request ReVanced/revanced-manager-compose#80 the patch "Spoof client" for Infinity for reddit doesn't work. The patch itself seems to work due to the fact that with the flutter app and with CLI it works as expected.

[Expected](https://github.com/ReVanced/revanced-manager-compose/assets/11486824/c2220ac6-9ccd-4fcd-8e72-6bea72efb1c4)

[Result](https://github.com/ReVanced/revanced-manager-compose/assets/11486824/020058b2-d2e0-4a2c-90d9-4d01f82975b0)

Edit: The same problem occurs with the Sync for Reddit

**Comment by Axelen123** [comment]
Leaving this open if anyone is able to replicate the issue. I was unable to replicate it with a somewhat recent build

**Comment by BabyOilJohnson** [comment]
I can't patch infinity, it failed.
<details><summary>Details</summary>
<p>

```
- Device Info
ReVanced Manager: 1.14.0
Build: release
Model: SM-A305F
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: ml.docilealligator.infinityforreddit v6.1.1
Patches version: v2.195.0
Patches: Spoof client [OAuth client ID: null]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Spoof client failed: app.revanced.patcher.patch.PatchException: 'Spoof client' depends on 'SpoofClientPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve GetHttpBasicAuthHeaderFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:21)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute$executePatch(AbstractSpoofClientPatch.kt:34)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute(AbstractSpoofClientPatch.kt:36)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute(AbstractSpoofClientPatch.kt:10)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:155)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:201)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:286)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$30(MainActivity.kt:285)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$nWp6SJoHVIOkEmiKbEEka4nn7Ag(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:160)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:201)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:286)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$30(MainActivity.kt:285)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$nWp6SJoHVIOkEmiKbEEka4nn7Ag(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Signing APK
Patched
```

</p>
</details>
