### ISSUE TITLE
bug: "No applications found" in "select an application" screen.

### ISSUE THREAD

**Issue by bagarwa** [ReVanced/revanced-manager#1221]
### Type

Error while running the manager

### Bug description

The Revanced Manager cannot detect any of the installed apps that have supported patches; including YT, YTM, Reddit, Trakt etc. it keeps saying "No applications found".

### Steps to reproduce

- Launch Revanced Manager
- Switch to Patcher tab
- Tap "Select an application".

### Android version

Android 14 Beta 5.1

### Manager version

1.9.4

### Target package name

- com.google.android.youtube
- com.google.android.apps.youtube.music
- com.reddit.frontpage

etc.

### Target package version.

NA. Apps don't show up in patcher screen.

### Installation type

Root

### Patches selected.

NA. Apps don't show up in patcher screen.
Before this, when apps were loading in patcher screen, I used to have "recommended" patches selected.

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: Error registering plugin root, com.gokul.root.RootPlugin
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: java.lang.IllegalStateException: The main shell was already created
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.internal.MainShell.setBuilder(MainShell.java:98)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.Shell.setDefaultBuilder(Shell.java:144)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at com.gokul.root.RootPlugin.onAttachedToEngine(RootPlugin.java:26)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:146)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:99)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1321)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at app.revanced.manager.flutter.MainActivity.configureFlutterEngine(MainActivity.kt:35)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:214)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:643)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8595)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8573)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.os.Looper.loopOnce(Looper.java:205)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.os.Looper.loop(Looper.java:294)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
08-30 22:25:32.794 16171 16171 E GeneratedPluginRegistrant: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
08-30 22:25:32.821 16264 16264 W sh      : type=1400 audit(0.0:38525): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:32.829 16264 16264 W sh      : type=1400 audit(0.0:38526): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:32.837 16264 16264 W sh      : type=1400 audit(0.0:38527): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:32.841 16264 16264 W sh      : type=1400 audit(0.0:38528): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:32.849 16264 16264 W sh      : type=1400 audit(0.0:38529): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:32.881 16171 17154 I flutter : dynamic_color: Core palette detected.
08-30 22:25:32.905 16171 17160 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#3](f:0,a:0) rejecting buffer:active_size=1440x3120, requested_size=1440x3120 buffer{size=1440x3049 transform=0}
08-30 22:25:33.997 16264 16264 W sh      : type=1400 audit(0.0:38533): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:34.025 16264 16264 W sh      : type=1400 audit(0.0:38534): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:34.037 16264 16264 W sh      : type=1400 audit(0.0:38535): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:34.045 16264 16264 W sh      : type=1400 audit(0.0:38536): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:25:34.053 16264 16264 W sh      : type=1400 audit(0.0:38537): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:26:12.514 16171 16171 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10497; state: ENABLED
08-30 22:26:34.325 16171 17154 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Deletion failed, path = '/data/local/tmp/revanced-manager' (OS Error: Permission denied, errno = 13)
08-30 22:26:34.325 16171 17154 E flutter : #0      _checkForErrorResponse (dart:io/common.dart:55)
08-30 22:26:34.325 16171 17154 E flutter : #1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185)
08-30 22:26:34.325 16171 17154 E flutter : <asynchronous suspension>
08-30 22:26:34.325 16171 17154 E flutter : #2      ManagerAPI.deleteTempFolder (package:revanced_manager/services/manager_api.dart:235)
08-30 22:26:34.325 16171 17154 E flutter : <asynchronous suspension>
08-30 22:26:34.325 16171 17154 E flutter : 
08-30 22:27:10.205 16264 16264 W sh      : type=1400 audit(0.0:38553): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:10.225 16264 16264 W sh      : type=1400 audit(0.0:38554): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:10.253 16264 16264 W sh      : type=1400 audit(0.0:38555): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:10.273 16264 16264 W sh      : type=1400 audit(0.0:38556): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:10.297 16264 16264 W sh      : type=1400 audit(0.0:38557): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:10.305 16264 16264 W sh      : type=1400 audit(0.0:38558): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:19.896 16171 16171 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Activity$$ExternalSyntheticLambda0@19b61ee
08-30 22:27:20.130 16171 17162 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
08-30 22:27:20.185 16171 16171 I Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
08-30 22:27:31.312 17681 17681 I manager.flutter: Using CollectorTypeCC GC.
08-30 22:27:31.315 17681 17681 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
08-30 22:27:31.343 17681 17681 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10497; state: ENABLED
08-30 22:27:31.343 17681 17681 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10497; state: DISABLED
08-30 22:27:31.358 17681 17681 D nativeloader: Configuring clns-4 for other apk /data/app/~~LmEI_JV2o6ZFNIjj6oojeQ==/app.revanced.manager.flutter-MSnRE_-Rjk_bE0DiF9n7ag==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~LmEI_JV2o6ZFNIjj6oojeQ==/app.revanced.manager.flutter-MSnRE_-Rjk_bE0DiF9n7ag==/lib/arm64:/data/app/~~LmEI_JV2o6ZFNIjj6oojeQ==/app.revanced.manager.flutter-MSnRE_-Rjk_bE0DiF9n7ag==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
08-30 22:27:31.366 17681 17681 V GraphicsEnvironment: Currently set values for:
08-30 22:27:31.366 17681 17681 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
08-30 22:27:31.366 17681 17681 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
08-30 22:27:31.366 17681 17681 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
08-30 22:27:31.366 17681 17681 V GraphicsEnvironment: app.revanced.manager.flutter is not listed in per-application setting
08-30 22:27:31.366 17681 17681 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
08-30 22:27:31.383 17681 17732 D vulkan  : searching for layers in '/data/app/~~LmEI_JV2o6ZFNIjj6oojeQ==/app.revanced.manager.flutter-MSnRE_-Rjk_bE0DiF9n7ag==/lib/arm64'
08-30 22:27:31.383 17681 17732 D vulkan  : searching for layers in '/data/app/~~LmEI_JV2o6ZFNIjj6oojeQ==/app.revanced.manager.flutter-MSnRE_-Rjk_bE0DiF9n7ag==/base.apk!/lib/arm64-v8a'
08-30 22:27:31.401 17681 17681 W manager.flutter: type=1400 audit(0.0:38569): avc:  denied  { read } for  name="max_map_count" dev="proc" ino=2233807 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
08-30 22:27:31.410 17681 17681 D libEGL  : loaded /vendor/lib64/egl/libGLES_mali.so
08-30 22:27:31.475 17681 17681 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10497; state: DISABLED
08-30 22:27:31.513 17788 17788 W sh      : type=1400 audit(0.0:38570): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:31.517 17788 17788 W sh      : type=1400 audit(0.0:38571): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:31.525 17788 17788 W sh      : type=1400 audit(0.0:38572): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:31.533 17788 17788 W sh      : type=1400 audit(0.0:38573): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:31.571 17681 17754 I flutter : dynamic_color: Core palette detected.
08-30 22:27:31.648 17681 17755 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1440x3120, requested_size=1440x3120 buffer{size=1440x3049 transform=0}
08-30 22:27:32.521 17788 17788 W sh      : type=1400 audit(0.0:38578): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:32.545 17788 17788 W sh      : type=1400 audit(0.0:38579): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:32.557 17788 17788 W sh      : type=1400 audit(0.0:38580): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:32.569 17788 17788 W sh      : type=1400 audit(0.0:38581): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:32.589 17788 17788 W sh      : type=1400 audit(0.0:38582): avc:  denied  { read } for  name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app_32:s0:c241,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-30 22:27:36.975 17681 17681 I ImeTracker: app.revanced.manager.flutter:db9277a8: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:36.980 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F....ID 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:37.043 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:37.197 17681 17681 I ImeTracker: app.revanced.manager.flutter:db9277a8: onShown
08-30 22:27:38.198 17681 17681 I ImeTracker: app.revanced.manager.flutter:471c4c32: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:38.198 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:38.203 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:38.204 17681 17681 I ImeTracker: app.revanced.manager.flutter:471c4c32: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:38.576 17681 17681 I ImeTracker: app.revanced.manager.flutter:dfaa6a64: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:38.577 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:38.587 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:38.587 17681 17681 I ImeTracker: app.revanced.manager.flutter:dfaa6a64: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:38.825 17681 17681 I ImeTracker: app.revanced.manager.flutter:4d32d14: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:38.825 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:38.831 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:38.831 17681 17681 I ImeTracker: app.revanced.manager.flutter:4d32d14: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:40.078 17681 17681 I ImeTracker: app.revanced.manager.flutter:f6598fc3: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:40.079 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:40.095 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:40.095 17681 17681 I ImeTracker: app.revanced.manager.flutter:f6598fc3: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:40.164 17681 17681 I ImeTracker: app.revanced.manager.flutter:8aa0468f: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:40.164 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:40.168 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:40.169 17681 17681 I ImeTracker: app.revanced.manager.flutter:8aa0468f: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:41.542 17681 17681 I ImeTracker: app.revanced.manager.flutter:9f4b5825: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:41.542 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:41.548 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:41.549 17681 17681 I ImeTracker: app.revanced.manager.flutter:9f4b5825: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:41.866 17681 17681 I ImeTracker: app.revanced.manager.flutter:98db06ba: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:41.867 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:41.873 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:41.873 17681 17681 I ImeTracker: app.revanced.manager.flutter:98db06ba: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:42.175 17681 17681 I ImeTracker: app.revanced.manager.flutter:1b446768: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:42.176 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:42.190 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:42.190 17681 17681 I ImeTracker: app.revanced.manager.flutter:1b446768: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:42.491 17681 17681 I ImeTracker: app.revanced.manager.flutter:1e4d67d2: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
08-30 22:27:42.492 17681 17681 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{6390deb VFE...... .F...... 0,0-1440,3120 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
08-30 22:27:42.496 17681 17681 D InsetsController: show(ime(), fromIme=true)
08-30 22:27:42.496 17681 17681 I ImeTracker: app.revanced.manager.flutter:1e4d67d2: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-30 22:27:43.038 17681 17681 I ImeTracker: app.revanced.manager.flutter:c5e91b40: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
08-30 22:27:43.061 17681 17681 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@28770690 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@48f2760
08-30 22:27:43.206 17681 17681 I ImeTracker: app.revanced.manager.flutter:97bdc2f7: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
08-30 22:27:43.207 17681 17681 I ImeTracker: app.revanced.manager.flutter:c5e91b40: onHidden
```

### Screenshots or video

![NAF](https://github.com/ReVanced/revanced-manager/assets/4424058/de97f10d-5a62-415e-8877-3c44cd5dad48)

Tried with Revanced source - 
![OG Source](https://github.com/ReVanced/revanced-manager/assets/4424058/8ddc433a-d63b-4e9f-b22a-982e7d30da90)

Tried with ReX source - 
![ReX Source](https://github.com/ReVanced/revanced-manager/assets/4424058/5270d25f-f0a0-4b1e-b3cd-258233ddd224)

### Additional context

Cleared Revanced Manager app cache, data. Uninstalled it and then reinstalled it. Gave it all permissions. Still the same error. 

I see same issue was reported by someone else [last month](https://github.com/ReVanced/revanced-manager/issues/1083). But unlike that user, I don't have internet issues. I'm browsing internet fine on my phone.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
This happens when the ReVanced Patches are not loaded. An active internet connection is required to download ReVanced Patches for the first time. Do you see the `Loading...` text on the ReVanced Patches section in the Dashboard page?? If  so, then it's your internet issue. If you believe your internet is working fine, then use a VPN and try.

**Comment by bagarwa** [comment]
Patches section is showing "4d ago", not `Loading...` Connected to VPN and tried after that too. Still seeing "4d ago", and "No applications found".

![Dashboard](https://github.com/ReVanced/revanced-manager/assets/4424058/5a7323b7-46ab-4572-8eb4-65059202340f)

**Comment by TheAabedKhan** [comment]
Can you please send a screen recording starting from downloading the latest apk and clean installing it?

**Comment by rockermeier** [comment]
I have got the same problem. I managed to get it working by deleting all data of the Revanved Manager App (only update did not help). On the first start, it asked ahain to download the patches.

**Comment by kulmegil** [comment]
This still does happen if:
- I have active connection
- selected "experimental universal patches" (despite it promised to display all apps list!)
- deleting all data of the Revanved Manager didn't help at all (like suggested)
- (unrelated but) it also happens now even in old RvX Manager despite not touching it for some time

Really frustrating bug, since I have now I cannot install as root and it's my goto method and have already unpatched 😢

**Comment by TheAabedKhan** [comment]
@Ushie We can clearly see the release time of the ReVanced Manager and ReVanced Patches on the Updates section. This means the API is set to `api.revanced.app` already. I have asked them for a screen recording. So, let's wait for them to send.

**Comment by bagarwa** [comment]
A whole system reboot after the reinstall seems to have fixed it for me, at least when source is set to "revanced". 
When I set the [source to that of RvX](https://github.com/YT-Advanced/revanced-documentation/wiki/Method-3.-Using-Revanced-Manager-(Android)), Revanced Manager still throws the "No applications found" error, even after clean reinstall and system reboot. But I understand Revanced Manager team can't provide support for RvX.

**Comment by pgsharp** [comment]
I have the same issue in my case the apps won't showing if yt music is installed I have to uninstall ytm to apps appear in manager
I tried different sources and old api too and luckily it worked with old api but it only detected yt & ytm 
Now how should I patch reddit 🥲🥲

**Comment by piknockyou** [comment]
I have found out that disabling AdGuard solved the problem for me.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/1083

**Comment by holcus** [comment]
> I have found out that disabling AdGuard solved the problem for me.

wow, that worked for me, had to disable ublock origin in firefox (my default browser)
