### ISSUE TITLE
bug: YouTube ReVanced closes immediately

### ISSUE THREAD

**Issue by XEROling** [revanced/revanced-manager#123]
### Type

Error at runtime

### Branch

Flutter

### Bug description

YouTube ReVanced closes immediately after launching with no visual error message
Additionally, it shows a fully loaded YouTube home screen when viewing in the recent apps screen

### Steps to reproduce

1. Install official YouTube v17.33.42
2. Go to ReVanced manager and select this YouTube app
3. Select all patches except "Enable debugging" patch
4. Apply (and stay in app, don't multitask while it's running)
5. Install (non-root)
6. Launch

(YouTube ReVanced closes immediately)
(Open many times until the exception is caught by Scoop)
exception caught has been attached below...

### Relevant log output

- No root (without Vanced MicroG)
```shell
FATAL EXCEPTION: yt-critical2-6
Process: app.revanced.android.youtube, PID: 20450
java.lang.SecurityException: Failed to find provider com.mgoogle.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1235)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2672)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2660)
	at ndg.j(PG:3)
	at ndg.e(PG:1)
	at urz.f(PG:1)
	at ejy.run(PG:156)
	at sxt.run(PG:7)
	at nru.run(PG:23)
	at nsn.run(PG:62)
	at sbv.run(PG:58)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:357)
	at android.content.IContentService$Stub.onTransact(IContentService.java:484)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
```
- Installed with root:
```shell
FATAL EXCEPTION: main
Process: com.google.android.youtube, PID: 30082
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:234)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:982)
	at android.content.res.Resources.getDrawable(Resources.java:922)
	at app.revanced.integrations.swipecontrols.views.SwipeControlsOverlayLayout.getDrawable(SwipeControlsOverlayLayout.kt:41)
	at app.revanced.integrations.swipecontrols.views.SwipeControlsOverlayLayout.<init>(SwipeControlsOverlayLayout.kt:85)
	at app.revanced.integrations.swipecontrols.views.SwipeControlsOverlayLayout.<init>(SwipeControlsOverlayLayout.kt:32)
	at app.revanced.integrations.swipecontrols.SwipeControlsHostActivity.onCreate(SwipeControlsHostActivity.kt:80)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1345)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	... 12 more
```

### Solution

- No root method:
 Install Vanced MicroG ([Tested apk](https://apt.izzysoft.de/fdroid/repo/com.mgoogle.android.gms_22022001.apk))

- Root method:
exclude `microg-support` patch before installing with root

### Additional context

- Galaxy Note 10 Lite (r7)
- Android 12
- (ROM) Fluid: `2.7-Soho //Unnofficial`
- GMS available
- Kernel version: `4.9.191-lateM+ #7 Thu Sep 1 21:53:56 CEST 2022`
- Build number: `SQ3A.220705.003 dev-keys`
- Baseband version: `N770FXXS8FVC1`
- Security update: `July 5, 2022`

**Comment by Ftamino** [comment]
Same here on Google Pixel 6 on Android 13

**Comment by Joemgu7** [comment]
Same here on Mi9 on Android 11

**Comment by Alprnn357** [comment]
@XEROling @Joemgu7 @Ftamino @SveyPlay 
YT ReVanced crashes because you don't have microg services installed.
Install Vanced MicroG from [here](https://github.com/TeamVanced/VancedMicroG/releases) to fix

**Comment by XEROling** [comment]
@Alprnn357 thanks this fixes the problem for non-root method

Unfortunately it still doesn't work with root (edited the main post with more information)

**Comment by Alprnn357** [comment]
> @Alprnn357 thanks this fixes the problem for non-root method
> 
> Unfortunately it still doesn't work with root (edited the main post with more information)

Did you exclude `microg-support` patch before using install as root button?

**Comment by Alprnn357** [comment]
> @Alprnn357 thanks this fixes the problem for non-root method
> 
> Unfortunately it still doesn't work with root (edited the main post with more information)

Did you exclude `microg-support` patch before installing with root?

**Comment by XEROling** [comment]
> Did you exclude `microg-support` patch before installing with root?

It works with root now too
Thank you
