### ISSUE TITLE
bug: 1.9.4 Patcher Aborts after Loading patches

### ISSUE THREAD

**Issue by Muffinmaker2** [ReVanced/revanced-manager#1232]
### Type

Error while running the manager

### Bug description

Tried to Patch Youtube Recommanded version 18.32.39, The Patcher reads A

### Steps to reproduce

1. Select youtube App in Patcher
2. Try patching it
3. See that the Patcher Aborts it

### Android version

8

### Manager version

1.9.4

### Target package name

Youtube

### Target package version.

18.32.39

### Installation type

Non-root

### Patches selected.

Default Patches for that Yt Version/ Only Ad Patch. Both didnt work

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
09-03 13:40:27.695 13565 13565 D ActivityThread: ActivityThread,attachApplication
09-03 13:40:27.916 13565 13565 V ActivityThread: ActivityThread,callActivityOnCreate
09-03 13:40:28.196 13565 13565 D ActivityThread: add activity client record, r= ActivityRecord{e8a932a token=android.os.BinderProxy@e8b60ba {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} token= android.os.BinderProxy@e8b60ba
09-03 13:43:15.779 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x6602c73,viewVisibility is0
09-03 13:43:15.793 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0x6602c73,relayoutResult is7
09-03 13:43:19.321 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0xd871ccf,viewVisibility is0
09-03 13:43:19.355 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0xd871ccf,relayoutResult is7
09-03 13:43:22.843 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x282b6eb,viewVisibility is0
09-03 13:43:22.861 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0x282b6eb,relayoutResult is7
09-03 13:43:26.381 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0xd53d6c7,viewVisibility is0
09-03 13:43:26.398 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0xd53d6c7,relayoutResult is7
09-03 13:43:29.904 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0xb2d1863,viewVisibility is0
09-03 13:43:29.921 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0xb2d1863,relayoutResult is7
09-03 13:43:33.464 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x25979d5,viewVisibility is0
09-03 13:43:33.526 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0x25979d5,relayoutResult is7
09-03 13:43:36.979 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0xd3586b6,viewVisibility is0
09-03 13:43:36.997 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0xd3586b6,relayoutResult is7
09-03 13:43:40.491 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x10b5842,viewVisibility is0
09-03 13:43:40.509 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =761ff9f000)/@0x10b5842,relayoutResult is7
09-03 13:43:41.977 13565 13565 D ActivityThread: Remove activity client record, r= ActivityRecord{e8a932a token=android.os.BinderProxy@e8b60ba {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} token= android.os.BinderProxy@e8b60ba
09-03 13:43:43.959 13565 13565 V ActivityThread: ActivityThread,callActivityOnCreate
09-03 13:43:44.019 13565 13565 D ActivityThread: add activity client record, r= ActivityRecord{6a58368 token=android.os.BinderProxy@547df3e {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} token= android.os.BinderProxy@547df3e
09-03 13:43:44.108 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0xeb35780,viewVisibility is0
09-03 13:43:44.132 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =76067cf000)/@0xeb35780,relayoutResult is7
09-03 13:43:47.530 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x4f49698,viewVisibility is0
09-03 13:43:47.544 13565 13565 W ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =app.revanced.manager.flutter) ( mSurfaceControllerIsValid =true) (mNativeObject  =76067cf000)/@0x4f49698,relayoutResult is7
--------- beginning of main
09-03 13:46:34.546 13565 13624 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
09-03 13:46:34.551 13565 15860 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
09-03 13:46:34.559 13565 13565 W InputMethodManager: startInputReason = 1
09-03 13:46:35.147 13565 13565 V AudioManager: playSoundEffect   effectType: 0
09-03 13:46:35.433 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 7, previously 15
09-03 13:46:35.434 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 578, previously 591
09-03 13:46:35.434 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 450, previously 868
09-03 13:46:35.434 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 208, previously 1317
09-03 13:46:35.494 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 4, previously 8
09-03 13:46:35.494 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 437, previously 435
09-03 13:46:35.494 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 181, previously 901
09-03 13:46:35.881 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 767, previously 786
09-03 13:46:35.881 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1724, previously 1818
09-03 13:46:35.881 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 208, previously 1124
09-03 13:46:35.918 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 25, previously 28
09-03 13:46:35.918 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 15, previously 17
09-03 13:46:35.918 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 312, previously 1027
09-03 13:46:35.918 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1197, previously 1222
09-03 13:46:35.918 13565 16517 W ResourceType: ResTable_typeSpec entry count inconsistent: given 213, previously 1394
09-03 13:46:38.328 13565 13565 V AudioManager: playSoundEffect   effectType: 0
09-03 13:47:45.817 13565 15860 W libEGL  : EGLNativeWindowType 0x760845d010 disconnect failed
09-03 13:47:45.826 13565 13624 W libEGL  : EGLNativeWindowType 0x761ff9f010 disconnect failed
09-03 13:48:39.834 13565 13624 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
09-03 13:48:39.845 13565 15860 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
09-03 13:48:39.849 13565 13565 E BpSurfaceComposerClient: Failed to transact (-1)
09-03 13:48:39.850 13565 13565 E BpSurfaceComposerClient: Failed to transact (-1)
09-03 13:48:39.852 13565 13565 W InputMethodManager: startInputReason = 1
09-03 13:48:40.591 13565 13565 V AudioManager: playSoundEffect   effectType: 0
09-03 13:48:43.042 13565 13565 V AudioManager: playSoundEffect   effectType: 0
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
An error occurred:
java.lang.NullPointerException
	at java.io.File.<init>(File.java:282)
	at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
	at app.revanced.patcher.PatchBundleLoader$Dex.<init>(PatchBundleLoader.kt:60)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:184)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:784)
```

### Screenshots or video

![image](https://github.com/ReVanced/revanced-manager/assets/107619523/d65a8c75-bc2f-4e44-9134-3fffd276a5d8)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
Depends on https://github.com/ReVanced/revanced-patcher/issues/230

**Comment by Ushie** [comment]
ReVanced Manager v1.9.5 has been released, should be fixed
