### ISSUE TITLE
Older Manager versions crash when fetching patches

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1330]
### Bug description

Older manager versions crash when fetching patches.

Steps to reproduce:

1. Install manager 1.10.3
2. Enable 'Auto-update patches' when prompted. 

I saw some stuff about how the api was changing. It isn't ideal if the changes cause older versions to crash on startup, which causes users to download the new manager instead of updating from within the Manager.

Attached is a bigger log. I put what I think is the most important error in the backticks below.

[logcat_10-04-2023_20-06-16.txt](https://github.com/ReVanced/revanced-manager/files/12810981/logcat_10-04-2023_20-06-16.txt)

### Version of ReVanced Manager and version & name of application you tried to patch

1.10.3

### Installation type

None

### Device logs

```shell
FATAL EXCEPTION: main
Process: app.revanced.manager.flutter, PID: 17636
java.lang.IncompatibleClassChangeError: Superclass app.revanced.patcher.patch.ResourcePatch of app.revanced.patches.all.activity.exportall.ExportAllActivitiesPatch is an interface (declaration of 'app.revanced.patches.all.activity.exportall.ExportAllActivitiesPatch' appears in /data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/8e1be250-6311-11ee-bac8-29611a7d8b30.bin)
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at app.revanced.patcher.PatchBundleLoader$Dex.<init>(PatchBundleLoader.kt:77)
	at app.revanced.manager.flutter.MainActivity.configureFlutterEngine$lambda$4(MainActivity.kt:100)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$37tT2fZXiYuuYL_syPu8Be8MFig(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.onMethodCall(Unknown Source:2)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This has been technically fixed. ReVanced Manager preloads the patches from the downloaded bundle, but if the version of ReVanced Manager is outdated, it can fail loading them. This is handled now.
