### ISSUE TITLE
bug: Patching/building apk with latest manager app triggers Play Protect when installing

### ISSUE THREAD

**Issue by pmsobrado** [ReVanced/revanced-manager#1336]
### Bug description

This is not exactly a bug, but it is certainly not a feature request, and those were the only options to open an issue here.

Basically, I've noticed that, with the latest Manager app, the created YT Revanced apk triggers a Play Protect block when installing. The apk can be installed anyway, that's not a problem. But just a couple days ago I built the apk with what it was the latest version of the Manager back then (older than the current one), using the same base YT apk, and that apk does NOT trigger Play Protect. I have both apks in case anyone needs them to check them.

In addition to this, I don't think this is caused by some patch, I used the same patches both times (I checked).

I also tried some other fishy apks I have (not published on Play Store) and they do not trigger Play Protect, so it really seems like something has changed on newer Revanced Manager apps, rather than a Play Protect update.

It's not a big deal, but I would like to know for sure, or confirm, if something has changed, and/or if the devs are aware of it.

I hope this is not a duplicate, I tried to find info, but I only saw people with the same Play Protect problem, not a real answer as for why it didn't happen before. I also checked the Discord channel without success. Sorry if I missed anything.

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced Manager: v1.11.1
Base YouTube apk: 18.32.39

### Installation type

Non-root

### Device logs

```shell
--------- beginning of system
10-05 18:16:21.952  8454  8454 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 467ms late (wall=134ms running=87ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 1 msg, msg 1 took 474ms (seq=2 running=434ms runnable=9ms io=4ms late=3ms h=android.app.ActivityThread$H w=110)
10-05 18:16:21.952  8454  8454 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 602ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 2 msg, msg 1 took 474ms (seq=2 running=434ms runnable=9ms io=4ms late=3ms h=android.app.ActivityThread$H w=110), msg 2 took 134ms (seq=3 running=87ms runnable=7ms io=2ms late=467ms h=android.app.ActivityThread$H w=159)
10-05 18:17:13.795 11659 11659 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [92, r=273ms, a=21ms, w=5260ms]
10-05 18:17:28.828 11659 11659 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
10-05 18:17:28.832 11659 11659 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
10-05 18:21:26.553 11659 11659 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [76, r=446ms, a=140ms, w=237811ms]
10-05 18:23:14.812 21443 21443 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [87, r=232ms, a=32ms, w=4014ms]
10-05 18:23:17.539 21443 21443 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
10-05 18:23:17.542 21443 21443 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
10-05 18:26:25.378 21443 23135 W FileUtils: Slow Operation: fsync took 111ms
10-05 18:26:46.268 21443 21443 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [89, r=380ms, a=46ms, w=208786ms]
10-05 18:33:34.777 25855 25855 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [89, r=309ms, a=35ms, w=9283ms]
10-05 18:33:38.378 25855 25855 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
10-05 18:33:38.380 25855 25855 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
10-05 18:38:37.937 25855 25855 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [88, r=369ms, a=50ms, w=299603ms]
10-05 18:40:28.606 25855 25855 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [78, r=18ms, a=5ms, w=1173ms]
10-05 18:40:31.653 25855 25855 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [79, r=19ms, a=5ms, w=1586ms]
10-05 18:47:21.602 31611 31611 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [95, r=471ms, a=21ms, w=10972ms]
10-05 18:47:22.505 31611 31611 W Activity: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 177ms
10-05 18:58:28.794   687   687 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [93, r=228ms, a=15ms, w=4301ms]
10-05 18:58:31.735   687   687 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
10-05 18:58:31.737   687   687 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
10-05 19:05:30.939   687  2273 W FileUtils: Slow Operation: fsync took 157ms
10-05 19:05:36.137   687   687 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [92, r=3218ms, a=251ms, w=424446ms]
10-05 19:06:48.372   687   687 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XRGRGD/out.apk Binary XML file line #2
10-05 19:06:48.374   687   687 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XRGRGD/out.apk Binary XML file line #136
10-05 19:06:48.377   687   687 W PackageParser: No actions in intent filter at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XRGRGD/out.apk Binary XML file line #464
10-05 19:06:50.556   687   687 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [82, r=55ms, a=12ms, w=2231ms]
10-05 19:06:53.462   687   687 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [66, r=8ms, a=4ms, w=1203ms]
10-05 19:06:56.078   687   687 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [90, r=9ms, a=1ms, w=2341ms]
--------- beginning of main
10-05 19:07:03.916   687   687 I InstallPlugin: handleActivityResult(2,0,null)
10-05 19:07:03.933   687   687 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:07:03.934   687   687 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:07:06.542   687   687 D ViewRootImpl: [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=2228452, downTime=2228452, deviceId=-1, source=0x101, displayId=-1 }
10-05 19:07:06.543   687   687 D ViewRootImpl: [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=2228452, downTime=2228452, deviceId=-1, source=0x101, displayId=-1 }
10-05 19:07:11.434   687   687 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [89, r=112ms, a=13ms, w=7518ms]
10-05 19:07:12.940   687   687 I InstallPlugin: handleActivityResult(2,-1,Intent { dat=content://com.android.externalstorage.documents/document/primary:Download/selected_patches_2023-10-05_19_07_11.json flg=0x43 })
10-05 19:07:12.948   687   687 D CrFileSaverPlugin: Saved file /document/primary:Download/selected_patches_2023-10-05_19_07_11.json via dialog
10-05 19:07:12.971   687   687 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:07:12.972   687   687 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:07:12.996   687   687 I Toast   : Show toast from OpPackageName:app.revanced.manager.flutter, PackageName:app.revanced.manager.flutter
10-05 19:07:15.600   687   687 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [75, r=12ms, a=4ms, w=2658ms]
10-05 19:08:08.221  4831  4831 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
10-05 19:08:08.267  4831  4831 I Perf    : Connecting to perf service.
10-05 19:08:08.280  4831  4831 I FeatureParser: cannot find cmi.xml in assets/device_features/,it may be in /vendor/etc/device_features
10-05 19:08:08.281  4831  4831 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
10-05 19:08:08.277  4831  4831 W manager.flutter: type=1400 audit(0.0:85846): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=19025 scontext=u:r:untrusted_app:s0:c221,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0
10-05 19:08:08.309  4831  4831 W manager.flutter: type=1400 audit(0.0:85847): avc: denied { read } for name="max_map_count" dev="proc" ino=1088494 scontext=u:r:untrusted_app:s0:c221,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: QUALCOMM build                   : 856adf3, I0624de940e
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: Build Date                       : 04/27/20
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.29.00.07
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: Local Branch                     : mybranchea88dfbf-7aec-f1b9-9eec-08f1eafda2d0
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r86
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: Remote Branch                    : NONE
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: Build Config                     : S P 8.0.12 AArch64
10-05 19:08:08.316  4831  4831 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-05 19:08:08.318  4831  4831 I AdrenoGLES-0: PFP: 0x016dd087, ME: 0x00000000
10-05 19:08:08.337  4831  4831 D View    : app.revanced.manager.flutter initForcedUseForceDark: 1
10-05 19:08:08.382  4831  4831 D SurfaceView: UPDATE null, mIsCastMode = false
10-05 19:08:08.383  4831  4831 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:08:08.383  4831  4831 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:08:08.523  4831  4873 I flutter : dynamic_color: Dynamic color not detected on this device.
10-05 19:08:08.543  4831  4831 D permissions_handler: No permissions found in manifest for: []22
10-05 19:08:08.556  4831  4874 E LB      : fail to open file: No such file or directory
10-05 19:08:08.848  4831  4831 W System.err: com.stericson.RootTools.exceptions.RootDeniedException: Root Access Denied
10-05 19:08:08.848  4831  4831 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:113)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:51)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:41)
10-05 19:08:08.848  4831  4831 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
10-05 19:08:08.848  4831  4831 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
10-05 19:08:08.848  4831  4831 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
10-05 19:08:08.848  4831  4831 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
10-05 19:08:08.848  4831  4831 W System.err: 	at android.os.Handler.handleCallback(Unknown Source:2)
10-05 19:08:08.848  4831  4831 W System.err: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
10-05 19:08:08.848  4831  4831 W System.err: 	at android.os.Looper.loop(Unknown Source:251)
10-05 19:08:08.848  4831  4831 W System.err: 	at android.app.ActivityThread.main(Unknown Source:98)
10-05 19:08:08.848  4831  4831 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
10-05 19:08:08.848  4831  4831 W System.err: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)
10-05 19:08:10.110  4831  4831 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [92, r=92ms, a=7ms, w=1760ms]
10-05 19:24:07.907  8885  8885 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
10-05 19:24:07.959  8885  8885 I Perf    : Connecting to perf service.
10-05 19:24:07.975  8885  8885 I FeatureParser: cannot find cmi.xml in assets/device_features/,it may be in /vendor/etc/device_features
10-05 19:24:07.975  8885  8885 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
10-05 19:24:07.972  8885  8885 W manager.flutter: type=1400 audit(0.0:175478): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=19025 scontext=u:r:untrusted_app:s0:c221,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0
10-05 19:24:08.008  8885  8885 W manager.flutter: type=1400 audit(0.0:175479): avc: denied { read } for name="max_map_count" dev="proc" ino=1201710 scontext=u:r:untrusted_app:s0:c221,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: QUALCOMM build                   : 856adf3, I0624de940e
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: Build Date                       : 04/27/20
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.29.00.07
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: Local Branch                     : mybranchea88dfbf-7aec-f1b9-9eec-08f1eafda2d0
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r86
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: Remote Branch                    : NONE
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: Build Config                     : S P 8.0.12 AArch64
10-05 19:24:08.017  8885  8885 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-05 19:24:08.020  8885  8885 I AdrenoGLES-0: PFP: 0x016dd087, ME: 0x00000000
10-05 19:24:08.041  8885  8885 D View    : app.revanced.manager.flutter initForcedUseForceDark: 1
10-05 19:24:08.088  8885  8885 D SurfaceView: UPDATE null, mIsCastMode = false
10-05 19:24:08.089  8885  8885 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:24:08.090  8885  8885 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:24:08.200  8885  8913 I flutter : dynamic_color: Dynamic color not detected on this device.
10-05 19:24:08.219  8885  8885 D permissions_handler: No permissions found in manifest for: []22
10-05 19:24:08.237  8885  8914 E LB      : fail to open file: No such file or directory
10-05 19:24:08.768  8885  8885 W System.err: com.stericson.RootTools.exceptions.RootDeniedException: Root Access Denied
10-05 19:24:08.768  8885  8885 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:113)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:51)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:41)
10-05 19:24:08.768  8885  8885 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
10-05 19:24:08.768  8885  8885 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
10-05 19:24:08.768  8885  8885 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
10-05 19:24:08.768  8885  8885 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
10-05 19:24:08.768  8885  8885 W System.err: 	at android.os.Handler.handleCallback(Unknown Source:2)
10-05 19:24:08.768  8885  8885 W System.err: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
10-05 19:24:08.768  8885  8885 W System.err: 	at android.os.Looper.loop(Unknown Source:251)
10-05 19:24:08.768  8885  8885 W System.err: 	at android.app.ActivityThread.main(Unknown Source:98)
10-05 19:24:08.768  8885  8885 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
10-05 19:24:08.768  8885  8885 W System.err: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)
10-05 19:24:11.110  8885  8885 W ActivityThread: SCHED: app.revanced.manager.flutter/.MainActivity [98, r=135ms, a=2ms, w=3055ms]
10-05 19:24:20.961  8885  8885 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
10-05 19:24:20.962  8885  8885 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
```

### Patcher logs

```shell
I do not have any :S
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Play Protect triggers for "Unknown" apps, which the Play Protect doesn't recognize the "signature" of.

The way ReVanced works is everything is done on your device, it decompiles the provided APK, applies changes, compiles it, signs it, and installs it

When ReVanced Manager signs an app, it needs to generate a new Keystore, what's a keystore? it is basically the key to signing apps with your developer "signature", and considering the Keystore is generated by ReVanced Manager, the signature will be unique.

The reason you didn't see this on older releases of ReVanced Manager is either Play Protect was acting silly, or you've already gone through the Play Protect warning once and forgotten about it (which means it learned about the signature)

As to why you don't see this happen to other APKs, it's because these APKs aren't compiled on your device, they've already been installed, tested, and all by the dev and other people who installed it before you. You'll see the same behavior when using other projects that generate the Keystore locally, such as Aliucord, Vendetta, LuckyPatcher(?)... etc

**Comment by pmsobrado** [comment]
Thanks for the explanations. I have a question though:

`The reason you didn't see this on older releases of ReVanced Manager is either Play Protect was acting silly, or you've already gone through the Play Protect warning once and forgotten about it (which means it learned about the signature)`

Why if I try to install Revanced again, the Play Protect prompt appears as the first time? Shouldn't it already know the signature of the previous installation? Or maybe Play Protect only stops complaining when the signature has been "used" a few times?

**Comment by Ushie** [comment]
I'm not sure what the exact process is, there used to be a button that sends information about the application to Play Protect to scan and determine that it's safe, but I don't see that button anymore

**Comment by RealYukiSan** [comment]
So does that imply prebuilt patch will no longer work? I tried install the yt patched apk but it crash each time I open it:
```
05-13 23:48:19.108 E/AndroidRuntime(19562): FATAL EXCEPTION: main
05-13 23:48:19.108 E/AndroidRuntime(19562): Process: app.revanced.android.apps.youtube.music, PID: 19562
05-13 23:48:19.108 E/AndroidRuntime(19562): java.lang.SecurityException: PackageVerificationRslt: not allowed: pkg=app.revanced.android.apps.youtube.music, sha256=[818684e946ab7c1c298187f52f34455e15b386a07fa990d6c22268fab586ad60], atk=true, ver=241518018.true
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at android.os.Parcel.createException(Parcel.java:2072)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at android.os.Parcel.readException(Parcel.java:2040)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at android.os.Parcel.readException(Parcel.java:1988)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at gns.a(SourceFile:14)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at gmr.a(SourceFile:220)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at gis.a(SourceFile:29)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at giw.run(SourceFile:10)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at hdm.run(SourceFile:6)
05-13 23:48:19.108 E/AndroidRuntime(19562): 	at java.lang.Thread.run(Thread.java:919)
05-13 23:48:19.109 E/mvo     (19562): APP CRASHED!
05-13 23:48:19.109 E/mvo     (19562): java.lang.SecurityException: PackageVerificationRslt: not allowed: pkg=app.revanced.android.apps.youtube.music, sha256=[818684e946ab7c1c298187f52f34455e15b386a07fa990d6c22268fab586ad60], atk=true, ver=241518018.true
05-13 23:48:19.109 E/mvo     (19562): 	at android.os.Parcel.createException(Parcel.java:2072)
05-13 23:48:19.109 E/mvo     (19562): 	at android.os.Parcel.readException(Parcel.java:2040)
05-13 23:48:19.109 E/mvo     (19562): 	at android.os.Parcel.readException(Parcel.java:1988)
05-13 23:48:19.109 E/mvo     (19562): 	at gns.a(SourceFile:14)
05-13 23:48:19.109 E/mvo     (19562): 	at gmr.a(SourceFile:220)
05-13 23:48:19.109 E/mvo     (19562): 	at gis.a(SourceFile:29)
05-13 23:48:19.109 E/mvo     (19562): 	at giw.run(SourceFile:10)
05-13 23:48:19.109 E/mvo     (19562): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-13 23:48:19.109 E/mvo     (19562): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-13 23:48:19.109 E/mvo     (19562): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-13 23:48:19.109 E/mvo     (19562): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-13 23:48:19.109 E/mvo     (19562): 	at hdm.run(SourceFile:6)
05-13 23:48:19.109 E/mvo     (19562): 	at java.lang.Thread.run(Thread.java:919)
```

The yt music apk version was 2.41.54 with armeabi v7a arch

Since I'm unable to patch it on armeabi v7a, so I patch it on arm64 v8a phone and transfer it to my v7a phone

**Comment by oSumAtrIX** [comment]
For support, move to one of our links at https://revanced.app.
