### ISSUE TITLE
bug: <tiktok30.8.4>

### ISSUE THREAD

**Issue by wangyi1573** [ReVanced/revanced-manager#1346]
### Bug description

app patch

### Version of ReVanced Manager and version & name of application you tried to patch

revanced version 1.11.2
tiktok version 30.8.4

### Installation type

Non-root

### Device logs

```shell
~ Device Info
ReVanced Manager: 1.11.2
Build: release
Model: Mi 10
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi

~ Patch Info
App: com.zhiliaoapp.musically v30.8.4
Patches version: v2.193.0
Patches: Hide ads, Feed filter, Downloads, Show seekbar, Playback speed, Disable login requirement, Fix Google login, Settings, SIM spoof

~ Settings
Enabled changing patches: true
Enabled universal patches: true
Enabled experimental patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

~ Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 7462048 byte allocation with 5623648 free bytes and 5491KB until OOM, target footprint 536870912, growth limit 536870912
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:256)
	at com.google.common.io.ByteStreamsHack.toByteArray(ByteStreamsHack.java:30)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:55)
	at lanchon.multidexlib2.ZipFileDexContainer.<init>(ZipFileDexContainer.java:48)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:64)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:50)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:41)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:35)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(BytecodeContext.kt:43)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(BytecodeContext.kt:41)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at app.revanced.patcher.data.BytecodeContext.getClasses(BytecodeContext.kt:41)
	at app.revanced.patcher.data.BytecodeContext$Integrations.flush(BytecodeContext.kt:111)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:188)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:256)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$23(MainActivity.kt:255)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$iczzv34SoBa_J1fRmhQ1dE2ClMs(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:22)
	at java.lang.Thread.run(Thread.java:1012)
```
```


### Patcher logs

_No response_

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by roy-heinrich** [comment]
why was this closed?

**Comment by oSumAtrIX** [comment]
It's a duplicate, not related to Manager as well as formatting was broken: 
![image](https://github.com/ReVanced/revanced-manager/assets/13122796/83958763-567b-41b9-b053-1b1fe933b08f)
