### ISSUE TITLE
bug. TikTok: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Smollejan** [ReVanced/revanced-manager#1408]
### Bug description

Patching TikTok failes.

Steps:
1. Download TikTok 30.8.4 from apkmirror 
2. Patch with default settings in manager 1.13.1
3. Patch fails: java.lang.OutOfMemoryError

### Version of ReVanced Manager and version & name of application you tried to patch

Manager: 1.13.1
TikTok:  30.8.4

### Installation type

Non-root

### Device logs

```shell
--------- beginning of system
10-20 14:46:33.778 13591 13591 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #5
10-20 14:46:33.779 13591 13591 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #335
10-20 14:46:33.779 13591 13591 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #357
10-20 14:46:33.789 13591 13591 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1611
10-20 14:46:33.789 13591 13591 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1613
10-20 14:46:33.789 13591 13591 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1615
10-20 14:46:33.789 13591 13591 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1617
10-20 14:46:33.789 13591 13591 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1619
10-20 14:46:33.789 13591 13591 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1621
10-20 14:46:33.794 13591 13591 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_30.8.4-2023008040_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #2387
--------- beginning of main
10-20 14:52:03.282 13591 13603 W System  : A resource failed to call close. 
10-20 15:01:05.401 13591 13609 E OpenGLRenderer: Unable to match the desired swap behavior.
10-20 15:01:05.415 13591 13591 E SurfaceSyncer: Failed to find sync for id=0
10-20 15:01:05.415 13591 13591 E SurfaceSyncer: Failed to find sync for id=1
10-20 15:01:05.415 13591 13591 E SurfaceSyncer: Failed to find sync for id=2
10-20 15:01:05.415 13591 13591 E SurfaceSyncer: Failed to find sync for id=3
```

### Patcher logs

```shell
~ Device Info
ReVanced Manager: 1.13.1
Build: release
Model: Mi 9T
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi

~ Patch Info
App: com.zhiliaoapp.musically v30.8.4
Patches version: v2.195.0
Patches: Disable login requirement, Downloads, Feed filter, Fix Google login, Hide ads, Playback speed, Settings, Show seekbar

~ Settings
Allow changing patch selection: false
Show universal patches: false
Version compatibility check: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

~ Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Disable login requirement succeeded
Downloads succeeded
Feed filter succeeded
Fix Google login succeeded
Hide ads succeeded
Playback speed succeeded
Settings succeeded
Show seekbar succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiled classes9.dex
Compiled classes10.dex
Compiled classes11.dex
Compiled classes12.dex
Compiled classes13.dex
Compiled classes14.dex
Compiled classes15.dex
Compiled classes16.dex
Compiled classes17.dex
Compiled classes18.dex
Compiled classes19.dex
Compiled classes20.dex
Compiled classes21.dex
Compiled classes22.dex
Compiled classes23.dex
Compiled classes24.dex
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1376440 free bytes and 1344KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.DexBuffer.readerAt(DexBuffer.java:144)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:334)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:329)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:372)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:367)
	at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedMethodReference.getDefiningClass(DexBackedMethodReference.java:57)
	at com.android.tools.smali.dexlib2.base.reference.BaseMethodReference.hashCode(BaseMethodReference.java:45)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:464)
	at com.android.tools.smali.dexlib2.writer.pool.BaseIndexPool.getItemIndex(BaseIndexPool.java:52)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(InstructionWriter.java:596)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(InstructionWriter.java:582)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:397)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1352)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1115)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:415)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:162)
	at lanchon.multidexlib2.DexIO.access$000(DexIO.java:37)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:102)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```
```


### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Dupe
