### ISSUE TITLE
bug: Battery drain GmsGcmRegister SpoofUtils

### ISSUE THREAD

**Issue by dmitryuk** [ReVanced/revanced-manager#1423]
### Bug description

Xiaomi mi 10T, rooted, gms updates disabled
With logcat I see an error, that continues infinitely

Can you assist what to do with it?

### Version of ReVanced Manager and version & name of application you tried to patch

Manager 1.8.15
Youtube ReVanced Extended 18.40.34

### Installation type

Root

### Device logs

```shell
10-25 10:30:52.512  7919  7919 D GmsGcmRegister: onBind: Intent { act=com.mgoogle.android.c2dm.intent.REGISTER pkg=com.mgoogle.android.gms }
10-25 10:30:52.515  7919  7919 I SpoofUtils: package name of app.rvx.android.youtube spoofed to com.google.android.youtube
10-25 10:30:52.515  7919  7919 D GmsGcmRegister: handleMessage: package=app.rvx.android.youtube what=1 id=95
10-25 10:30:52.522  7919  7919 W GmsGcmRegister: java.lang.RuntimeException: Checkin disabled
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at org.microg.gms.gcm.PushRegisterServiceKt.ensureCheckinIsUpToDate(PushRegisterService.kt:32)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at org.microg.gms.gcm.PushRegisterServiceKt.access$ensureCheckinIsUpToDate(PushRegisterService.kt:1)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at org.microg.gms.gcm.PushRegisterHandler$handleMessage$1.invokeSuspend(PushRegisterService.kt:310)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:373)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at androidx.lifecycle.LifecycleCoroutineScope.launchWhenStarted(Lifecycle.kt:355)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at org.microg.gms.gcm.PushRegisterHandler.handleMessage(PushRegisterService.kt:306)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at android.os.Looper.loopOnce(Looper.java:201)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at android.os.Looper.loop(Looper.java:288)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at android.app.ActivityThread.main(ActivityThread.java:7925)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at java.lang.reflect.Method.invoke(Native Method)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-25 10:30:52.522  7919  7919 W GmsGcmRegister:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```
```


### Patcher logs

_No response_

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by TheAabedKhan** [comment]
We do not provide support for unofficial ReVanced services.

**Comment by dmitryuk** [comment]
Why do you think it is unofficial service? I installed `Revanced Manager` from https://revanced.net/, installed   `Youtube revanced extended` from app

**Comment by oSumAtrIX** [comment]
Because ReVanced.app is the official page
