### ISSUE TITLE
bug: Failed to build

### ISSUE THREAD

**Issue by selvinjack** [ReVanced/revanced-manager#1436]
### Bug description

Every time I try to build a YouTube APK using the Revanced Manager, it always fails, even when selecting limited features.

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced version: v1.14.1
Patching app: YouTube v18.38.44

### Installation type

Root

### Device logs

```shell
I can't paste it here because it's too long, so I've uploaded it there.

Here is the link: https://rentry.co/dfpzz
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.14.1
Build: release
Model: LE2101
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v18.38.44
Patches version: v2.195.0
Patches: Client spoof, Copy video url, Disable Shorts on startup, Hide Shorts components, Hide ads, Old video quality menu, Return YouTube Dislike, SponsorBlock, Spoof app version, Spoof device dimensions, Swipe controls, Video ads

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Client spoof succeeded
Copy video url succeeded
Disable Shorts on startup succeeded
Hide Shorts components succeeded
Hide ads succeeded
Old video quality menu succeeded
Return YouTube Dislike succeeded
SponsorBlock succeeded
Spoof app version succeeded
Spoof device dimensions succeeded
Swipe controls succeeded
Video ads succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~ot6i02MjH4AXJmD9mjzEaw==/app.revanced.manager.flutter-TCx-aqKItGghBtlGWugxzg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4515127984322114930.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:261)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$30(MainActivity.kt:316)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$nWp6SJoHVIOkEmiKbEEka4nn7Ag(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~ot6i02MjH4AXJmD9mjzEaw==/app.revanced.manager.flutter-TCx-aqKItGghBtlGWugxzg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4515127984322114930.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHSYFB/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
![image](https://github.com/ReVanced/revanced-manager/assets/13122796/17147f12-29a3-46ae-9e69-c715a7133942)

**Comment by selvinjack** [comment]
Here is the video 

https://github.com/ReVanced/revanced-manager/assets/83247692/b881ae8b-82af-4f95-9c6e-4b37ab42f878

**Comment by oSumAtrIX** [comment]
Try disabling root permissions.

**Comment by selvinjack** [comment]
Stil same issue

**Comment by ILoveOpenSourceApplications** [comment]
Maybe try again without `client spoof` patch included as it's not required for rooted users? (A suggestion)

**Comment by selvinjack** [comment]
It works thanks!

**Comment by oSumAtrIX** [comment]
That makes no sense. The issue is not caused by the patch

**Comment by Fusseldieb** [comment]
Same issue here. Modifying the patches didn't work. 

I'm trying it on the suggested version and it throws the same error.
