### ISSUE TITLE
Installed apps don't show

### ISSUE THREAD

**Issue by cod-md** [ReVanced/revanced-manager#1447]
### Bug description

The installed apps don't show so i can patch them
{Although i have apps that should have supported patches}
![Screenshot_20231029-231501_ReVanced_Manager](https://github.com/ReVanced/revanced-manager/assets/92212094/9e041257-8628-4e18-a16e-649b436161a3)

I am on Android 10

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced manager 1.14.2
Application doesn't show

### Installation type

Root

### Device logs

```shell
--------- beginning of main
10-29 23:17:24.067 23175 23175 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
10-29 23:18:02.726 23175 23175 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@9d03e02
10-29 23:18:02.814 23175 23175 I AdrenoGLES: QUALCOMM build                   : b7a53ba, I65c4755304
10-29 23:18:02.814 23175 23175 I AdrenoGLES: Build Date                       : 09/11/19
10-29 23:18:02.814 23175 23175 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.01
10-29 23:18:02.814 23175 23175 I AdrenoGLES: Local Branch                     : mybranche9d496a3-67c3-f1d6-9f04-1458d0b52ae8
10-29 23:18:02.814 23175 23175 I AdrenoGLES: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r84-rel
10-29 23:18:02.814 23175 23175 I AdrenoGLES: Remote Branch                    : NONE
10-29 23:18:02.814 23175 23175 I AdrenoGLES: Reconstruct Branch               : NOTHING
10-29 23:18:02.814 23175 23175 I AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
10-29 23:18:02.817 23175 23175 I AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
10-29 23:18:02.847 23175 23175 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
10-29 23:18:02.847 23175 23175 I chatty  : uid=10312(app.revanced.manager.flutter) identical 1 line
10-29 23:18:02.848 23175 23175 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
10-29 23:18:03.440 23175 23218 I flutter : dynamic_color: Dynamic color not detected on this device.
10-29 23:18:03.467 23175 23219 W Gralloc3: mapper 3.x is not supported
10-29 23:18:19.444 23175 23218 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
10-29 23:18:19.444 23175 23218 E flutter : #0      StatefulElement.state (package:flutter/src/widgets/framework.dart:5416)
10-29 23:18:19.444 23175 23218 E flutter : #1      Element.findRootAncestorStateOfType (package:flutter/src/widgets/framework.dart:4661)
10-29 23:18:19.444 23175 23218 E flutter : #2      Navigator.of (package:flutter/src/widgets/navigator.dart:2621)
10-29 23:18:19.444 23175 23218 E flutter : #3      showDialog (package:flutter/src/material/dialog.dart:1420)
10-29 23:18:19.444 23175 23218 E flutter : #4      HomeViewModel.showPatchesConsent (package:revanced_manager/ui/views/home/home_viewmodel.dart:167)
10-29 23:18:19.444 23175 23218 E flutter : #5      HomeViewModel.initialize (package:revanced_manager/ui/views/home/home_viewmodel.dart:45)
10-29 23:18:19.444 23175 23218 E flutter : <asynchronous suspension>
10-29 23:18:19.444 23175 23218 E flutter : 
10-29 23:20:03.233 16440 16440 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
10-29 23:20:03.359 16440 16440 I AdrenoGLES: QUALCOMM build                   : b7a53ba, I65c4755304
10-29 23:20:03.359 16440 16440 I AdrenoGLES: Build Date                       : 09/11/19
10-29 23:20:03.359 16440 16440 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.01
10-29 23:20:03.359 16440 16440 I AdrenoGLES: Local Branch                     : mybranche9d496a3-67c3-f1d6-9f04-1458d0b52ae8
10-29 23:20:03.359 16440 16440 I AdrenoGLES: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r84-rel
10-29 23:20:03.359 16440 16440 I AdrenoGLES: Remote Branch                    : NONE
10-29 23:20:03.359 16440 16440 I AdrenoGLES: Reconstruct Branch               : NOTHING
10-29 23:20:03.359 16440 16440 I AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
10-29 23:20:03.361 16440 16440 I AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
10-29 23:20:03.398 16440 16440 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
10-29 23:20:03.399 16440 16440 I chatty  : uid=10312(app.revanced.manager.flutter) identical 1 line
10-29 23:20:03.399 16440 16440 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
10-29 23:20:03.610 16440 24104 I flutter : dynamic_color: Dynamic color not detected on this device.
10-29 23:20:03.647 16440 24105 W Gralloc3: mapper 3.x is not supported
10-29 23:20:19.171 16440 24104 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
10-29 23:20:19.171 16440 24104 E flutter : #0      StatefulElement.state (package:flutter/src/widgets/framework.dart:5416)
10-29 23:20:19.171 16440 24104 E flutter : #1      Element.findRootAncestorStateOfType (package:flutter/src/widgets/framework.dart:4661)
10-29 23:20:19.171 16440 24104 E flutter : #2      Navigator.of (package:flutter/src/widgets/navigator.dart:2621)
10-29 23:20:19.171 16440 24104 E flutter : #3      showDialog (package:flutter/src/material/dialog.dart:1420)
10-29 23:20:19.171 16440 24104 E flutter : #4      HomeViewModel.showPatchesConsent (package:revanced_manager/ui/views/home/home_viewmodel.dart:167)
10-29 23:20:19.171 16440 24104 E flutter : #5      HomeViewModel.initialize (package:revanced_manager/ui/views/home/home_viewmodel.dart:45)
10-29 23:20:19.171 16440 24104 E flutter : <asynchronous suspension>
10-29 23:20:19.171 16440 24104 E flutter :
```

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by cod-md** [comment]
For example : 

https://github.com/ReVanced/revanced-manager/assets/92212094/fe685f8f-d202-492c-9230-4350bceec111

**Comment by cod-md** [comment]
I think because i can't download the patches
![Screenshot_20231029-233400_ReVanced_Manager](https://github.com/ReVanced/revanced-manager/assets/92212094/fb72b4e8-5674-40b2-99ce-66e836b32732)

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/1441
