### ISSUE TITLE
bug: YouTube patch fail with default patches

### ISSUE THREAD

**Issue by JosephBoom02** [ReVanced/revanced-manager#1466]
### Bug description

So, the title explains what is my problem: I select YouTube in the patcher section, I let the default patches and then I select patch, but at the end It says "Failed".
I didn't change any settings in Revanced Manager application (I enabled only Material You).
I installed YouTube from Aurora Store.

### Version of ReVanced Manager and version & name of application you tried to patch

YouTube version: 18.34.44 (the version suggested by the manager)
Revanced Manager version: 1.15.1

### Installation type

Root

### Device logs

```shell
--------- beginning of main
11-05 10:35:59.560 22663 22680 E OpenGLRenderer: Unable to match the desired swap behavior.
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=0
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=1
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=2
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=3
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=4
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=5
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=6
11-05 10:35:59.568 22663 22663 E SurfaceSyncer: Failed to find sync for id=7
11-05 10:35:59.584 22663 22663 E SurfaceSyncer: Failed to find sync for id=0
11-05 10:35:59.584 22663 22663 E SurfaceSyncer: Failed to find sync for id=1
11-05 10:35:59.584 22663 22663 E SurfaceSyncer: Failed to find sync for id=2
11-05 10:35:59.584 22663 22663 E SurfaceSyncer: Failed to find sync for id=3
11-05 10:35:59.584 22663 22663 E SurfaceSyncer: Failed to find sync for id=4
11-05 10:35:59.584 22663 22663 E SurfaceSyncer: Failed to find sync for id=5
11-05 10:35:59.585 22663 22663 E SurfaceSyncer: Failed to find sync for id=6
11-05 10:35:59.585 22663 22663 E SurfaceSyncer: Failed to find sync for id=7
11-05 10:36:00.347 22663 22685 I flutter : Error: google_fonts was unable to load font Inter-Regular because the following exception occurred:
11-05 10:36:00.347 22663 22685 I flutter : Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 40430, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:36:00.347 22663 22685 I flutter : See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
11-05 10:36:00.347 22663 22685 I flutter : If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
11-05 10:36:00.348 22663 22685 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 40430, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:36:00.348 22663 22685 E flutter : #0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:263)
11-05 10:36:00.348 22663 22685 E flutter : <asynchronous suspension>
11-05 10:36:00.348 22663 22685 E flutter : #1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:180)
11-05 10:36:00.348 22663 22685 E flutter : <asynchronous suspension>
11-05 10:36:00.348 22663 22685 E flutter : 
11-05 10:36:46.325 22663 22680 E OpenGLRenderer: Unable to match the desired swap behavior.
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=0
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=1
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=2
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=3
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=4
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=5
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=6
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=7
11-05 10:36:46.330 22663 22663 E SurfaceSyncer: Failed to find sync for id=8
11-05 10:36:48.537 22663 22685 I flutter : Error: google_fonts was unable to load font Inter-Regular because the following exception occurred:
11-05 10:36:48.537 22663 22685 I flutter : Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 43838, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:36:48.537 22663 22685 I flutter : See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
11-05 10:36:48.537 22663 22685 I flutter : If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
11-05 10:36:48.537 22663 22685 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 43838, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:36:48.537 22663 22685 E flutter : #0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:263)
11-05 10:36:48.537 22663 22685 E flutter : <asynchronous suspension>
11-05 10:36:48.537 22663 22685 E flutter : #1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:180)
11-05 10:36:48.537 22663 22685 E flutter : <asynchronous suspension>
11-05 10:36:48.537 22663 22685 E flutter : 
11-05 10:38:51.406 22663 22680 E OpenGLRenderer: Unable to match the desired swap behavior.
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=0
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=1
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=2
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=3
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=4
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=5
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=6
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=7
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=8
11-05 10:38:51.409 22663 22663 E SurfaceSyncer: Failed to find sync for id=9
11-05 10:40:45.186 22663 22680 E OpenGLRenderer: Unable to match the desired swap behavior.
11-05 10:40:45.188 22663 22663 E SurfaceSyncer: Failed to find sync for id=0
11-05 10:40:45.188 22663 22663 E SurfaceSyncer: Failed to find sync for id=1
11-05 10:40:45.188 22663 22663 E SurfaceSyncer: Failed to find sync for id=2
11-05 10:40:45.188 22663 22663 E SurfaceSyncer: Failed to find sync for id=3
11-05 10:40:45.189 22663 22663 E SurfaceSyncer: Failed to find sync for id=4
11-05 10:40:45.189 22663 22663 E SurfaceSyncer: Failed to find sync for id=5
11-05 10:40:45.189 22663 22663 E SurfaceSyncer: Failed to find sync for id=6
11-05 10:40:45.189 22663 22663 E SurfaceSyncer: Failed to find sync for id=7
11-05 10:40:45.189 22663 22663 E SurfaceSyncer: Failed to find sync for id=8
11-05 10:40:45.189 22663 22663 E SurfaceSyncer: Failed to find sync for id=9
11-05 10:40:45.189 22663 22663 E SurfaceSyncer: Failed to find sync for id=10
11-05 10:40:46.011 22663 22685 I flutter : Error: google_fonts was unable to load font Inter-Regular because the following exception occurred:
11-05 10:40:46.011 22663 22685 I flutter : Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 44682, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:40:46.011 22663 22685 I flutter : See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
11-05 10:40:46.011 22663 22685 I flutter : If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
11-05 10:40:46.011 22663 22685 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 44682, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:40:46.011 22663 22685 E flutter : #0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:263)
11-05 10:40:46.011 22663 22685 E flutter : <asynchronous suspension>
11-05 10:40:46.011 22663 22685 E flutter : #1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:180)
11-05 10:40:46.011 22663 22685 E flutter : <asynchronous suspension>
11-05 10:40:46.011 22663 22685 E flutter : 
11-05 10:40:52.671 22663 22663 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10724; state: ENABLED
11-05 10:41:00.917 22663 22663 I InstallPlugin: handleActivityResult(22643,0,null)
11-05 10:41:06.297 22663 22685 I flutter : Error: google_fonts was unable to load font Inter-Regular because the following exception occurred:
11-05 10:41:06.297 22663 22685 I flutter : Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 45182, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:41:06.297 22663 22685 I flutter : See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
11-05 10:41:06.297 22663 22685 I flutter : If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
11-05 10:41:06.298 22663 22685 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 45182, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:41:06.298 22663 22685 E flutter : #0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:263)
11-05 10:41:06.298 22663 22685 E flutter : <asynchronous suspension>
11-05 10:41:06.298 22663 22685 E flutter : #1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:180)
11-05 10:41:06.298 22663 22685 E flutter : <asynchronous suspension>
11-05 10:41:06.298 22663 22685 E flutter : 
11-05 10:41:31.101 22663 22680 E OpenGLRenderer: Unable to match the desired swap behavior.
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=0
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=1
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=2
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=3
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=4
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=5
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=6
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=7
11-05 10:41:31.107 22663 22663 E SurfaceSyncer: Failed to find sync for id=8
11-05 10:41:31.108 22663 22663 E SurfaceSyncer: Failed to find sync for id=9
11-05 10:41:31.108 22663 22663 E SurfaceSyncer: Failed to find sync for id=10
11-05 10:41:31.108 22663 22663 E SurfaceSyncer: Failed to find sync for id=11
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=0
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=1
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=2
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=3
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=4
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=5
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=6
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=7
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=8
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=9
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=10
11-05 10:41:31.117 22663 22663 E SurfaceSyncer: Failed to find sync for id=11
11-05 10:41:31.623 22663 22685 I flutter : Error: google_fonts was unable to load font Inter-Regular because the following exception occurred:
11-05 10:41:31.623 22663 22685 I flutter : Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 46736, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:41:31.624 22663 22685 I flutter : See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
11-05 10:41:31.624 22663 22685 I flutter : If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
11-05 10:41:31.624 22663 22685 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 46736, uri=https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf
11-05 10:41:31.624 22663 22685 E flutter : #0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:263)
11-05 10:41:31.624 22663 22685 E flutter : <asynchronous suspension>
11-05 10:41:31.624 22663 22685 E flutter : #1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:180)
11-05 10:41:31.624 22663 22685 E flutter : <asynchronous suspension>
11-05 10:41:31.624 22663 22685 E flutter : 
11-05 10:41:45.468 22663 22663 I InstallPlugin: handleActivityResult(22643,0,null)
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.15.1
Build: release
Model: KB2003
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v18.38.44
Patches version: v2.196.0
Patches: Alternative thumbnails, Always autorepeat, Announcements, Bypass URL redirects, Client spoof, Comments, Copy video url, Custom player overlay opacity, Disable Shorts on startup, Disable auto captions, Disable fullscreen ambient mode, Disable player popup panels, Disable precise seeking gesture, Disable suggested video end screen, Disable zoom haptics, Enable debugging, Enable old seekbar thumbnails, Enable tablet layout, External downloads, HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, Hide crowdfunding box, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide timestamp, Hide video action buttons, Minimized playback, Navigation buttons, Old video quality menu, Open links externally, Playback speed, Player flyout menu, Premium heading [Use premium heading: true], Remember video quality, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Spoof device dimensions, Swipe controls, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Vanced MicroG support, Video ads, Wide searchbar

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Alternative thumbnails succeeded
Always autorepeat succeeded
Announcements succeeded
Bypass URL redirects succeeded
Client spoof succeeded
Comments succeeded
Copy video url succeeded
Custom player overlay opacity succeeded
Disable Shorts on startup succeeded
Disable auto captions succeeded
Disable fullscreen ambient mode succeeded
Disable player popup panels succeeded
Disable precise seeking gesture succeeded
Disable suggested video end screen succeeded
Disable zoom haptics succeeded
Enable debugging succeeded
Enable old seekbar thumbnails succeeded
Enable tablet layout succeeded
External downloads succeeded
HDR auto brightness succeeded
Hide 'Load more' button succeeded
Hide Shorts components succeeded
Hide ads succeeded
Hide album cards succeeded
Hide autoplay button succeeded
Hide breaking news shelf succeeded
Hide captions button succeeded
Hide cast button succeeded
Hide crowdfunding box succeeded
Hide email address succeeded
Hide endscreen cards succeeded
Hide filter bar succeeded
Hide floating microphone button succeeded
Hide info cards succeeded
Hide layout components succeeded
Hide player buttons succeeded
Hide seekbar succeeded
Hide timestamp succeeded
Hide video action buttons succeeded
Minimized playback succeeded
Navigation buttons succeeded
Old video quality menu succeeded
Open links externally succeeded
Playback speed succeeded
Player flyout menu succeeded
Premium heading failed: app.revanced.patcher.patch.PatchException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.nio.file.NoSuchFileException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at app.revanced.patches.youtube.layout.branding.header.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:58)
	at app.revanced.patches.youtube.layout.branding.header.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:11)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	... 18 more
Remember video quality succeeded
Return YouTube Dislike succeeded
Seekbar tapping succeeded
SponsorBlock succeeded
Spoof app version succeeded
Spoof device dimensions succeeded
Swipe controls succeeded
Tablet mini player succeeded
Theme succeeded
Vanced MicroG support succeeded
Video ads succeeded
Wide searchbar succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4BtFnW6eiMmZhGcRVASMQA==/app.revanced.manager.flutter-gpuoMK_JR4tNEYUka7rFtw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL9212074635690841495.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:262)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:332)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4BtFnW6eiMmZhGcRVASMQA==/app.revanced.manager.flutter-gpuoMK_JR4tNEYUka7rFtw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL9212074635690841495.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUXFWW/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
You are patching a split APK file but you need a full one
