### ISSUE TITLE
bug: failed to build 

### ISSUE THREAD

**Issue by not-programmer98** [ReVanced/revanced-manager#1477]
### Bug description

Failed to build YouTube I put the logs below

### Version of ReVanced Manager and version & name of application you tried to patch

Version 1.15.1
YouTube 

### Installation type

Non-root

### Device logs

```shell
- Device Info
ReVanced Manager: 1.15.1
Build: release
Model: SM-T585
Android version: 8.1.0
Supported architectures: armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.38.44
Patches version: v2.196.0
Patches: Alternative thumbnails, Always autorepeat, Announcements, Bypass URL redirects, Client spoof, Comments, Copy video url, Custom branding [App name: YouTube ReVanced, App icon: ReVanced*Logo], Custom player overlay opacity, Disable Shorts on startup, Disable auto captions, Disable fullscreen ambient mode, Disable player popup panels, Disable precise seeking gesture, Disable suggested video end screen, Disable zoom haptics, Enable debugging, Enable old seekbar thumbnails, Enable tablet layout, External downloads, HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, Hide crowdfunding box, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide timestamp, Hide video action buttons, Minimized playback, Navigation buttons, Old video quality menu, Open links externally, Playback speed, Player flyout menu, Premium heading [Use premium heading: true], Remember video quality, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Spoof device dimensions, Swipe controls, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Vanced MicroG support, Video ads, Wide searchbar

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Alternative thumbnails succeeded
Always autorepeat succeeded
Announcements succeeded
Bypass URL redirects succeeded
Client spoof succeeded
Comments succeeded
Copy video url succeeded
Custom branding succeeded
Custom player overlay opacity succeeded
Disable Shorts on startup succeeded
Disable auto captions succeeded
Disable fullscreen ambient mode succeeded
Disable player popup panels succeeded
Disable precise seeking gesture succeeded
Disable suggested video end screen succeeded
Disable zoom haptics succeeded
Enable debugging succeeded
Enable old seekbar thumbnails succeeded
Enable tablet layout succeeded
External downloads succeeded
HDR auto brightness succeeded
Hide 'Load more' button succeeded
Hide Shorts components succeeded
Hide ads succeeded
Hide album cards succeeded
Hide autoplay button succeeded
Hide breaking news shelf succeeded
Hide captions button succeeded
Hide cast button succeeded
Hide crowdfunding box succeeded
Hide email address succeeded
Hide endscreen cards succeeded
Hide filter bar succeeded
Hide floating microphone button succeeded
Hide info cards succeeded
Hide layout components succeeded
Hide player buttons succeeded
Hide seekbar succeeded
Hide timestamp succeeded
Hide video action buttons succeeded
Minimized playback succeeded
Navigation buttons succeeded
Old video quality menu succeeded
Open links externally succeeded
Playback speed succeeded
Player flyout menu succeeded
Premium heading succeeded
Remember video quality succeeded
Return YouTube Dislike succeeded
Seekbar tapping succeeded
SponsorBlock succeeded
Spoof app version succeeded
Spoof device dimensions succeeded
Swipe controls succeeded
Tablet mini player succeeded
Theme succeeded
Vanced MicroG support succeeded
Video ads succeeded
Wide searchbar succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-Un4DVugrwyY-f_TGuu9XiA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4239446237636356323.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:262)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:332)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:764)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-Un4DVugrwyY-f_TGuu9XiA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4239446237636356323.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.15.1
Build: release
Model: SM-T585
Android version: 8.1.0
Supported architectures: armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.38.44
Patches version: v2.196.0
Patches: Alternative thumbnails, Always autorepeat, Announcements, Bypass URL redirects, Client spoof, Comments, Copy video url, Custom branding [App name: YouTube ReVanced, App icon: ReVanced*Logo], Custom player overlay opacity, Disable Shorts on startup, Disable auto captions, Disable fullscreen ambient mode, Disable player popup panels, Disable precise seeking gesture, Disable suggested video end screen, Disable zoom haptics, Enable debugging, Enable old seekbar thumbnails, Enable tablet layout, External downloads, HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, Hide crowdfunding box, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide timestamp, Hide video action buttons, Minimized playback, Navigation buttons, Old video quality menu, Open links externally, Playback speed, Player flyout menu, Premium heading [Use premium heading: true], Remember video quality, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Spoof device dimensions, Swipe controls, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Vanced MicroG support, Video ads, Wide searchbar

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Alternative thumbnails succeeded
Always autorepeat succeeded
Announcements succeeded
Bypass URL redirects succeeded
Client spoof succeeded
Comments succeeded
Copy video url succeeded
Custom branding succeeded
Custom player overlay opacity succeeded
Disable Shorts on startup succeeded
Disable auto captions succeeded
Disable fullscreen ambient mode succeeded
Disable player popup panels succeeded
Disable precise seeking gesture succeeded
Disable suggested video end screen succeeded
Disable zoom haptics succeeded
Enable debugging succeeded
Enable old seekbar thumbnails succeeded
Enable tablet layout succeeded
External downloads succeeded
HDR auto brightness succeeded
Hide 'Load more' button succeeded
Hide Shorts components succeeded
Hide ads succeeded
Hide album cards succeeded
Hide autoplay button succeeded
Hide breaking news shelf succeeded
Hide captions button succeeded
Hide cast button succeeded
Hide crowdfunding box succeeded
Hide email address succeeded
Hide endscreen cards succeeded
Hide filter bar succeeded
Hide floating microphone button succeeded
Hide info cards succeeded
Hide layout components succeeded
Hide player buttons succeeded
Hide seekbar succeeded
Hide timestamp succeeded
Hide video action buttons succeeded
Minimized playback succeeded
Navigation buttons succeeded
Old video quality menu succeeded
Open links externally succeeded
Playback speed succeeded
Player flyout menu succeeded
Premium heading succeeded
Remember video quality succeeded
Return YouTube Dislike succeeded
Seekbar tapping succeeded
SponsorBlock succeeded
Spoof app version succeeded
Spoof device dimensions succeeded
Swipe controls succeeded
Tablet mini player succeeded
Theme succeeded
Vanced MicroG support succeeded
Video ads succeeded
Wide searchbar succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-Un4DVugrwyY-f_TGuu9XiA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4239446237636356323.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:262)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:332)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:764)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-Un4DVugrwyY-f_TGuu9XiA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1540236736, --version-name, 18.38.44, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4239446237636356323.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IUBHMC/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
ARMv7 isn't supported

**Comment by odkate** [comment]
on the version v1.21.0 has already been fixed, now can patch on the armeabi-v7a devices
