### ISSUE TITLE
Compiling Resources fails on Samsung Galaxy S21

### ISSUE THREAD

**Issue by fluxie31** [ReVanced/revanced-manager#1551]
### Bug description

Watching carefully the build fails when resource compilation starts. After two tries all classes compiled successfully but both runs failed at the "Compiling resources" part.

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced: 1.17.1
YouTube: 18.45.43 (from file)

### Installation type

Non-root

### Device logs

```shell
Uploaded https://github.com/ReVanced/revanced-manager/files/13555610/revanced-manager_logcat_20231204212736912445.log
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: SM-G991U
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.43
Patches version: v2.202.0
Patches added: Alternative thumbnails, Always autorepeat, Announcements, Bypass URL redirects, Client spoof, Comments, Copy video url, Custom player overlay opacity, Disable auto captions, Disable fullscreen ambient mode, Disable player popup panels, Disable precise seeking gesture, Disable resuming Shorts on startup, Disable rolling number animations, Disable suggested video end screen, Disable zoom haptics, Enable debugging, Enable slide to seek, Enable tablet layout, External downloads, HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, Hide crowdfunding box, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide timestamp, Hide video action buttons, Minimized playback, Navigation buttons, Open links externally, Playback speed, Player flyout menu, Premium heading [Use premium heading: true], Remember video quality, Remove tracking query parameter, Restore old seekbar thumbnails, Restore old video quality menu, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Spoof device dimensions, Swipe controls, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Vanced MicroG support, Video ads, Wide searchbar
Patches removed: Hide ads, Video ads, Copy video url, External downloads, Disable precise seeking gesture, Seekbar tapping, Enable slide to seek, Swipe controls, Disable auto captions, Premium heading [Use premium heading: true], Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Hide email address, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Alternative thumbnails, Announcements, Always autorepeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Vanced MicroG support, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, Open links externally
Options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 61 patches
Premium heading failed: app.revanced.patcher.patch.PatchException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.nio.file.NoSuchFileException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at app.revanced.patches.youtube.layout.branding.header.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:58)
	at app.revanced.patches.youtube.layout.branding.header.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:11)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	... 18 more
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4i8kf9FJZtbL-atIo5Qzjg==/app.revanced.manager.flutter-vKCKRoVzqj4oj70gVU-Qag==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541152192, --version-name, 18.45.43, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7960189246627896435.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:354)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4i8kf9FJZtbL-atIo5Qzjg==/app.revanced.manager.flutter-vKCKRoVzqj4oj70gVU-Qag==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541152192, --version-name, 18.45.43, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7960189246627896435.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TTPSJY/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by TheAabedKhan** [comment]
You're patching a split apk. Download the full apk of YouTube from APKMirror and try again.
