### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Kaustubh18111** [ReVanced/revanced-manager#1554]
### Bug description

It's failing to patch and then app becomes unresponsive 

### Version of ReVanced Manager and version & name of application you tried to patch

Manager version 1.17.1
App tried to patch YouTube on sugested 18.45.43

### Installation type

Non-root

### Device logs

```shell
Am unable to get it
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: EB2101
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.43
Patches version: v2.202.0
Patches added: Always autorepeat, Announcements, Bypass URL redirects, Client spoof, Comments, Copy video url, Custom player overlay opacity, Disable auto captions, Disable fullscreen ambient mode, Disable player popup panels, Disable resuming Shorts on startup, Disable zoom haptics, Enable slide to seek, Enable tablet layout, External downloads, HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, Hide crowdfunding box, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide timestamp, Hide video action buttons, Minimized playback, Navigation buttons, Open links externally, Playback speed, Player flyout menu, Premium heading [Use premium heading: true], Remember video quality, Remove screen capture restriction, Remove screenshot restriction, Restore old seekbar thumbnails, Restore old video quality menu, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Spoof device dimensions, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Vanced MicroG support, Video ads, Wide searchbar
Patches removed: Hide ads, Video ads, Copy video url, External downloads, Disable precise seeking gesture, Seekbar tapping, Enable slide to seek, Swipe controls, Disable auto captions, Premium heading [Use premium heading: true], Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Hide email address, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Alternative thumbnails, Announcements, Always autorepeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Vanced MicroG support, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, Open links externally
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
An error occurred:
java.lang.IncompatibleClassChangeError: Class 'app.revanced.patches.shared.integrations.AbstractIntegrationsPatch$IntegrationsFingerprint$1' does not implement interface 'java.lang.Iterable' in call to 'java.util.Iterator java.lang.Iterable.iterator()' (declaration of 'app.revanced.patcher.fingerprint.MethodFingerprint' appears in base.apk)
	at app.revanced.patcher.fingerprint.MethodFingerprint.resolveUsingLookupMap$methodStringsLookup(MethodFingerprint.kt:369)
	at app.revanced.patcher.fingerprint.MethodFingerprint.resolveUsingLookupMap$revanced_patcher(MethodFingerprint.kt:118)
	at app.revanced.patcher.fingerprint.MethodFingerprint$Companion.resolveUsingLookupMap$revanced_patcher(MethodFingerprint.kt:337)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Update
