### ISSUE TITLE
bug: patching Google Recorder errors out OR creates an unusable app

### ISSUE THREAD

**Issue by aetonsi** [ReVanced/revanced-manager#1570]
### Bug description

Hello,
trying to patch the Google Rec on my Xiaomi Mi A3 (NB: it's an **android one** phone), the only patch `RemoveDeviceRestrictions` either:
- **errors out**, the patching still goes on, then it generates a broken apk that **cannot** be installed (as if it wasn't patched and it's still device restricted)
- OR, **it does not produce any error**, the apk can be installed, but then the Google Rec app does **not** open nor crash: it does absolutely nothing, when trying to launch it from my launcher

The outcome depends purely on the Google Recorder app version i use.
I know there are multiple Google Recorder apk signatures, i just can't figure out which one to get and patch....

### Version of ReVanced Manager and version & name of application you tried to patch

- rev mgr: `1.17.3`
- google rec:
  - `4.2.20230801.561280372` (with this version i get no error, but then the app does not open)
  - `1.0.271580629` (with this extremely old version i get the error below)

### Installation type

Non-root

### Device logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: Mi A3
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.recorder v1.0.271580629
Patches version: v2.202.0
Patches added: Remove device restrictions
Patches removed: Remove device restrictions
Options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations
```

### Patcher logs

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Remove device restrictions failed: app.revanced.patcher.patch.PatchException: Failed to resolve OnApplicationCreateFingerprint
 at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:24)
 at app.revanced.patches.googlerecorder.restrictions.RemoveDeviceRestrictions.execute(RemoveDeviceRestrictions.kt:36)
 at app.revanced.patches.googlerecorder.restrictions.RemoveDeviceRestrictions.execute(RemoveDeviceRestrictions.kt:14)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
 at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
 at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
 at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
 at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
 at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
 at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
 at java.lang.Thread.run(Thread.java:923)
Compiling patched dex files
Compiled 4 dex files
Signing APK
Patched
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
This issue belongs in the [revanced-patches](https://github.com/ReVanced/revanced-patches) repository, however, I believe there are similar or identical issues already made there so please check for duplicates before opening an issue there. Thanks!

**Comment by aetonsi** [comment]
@KobeW50 oh sorry! i will check there. i thought this was the right place. Thank you both.
