### ISSUE TITLE
bug: not able to patch tiktok due to no more space in heap for allocation

### ISSUE THREAD

**Issue by aikooo7** [ReVanced/revanced-manager#1571]
### Bug description

When trying to patch version 32.5.3 of TikTok with Revanced version 1.17.3 I get a lot of class.dex decompilation at a point that no space in heap is left.

- Steps to reproduce:
    - Download Revanced manager and TikTok with the specified version;
    - Apply the following patches:
        - Downloads;
        - Feed filter;
        - Fix Google login;
        - Feed filter;
        - Playback speed;
        - Settings;
        - Show seekbar.
    - Wait until you get a heap allocation memory error.

### Version of ReVanced Manager and version & name of application you tried to patch

- Revanced:
    - Version: 
        - 1.17.3
- Patched app:
    - Name:
        - TikTok
    - Version:
        - 32.5.3

### Installation type

None

### Device logs

```shell
--------- beginning of main
12-14 23:11:10.358 29011 29029 E OpenGLRenderer: Unable to match the desired swap behavior.
12-14 23:11:10.367 29011 29011 E SurfaceSyncer: Failed to find sync for id=0
12-14 23:11:10.367 29011 29011 E SurfaceSyncer: Failed to find sync for id=1
12-14 23:11:10.367 29011 29011 E SurfaceSyncer: Failed to find sync for id=2
12-14 23:11:10.367 29011 29011 E SurfaceSyncer: Failed to find sync for id=3
12-14 23:11:10.367 29011 29011 E SurfaceSyncer: Failed to find sync for id=4
12-14 23:11:10.367 29011 29011 E SurfaceSyncer: Failed to find sync for id=5
12-14 23:11:10.367 29011 29011 E SurfaceSyncer: Failed to find sync for id=6
12-14 23:11:12.134 29011 29011 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
12-14 23:11:12.134 29011 29011 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
12-14 23:11:19.278 29011 29029 E OpenGLRenderer: Unable to match the desired swap behavior.
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=0
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=1
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=2
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=3
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=4
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=5
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=6
12-14 23:11:19.280 29011 29011 E SurfaceSyncer: Failed to find sync for id=7
12-14 23:11:35.534 29011 29029 E OpenGLRenderer: Unable to match the desired swap behavior.
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=0
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=1
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=2
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=3
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=4
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=5
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=6
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=7
12-14 23:11:35.536 29011 29011 E SurfaceSyncer: Failed to find sync for id=8
12-14 23:11:43.646 29011 29029 E OpenGLRenderer: Unable to match the desired swap behavior.
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=0
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=1
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=2
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=3
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=4
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=5
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=6
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=7
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=8
12-14 23:11:43.649 29011 29011 E SurfaceSyncer: Failed to find sync for id=9
12-14 23:11:50.517 29011 29029 E OpenGLRenderer: Unable to match the desired swap behavior.
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=0
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=1
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=2
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=3
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=4
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=5
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=6
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=7
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=8
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=9
12-14 23:11:50.519 29011 29011 E SurfaceSyncer: Failed to find sync for id=10
12-14 23:12:34.015 29011 29029 E OpenGLRenderer: Unable to match the desired swap behavior.
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=0
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=1
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=2
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=3
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=4
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=5
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=6
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=7
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=8
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=9
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=10
12-14 23:12:34.017 29011 29011 E SurfaceSyncer: Failed to find sync for id=11
12-14 23:12:48.094 29011 29029 E OpenGLRenderer: Unable to match the desired swap behavior.
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=0
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=1
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=2
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=3
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=4
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=5
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=6
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=7
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=8
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=9
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=10
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=11
12-14 23:12:48.097 29011 29011 E SurfaceSyncer: Failed to find sync for id=12
12-14 23:12:49.955 29011 29011 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10177; state: ENABLED
12-14 23:13:07.014 29011 29011 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10177; state: ENABLED
12-14 23:13:07.020 29011 29011 I InstallPlugin: handleActivityResult(22643,0,null)
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: Pixel 6 Pro
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.zhiliaoapp.musically v32.5.3 (Suggested: v32.5.3)
Patches version: v3.1.0
Patches added: Downloads, Feed filter, Fix Google login, Playback speed, Settings, Show seekbar
Patches removed: Feed filter, Downloads, Show seekbar, Playback speed, Disable login requirement, Fix Google login, Settings
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 6 patches
Compiling patched dex files
Compiled 21 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1881240 free bytes and 1837KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.buildInstruction(DexBackedInstruction.java:96)
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.readFrom(DexBackedInstruction.java:68)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:93)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:86)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:59)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.internCode(ClassPool.java:158)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.intern(ClassPool.java:140)
	at com.android.tools.smali.dexlib2.writer.pool.DexPool.internClass(DexPool.java:129)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:143)
	at lanchon.multidexlib2.DexIO.access$000(DexIO.java:37)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:102)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/592
