### ISSUE TITLE
bug: Reddit keeps crashing after patch

### ISSUE THREAD

**Issue by Inf4ge** [revanced/revanced-manager#159]
### Type

Error at runtime

### Branch

Flutter

### Bug description

Found while trying to launch Reddit

### Steps to reproduce

1- Download Reddit
2- Patch it
3- After patch, uninstall original Reddit because otherwise it won't install the patched one
4- Install patched app (Non-root)
5- Launch

### Relevant log output

```shell
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.reddit.frontpage/com.reddit.frontpage.main.MainActivity}: android.view.InflateException: Binary XML file line #34 in com.reddit.frontpage:layout/activity_main: Binary XML file line #24: You must supply a layout_height attribute.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3539)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3699)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.view.InflateException: Binary XML file line #34 in com.reddit.frontpage:layout/activity_main: Binary XML file line #24: You must supply a layout_height attribute.
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #24: You must supply a layout_height attribute.
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:832)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8323)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8520)
	at androidx.constraintlayout.widget.ConstraintLayout$a.<init>(ConstraintLayout.java:1)
	at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:2)
	at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1265)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at h.e.w(AppCompatDelegateImpl.java:4)
	at androidx.appcompat.app.f.setContentView(AppCompatActivity.java:2)
	at mu0.a.onCreate(BaseActivity.java:12)
	at com.reddit.frontpage.main.MainActivity.onCreate(MainActivity.java:9)
	at android.app.Activity.performCreate(Activity.java:8157)
	at android.app.Activity.performCreate(Activity.java:8129)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3512)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3699)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/69483795/190852486-1953edc5-107d-4018-8671-7f94528b4ce1.png)

### Additional context

Reddit Ver.   2022.33.0
MIUI Global 12.5.2.0 Stable

**Comment by Aunali321** [comment]
Where did you download reddit from? and is it full or split apk?

**Comment by Aiakio** [comment]
Same issue here. Downloaded reddit from play store.

**Comment by Aunali321** [comment]
Play Store version won't work. Download reddit from apkmirror. Make sure its full apk (200mb).

**Comment by Aiakio** [comment]
> Play Store version won't work. Download reddit from apkmirror. Make sure its full apk (200mb).

This was the solution. Also for Twitter. Thank you.
