### ISSUE TITLE
bug: Compiler crashes when patching youtube

### ISSUE THREAD

**Issue by Nubidubi23** [ReVanced/revanced-manager#1649]
### Bug description

Step 1. Downloaded Youtube 18.45.43 from apkmirror
Step 2. Download the manager from https://revanced.app/
Step 3. Grant the manager root access and try to patch youtube with the default patch selection

### Version of ReVanced Manager and version & name of application you tried to patch

Version: 1.18.0
Model: SM-G991B
Android Version: 12
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

Youtube version: 18.45.43

### Installation type

Root

### Device logs

```shell
https://mega.nz/file/tMJBkRaC#qYI5QIGcPhICqZDWzAKeccF_zZGj8cvGMCASjGipEUA
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: SM-G991B
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v18.45.43 (Suggested: v18.45.43)
Patches version: v3.2.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 62 patches
Premium heading failed: app.revanced.patcher.patch.PatchException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.nio.file.NoSuchFileException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:259)
	at java.nio.file.Files.copy(Files.java:1274)
	at app.revanced.patches.youtube.layout.branding.header.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:58)
	at app.revanced.patches.youtube.layout.branding.header.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:11)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	... 18 more
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~VuCua97LWy_HHn5AdHBmQQ==/app.revanced.manager.flutter-P11X3yVL8hGDdgFPrKIG6Q==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541152192, --version-name, 18.45.43, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3396939280826215464.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:371)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~VuCua97LWy_HHn5AdHBmQQ==/app.revanced.manager.flutter-P11X3yVL8hGDdgFPrKIG6Q==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541152192, --version-name, 18.45.43, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3396939280826215464.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BVZWDD/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Nubidubi23** [comment]
Tried disabling Premium Header and i get the same error. The premium header error obviously disappears but the brut.androlib.exceptions.AndrolibException remains and the patch still fails

**Comment by yonggamer** [comment]
try reinstall the manager and then trie disabling Premium Header

**Comment by Nubidubi23** [comment]
I've already tried disabling premium header. Reinstalling didn't help either

**Comment by oSumAtrIX** [comment]
You don't have enough space, please make more free.

**Comment by yonggamer** [comment]
[split_merged.z01.zip](https://github.com/ReVanced/revanced-manager/files/14073344/split_merged.z01.zip)
[split_merged.zip](https://github.com/ReVanced/revanced-manager/files/14073345/split_merged.zip)
maby is drawable-xxxhdpi/yt_premium_wordmark_header_light.png missing try it with this apk

**Comment by fillwithjoy1** [comment]
Same error. The only time this ever worked was when I factory reset this device. Don't want to deal with this hassle if this keeps happening

- Device Info
ReVanced Manager: 1.20.1
Model: Pixel 6 Pro
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.9.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 58 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~gBb9Dh36LGgeLevo0OGfUA==/app.revanced.manager.flutter-ELXpOouDtrkOLi7VsCpRqw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL878425225282740257.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~gBb9Dh36LGgeLevo0OGfUA==/app.revanced.manager.flutter-ELXpOouDtrkOLi7VsCpRqw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL878425225282740257.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QCUFPC/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
