### ISSUE TITLE
bug: Error while compiling Youtube without GmsCore patch

### ISSUE THREAD

**Issue by MattFromGer** [ReVanced/revanced-manager#1658]
### Bug description

1. Download latest Youtube app (19.03.35) from PlayStore
2. Install latest ReVanced (v1.18.0 or v1.19.0-dev.3)
3. Standard patches except de-select GmsCore

Device logs:
[revanced-manager_logcat_20240127145148473281.log](https://github.com/ReVanced/revanced-manager/files/14072554/revanced-manager_logcat_20240127145148473281.log)

### Version of ReVanced Manager and version & name of application you tried to patch

v1.18.0 or v1.19.0-dev.3

### Installation type

Root

### Device logs

```shell
see attached file above
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.19.0-dev.3
Model: SM-G998B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.03.35 (Suggested: 19.03.35)
Patches version: v4.0.1
Patches added: Default
Patches removed: GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~IcYBHU8HXlXeyBuWo40qvg==/app.revanced.manager.flutter-WI_w8Fxn8_6RL4Y1-3pyLw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL991676130144856508.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:371)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~IcYBHU8HXlXeyBuWo40qvg==/app.revanced.manager.flutter-WI_w8Fxn8_6RL4Y1-3pyLw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL991676130144856508.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AAROQQ/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 morereAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
You have toggled settings in ReVanced Manager that are not recommended to change. Please review the warnings that appear when adjusting these settings and reset them to their default configuration.

**Comment by MattFromGer** [comment]
> Try patching a full APK

Thank you! Tried with a full apk (19.03.35 (nodpi)) and now compiling was successful! Unfortunately after installing it as "mount" the app won't open. Clicking on "open" doesn't do anything, the manager is basically frozen, can't even use the back button. When opening Youtube trough the app drawer, it immediately closes again without error.

```
- Device Info
ReVanced Manager: 1.19.0-dev.3
Model: SM-G998B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.apps.youtube v19.03.35 (Suggested: Any)
Patches version: v4.0.1
Patches added: Enable slide to seek
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 61 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK
Mounting patched app
Installed
```

It says `Patches removed: None` even though I removed GmsCore.
[revanced-manager_logcat_20240127181354120490.log](https://github.com/ReVanced/revanced-manager/files/14073184/revanced-manager_logcat_20240127181354120490.log)

**Comment by oSumAtrIX** [comment]
Please open an issue regarding that with a recording
