### ISSUE TITLE
Unable to patch latest Facebook APK

### ISSUE THREAD

**Issue by lothkang** [ReVanced/revanced-manager#1667]
### Bug description

I'm unable to patch Facebook.
- The APK was downloaded from APK Mirror and from APK Pure, but no luck with either versions.
- Selected patch: Hide story ads

### Version of ReVanced Manager and version & name of application you tried to patch

- ReVanced Manager: 1.18.0
- App: com.facebook.katana v448.0.0.30.11

### Installation type

Non-root

### Device logs

```shell
--------- beginning of system
01-30 13:21:07.242 32322 32322 D MiuiMultiWindowUtils: freeform resolution args raw data:{  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}    },    "mini_freeform_args":{        "vertical_portrait":{"original_ratio":0.147},        "horizontal_portrait":{"original_ratio":0.147},        "vertical_landscape":{"original_ratio":0.165},        "horizontal_landscape":{"original_ratio":0.165}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}    },    "mini_freeform_args":{        "vertical_portrait":{"original_ratio":0.26},        "horizontal_portrait":{"original_ratio":0.26},        "vertical_landscape":{"original_ratio":0.293},        "horizontal_landscape":{"original_ratio":0.293}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.4244,"top_margin":0.109,"left_margin":-1},      "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.4244,"top_margin":-1,"left_margin":0.026}    },    "mini_freeform_args":{      "vertical_portrait":{"original_ratio":0.25},      "horizontal_portrait":{"original_ratio":0.25},      "vertical_landscape":{"original_ratio":0.25},      "horizontal_landscape":{"original_ratio":0.25}    }  },  "pad_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.375,"original_scale":0.835,"top_margin":0.049,"left_margin":0.2775},      "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.375,"original_scale":0.835,"top_margin":-1,"left_margin":0.6525},      "vertical_landscape":{"aspect_ratio":-1, "original_ratio":1,"original_scale":0.468,"top_margin":0.049,"left_margin":-1},      "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":1,"original_scale":0.468,"top_margin":-1,"left_margin":0.4976}    },    "mini_freeform_args":{      "vertical_portrait":{"original_ratio":0.144},      "horizontal_portrait":{"original_ratio":0.144},      "vertical_landscape":{"original_ratio":0.2},      "horizontal_landscape":{"original_ratio":0.2}    }  }}
01-30 13:21:07.242 32322 32322 D MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is taoyao
01-30 13:21:07.300 32322 32322 D FramePredict: FramePredict init: false
01-30 13:21:07.301 32322 32322 D FramePredict: init success
01-30 13:21:07.305 32322 32369 E FramePredict: registerContentObserver fail
01-30 13:21:07.312 32322 32322 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ed46fa1, reason: AppDarkModeEnable
01-30 13:21:07.327 32322 32322 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=642ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=135ms seq=2 running=46ms runnable=29ms io=38ms late=20ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=504ms seq=3 running=91ms runnable=17ms io=121ms late=143ms h=android.app.ActivityThread$H w=159)
01-30 13:21:08.066 32322 32322 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=517ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=529ms seq=24 running=45ms runnable=4ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
01-30 13:21:08.628 32322 32322 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=531ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=533ms seq=30 running=44ms runnable=6ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
01-30 13:21:18.084 32322 32322 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ed46fa1, reason: AppDarkModeEnable
01-30 13:21:18.111 32322 32322 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
01-30 13:21:18.112 32322 32322 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
01-30 13:21:18.436 32322 32322 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_MEDIA_LOCATION in package: com.facebook.katana at: Binary XML file line #68
01-30 13:21:18.437 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #190
01-30 13:21:18.437 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #225
01-30 13:21:18.437 32322 32322 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: com.google.android.gms.permission.AD_ID in package: com.facebook.katana at: Binary XML file line #233
01-30 13:21:18.437 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #242
01-30 13:21:18.437 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #247
01-30 13:21:18.439 32322 32322 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #708
01-30 13:21:18.454 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #4119
01-30 13:21:44.046 32322 32322 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ed46fa1, reason: AppDarkModeEnable
01-30 13:21:44.063 32322 32322 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
01-30 13:21:44.066 32322 32322 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
01-30 13:21:44.367 32322 32322 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_MEDIA_LOCATION in package: com.facebook.katana at: Binary XML file line #68
01-30 13:21:44.367 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #190
01-30 13:21:44.367 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #225
01-30 13:21:44.367 32322 32322 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: com.google.android.gms.permission.AD_ID in package: com.facebook.katana at: Binary XML file line #233
01-30 13:21:44.367 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #242
01-30 13:21:44.367 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #247
01-30 13:21:44.370 32322 32322 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #708
01-30 13:21:44.392 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #4119
01-30 13:21:46.507 32322 32322 W Looper  : PerfMonitor longMsg : seq=347 plan=13:21:45.315 late=15ms wall=1176ms running=112ms runnable=7ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
01-30 13:29:55.025 32322 32322 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ed46fa1, reason: AppDarkModeEnable
--------- beginning of main
01-30 13:29:55.038 32322 32371 D AppScoutStateMachine: 32322-ScoutStateMachinecreated
01-30 13:29:55.119 32322 32351 E libEGL  : pre_cache appList: ,,
01-30 13:29:55.120 32322 32322 D VRI[MainActivity]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4337 android.view.ViewRootImpl.doTraversal:2977 android.view.ViewRootImpl$TraversalRunnable.run:10289 android.view.Choreographer$CallbackRecord.run:1626 android.view.Choreographer$CallbackRecord.run:1635 
01-30 13:29:55.120 32322 32322 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#25617)/@0x25f8b81, mIsProjectionMode = false
01-30 13:29:55.121 32322 32322 D VRI[MainActivity]: vri.Setup new sync=wmsSync-VRI[MainActivity]#12
01-30 13:29:55.122 32322 32351 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 13:29:55.127 32322 32351 D OpenGLRenderer: makeCurrent grContext:0xb400007a91e8ad80 reset mTextureAvailable
01-30 13:29:55.133 32322 32322 D VRI[MainActivity]: vri.reportDrawFinished
01-30 13:29:55.145 32322 32322 I HandWritingStubImpl: refreshLastKeyboardType: 1
01-30 13:29:55.145 32322 32322 I HandWritingStubImpl: getCurrentKeyboardType: 1
01-30 13:29:59.065 32322 32322 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10271; state: ENABLED
01-30 13:30:22.940 32322 32322 I HandWritingStubImpl: refreshLastKeyboardType: 1
01-30 13:30:22.941 32322 32322 I HandWritingStubImpl: getCurrentKeyboardType: 1
01-30 13:30:31.709 32322 32322 I HandWritingStubImpl: refreshLastKeyboardType: 1
01-30 13:30:31.709 32322 32322 I HandWritingStubImpl: getCurrentKeyboardType: 1
01-30 13:30:35.587 32322 32322 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
01-30 13:30:35.587 32322 32322 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
01-30 13:30:36.380 32322 32322 D FlutterFileDialogPlugin: onMethodCall - IN , method=pickFile
01-30 13:30:36.384 32322 32322 D FileDialog: pickFile - IN, fileExtensionsFilter=[Ljava.lang.String;@524067a, mimeTypesFilter=null, localOnly=false, copyFileToCacheDir=true
01-30 13:30:36.422 32322 32322 D FileDialog: pickFile - OUT
01-30 13:30:40.032 32322 32322 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ed46fa1, reason: AppDarkModeEnable
01-30 13:30:40.059 32322 32339 D AppScoutStateMachine: 32322-ScoutStateMachinecreated
01-30 13:30:40.061 32322 32322 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
01-30 13:30:40.064 32322 32322 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
01-30 13:30:40.068 32322 32322 D FileDialog: Picked file: content://com.android.providers.downloads.documents/document/1130
01-30 13:30:40.121 32322 32351 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 13:30:40.125 32322 32322 D VRI[MainActivity]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4337 android.view.ViewRootImpl.doTraversal:2977 android.view.ViewRootImpl$TraversalRunnable.run:10289 android.view.Choreographer$CallbackRecord.run:1626 android.view.Choreographer$CallbackRecord.run:1635 
01-30 13:30:40.125 32322 32322 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#25683)/@0x116e21e, mIsProjectionMode = false
01-30 13:30:40.127 32322 32322 D VRI[MainActivity]: vri.Setup new sync=wmsSync-VRI[MainActivity]#15
01-30 13:30:40.140 32322 32322 D VRI[MainActivity]: vri.reportDrawFinished
01-30 13:30:40.141 32322 32322 D FileDialog: Launch...
01-30 13:30:40.142 32322 32322 D FileDialog: Copy on background...
01-30 13:30:40.156 32322  2261 D FileDialog: Deleting existing destination file '/data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk'
01-30 13:30:40.183 32322 32322 I HandWritingStubImpl: refreshLastKeyboardType: 1
01-30 13:30:40.183 32322 32322 I HandWritingStubImpl: getCurrentKeyboardType: 1
01-30 13:30:40.186 32322  2261 D FileDialog: Copying 'content://com.android.providers.downloads.documents/document/1130' to '/data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk'
01-30 13:30:40.464 32322  2261 D FileDialog: Successfully copied file to '/data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk, bytes=64595635'
01-30 13:30:40.469 32322 32322 D FileDialog: ...copied on background, result: /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk
01-30 13:30:40.469 32322 32322 D FileDialog: ...launch
01-30 13:30:40.486 32322 32322 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_MEDIA_LOCATION in package: com.facebook.katana at: Binary XML file line #68
01-30 13:30:40.487 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #190
01-30 13:30:40.487 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #225
01-30 13:30:40.487 32322 32322 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: com.google.android.gms.permission.AD_ID in package: com.facebook.katana at: Binary XML file line #233
01-30 13:30:40.487 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #242
01-30 13:30:40.487 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #247
01-30 13:30:40.490 32322 32322 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #708
01-30 13:30:40.513 32322 32322 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.facebook.katana_448.0.0.30.115-448614331_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #4119
01-30 13:30:41.660 17534 17534 W sh      : type=1400 audit(0.0:82358): avc:  denied  { read } for  name="/" dev="dm-8" ino=59 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
01-30 13:30:41.672 17534 17534 W sh      : type=1400 audit(0.0:82359): avc:  denied  { read } for  name="/" dev="dm-8" ino=59 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
01-30 13:30:41.684 17534 17534 W sh      : type=1400 audit(0.0:82360): avc:  denied  { read } for  name="/" dev="dm-8" ino=59 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
01-30 13:30:41.700 17534 17534 W sh      : type=1400 audit(0.0:82361): avc:  denied  { read } for  name="/" dev="dm-8" ino=59 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
01-30 13:30:41.716 17534 17534 W sh      : type=1400 audit(0.0:82362): avc:  denied  { read } for  name="/" dev="dm-8" ino=59 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
01-30 13:30:42.700 17867 17867 W sh      : type=1400 audit(0.0:82428): avc:  denied  { read } for  name="/" dev="dm-8" ino=59 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
01-30 13:30:42.796 17882 17882 W sh      : type=1400 audit(0.0:82429): avc:  denied  { read } for  name="/" dev="dm-8" ino=59 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
01-30 13:30:42.818 32322 32322 W Looper  : PerfMonitor longMsg : seq=702 plan=13:30:41.617 late=6ms wall=1194ms running=83ms runnable=25ms io=2ms reclaim=7ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
01-30 13:30:42.820 32322 32322 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
01-30 13:30:42.820 32322 32322 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
01-30 13:30:44.027 32322 32333 I manager.flutter: Background concurrent copying GC freed 545980(23MB) AllocSpace objects, 94(24MB) LOS objects, 49% free, 24MB/48MB, paused 11.103ms,58us total 325.721ms
01-30 13:30:44.039 32322 32335 W System  : A resource failed to call close. 
01-30 13:30:44.609 32322 32333 I manager.flutter: Background young concurrent copying GC freed 514274(20MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 34MB/48MB, paused 806us,35us total 204.307ms
01-30 13:30:44.971 32322 32333 I manager.flutter: Background concurrent copying GC freed 433890(17MB) AllocSpace objects, 1(68KB) LOS objects, 38% free, 38MB/62MB, paused 162us,50us total 166.954ms
01-30 13:30:45.361 32322 32333 I manager.flutter: Background young concurrent copying GC freed 510132(20MB) AllocSpace objects, 0(0B) LOS objects, 21% free, 49MB/62MB, paused 131us,35us total 113.027ms
01-30 13:30:45.662 32322 32333 I manager.flutter: Background concurrent copying GC freed 474955(19MB) AllocSpace objects, 0(0B) LOS objects, 30% free, 54MB/78MB, paused 62us,20us total 158.863ms
01-30 13:30:46.426 32322 32333 I manager.flutter: Background concurrent copying GC freed 730143(24MB) AllocSpace objects, 0(0B) LOS objects, 25% free, 70MB/94MB, paused 57us,87us total 215.403ms
01-30 13:30:47.447 32322 32333 I manager.flutter: Background concurrent copying GC freed 2402803(74MB) AllocSpace objects, 8(11MB) LOS objects, 55% free, 19MB/43MB, paused 217us,135us total 124.527ms
01-30 13:30:47.450 32322 32335 W System  : A resource failed to call close. 
01-30 13:30:47.870 32322 32333 I manager.flutter: Background concurrent copying GC freed 3649146(75MB) AllocSpace objects, 2(136KB) LOS objects, 33% free, 47MB/71MB, paused 218us,115us total 259.501ms
01-30 13:30:48.041 32322 32333 I manager.flutter: Background young concurrent copying GC freed 2363611(50MB) AllocSpace objects, 0(0B) LOS objects, 33% free, 47MB/71MB, paused 289us,95us total 113.248ms
01-30 13:30:48.528 32322 32333 I manager.flutter: Background concurrent copying GC freed 6192221(130MB) AllocSpace objects, 0(0B) LOS objects, 19% free, 99MB/123MB, paused 215us,126us total 434.741ms
01-30 13:30:55.658 32322 32335 W System  : A resource failed to call close. 
01-30 13:30:55.670 32322 32335 W System  : A resource failed to call close. 
01-30 13:30:55.670 32322 32335 W System  : A resource failed to call close. 
01-30 13:30:55.670 32322 32335 W System  : A resource failed to call close. 
01-30 13:30:55.670 32322 32335 W System  : A resource failed to call close. 
01-30 13:30:57.587 32322 32335 W System  : A resource failed to call end. 
01-30 13:30:57.587 32322 32335 W System  : A resource failed to call end. 
01-30 13:30:57.587 32322 32335 W System  : A resource failed to call end.
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: 2203129G
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.facebook.katana v448.0.0.30.115 (Suggested: Any)
Patches version: v4.0.2
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Hide story ads failed: app.revanced.patcher.patch.PatchException: Failed to resolve FetchMoreAdsFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:24)
	at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:12)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 4 dex files
Signing APK
Patched APK
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
This issue belongs in the patches repository, although it seems that this issue has already been opened.

https://github.com/ReVanced/revanced-patches/issues/96

**Comment by karb10** [comment]
does facebook patch removes all ads or only short ads?

**Comment by oSumAtrIX** [comment]
It removes ads as described in the patch description.
