### ISSUE TITLE
bug: Patching YouTube 19.04.37 causes crash

### ISSUE THREAD

**Issue by RunDevelopment** [ReVanced/revanced-manager#1715]
### Bug description

After downloading the YT 19.04.27 full APKfrom APKPure and trying to apply the default patches, Revanced manager crashes while trying to apply patches. 

The last patch I saw it apply before the crash was Hide Seekbar. After that, some more messaged flew by, but they were too fast to read. It then printed a stack trace and crashed. I grabbed a screenshot of the visible part of the stack trace.

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager: 1.18.0
App: Youtube 19.04.37 (suggested version)

### Installation type

Non-root

### Device logs

[revanced-manager_logcat_20240302022222933724.log](https://github.com/ReVanced/revanced-manager/files/14467461/revanced-manager_logcat_20240302022222933724.log)

I had to zip and attach the logs, because they were too long for Github.

### Patcher logs

```shell
Due to the app crashing, I cannot export any logs. The best I have a screenshot of the last frame of the app.
```
![image](https://github.com/ReVanced/revanced-manager/assets/20878432/42950077-625c-4c13-83a1-58255c030b82)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Please capture logs using logcat and grep for AndroidRuntime.

**Comment by RunDevelopment** [comment]
When you say "logs" I assume you mean patcher logs? If so, I never debugged an app crash on a phone before (or anything on android). So is there any documentation on using those tools?

**Comment by sssh7710** [comment]
I also get a patch error


- Device Info
ReVanced Manager: 1.18.0
Model: SM-A336N
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: v19.04.37)
Patches version: v4.3.0
Patches added: Change header [Header: yt_premium_wordmark_header], Custom branding, Enable slide to seek, Remove player controls background
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 64 patches
Change header failed: app.revanced.patcher.patch.PatchException: The provided path is not a directory: yt_premium_wordmark_header
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:117)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:115)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:143)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:14)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK

**Comment by oSumAtrIX** [comment]
Re set the patch option again.

**Comment by RunDevelopment** [comment]
@oSumAtrIX Please re-open. I already reset all settings/options multiple times and even re-installed revanced manager multiple times to get this working. Same error every time.

So unless the reset patch option button also does nothing like "Clear logs" button (#1716), this is not the cause of the issue.

**Comment by oSumAtrIX** [comment]
The reset patch option button works. This is not a support channel, move to our links at https://revanced.app

**Comment by oSumAtrIX** [comment]
Just noticed that the original author was not the one who responded with a crashlog that my response was meant for. Reopening therefore, sorry!

**Comment by RunDevelopment** [comment]
> it seems we both got confused

What a charitable interpretation of events.

@oSumAtrIX You [clearly demonstrated](https://github.com/ReVanced/revanced-manager/issues/1716#issuecomment-1975179432) that you do not value me spending my time on this project. You are also mistaken about the current situation. I already found a workaround for yet another bug that allowed me to work around this crash. I'm not here to get "support", I wanted to help to fix a bug. But that ship has sailed.

As I said before, I hope you can be kinder one day, if only to avoid similar situations in the future.

**Comment by oSumAtrIX** [comment]
My previous comment stands. Your time is valued, but the issue has nothing to do with you, therefor it should stay open.
