### ISSUE TITLE
java.io.FileNotFoundException when trying to patch the YT app

### ISSUE THREAD

**Issue by gozes** [ReVanced/revanced-manager#1758]
### Bug description

After installing version 1.19.2 I get the following stack trace when trying to patch the YT app

```

- Device Info
ReVanced Manager: 1.19.2
Model: FP4
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
Patches version: v4.3.0
Patches added: Default
Patches removed: Copy video URL, Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 12 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
An error occurred:
java.io.FileNotFoundException: /data/app/~~A-0shl3r1-9_2oX_8JsAdA==/com.google.android.youtube-xT_LRpddEGZBjLN4lW-lbw==/base.apk: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
	at n1.s0.M0(Unknown Source:105)
	at n1.s0.Q0(Unknown Source:2)
	at n1.s0.P0(Unknown Source:21)
	at n1.s0.close(Unknown Source:9)
	at kotlin.io.CloseableKt.closeFinally(Unknown Source:4)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:323)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7818)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more
```

### Version of ReVanced Manager and version & name of app you are patching

```

- Device Info
ReVanced Manager: 1.19.2
Model: FP4
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
Patches version: v4.3.0
Patches added: Default
Patches removed: Copy video URL, Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 12 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
An error occurred:
java.io.FileNotFoundException: /data/app/~~A-0shl3r1-9_2oX_8JsAdA==/com.google.android.youtube-xT_LRpddEGZBjLN4lW-lbw==/base.apk: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
	at n1.s0.M0(Unknown Source:105)
	at n1.s0.Q0(Unknown Source:2)
	at n1.s0.P0(Unknown Source:21)
	at n1.s0.close(Unknown Source:9)
	at kotlin.io.CloseableKt.closeFinally(Unknown Source:4)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:323)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7818)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more
```

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.19.2
Model: FP4
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
Patches version: v4.3.0
Patches added: Default
Patches removed: Copy video URL, Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 12 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
An error occurred:
java.io.FileNotFoundException: /data/app/~~A-0shl3r1-9_2oX_8JsAdA==/com.google.android.youtube-xT_LRpddEGZBjLN4lW-lbw==/base.apk: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
	at n1.s0.M0(Unknown Source:105)
	at n1.s0.Q0(Unknown Source:2)
	at n1.s0.P0(Unknown Source:21)
	at n1.s0.close(Unknown Source:9)
	at kotlin.io.CloseableKt.closeFinally(Unknown Source:4)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:323)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7818)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more
```
```


### Patch logs

```shell
- Device Info
ReVanced Manager: 1.19.2
Model: FP4
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
Patches version: v4.3.0
Patches added: Default
Patches removed: Copy video URL, Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 12 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
An error occurred:
java.io.FileNotFoundException: /data/app/~~A-0shl3r1-9_2oX_8JsAdA==/com.google.android.youtube-xT_LRpddEGZBjLN4lW-lbw==/base.apk: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
	at n1.s0.M0(Unknown Source:105)
	at n1.s0.Q0(Unknown Source:2)
	at n1.s0.P0(Unknown Source:21)
	at n1.s0.close(Unknown Source:9)
	at kotlin.io.CloseableKt.closeFinally(Unknown Source:4)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:323)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7818)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more
```
```


### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Update the app
