### ISSUE TITLE
bug: alternative sources not loading

### ISSUE THREAD

**Issue by realies** [ReVanced/revanced-manager#1760]
### Bug description

Enabling 'Use alternative sources' and updating the patches organization to 'realies', patches source to 'revanced-p' and restarting ReVanced Manager has the "ReVanced Patches" stuck at "Loading...".

It appears that it's not just a visual bug; I can't see any patches in the list of patches.

<img width="712" alt="" src="https://github.com/ReVanced/revanced-manager/assets/5107843/22908fe2-32b5-4335-a938-c8e01cece31f">

### Version of ReVanced Manager and version & name of app you are patching

1.19.3

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of crash
03-09 21:44:29.964 18225 18225 E AndroidRuntime: FATAL EXCEPTION: main
03-09 21:44:29.964 18225 18225 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 18225
03-09 21:44:29.964 18225 18225 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4499)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: Caused by: java.lang.NullPointerException
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(Unknown Source:63)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4490)
03-09 21:44:29.964 18225 18225 E AndroidRuntime: 	... 9 more
--------- beginning of system
03-09 22:37:53.613 21343 21343 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_COARSE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #25
03-09 22:37:53.613 21343 21343 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_FINE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #26
03-09 22:37:53.613 21343 21343 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/Nova-Launcher-Prime-Beta-8.0.14-www.ReXdl.com.apk Binary XML file line #32
03-09 22:38:00.889 21343 21343 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_COARSE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #98
03-09 22:38:00.889 21343 21343 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_FINE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #100
03-09 22:38:00.889 21343 21343 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/NovaLauncher_8.0.14.apk Binary XML file line #114
03-09 22:40:46.102 22945 22945 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_COARSE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #98
03-09 22:40:46.102 22945 22945 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_FINE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #100
03-09 22:40:46.102 22945 22945 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/NovaLauncher_8.0.14.apk Binary XML file line #114
03-09 22:50:01.315 26018 26018 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_COARSE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #98
03-09 22:50:01.316 26018 26018 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_FINE_LOCATION in package: com.teslacoilsw.launcher at: Binary XML file line #100
03-09 22:50:01.316 26018 26018 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/NovaLauncher_8.0.14.apk Binary XML file line #114
--------- beginning of main
03-09 22:53:47.007 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/base.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_arservicesoptional.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_cgnativeplayer.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_cgwebrtc.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_groupsadmin.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_i18n_en_GB.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_instantgames.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_instantgamesads.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_papaya.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_papayaanalyticstorch.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_papayatorch.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_pytorch.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_s_arservicesoptional_slam.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_s_cgwebrtc_horizon.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_s_papaya_torchedlooper.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_s_papayaanalyticstorch_papayatorch.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_s_papayaanalyticstorch_papayatorch_torchedlooper.apk' with 1 weak references
03-09 22:53:47.008 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_s_papayatorch_torchedlooper.apk' with 1 weak references
03-09 22:53:47.009 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~A1VnRtHYm3QjUb1R9FUlww==/com.facebook.katana-af_XOSrDWDVKSxsLmMar5w==/split_slam.apk' with 1 weak references
03-09 22:53:47.009 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~GZqat7me1Z3Zvn6EByo9Aw==/com.facebook.orca-6B-VEAINeTfC_KPuhWX0lA==/base.apk' with 1 weak references
03-09 22:53:47.010 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~GZqat7me1Z3Zvn6EByo9Aw==/com.facebook.orca-6B-VEAINeTfC_KPuhWX0lA==/split_arsegmentation.apk' with 1 weak references
03-09 22:53:47.010 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~GZqat7me1Z3Zvn6EByo9Aw==/com.facebook.orca-6B-VEAINeTfC_KPuhWX0lA==/split_arservicesforexpressionfitting.apk' with 1 weak references
03-09 22:53:47.010 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~GZqat7me1Z3Zvn6EByo9Aw==/com.facebook.orca-6B-VEAINeTfC_KPuhWX0lA==/split_arservicesforruntimerigmapping.apk' with 1 weak references
03-09 22:53:47.010 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~GZqat7me1Z3Zvn6EByo9Aw==/com.facebook.orca-6B-VEAINeTfC_KPuhWX0lA==/split_i18n_en_GB.apk' with 1 weak references
03-09 22:53:47.010 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~2D-c28GzeR34TWVDnxNAUQ==/com.spotify.music-v2OEHGyzny_QQVw0hVGkGA==/base.apk' with 1 weak references
03-09 22:53:47.012 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~DvNNcywpFkCy1-MRbK8TXw==/com.zhiliaoapp.musically-RWql-1NYk0qP3Mwn9on-4g==/base.apk' with 1 weak references
03-09 22:53:47.013 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~UaJI4tzjtwOIM_MlgoHHfw==/com.twitter.android-E0_HfoxHaNZttp-kENRuoQ==/base.apk' with 1 weak references
03-09 22:53:47.014 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~J71GuYgQMaDG2PqaxC4Tyw==/app.revanced.android.youtube-zZDlBBb-sn9M9qT2iGBOlA==/base.apk' with 1 weak references
03-09 22:53:47.015 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~6bbLew-gB3WJHtTlThBSzQ==/com.google.android.apps.translate-6OjgR1St9rIqflblC4iC9A==/base.apk' with 1 weak references
03-09 22:53:47.017 26018 26031 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/user/0/app.revanced.manager.flutter/cache/NovaLauncher_8.0.14.apk' with 1 weak references
03-09 22:54:15.158 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:54:16.318 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:54:16.439 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:54:16.449 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:54:17.168 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:54:17.500 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:54:17.579 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:39.638 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:39.917 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:40.355 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.029 26018 26018 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
03-09 22:59:41.029 26018 26018 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
03-09 22:59:41.050 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.392 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.439 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.449 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.456 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.531 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.557 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.589 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.597 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:41.649 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:42.163 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:48.128 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:48.828 26018 26055 E manager.flutter: PIXEL: ioctl err: 1
03-09 22:59:57.822 26018 26018 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10312; state: ENABLED
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by realies** [comment]
I've just noticed the behaviour is the same without changing any of the alternative sources fields and only enabling it via the toggle button.

**Comment by oSumAtrIX** [comment]
In that case open a new issue

**Comment by realies** [comment]
> In that case open a new issue 

why?

**Comment by oSumAtrIX** [comment]
Because it has nothing to do with "changing any of the alternative sources fields and only enabling it via the toggle button."
