### ISSUE TITLE
bug: Patched YouTube keeps stopping error after reboot

### ISSUE THREAD

**Issue by mauriciabad** [ReVanced/revanced-manager#1769]
### Bug description

When you patch YouTube, install it with mount (root), and reboot your phone, the patched YouTube app crashes on opening it and gives the error "YouTube keeps stopping".

If you open the patched app after patching it, it works perfectly, the issue is when you reboot.

I've been having this issue for a really long time, so it is not a new thing.

I tried to uninstall YouTube, but I can't because it is a system app. Even if I use ADB, I still get an error saying that the signature is different, although I have no YouTube app installed...

I would like to not install MicroG, since I have root and it would be unnecessary. So I didn't even try this method.

I researched and there's this random Magisk module ([j-hc/revanced-magisk-module](https://github.com/j-hc/revanced-magisk-module)) that some Reddit users say it fixes this issue, but I don't trust it since it's not mentioned anywere by you. Do you know if it is legit/safe? 

I'm not adding any videos/screenshots because the way to reproduce it is the main "happy path" of the app, I'm not doing anything weird (I can add them if you request them). 
I'm surprised that this has been happening to me for such a long time, because it seems so simple to reproduce that I assumed someone would have already reported it, but no. Therefore, I'm starting to think that it may be something related to my device, but I can't figure out what. Are you able to reproduce it? Or it just happens to me? 

### Version of ReVanced Manager and version & name of app you are patching

- ReVanced Manager: `v1.19.3`
- Youtube: `v19.04.37`

_(All latest at the time of writing this)_

### Installation method

Mount

### ReVanced Manager logs

```shell
--------- beginning of main
03-17 03:16:05.053 30374 30374 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10511; state: ENABLED
03-17 03:16:05.066 30374 30374 D FileDialog: Saving file on background...
03-17 03:16:05.069 30374 32097 D FileDialog: Saving file '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWBTUL/out.apk' to '/document/4330'
03-17 03:16:05.100 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:05.138 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:05.369 30374 32097 D FileDialog: Saved file to '/document/4330'
03-17 03:16:05.369 30374 30374 D FileDialog: ...saved file on background, result: /document/4330
03-17 03:16:07.048 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:07.068 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:08.286 30374 30374 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10511; state: ENABLED
03-17 03:16:10.265 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:10.382 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:11.101 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:11.126 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:11.931 30430 30430 W sh      : type=1400 audit(0.0:1795): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:11.947 30430 30430 W sh      : type=1400 audit(0.0:1796): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:11.967 30430 30430 W sh      : type=1400 audit(0.0:1797): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:11.991 30430 30430 W sh      : type=1400 audit(0.0:1798): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:12.015 30430 30430 W sh      : type=1400 audit(0.0:1799): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:12.046 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
--------- beginning of system
03-17 03:16:12.767 30374 30374 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWBTUL/out.apk Binary XML file line #2
03-17 03:16:12.769 30374 30374 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWBTUL/out.apk Binary XML file line #147
03-17 03:16:12.775 30374 30374 W PackageParser: No actions in intent filter at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWBTUL/out.apk Binary XML file line #481
03-17 03:16:12.857 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:12.895 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:12.943 30430 30430 W sh      : type=1400 audit(0.0:1808): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:12.951 30430 30430 W sh      : type=1400 audit(0.0:1809): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:12.959 30430 30430 W sh      : type=1400 audit(0.0:1810): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:12.987 30430 30430 W sh      : type=1400 audit(0.0:1811): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:13.003 30430 30430 W sh      : type=1400 audit(0.0:1812): avc:  denied  { read } for  name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c255,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
03-17 03:16:15.969 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:26.850 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:26.856 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:29.042 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:35.894 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:35.974 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:36.296 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:36.359 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.444 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.464 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.498 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.543 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.733 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.777 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.890 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.912 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:37.922 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:38.750 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:40.840 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
03-17 03:16:40.916 30374 30374 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10511; state: ENABLED
03-17 03:16:54.199 30374 30406 E manager.flutter: PIXEL: ioctl err: 1
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.19.3
Model: Pixel 6
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
Patches version: v4.3.0
Patches added: Change header
Patches removed: Copy video URL, Remove viewer discretion dialog, External downloads, Disable precise seeking gesture, Seekbar tapping, Disable auto captions, Hide video action buttons, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Spoof app version, Change start page, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Always repeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, GmsCore support, Open links externally
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 10 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Mounting patched app
Installed
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
If it crashes, send the crashlogs using logcat and filter for AndroidRuntime using grep for example

**Comment by mauriciabad** [comment]
I got this:
```log
03-17 14:53:30.975  6207  6207 E AndroidRuntime: FATAL EXCEPTION: main
03-17 14:53:30.975  6207  6207 E AndroidRuntime: Process: com.google.android.youtube, PID: 6207
03-17 14:53:30.975  6207  6207 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libelements.so" not found
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at fwo.<clinit>(PG:3)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateApplication(PG:1)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1282)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7018)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-17 14:53:30.975  6207  6207 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
03-17 14:55:21.724 19389 19389 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10546 <<<<<<
03-17 14:55:21.768 19389 19389 I AndroidRuntime: Using default boot image
03-17 14:55:21.768 19389 19389 I AndroidRuntime: Leaving lock profiling enabled
03-17 14:55:22.335 19404 19404 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10546 <<<<<<
03-17 14:55:22.353 19404 19404 I AndroidRuntime: Using default boot image
03-17 14:55:22.353 19404 19404 I AndroidRuntime: Leaving lock profiling enabled
03-17 14:55:24.848 19404 19404 D AndroidRuntime: Calling main entry com.aidc.immortal.DaemonEntry
03-17 14:55:24.848 19389 19389 D AndroidRuntime: Calling main entry com.aidc.immortal.DaemonEntry
03-17 14:55:25.871 19463 19463 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10546 <<<<<<
03-17 14:55:25.886 19463 19463 I AndroidRuntime: Using default boot image
03-17 14:55:25.886 19463 19463 I AndroidRuntime: Leaving lock profiling enabled
03-17 14:55:28.182 19463 19463 D AndroidRuntime: Calling main entry com.aidc.immortal.DaemonEntry
03-17 14:58:05.333 20033 20033 D AndroidRuntime: Shutting down VM
03-17 14:58:05.333 20033 20033 E AndroidRuntime: FATAL EXCEPTION: main
03-17 14:58:05.333 20033 20033 E AndroidRuntime: Process: com.google.android.youtube, PID: 20033
03-17 14:58:05.333 20033 20033 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libelements.so" not found
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at fwo.<clinit>(PG:3)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateApplication(PG:1)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1282)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7018)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-17 14:58:05.333 20033 20033 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
03-17 14:58:06.745 20073 20073 D AndroidRuntime: Shutting down VM
03-17 14:58:06.745 20073 20073 E AndroidRuntime: FATAL EXCEPTION: main
03-17 14:58:06.745 20073 20073 E AndroidRuntime: Process: com.google.android.youtube, PID: 20073
03-17 14:58:06.745 20073 20073 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libelements.so" not found
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at fwo.<clinit>(PG:3)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateApplication(PG:1)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1282)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7018)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-17 14:58:06.745 20073 20073 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by mauriciabad** [comment]
<img src="https://github.com/ReVanced/revanced-manager/assets/12821361/491fad7d-761c-4934-b4c5-cafffeaf7dd0" width="300"/>

**Comment by mauriciabad** [comment]
I found a workaround!

**When selecting the app, if instead of picking from the installed apps, I tap "Storage", and selected the APK. Then the patching works and rebooting it as well.**
<img src="https://github.com/ReVanced/revanced-manager/assets/12821361/55457356-e22a-4737-bb47-3af9405512c4" width="300"/>



Maybe there was an issue with removed patches? Maybe they were not being removed properly and caused YT to crash.

**Comment by oSumAtrIX** [comment]
You have probably patched a split apk

**Comment by mauriciabad** [comment]
Nope, I tried to re-install i to see if it was consistent, and I can't manage to get the patched app to work again.

I'm patching the nodpi apk

**Comment by oSumAtrIX** [comment]
The logs indicate a split APK. If you have a different issue please open a new one
