### ISSUE TITLE
bug: unable to import keystore with empty password

### ISSUE THREAD

**Issue by Howard20181** [ReVanced/revanced-manager#1781]
### Bug description

When import a keystore with empty password (generated by cli with default parameter), manager failed to signing 

### Version of ReVanced Manager and version & name of app you are patching

Manager 1.19.4-dev.2
YouTube 19.04.37

### Installation method

None

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.19.4-dev.2
Model: 23127PN0CC
Android version: 14
Supported architectures: arm64-v8a
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
Patches version: v4.3.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 61 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
An error occurred:
java.lang.IllegalArgumentException: Invalid password for keystore entry alias
	at app.revanced.library.ApkSigner.readKeyCertificatePair(Unknown Source:99)
	at app.revanced.library.ApkSigner.newApkSigner(SourceFile:3)
	at app.revanced.library.ApkUtils.sign(SourceFile:2)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:553)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Ushie** [comment]
This is likely not an issue on the pre-release version, closing to make tracking issues easier
