### ISSUE TITLE
bug: java.lang.OutOfMemoryError while patching TikTok

### ISSUE THREAD

**Issue by Ondrejtra** [ReVanced/revanced-manager#1802]
### Bug description

Attempting to patch TikTok from an apk file fails with java.lang.OutOfMemoryError. This issue occurs with default patches as well as a custom patch selection. Patches in logs below are Downloads, Feed filter, Playback speed, Remember clear display, Settings and Show seekbar. Patching the recommended version 32.5.3.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.19.3
App: TikTok (com.zhiliaoapp.musically v32.5.3)

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of kernel
03-28 21:57:44.874 12253 12253 I binder  : 12253:12253 ioctl 40046210 7fed472a80 returned -22
--------- beginning of system
03-28 21:57:45.051 12253 12253 D NtViewRootImpl: mPopUpViewOffsets: offset=(0.0, 0.0), scale=(1.0, 1.0)
03-28 21:57:45.100 12292 12292 W audit   : audit_lost=50 audit_rate_limit=5 audit_backlog_limit=64
03-28 21:57:45.100 12292 12292 E audit   : rate limit exceeded
03-28 21:57:45.735 12280 12280 I binder  : 12253:12280 ioctl 40046210 7c1e985dd4 returned -22
03-28 21:57:49.682 12279 12279 W         : process 12830 (DartWorker) no longer affine to cpu7
03-28 21:57:50.412 12279 12279 W         : process 12829 (DartWorker) no longer affine to cpu7
03-28 21:57:50.633 12279 12279 W         : process 12828 (DartWorker) no longer affine to cpu7
03-28 21:57:50.652 12279 12279 W         : process 12557 (DartWorker) no longer affine to cpu7
03-28 21:57:56.374 12253 12253 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #5
03-28 21:57:56.374 12253 12253 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #373
03-28 21:57:56.374 12253 12253 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.ACCESS_NETWORK_STATE in package: com.zhiliaoapp.musically at: Binary XML file line #407
03-28 21:57:56.377 12253 12253 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1349
03-28 21:57:56.377 12253 12253 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1351
03-28 21:57:56.377 12253 12253 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1353
03-28 21:57:56.377 12253 12253 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1355
03-28 21:57:56.377 12253 12253 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1357
03-28 21:57:56.377 12253 12253 W PackageParser: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1359
03-28 21:57:56.379 12253 12253 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/com.zhiliaoapp.musically_32.5.3-2023205030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #2401
03-28 21:58:05.343 12279 12279 W         : process 12821 (flutter-worker-) no longer affine to cpu7
03-28 21:58:05.413 13942 13942 W audit   : audit_lost=117 audit_rate_limit=5 audit_backlog_limit=64
03-28 21:58:05.413 13942 13942 E audit   : rate limit exceeded
--------- beginning of main
03-28 22:00:01.328 12253 14223 I manager.flutter: Waiting for a blocking GC Alloc
03-28 22:00:01.646 12253 12264 I manager.flutter: Background concurrent copying GC freed 3880952(110MB) AllocSpace objects, 860(20MB) LOS objects, 20% free, 380MB/476MB, paused 36us,17us total 394.659ms
03-28 22:00:01.647 12253 14223 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 318.756ms
03-28 22:00:01.647 12253 14223 I manager.flutter: Starting a blocking GC Alloc
03-28 22:00:16.033 12253 14223 I manager.flutter: Waiting for a blocking GC Alloc
03-28 22:00:16.332 12253 12264 I manager.flutter: Background concurrent copying GC freed 3681929(102MB) AllocSpace objects, 609(14MB) LOS objects, 19% free, 394MB/490MB, paused 40us,16us total 404.367ms
03-28 22:00:16.333 12253 14223 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 299.672ms
03-28 22:00:16.333 12253 14223 I manager.flutter: Starting a blocking GC Alloc
03-28 22:00:41.124 12253 12253 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10280; state: ENABLED
03-28 22:01:37.988 12253 12274 E OpenGLRenderer: Unable to match the desired swap behavior.
03-28 22:01:37.991 12253 12253 I SurfaceView: surfaceview vote min fps
03-28 22:02:08.335 12271 12271 W         : process 12279 (1.ui) no longer affine to cpu5
03-28 22:04:33.244 12253 12253 I SurfaceView: surfaceview vote min fps
03-28 22:04:33.246 12253 12274 E OpenGLRenderer: Unable to match the desired swap behavior.
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.19.3
Model: A063
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.zhiliaoapp.musically v32.5.3 (Suggested: 32.5.3)
Patches version: v4.4.0
Patches added: Default
Patches removed: Disable login requirement, Fix Google login
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 6 patches
Compiling patched dex files
Compiled 18 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 4984 free bytes and 4984B until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.buildInstruction(Unknown Source:243)
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.readFrom(Unknown Source:43)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(SourceFile:1)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(SourceFile:2)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(Unknown Source:2)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.tryToComputeNext(Unknown Source:3)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.hasNext(Unknown Source:8)
	at com.android.tools.smali.util.IteratorUtils.getLast(Unknown Source:4)
	at com.android.tools.smali.dexlib2.dexbacked.util.DebugInfo$DebugInfoImpl.iterator(Unknown Source:38)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.internDebug(Unknown Source:46)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.intern(Unknown Source:222)
	at com.android.tools.smali.dexlib2.writer.pool.DexPool.internClass(Unknown Source:4)
	at h6.h.c(Unknown Source:27)
	at h6.h.a(Unknown Source:0)
	at h6.h$a.a(Unknown Source:20)
	at h6.h$a.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
#1454
