### ISSUE TITLE
bug: app not installed due to package conflicts

### ISSUE THREAD

**Issue by meichengg** [revanced/revanced-manager#183]
### Type

Other

### Branch

both

### Bug description

I had my Reddit, Twitter, TikTok, Youtube pre-installed directly from Google Play, when i try to patch them using Revanced Manager, all gives me this result as below.

![Screenshot_2022-09-18-10-59-57-22_3d73e98b1ad3bd2575f7a56513d89a0c](https://user-images.githubusercontent.com/25204246/190885205-417d3702-5bc3-45bd-9ba8-52da5589b5be.jpg)

### Steps to reproduce

1. Install Reddit from Google Play
2. Patch using Revanced Manager.

### Relevant log output

```shell
--------- beginning of crash
09-17 19:54:02.231  3261  3994 E AndroidRuntime: FATAL EXCEPTION: Thread-7
09-17 19:54:02.231  3261  3994 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 3261
09-17 19:54:02.231  3261  3994 E AndroidRuntime: kotlin.io.NoSuchFileException: /data/app/~~6TpenR5wueU7dIXIDiqEig==/com.ss.android.ugc.trill-6ag7HWn2gSn31g9FWAhiaw==/base.apk: The source file doesn't exist.
09-17 19:54:02.231  3261  3994 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
09-17 19:54:02.231  3261  3994 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
09-17 19:54:02.231  3261  3994 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:125)
09-17 19:54:02.231  3261  3994 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-17 19:54:02.231  3261  3994 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-17 19:54:02.231  3261  3994 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: FATAL EXCEPTION: Thread-7
09-17 23:54:48.604 10992 13272 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 10992
09-17 23:54:48.604 10992 13272 E AndroidRuntime: java.util.NoSuchElementException: Array is empty.
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.resolveAapt(Aapt.kt:12)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.access$resolveAapt(Aapt.kt:1)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.Aapt.binary(Aapt.kt:8)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:143)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-17 23:54:48.604 10992 13272 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: FATAL EXCEPTION: Thread-6
09-17 23:55:10.848 13303 13516 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 13303
09-17 23:55:10.848 13303 13516 E AndroidRuntime: java.util.NoSuchElementException: Array is empty.
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.resolveAapt(Aapt.kt:12)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.access$resolveAapt(Aapt.kt:1)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.Aapt.binary(Aapt.kt:8)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:143)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-17 23:55:10.848 13303 13516 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: FATAL EXCEPTION: Thread-7
09-17 23:55:20.463 13548 13720 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 13548
09-17 23:55:20.463 13548 13720 E AndroidRuntime: java.util.NoSuchElementException: Array is empty.
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.resolveAapt(Aapt.kt:12)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.access$resolveAapt(Aapt.kt:1)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.Aapt.binary(Aapt.kt:8)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:143)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-17 23:55:20.463 13548 13720 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: FATAL EXCEPTION: Thread-11
09-17 23:55:43.472 13773 14124 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 13773
09-17 23:55:43.472 13773 14124 E AndroidRuntime: java.util.NoSuchElementException: Array is empty.
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.resolveAapt(Aapt.kt:12)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.access$resolveAapt(Aapt.kt:1)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.Aapt.binary(Aapt.kt:8)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:143)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-17 23:55:43.472 13773 14124 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-18 06:53:44.460  9323  9478 E AndroidRuntime: FATAL EXCEPTION: Thread-6
09-18 06:53:44.460  9323  9478 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 9323
09-18 06:53:44.460  9323  9478 E AndroidRuntime: kotlin.io.NoSuchFileException: /data/app/~~6TpenR5wueU7dIXIDiqEig==/com.ss.android.ugc.trill-6ag7HWn2gSn31g9FWAhiaw==/base.apk: The source file doesn't exist.
09-18 06:53:44.460  9323  9478 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
09-18 06:53:44.460  9323  9478 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
09-18 06:53:44.460  9323  9478 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:125)
09-18 06:53:44.460  9323  9478 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-18 06:53:44.460  9323  9478 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-18 06:53:44.460  9323  9478 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of system
09-18 11:02:44.233 32410 32410 I Quality : Skipped: false 5 cost 47.716263 refreshRate 0 processName app.revanced.manager.flutter
--------- beginning of main
09-18 11:05:38.241  2061  5658 E manager.flutte: Loaded layer handle (17902856901774481909) for layer /my_product/lib64/libcolorx-loader.so
09-18 11:05:38.241  2061  5658 E manager.flutte: Looking for entrypoint ColorX_Check
09-18 11:05:38.241  2061  5658 E manager.flutte: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
09-18 11:05:38.242  2061  5658 E manager.flutte: Check failed
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: QUALCOMM build                   : 629d727fc2, I97e7a4565c
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: Build Date                       : 03/08/22
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.06
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: Local Branch                     : 
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: Remote Branch                    : 
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: Remote Branch                    : 
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: Reconstruct Branch               : 
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
09-18 11:05:38.270  2061  2061 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-18 11:05:38.272  2061  2061 I AdrenoGLES-0: PFP: 0x016dd091, ME: 0x00000000
09-18 11:05:38.287  2061  2061 I oplus.android.OplusFrameworkFactoryImpl: Unknow feature:IOplusTextViewRTLUtilForUG
09-18 11:05:38.294  2061  2061 D OplusInputMethodUtil: init DEBUG to false, update DEBUG_IME to false
09-18 11:05:38.294  2061  2061 D OplusInputMethodUtil: init DEBUG to false, update DEBUG_IME to false
09-18 11:05:38.308  2061  2061 I Quality : ActivityThread: activityStart delay 91 app.revanced.manager.flutter 2061
09-18 11:05:38.313  2061  2061 D OplusSlideAnimOptHelper: app.revanced.manager.flutter scrollEffectOpt enable = false
09-18 11:05:38.317  2061  2061 D WindowManager: Add to mViews: DecorView@f063090[MainActivity],pkg= app.revanced.manager.flutter
09-18 11:05:38.319  2061  5656 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-18 11:05:38.320  2061  5656 D ExtensionsLoader: Opened libhwuiextimpl.so
09-18 11:05:38.320  2061  2061 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-18 11:05:38.321  2061  2061 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-18 11:05:38.321  2061  2061 E manager.flutte: ofbOpen failed with error=No such file or directory
09-18 11:05:38.321  2061  2061 E manager.flutte: sysOpen failed with error=No such file or directory
09-18 11:05:38.330  2061  2061 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-18 11:05:38.330  2061  2061 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-18 11:05:38.345  2061  2061 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-18 11:05:38.346  2061  2061 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-18 11:05:38.346  2061  2061 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.252063888
09-18 11:05:38.351  2061  5663 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-18 11:05:38.359  2061  2061 I Quality : Skipped: false 1 cost 14.650918 refreshRate 0 processName app.revanced.manager.flutter
09-18 11:05:38.754  2061  2061 D ViewRootImpl[MainActivity]:  debugCancelDraw some OnPreDrawListener onPreDraw return false,cancelDraw=true,count=50,android.view.ViewRootImpl@f6687a1
09-18 11:05:39.718  2061  5662 I flutter : dynamic_color: Core palette detected.
09-18 11:05:39.747  2061  2061 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-18 11:05:39.747  2061  2061 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-18 11:05:39.747  2061  2061 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-18 11:05:39.747  2061  2061 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-18 11:05:39.747  2061  2061 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-18 11:05:39.747  2061  2061 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-18 11:05:39.747  2061  2061 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-18 11:05:39.747  2061  2061 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 11:05:39.747  2061  2061 W System.err: 	at android.os.Looper.loopOnce(Looper.java:233)
09-18 11:05:39.747  2061  2061 W System.err: 	at android.os.Looper.loop(Looper.java:344)
09-18 11:05:39.747  2061  2061 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
09-18 11:05:39.747  2061  2061 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-18 11:05:39.747  2061  2061 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
09-18 11:05:39.747  2061  2061 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-18 11:05:39.747  2061  2061 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-18 11:05:39.747  2061  2061 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-18 11:05:39.747  2061  2061 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-18 11:05:39.747  2061  2061 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-18 11:05:39.747  2061  2061 W System.err: 	... 19 more
09-18 11:05:39.756  2061  2061 I Quality : Skipped: false 1 cost 13.704481 refreshRate 0 processName app.revanced.manager.flutter
09-18 11:05:39.760  2061  2115 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
09-18 11:05:39.760  2061  2061 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-18 11:05:39.760  2061  2061 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-18 11:05:39.760  2061  2061 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-18 11:05:39.760  2061  2061 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-18 11:05:39.760  2061  2061 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-18 11:05:39.760  2061  2061 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-18 11:05:39.760  2061  2061 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-18 11:05:39.760  2061  2061 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 11:05:39.760  2061  2061 W System.err: 	at android.os.Looper.loopOnce(Looper.java:233)
09-18 11:05:39.760  2061  2061 W System.err: 	at android.os.Looper.loop(Looper.java:344)
09-18 11:05:39.760  2061  2061 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
09-18 11:05:39.760  2061  2061 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-18 11:05:39.760  2061  2061 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
09-18 11:05:39.760  2061  2061 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-18 11:05:39.760  2061  2061 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-18 11:05:39.760  2061  2061 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-18 11:05:39.760  2061  2061 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-18 11:05:39.761  2061  2061 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-18 11:05:39.761  2061  2061 W System.err: 	... 19 more
09-18 11:05:39.765  2061  5731 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-18 11:05:39.765  2061  5731 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-18 11:05:39.772  2061  2061 D ViewRootImpl[MainActivity]:  debugCancelDraw  cancelDraw=false,count = 169,android.view.ViewRootImpl@f6687a1
09-18 11:05:39.779  2061  2115 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
09-18 11:05:40.327  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.327  2061  5731 W SQLiteLog: (28) double-quoted string literal: "EBEABC79CAA493ED3E5A00CA13A56A22"
09-18 11:05:40.898  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.898  2061  5731 W SQLiteLog: (28) double-quoted string literal: "0D8911B1DDFCA2090CB01B655AA2FF78"
09-18 11:05:40.900  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.900  2061  5731 W SQLiteLog: (28) double-quoted string literal: "B43E262523F7AE777ABA33C1266A497A"
09-18 11:05:40.901  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.901  2061  5731 W SQLiteLog: (28) double-quoted string literal: "BE00820C7ED8D980B4A41D0D625579D0"
09-18 11:05:40.902  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.902  2061  5731 W SQLiteLog: (28) double-quoted string literal: "36422CCCC031C8EB8F713A473CE0C2DA"
09-18 11:05:40.903  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.903  2061  5731 W SQLiteLog: (28) double-quoted string literal: "B0EF685DB778A49604A9EE705B375253"
09-18 11:05:40.905  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.905  2061  5731 W SQLiteLog: (28) double-quoted string literal: "47DF83BEC2297417C58CD214A3EF398B"
09-18 11:05:40.908  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.908  2061  5731 W SQLiteLog: (28) double-quoted string literal: "6647230F7460048127277021122A0746"
09-18 11:05:40.910  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.910  2061  5731 W SQLiteLog: (28) double-quoted string literal: "81EFE155C539B33147EBC3B2B709B58B"
09-18 11:05:40.912  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.912  2061  5731 W SQLiteLog: (28) double-quoted string literal: "4483E083192F29F7DCE263BF1ED84D25"
09-18 11:05:40.913  2061  5731 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-18 11:05:40.913  2061  5731 W SQLiteLog: (28) double-quoted string literal: "0E6D75526299A7D21A4A6C4FB25AC14D"
09-18 11:05:43.080  2061  5663 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
09-18 11:05:43.088  2061  5656 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
09-18 11:05:47.055  2061  2113 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
09-18 11:05:47.063  2061  2113 I OpenGLRenderer: Davey! duration=7288ms; Flags=1, FrameTimelineVsyncId=5629679, IntendedVsync=43040424369711, Vsync=43040424369711, InputEventId=0, HandleInputStart=43040426727902, AnimationStart=43040426730089, PerformTraversalsStart=43040426731027, DrawStart=43040426916964, FrameDeadline=43040435036377, FrameInterval=43040426705662, FrameStartTime=8333333, SyncQueued=43040427228110, SyncStart=43040427283214, IssueDrawCommandsStart=43040428220818, SwapBuffers=43040433165193, FrameCompleted=43047712992743, DequeueBufferDuration=1594010, QueueBufferDuration=691146, GpuCompleted=43047712992743, SwapBuffersCompleted=43040434250766, DisplayPresentTime=16384, 
09-18 11:05:47.063  2061  2113 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
```

### Additional context

Im using Android 12.

**Comment by ponces** [comment]
Expected behavior.
If you're installing on non-root mode, you should uninstall the original version before installing the patched version.
Closed.

**Comment by meichengg** [comment]
> 

by installing the patched version, will i be able to get Reddit updates from Google Play? Or i have to find the apk manually?
