### ISSUE TITLE
bug: failed at compiling modified resources

### ISSUE THREAD

**Issue by Conarius** [ReVanced/revanced-manager#1830]
### Bug description

When I try to patch Instagram with a few patches, it crashes at "compiling modified resources". It also takes a lot of time, especiallz compiling all dex files and resources.
Installation method is non-root btw
![Screenshot_20240403-034018~2](https://github.com/ReVanced/revanced-manager/assets/34580743/9032db08-ec8e-4cc3-bf28-d1cdf72802d1)
![Screenshot_20240403-034035](https://github.com/ReVanced/revanced-manager/assets/34580743/15851cc5-bf17-4fb6-8e90-5da2cf87c873)
![Screenshot_20240403-034057](https://github.com/ReVanced/revanced-manager/assets/34580743/b844cd8e-42ec-4e79-add0-85bad6877c8c)

### Version of ReVanced Manager and version & name of app you are patching

Revanced Manager Version: 1.19.3
Patches: 4.6.0
Instagram Version: 325.0.0.35.91

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of crash
03-09 12:30:58.731 11104 11104 E AndroidRuntime: FATAL EXCEPTION: main
03-09 12:30:58.731 11104 11104 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 11104
03-09 12:30:58.731 11104 11104 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4672)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2357)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: Caused by: java.lang.NullPointerException
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(Unknown Source:63)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4663)
03-09 12:30:58.731 11104 11104 E AndroidRuntime: 	... 9 more
03-29 13:39:06.251 24864 24864 E AndroidRuntime: FATAL EXCEPTION: main
03-29 13:39:06.251 24864 24864 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 24864
03-29 13:39:06.251 24864 24864 E AndroidRuntime: java.lang.IllegalStateException: Reply already submitted
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at g5.c$g.a(Unknown Source:35)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at o5.j$a$a.a(Unknown Source:14)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34$postStop$lambda$22(Unknown Source:11)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.i(Unknown Source:0)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at app.revanced.manager.flutter.c.run(Unknown Source:2)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-29 13:39:06.251 24864 24864 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
--------- beginning of main
04-03 03:30:07.073  2503  2503 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
04-03 03:30:07.111  2503  2503 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
04-03 03:30:07.112  2503  2503 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
04-03 03:30:07.112  2503  2503 D VRI[MainActivity]: Not drawing due to not visible
04-03 03:30:07.118  2503  2503 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
04-03 03:30:07.119  2503  2503 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
04-03 03:30:48.209  2503  2503 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
04-03 03:30:48.215  2503  2503 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
04-03 03:30:48.251  2503  2503 D VRI[MainActivity]: Start draw after previous draw not visible
04-03 03:31:01.511  2503  2503 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10390; state: ENABLED
04-03 03:31:07.199  2503  2503 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10390; state: ENABLED
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.19.3
Model: Pixel 7 Pro
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.instagram.android v325.0.0.35.91 (Suggested: Any)
Patches version: v4.6.0
Patches added: Change package name, Predictive back gesture
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 13 dex files
Compiling modified resources
An error occurred:
t0.b: d1.a: could not exec (exit code = 1): [/data/app/~~5B3XzBpC-zTsx5VX0P7hdg==/app.revanced.manager.flutter-EpXOsaBMlcNH3Vv6GdAJIA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEDLYZ/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEDLYZ/revanced-temporary-files/apk/build/resources.zip]
	at r0.a.f(Unknown Source:144)
	at r0.a.d(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:1)
	at app.revanced.patcher.Patcher.get(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: d1.a: could not exec (exit code = 1): [/data/app/~~5B3XzBpC-zTsx5VX0P7hdg==/app.revanced.manager.flutter-EpXOsaBMlcNH3Vv6GdAJIA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEDLYZ/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEDLYZ/revanced-temporary-files/apk/build/resources.zip]
	at f1.h.b(Unknown Source:75)
	at r0.a.f(Unknown Source:122)
	... 7 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Use the default ReVanced Manager settings. Resource compilation is unstable and outside of our reach to fix.
