### ISSUE TITLE
bug: App shows grey screen after pressing "Select an app"

### ISSUE THREAD

**Issue by ln-12** [ReVanced/revanced-manager#1863]
### Bug description

I am using a fresh install of revanced manager. When I go to "Patcher" and press "Select an app", the loading screen is shown for a short time followed by a grey screen. 

https://github.com/ReVanced/revanced-manager/assets/36760115/838e77c8-dfdf-4be2-8def-df9cfcdbd647

### Version of ReVanced Manager and version & name of app you are patching

Version: 1.20.1
Model: Pixel 7
Android Version: 14
Supported Arch: arm64-v8a

### Installation method

Regular

### ReVanced Manager logs

```shell
04-12 15:05:36.594  4232  4274 I flutter : Null check operator used on a null value
04-12 15:05:36.595  4232  4274 I flutter : #0      _AppSelectorViewState.build.<anonymous closure>.<anonymous closure> (package:revanced_manager/ui/views/app_selector/app_selector_view.dart:102)
04-12 15:05:36.595  4232  4274 I flutter : #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425)
04-12 15:05:36.595  4232  4274 I flutter : #2      ListIterator.moveNext (dart:_internal/iterable.dart:354)
04-12 15:05:36.595  4232  4274 I flutter : #3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
04-12 15:05:36.595  4232  4274 I flutter : #4      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
04-12 15:05:36.595  4232  4274 I flutter : #5      new List.of (dart:core-patch/array_patch.dart:39)
04-12 15:05:36.595  4232  4274 I flutter : #6      _AppSelectorViewState.build.<anonymous closure> (package:revanced_manager/ui/views/app_selector/app_selector_view.dart:90)
04-12 15:05:36.595  4232  4274 I flutter : #7      ViewModelBuilderState.builderWithDynamicSourceInitialise (package:stacked/src/view_models/view_model_builder.dart:213)
04-12 15:05:36.595  4232  4274 I flutter : #8      Consumer.buildWithChild (package:provider/src/consumer.dart:179)
04-12 15:05:36.595  4232  4274 I flutter : #9      SingleChildStatelessWidget.build (package:nested/nested.dart:259)
04-12 15:05:36.595  4232  4274 I flutter : #10     StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
04-12 15:05:36.595  4232  4274 I flutter : #11     SingleChildStatelessElement.build (package:nested/nested.dart:279)
04-12 15:05:36.595  4232  4274 I flutter : #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
04-12 15:05:36.595  4232  4274 I flutter : #13     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
04-12 15:05:36.595  4232  4274 I flutter : #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
04-12 15:05:36.595  4232  4274 I flutter : #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
04-12 15:05:36.595  4232  4274 I flutter : #16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
04-12 15:05:36.595  4232  4274 I flutter : #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
04-12 15:05:36.595  4232  4274 I flutter : #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
04-12 15:05:36.595  4232  4274 I flutter : #19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
04-12 15:05:36.595  4232  4274 I flutter : #20     _invoke (dart:ui/hooks.dart:312)
04-12 15:05:36.595  4232  4274 I flutter : #21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
04-12 15:05:36.595  4232  4274 I flutter : #22     _drawFrame (dart:ui/hooks.dart:283)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by validcube** [comment]
Whoops...

**Comment by tholeb** [comment]
I have the issue. Any way to fix this ?
