### ISSUE TITLE
bug: Crashes after initialization on CalyxOS.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ReVanced/revanced-manager#1874]
### Bug description

Patching https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-09-37-release/youtube-19-09-37-android-apk-download/download/?forcebaseapk=true using https://github.com/ReVanced/revanced-manager/releases/download/v1.20.0/revanced-manager-v1.20.0.apk installed with https://f-droid.org/repo/dev.imranr.obtainium.fdroid_22603.apk causes the resultant YouTube application to crash immediately after initializing. I can see its GUI for a moment.

Manually installing https://github.com/ReVanced/GmsCore/releases/download/v0.3.1.4.240913/app.revanced.android.gms-240913008-signed.apk didn't modify its behaviour.

### Version of ReVanced Manager and version & name of app you are patching

1.  https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-09-37-release/youtube-19-09-37-android-apk-download/download/?forcebaseapk=true
1.  https://github.com/ReVanced/revanced-manager/releases/download/v1.20.0/revanced-manager-v1.20.0.apk

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of crash
04-20 01:50:38.858  7244  7244 E AndroidRuntime: FATAL EXCEPTION: main
04-20 01:50:38.858  7244  7244 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 7244
04-20 01:50:38.858  7244  7244 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4316)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: Caused by: java.lang.NullPointerException
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(Unknown Source:63)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4307)
04-20 01:50:38.858  7244  7244 E AndroidRuntime: 	... 9 more
--------- beginning of system
04-20 02:02:39.257  7260  7260 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.09.37-1544809920_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
04-20 02:02:39.258  7260  7260 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.09.37-1544809920_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
04-20 02:05:16.538  7260  7260 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.09.37-1544809920_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
04-20 02:05:16.539  7260  7260 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.09.37-1544809920_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
04-20 02:08:29.565  7260  7260 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OAWYLT/out.apk Binary XML file line #2
04-20 02:08:29.566  7260  7260 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OAWYLT/out.apk Binary XML file line #146
--------- beginning of main
04-20 02:26:14.821  7260  7276 E OpenGLRenderer: Unable to match the desired swap behavior.
04-20 02:26:14.832  7260  7260 E SurfaceSyncer: Failed to find sync for id=0
04-20 02:26:14.832  7260  7260 E SurfaceSyncer: Failed to find sync for id=1
04-20 02:26:14.832  7260  7260 E SurfaceSyncer: Failed to find sync for id=2
04-20 02:26:14.832  7260  7260 E SurfaceSyncer: Failed to find sync for id=3
04-20 02:26:14.832  7260  7260 E SurfaceSyncer: Failed to find sync for id=4
04-20 02:26:14.832  7260  7260 E SurfaceSyncer: Failed to find sync for id=5
04-20 02:26:14.832  7260  7260 E SurfaceSyncer: Failed to find sync for id=6
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: Pixel 3
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: app.revanced.android.youtube v19.09.37 (Suggested: Any)
Patches version: v4.6.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installed
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by RokeJulianLockhart** [comment]
Merely repatching and reinstalling it worked. I didn't even need to change APKs. I'd ask for this to be transferred, except for [`gitlab.com/gitlab-org/gitlab/-/work_items/596800`](https://gitlab.com/gitlab-org/gitlab/-/work_items/596800).
