### ISSUE TITLE
bug: Adding the YT Premium Header patch is failed

### ISSUE THREAD

**Issue by BedBug2479** [ReVanced/revanced-manager#1875]
### Bug description

YT Premium Header patch is not working 

If i skip this patch it is not showing any issue

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.20.1
Model: LE2121
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No
App: com.google.android.youtube v19.11.43 (Suggested: 19.11.43)

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of crash
04-05 10:51:46.228 23712 23712 E AndroidRuntime: FATAL EXCEPTION: main
04-05 10:51:46.228 23712 23712 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 23712
04-05 10:51:46.228 23712 23712 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4722)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2439)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:257)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:368)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8826)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: Caused by: java.lang.NullPointerException
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(Unknown Source:63)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4706)
04-05 10:51:46.228 23712 23712 E AndroidRuntime: 	... 9 more
--------- beginning of system
04-21 15:55:39.238 18537 18537 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:true, transformHintChanged:false, mSurfaceSize:Point(1440, 3216), mLastSurfaceSize:Point(1440, 3216), mWidth:1440, mHeight:3216, requestedWidth:1440, requestedHeight:3216, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:false, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3216] display=[0,0][1440,3216] parentFrame=[0,0][0,0]}, params:null
04-21 15:55:40.054 18537 18537 D ActivityThread: ComponentInfo{app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity} checkFinished=false 2
04-21 15:55:40.054 18537 18537 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
04-21 15:55:40.055 18537 18537 I Quality : Skipped: false 0 cost 1.232292 refreshRate 8323006 bit true processName app.revanced.manager.flutter
04-21 15:55:40.069 18537 18537 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:true, transformHintChanged:false, mSurfaceSize:Point(1440, 3216), mLastSurfaceSize:Point(1440, 3216), mWidth:1440, mHeight:3216, requestedWidth:1440, requestedHeight:3216, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3216] display=[0,0][1440,3216] parentFrame=[0,0][0,0]}, params:null
04-21 15:55:40.069 18537 18537 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1440, 3216), lastSurfaceSize:Point(1440, 3216), format:-3, blastBufferQueue:null
04-21 15:55:40.276 18537 18537 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.11.43-1545084352_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
04-21 15:55:40.277 18537 18537 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.11.43-1545084352_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
04-21 15:55:40.623 18537 18537 W VRI[MainActivity]: handleResized abandoned!
04-21 15:55:42.512 18537 18537 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:false, transformHintChanged:false, mSurfaceSize:Point(1440, 3216), mLastSurfaceSize:Point(1440, 3216), mWidth:1440, mHeight:3216, requestedWidth:1440, requestedHeight:3216, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122251904, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3216] display=[0,0][1440,3216] parentFrame=[0,0][1440,3216]}, params:{(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
04-21 15:55:42.512 18537 18537 D VRI[MainActivity]:   fl=KEEP_SCREEN_ON LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
04-21 15:55:42.512 18537 18537 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
04-21 15:55:42.512 18537 18537 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
04-21 15:55:42.512 18537 18537 D VRI[MainActivity]:   bhv=DEFAULT
04-21 15:55:42.512 18537 18537 D VRI[MainActivity]:   fitSides= CLP[ ]}
04-21 15:55:42.512 18537 18537 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1440, 3216), lastSurfaceSize:Point(1440, 3216), format:-3, blastBufferQueue:android.graphics.BLASTBufferQueue@13bc00
04-21 15:56:01.177 18537 18554 D ActivityThread: Dalvik max=524288 total=395356 used=395356
04-21 15:57:07.428 18537 18537 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:false, transformHintChanged:false, mSurfaceSize:Point(1440, 3216), mLastSurfaceSize:Point(1440, 3216), mWidth:1440, mHeight:3216, requestedWidth:1440, requestedHeight:3216, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3216] display=[0,0][1440,3216] parentFrame=[0,0][1440,3216]}, params:{(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
04-21 15:57:07.428 18537 18537 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
04-21 15:57:07.428 18537 18537 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
04-21 15:57:07.428 18537 18537 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
04-21 15:57:07.428 18537 18537 D VRI[MainActivity]:   bhv=DEFAULT
04-21 15:57:07.428 18537 18537 D VRI[MainActivity]:   fitSides= CLP[ ]}
04-21 15:57:07.428 18537 18537 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1440, 3216), lastSurfaceSize:Point(1440, 3216), format:-3, blastBufferQueue:android.graphics.BLASTBufferQueue@13bc00
04-21 15:57:14.355 18537 18537 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:true, transformHintChanged:false, mSurfaceSize:Point(1440, 3216), mLastSurfaceSize:Point(1440, 3216), mWidth:1440, mHeight:3216, requestedWidth:1440, requestedHeight:3216, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:false, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3216] display=[0,0][1440,3216] parentFrame=[0,0][0,0]}, params:null
04-21 15:57:16.845 18537 18537 D ActivityThread: do gfx trim 40 success
--------- beginning of main
04-21 15:57:23.296 18537 18558 D VRI[MainActivity]: dispatchAppVisibility visible:true
04-21 15:57:23.299 18537 18558 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@f81afc7
04-21 15:57:23.300 18537 18537 D VRI[MainActivity]: setWindowStopped stopped:false
04-21 15:57:23.305 18537 18537 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=app.revanced.manager.flutter.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
04-21 15:57:23.305 18537 18537 D ActivityThread: ComponentInfo{app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity} checkFinished=false 2
04-21 15:57:23.306 18537 18537 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
04-21 15:57:23.314 18537 18537 I Quality : Skipped: false 1 cost 8.5868225 refreshRate 8329007 bit true processName app.revanced.manager.flutter
04-21 15:57:23.315 18537 18537 D ViewRootImplExtImpl: wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=411, relayoutAsync=false, newFlags=26935296, title=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
04-21 15:57:23.338 18537 18537 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:true, transformHintChanged:false, mSurfaceSize:Point(1440, 3216), mLastSurfaceSize:Point(1440, 3216), mWidth:1440, mHeight:3216, requestedWidth:1440, requestedHeight:3216, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3216] display=[0,0][1440,3216] parentFrame=[0,0][0,0]}, params:{(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
04-21 15:57:23.338 18537 18537 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
04-21 15:57:23.338 18537 18537 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
04-21 15:57:23.338 18537 18537 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
04-21 15:57:23.338 18537 18537 D VRI[MainActivity]:   bhv=DEFAULT
04-21 15:57:23.338 18537 18537 D VRI[MainActivity]:   fitSides= CLP[ ]}
04-21 15:57:23.338 18537 18537 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1440, 3216), lastSurfaceSize:Point(1440, 3216), format:-3, blastBufferQueue:null
04-21 15:57:23.338 18537 18537 D BufferQueueConsumer: [](id:486900000010,api:0,p:-1,c:18537) connect: controlledByApp=false
04-21 15:57:23.342 18537 11011 D BufferQueueProducer: [VRI[MainActivity]#16(BLAST Consumer)16](id:486900000010,api:1,p:18537,c:18537) connect: api=1 producerControlledByApp=true
04-21 15:57:23.342 18537 11011 E OpenGLRenderer: Unable to match the desired swap behavior.
04-21 15:57:23.344 18537 18537 D BufferQueueConsumer: [](id:486900000011,api:0,p:-1,c:18537) connect: controlledByApp=false
04-21 15:57:23.345 18537 18537 I SurfaceView: 251555413 visibleChanged -- surfaceCreated 
04-21 15:57:23.345 18537 11018 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#17(BLAST Consumer)17](id:486900000011,api:1,p:18537,c:18537) connect: api=1 producerControlledByApp=true
04-21 15:57:23.347 18537 18537 D SurfaceView: 251555413 handleSyncNoBuffer
04-21 15:57:23.348 18537 18537 D SurfaceView: 251555413 finishedDrawing
04-21 15:57:23.348 18537 18537 D SurfaceView: 251555413 performDrawFinished mAttachedToWindow true
04-21 15:57:23.348 18537 18537 I SurfaceControl:  setExtendedRangeBrightness sc=Surface(name=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity)/@0x2a4dd52,currentBufferRatio=1.0,desiredRatio=1.0
04-21 15:57:23.348 18537 18537 D SurfaceView: 251555413 dispatchDraw mDrawFinished true isAboveParent false (mPrivateFlags & PFLAG_SKIP_DRAW) 128
04-21 15:57:23.348 18537 18537 D SurfaceView: 251555413 clearSurfaceViewPort mCornerRadius 0.0
04-21 15:57:23.353 18537 11011 D BLASTBufferQueue: [VRI[MainActivity]#16](f:0,a:1) acquireNextBufferLocked size=1440x3216 mFrameNumber=1 applyTransaction=true mTimestamp=1243316016314095(auto) mPendingTransactions.size=0 graphicBufferId=79615808765993 transform=0
04-21 15:57:23.353 18537 11011 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
04-21 15:57:23.353 18537 18537 D VRI[MainActivity]: draw finished.
04-21 15:57:23.353 18537 18537 D VRI[MainActivity]: reportDrawFinished
04-21 15:57:23.354 18537 18537 D ViewRootImplExtImpl: setMaxDequeuedBufferCount: 2
04-21 15:57:23.370 18537 11018 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#17](f:0,a:1) acquireNextBufferLocked size=1440x3216 mFrameNumber=1 applyTransaction=true mTimestamp=1243316032742741(auto) mPendingTransactions.size=0 graphicBufferId=79615808765994 transform=0
04-21 15:57:23.380 18537 18537 D VRI[MainActivity]: onFocusEvent true
04-21 15:57:23.949 18537 18537 W VRI[MainActivity]: handleResized abandoned!
04-21 15:57:24.385 18537 12065 D OplusScrollToTopManager: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity,This DecorView@5b81868[MainActivity] change focus to true
04-21 15:57:24.574 18537 18537 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=90.0, y[0]=244.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1243317236, downTime=1243317188, deviceId=4, source=0x1002, displayId=0, eventId=323080694 } handled by client, just return
04-21 15:57:25.930 18537 18537 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1240.0, y[0]=3092.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1243318591, downTime=1243318504, deviceId=4, source=0x1002, displayId=0, eventId=455498720 } handled by client, just return
04-21 15:57:26.606 18537 18537 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1247.0, y[0]=2008.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1243319268, downTime=1243319189, deviceId=4, source=0x1002, displayId=0, eventId=789490578 } handled by client, just return
04-21 15:57:28.941 18537 18537 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1248.0, y[0]=1741.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1243321602, downTime=1243321523, deviceId=4, source=0x1002, displayId=0, eventId=254326988 } handled by client, just return
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: LE2121
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.11.43 (Suggested: 19.11.43)
Patches version: v4.7.0
Patches added: Change header [Header: yt_premium_wordmark_header], Custom branding, Enable slide to seek
Patches removed: Disable precise seeking gesture, Hide captions button, Hide player buttons, Comments, Hide filter bar, Disable fullscreen ambient mode, Player flyout menu, Disable rolling number animations, Hide timestamp, Custom player overlay opacity, Alternative thumbnails, Disable zoom haptics
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 48 patches
Change header failed: app.revanced.patcher.patch.PatchException: The provided path is not a directory: yt_premium_wordmark_header
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:117)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:115)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:143)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:14)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by validcube** [comment]
👋 Hello, @BedBug2479!

Thanks for filing this issue, but however this issue is out-of-scope for this repository (ReVanced Manager), the correct repository to file this issue in would be our [ReVanced Patches repository](https://github.com/ReVanced/revanced-patches).
