### ISSUE TITLE
bug: imported json file for patch doesn't work

### ISSUE THREAD

**Issue by SEggsee** [ReVanced/revanced-manager#1878]
### Bug description

importing older json file for patches after patch updates doesn't select the patches on said json file

### Version of ReVanced Manager and version & name of app you are patching

Version of Revanced Manager : 1.20.1
Name of app : YouTube version 19.11.43

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of system
04-22 06:29:46.000 20783 20783 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
04-22 06:29:46.113 20783 20783 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
04-22 06:29:46.134 20783 20783 D MiuiMultiWindowUtils: freeform resolution args raw data:{  "zizhan":{    "freeform_args": {      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}}    },    "mini_freeform_args":{      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.165},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.165}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.293},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.293}}    }  },  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":0.125,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":-1,"left_margin":0.0714},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":0.125,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":-1,"left_margin":0.0714}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "vertical_landscape":{"aspect_ratio":-1, "original_ratio":0.144},        "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":0.144}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":1,"original_scale":0.7182,"top_margin":0.142,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.8, "original_ratio":1,"original_scale":0.7182,"top_margin":-1,"left_margin":0.05},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":0.142,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":-1,"left_margin":0.05}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "vertical_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3},        "horizontal_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio
04-22 06:29:46.648 20783 20783 W Looper  : PerfMonitor doFrame : time=2ms vsyncFrame=0 latency=460ms procState=-1 historyMsgCount=3 (msgIndex=3 wall=446ms seq=12 running=46ms runnable=3ms late=21ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
04-22 06:29:47.176 20783 20783 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=488ms procState=-1 historyMsgCount=4
04-22 06:29:47.716 20783 20783 W Looper  : PerfMonitor doFrame : time=17ms vsyncFrame=0 latency=460ms procState=-1 historyMsgCount=2 (msgIndex=2 wall=459ms seq=47 running=43ms runnable=1ms late=4ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
04-22 22:40:10.517  9854  9854 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
04-22 22:40:10.622  9854  9854 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
04-22 22:40:10.640  9854  9854 D MiuiMultiWindowUtils: freeform resolution args raw data:{  "zizhan":{    "freeform_args": {      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}}    },    "mini_freeform_args":{      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.165},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.165}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.293},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.293}}    }  },  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":0.125,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":-1,"left_margin":0.0714},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":0.125,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":-1,"left_margin":0.0714}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "vertical_landscape":{"aspect_ratio":-1, "original_ratio":0.144},        "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":0.144}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":1,"original_scale":0.7182,"top_margin":0.142,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.8, "original_ratio":1,"original_scale":0.7182,"top_margin":-1,"left_margin":0.05},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":0.142,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":-1,"left_margin":0.05}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "vertical_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3},        "horizontal_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio
04-22 22:40:11.343  9854  9854 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=498ms procState=-1 historyMsgCount=12
04-22 22:40:11.911  9854  9854 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=531ms procState=-1 historyMsgCount=1
04-22 22:40:12.453  9854  9854 W Looper  : PerfMonitor doFrame : time=18ms vsyncFrame=0 latency=454ms procState=-1 historyMsgCount=1
--------- beginning of main
04-22 23:13:11.485 17928 17928 I manager.flutte: Using CollectorTypeCC GC.
04-22 23:13:11.488 17928 17928 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
04-22 23:13:11.489 17928 17928 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
04-22 23:13:11.491 17928 17928 I MessageMonitor: Load libmiui_runtime
04-22 23:13:11.507 17928 17928 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10316; state: ENABLED
04-22 23:13:11.508 17928 17944 D AppScoutStateMachine: 17928-ScoutStateMachinecreated
04-22 23:13:11.522 17928 17928 W System.err: org.xml.sax.SAXParseException: name expected (position:START_TAG <integer>@4:1 in java.io.InputStreamReader@ee8d063) 
04-22 23:13:11.522 17928 17928 W System.err: 	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
04-22 23:13:11.522 17928 17928 W System.err: 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeValues.parseThemeValues(ThemeValues.java:123)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.load(ThemeResources.java:486)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfigInner(ThemeZipFile.java:274)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfig(ThemeZipFile.java:256)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.newTarget(ThemeResources.java:479)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeResources.loadThemeValues(ThemeResources.java:498)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeResources.checkUpdate(ThemeResources.java:262)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeResourcesSystem.checkUpdate(ThemeResourcesSystem.java:94)
04-22 23:13:11.522 17928 17928 W System.err: 	at miui.content.res.ThemeResources.getSystem(ThemeResources.java:136)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.content.res.MiuiResourcesImpl.updateConfiguration(MiuiResourcesImpl.java:248)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.content.res.Resources.updateConfiguration(Resources.java:2126)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.content.res.Resources.updateSystemConfiguration(Resources.java:2139)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.app.ResourcesManager.applyConfigurationToResources(ResourcesManager.java:1407)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.app.ResourcesManager.applyConfigurationToResources(ResourcesManager.java:1366)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6876)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.app.ActivityThread.access$1600(ActivityThread.java:271)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.os.Looper.loopOnce(Looper.java:210)
04-22 23:13:11.522 17928 17928 W System.err: 	at android.os.Looper.loop(Looper.java:299)
04-22 23:13:11.523 17928 17928 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8319)
04-22 23:13:11.523 17928 17928 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 23:13:11.523 17928 17928 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
04-22 23:13:11.523 17928 17928 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
04-22 23:13:11.533 17928 17928 W System.err: org.xml.sax.SAXParseException: name expected (position:START_TAG <integer>@4:1 in java.io.InputStreamReader@70837b7) 
04-22 23:13:11.533 17928 17928 W System.err: 	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
04-22 23:13:11.533 17928 17928 W System.err: 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeValues.parseThemeValues(ThemeValues.java:123)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.load(ThemeResources.java:486)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfigInner(ThemeZipFile.java:274)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfig(ThemeZipFile.java:256)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.newTarget(ThemeResources.java:479)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeResources.loadThemeValues(ThemeResources.java:498)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeResources.checkUpdate(ThemeResources.java:262)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeResourcesSystem.checkUpdate(ThemeResourcesSystem.java:102)
04-22 23:13:11.533 17928 17928 W System.err: 	at miui.content.res.ThemeResources.getSystem(ThemeResources.java:136)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.content.res.MiuiResourcesImpl.updateConfiguration(MiuiResourcesImpl.java:248)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.content.res.Resources.updateConfiguration(Resources.java:2126)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.content.res.Resources.updateSystemConfiguration(Resources.java:2139)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.app.ResourcesManager.applyConfigurationToResources(ResourcesManager.java:1407)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.app.ResourcesManager.applyConfigurationToResources(ResourcesManager.java:1366)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6876)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.app.ActivityThread.access$1600(ActivityThread.java:271)
04-22 23:13:11.533 17928 17928 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
04-22 23:13:11.534 17928 17928 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-22 23:13:11.534 17928 17928 W System.err: 	at android.os.Looper.loopOnce(Looper.java:210)
04-22 23:13:11.534 17928 17928 W System.err: 	at android.os.Looper.loop(Looper.java:299)
04-22 23:13:11.534 17928 17928 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8319)
04-22 23:13:11.534 17928 17928 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 23:13:11.534 17928 17928 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
04-22 23:13:11.534 17928 17928 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
04-22 23:13:11.546 17928 17928 W System.err: org.xml.sax.SAXParseException: name expected (position:START_TAG <integer>@4:1 in java.io.InputStreamReader@2fc75c1) 
04-22 23:13:11.547 17928 17928 W System.err: 	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
04-22 23:13:11.547 17928 17928 W System.err: 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeValues.parseThemeValues(ThemeValues.java:123)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.load(ThemeResources.java:486)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfigInner(ThemeZipFile.java:274)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfig(ThemeZipFile.java:256)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.newTarget(ThemeResources.java:479)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeResources.loadThemeValues(ThemeResources.java:498)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeResources.checkUpdate(ThemeResources.java:262)
04-22 23:13:11.547 17928 17928 W System.err: 	at miui.content.res.ThemeResourcesSystem.checkUpdate(ThemeResourcesSystem.java:94)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.content.res.MiuiResourcesImpl.updateConfiguration(MiuiResourcesImpl.java:254)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.content.res.Resources.updateConfiguration(Resources.java:2126)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.content.res.Resources.updateSystemConfiguration(Resources.java:2139)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.app.ResourcesManager.applyConfigurationToResources(ResourcesManager.java:1407)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.app.ResourcesManager.applyConfigurationToResources(ResourcesManager.java:1366)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6876)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.app.ActivityThread.access$1600(ActivityThread.java:271)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.os.Looper.loopOnce(Looper.java:210)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.os.Looper.loop(Looper.java:299)
04-22 23:13:11.547 17928 17928 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8319)
04-22 23:13:11.547 17928 17928 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 23:13:11.547 17928 17928 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
04-22 23:13:11.5
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Vertuhai** [comment]
It also does not export or save the settings of the patches you have selected; you need to select it again every time you log in.
