### ISSUE TITLE
I can't seem to finish compiling the patched YouTube app

### ISSUE THREAD

**Issue by MasklessFate** [ReVanced/revanced-manager#1889]
- Device Info
ReVanced Manager: 1.20.1
Model: moto g84 5G
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.11.43 (Suggested: 19.11.43)
Patches version: v4.7.0
Patches added: Change header [Header: /data/user/0/app.revanced.manager.flutter/cache], Custom branding [App name: YT, App icon: /data/user/0/app.revanced.manager.flutter/cache], Enable slide to seek, Remove player controls background
Patches removed: Theme, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 59 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~_QzHvmjgatg6hlgv9chzzw==/app.revanced.manager.flutter-E8AyB21mdWIPRHaT6hCYHA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TPRPSK/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TPRPSK/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~_QzHvmjgatg6hlgv9chzzw==/app.revanced.manager.flutter-E8AyB21mdWIPRHaT6hCYHA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TPRPSK/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TPRPSK/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more

**Comment by oSumAtrIX** [comment]
Patch a full APK and reset the ReVanced Manager settings to their recommended default value. For support move to one of our links at https://revanced.app
