### ISSUE TITLE
bug: Out of Memory Error

### ISSUE THREAD

**Issue by Rifa335** [ReVanced/revanced-manager#1905]
### Bug description

I just start Patching, and when it comes to Compiling Classes24.dex it just errors

### Version of ReVanced Manager and version & name of app you are patching

Revanced Manager : Newest
TikTok Asia (com.ss.android.ugc.trills) : V.32.5.3

### Installation method

None

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: 2209116AG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.ss.android.ugc.trill v32.5.3 (Suggested: 32.5.3)
Patches version: v4.7.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 8 patches
Compiling patched dex files
Compiled 23 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 3578736 free bytes and 3494KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:124)
	at com.android.tools.smali.util.Utf8Utils.utf8BytesWithUtf16LengthToString(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexReader.readString(Unknown Source:12)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedMethodReference.getReturnType(Unknown Source:22)
	at com.android.tools.smali.dexlib2.base.reference.BaseMethodReference.hashCode(Unknown Source:21)
	at java.util.HashMap.hash(HashMap.java:336)
	at java.util.HashMap.getNode(HashMap.java:566)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:464)
	at com.android.tools.smali.dexlib2.writer.pool.BaseIndexPool.getItemIndex(Unknown Source:2)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.write(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(Unknown Source:323)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(Unknown Source:211)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:80)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
#memo
