### ISSUE TITLE
bug: crash while patching reddit apk

### ISSUE THREAD

**Issue by rufftruffles** [ReVanced/revanced-manager#1907]
### Bug description

The crash happens while trying to patch reddit apks, I tried both the latest (2024.20.1) and previous (2024.19.0) versions.

Default patches selected.

### Version of ReVanced Manager and version & name of app you are patching

Revanced manager: 1.20.1
Reddit apk: 2024.20.1 & 2024.19.0

### Installation method

Regular

### ReVanced Manager logs

```shell
android.view.Choreographer$CallbackRecord.run:1698 
05-17 01:37:51.495 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: Setup new sync=wmsSync-ViewRootImpl@1208ee5[MainActivity]#9
05-17 01:37:51.495 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: Creating new active sync group ViewRootImpl@1208ee5[MainActivity]#10
05-17 01:37:51.495 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: registerCallbacksForSync syncBuffer=false
05-17 01:37:51.496 15037 15065 D SurfaceView: 198935391 updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 1440, 3088] surfaceSize = 1440x3088
05-17 01:37:51.496 15037 15065 I SurfaceView@bdb835f: uSP: rtp = Rect(0, 0 - 1440, 3088) rtsw = 1440 rtsh = 3088
05-17 01:37:51.496 15037 15065 I SurfaceView@bdb835f: onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
05-17 01:37:51.496 15037 15065 I SurfaceView@bdb835f: aOrMT: ViewRootImpl@1208ee5[MainActivity] t = android.view.SurfaceControl$Transaction@c54db13 fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:369 
05-17 01:37:51.496 15037 15065 I ViewRootImpl@1208ee5[MainActivity]: mWNT: t=0xb400007752d8e600 mBlastBufferQueue=0xb400007752dd2d00 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.SurfaceView.applyOrMergeTransaction:1598 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 
05-17 01:37:51.496 15037 15958 I ViewRootImpl@1208ee5[MainActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
05-17 01:37:51.496 15037 15958 I ViewRootImpl@1208ee5[MainActivity]: mWNT: t=0xb40000762612ad00 mBlastBufferQueue=0xb400007752dd2d00 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13841 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack> 
05-17 01:37:51.496 15037 15958 I ViewRootImpl@1208ee5[MainActivity]: Setting up sync and frameCommitCallback
05-17 01:37:51.540 15037 15065 I BLASTBufferQueue: [ViewRootImpl@1208ee5[MainActivity]#4](f:0,a:0,s:0) onFrameAvailable the first frame is available
05-17 01:37:51.541 15037 15065 I ViewRootImpl@1208ee5[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
05-17 01:37:51.541 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: reportDrawFinished seqId=0
05-17 01:37:51.559 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
05-17 01:37:51.560 15037 15037 D ViewRootImpl@1208ee5[MainActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb40000762632a000}
05-17 01:37:51.560 15037 15037 D InputMethodManagerUtils: startInputInner - Id : 0
05-17 01:37:51.560 15037 15037 I InputMethodManager: startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
05-17 01:37:51.566 15037 15070 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]@0#5](f:0,a:0,s:0) onFrameAvailable the first frame is available
05-17 01:37:51.573 15037 15037 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=false, type=ime, host=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
05-17 01:37:51.574 15037 15160 I ViewRootImpl@1208ee5[MainActivity]: Resizing android.view.ViewRootImpl@5b2f311: frame = [0,0][1440,3088] reportDraw = false forceLayout = false syncSeqId = -1
05-17 01:37:51.574 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1440,3088] display=[0,0][1440,3088] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false
05-17 01:37:51.610 15037 15051 I manager.flutter: CollectorTransition concurrent mark compact GC freed 5928193(165MB) AllocSpace objects, 95(6012KB) LOS objects, 17% free, 110MB/134MB, paused 95us,2.625ms total 210.902ms
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:51.611 15037 15053 W System  : A resource failed to call close. 
05-17 01:37:52.377 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme key 0
05-17 01:37:52.377 15037 15037 D Activity: onKeyDown(KEYCODE_BACK)
05-17 01:37:52.410 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme key 1
05-17 01:37:52.410 15037 15037 D Activity: onKeyUp(KEYCODE_BACK) isTracking()=true isCanceled()=false hasCallback=false
05-17 01:37:54.010 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:37:54.046 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:37:54.699 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:37:54.797 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:37:55.015 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:37:55.372 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:37:55.775 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:37:55.864 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:37:56.007 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:37:56.872 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:37:57.132 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:37:57.681 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:37:59.479 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:37:59.742 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:00.263 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:00.517 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:00.997 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:01.267 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:02.066 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:02.469 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:05.368 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:05.464 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:05.615 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:05.939 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:06.243 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:06.331 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:06.666 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:06.856 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:07.451 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:07.581 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:07.766 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:07.931 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
05-17 01:38:08.670 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 0
05-17 01:38:08.716 15037 15037 I ViewRootImpl@1208ee5[MainActivity]: ViewPostIme pointer 1
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: SM-S918B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.20.1 (Suggested: Any)
Patches version: v4.7.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~KeWe2ebNWQh8MqBemKxYLQ==/app.revanced.manager.flutter-EysOhQHJDhfZaCFOGAmA8Q==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1615586, --version-name, 2024.20.1, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL629691680853244322.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~KeWe2ebNWQh8MqBemKxYLQ==/app.revanced.manager.flutter-EysOhQHJDhfZaCFOGAmA8Q==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1615586, --version-name, 2024.20.1, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL629691680853244322.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BCULEB/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
#1258
