### ISSUE TITLE
bug: failed to patch the recommended Reddit 2024.17.0 version

### ISSUE THREAD

**Issue by dushmanta05** [ReVanced/revanced-manager#1950]
### Bug description

I tried to patch the recommended 2024.17.0, which I downloaded from the ApkMirror website resulted in an `OutOfMemory` error.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager Version: 1.20.1
App Name: Reddit (2024.17.1)

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of system
06-16 08:01:31.087  5792  5792 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
06-16 08:01:32.539  5792  5792 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
06-16 08:01:33.413  5792  5792 W BpBinder: Slow Binder: BpBinder transact took 871 ms, interface=android.view.accessibility.IAccessibilityManager, code=3 oneway=false
06-16 08:01:33.609  5792  5792 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onCreate took 2364ms
06-16 08:01:33.688  5792  5792 W Looper  : PerfMonitor longMsg : seq=3 plan=08:01:30.967 late=133ms wall=2588ms running=0ms h=android.app.ActivityThread$H w=159 procState=-1
06-16 08:01:33.688  5792  5792 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=2721ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=122ms seq=2 late=15ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=2588ms seq=3 late=133ms h=android.app.ActivityThread$H w=159)
06-16 08:01:34.752  5792  5792 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=928ms procState=-1 historyMsgCount=2
06-16 08:01:35.374  5792  5792 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=550ms procState=-1 historyMsgCount=1
06-16 08:01:36.182  5792  5792 W Looper  : PerfMonitor doFrame : time=70ms vsyncFrame=0 latency=704ms procState=-1 historyMsgCount=11 (msgIndex=1 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=6 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=7 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=8 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=9 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=10 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-16 08:01:36.212  5792  5792 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=3ms latency=722ms running=0ms  procState=-1  historyMsgCount=19 (msgIndex=1 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=6 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=7 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=8 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=9 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=10 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=12 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
06-16 08:01:36.216  5792  5792 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=3ms latency=725ms running=0ms  procState=-1  historyMsgCount=20 (msgIndex=1 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=6 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=7 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=8 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=9 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=10 wall=617ms seq=37 late=93ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=12 wall=70ms seq=39 late=704ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
06-16 08:02:56.996  5792  5792 W Looper  : PerfMonitor doFrame : time=318ms vsyncFrame=0 latency=6ms procState=-1 historyMsgCount=2 (msgIndex=1 wall=318ms seq=127 late=6ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=318ms seq=127 late=6ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
06-16 08:05:29.748  5792  5792 W Looper  : PerfMonitor longMsg : seq=680 plan=08:05:28.389 late=12ms wall=1340ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:07:46.056  5792  5792 W Looper  : PerfMonitor longMsg : seq=790 plan=08:07:44.875 late=1ms wall=1179ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:07:46.057  5792  5792 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=1179ms procState=-1 historyMsgCount=1
06-16 08:07:47.125  5792  5792 W Looper  : PerfMonitor longMsg : seq=793 plan=08:07:46.056 late=2ms wall=1066ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:08:10.104  5792  5792 W Looper  : PerfMonitor longMsg : seq=815 plan=08:08:08.964 late=3ms wall=1136ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:09:14.862  5792  5792 W Looper  : PerfMonitor doFrame : time=440ms vsyncFrame=0 latency=1ms procState=-1 historyMsgCount=2 (msgIndex=1 wall=440ms seq=834 late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=440ms seq=834 late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
06-16 08:12:49.862  5792  5792 W PackageParsing: No actions in intent-filter at /data/user/0/app.revanced.manager.flutter/cache/com.reddit.frontpage_2024.17.0-1568106_minAPI26(arm64-v8a,armeabi-v7a,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #526
06-16 08:13:56.498  5792  5792 W Looper  : PerfMonitor longMsg : seq=1984 plan=08:13:54.921 late=0ms wall=1577ms running=0ms h=android.view.ViewRootImpl$ViewRootHandler w=6 procState=-1
06-16 08:14:02.921  5792  5792 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 275ms
06-16 08:14:36.642  5792  5792 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=348ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=347ms seq=2004 h=android.app.ActivityThread$H w=159) (msgIndex=3 wall=347ms seq=2004 h=android.app.ActivityThread$H w=159)
06-16 08:14:37.251  5792  5792 W Looper  : PerfMonitor doFrame : time=609ms vsyncFrame=0 latency=4ms procState=-1 historyMsgCount=11 (msgIndex=1 wall=609ms seq=2007 late=4ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=8 wall=609ms seq=2007 late=4ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=9 wall=609ms seq=2007 late=4ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
06-16 08:14:40.382  5792  5792 W Looper  : PerfMonitor longMsg : seq=2015 plan=08:14:37.206 late=53ms wall=3120ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:14:40.383  5792  5792 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=3111ms procState=-1 historyMsgCount=2
06-16 08:14:42.109  5792  5792 W Looper  : PerfMonitor longMsg : seq=2023 plan=08:14:40.421 late=0ms wall=1687ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:14:42.110  5792  5792 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=1687ms procState=-1 historyMsgCount=5
06-16 08:14:43.208  5792  5792 W Looper  : PerfMonitor longMsg : seq=2039 plan=08:14:42.179 late=9ms wall=1020ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:14:43.252  5792  5792 W Looper  : PerfMonitor doFrame : time=36ms vsyncFrame=0 latency=1026ms procState=-1 historyMsgCount=3
06-16 08:14:45.695  5792  5792 W Looper  : PerfMonitor longMsg : seq=2046 plan=08:14:42.559 late=729ms wall=2407ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:14:48.426  5792  5792 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=667ms procState=-1 historyMsgCount=1
06-16 08:14:58.585  5792  5792 W Looper  : PerfMonitor longMsg : seq=2233 plan=08:14:57.314 late=0ms wall=1270ms running=0ms h=android.app.ActivityThread$H w=149 procState=-1
06-16 08:14:58.644  5792  5792 W PackageParsing: No actions in intent-filter at /data/user/0/app.revanced.manager.flutter/cache/com.reddit.frontpage_2024.17.0-1568106_minAPI26(arm64-v8a,armeabi-v7a,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #526
06-16 08:15:02.749  5792  5792 W Looper  : PerfMonitor longMsg : seq=2248 plan=08:15:00.647 late=2ms wall=2098ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-16 08:17:36.980  5792  5792 W Looper  : PerfMonitor doFrame : time=885ms vsyncFrame=0 latency=1ms procState=-1 historyMsgCount=4 (msgIndex=1 wall=885ms seq=2300 late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=885ms seq=2300 late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=3 wall=885ms seq=2300 late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=4 wall=885ms seq=2300 late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
--------- beginning of main
06-16 08:29:15.309  5792  5792 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=377810931, downTime=377810931, deviceId=-1, source=0x101, displayId=0 }
06-16 08:29:15.332  5792  5792 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=377810931, downTime=377810931, deviceId=-1, source=0x101, displayId=0 }
06-16 08:29:37.951  5792  5792 D DecorView[]: onWindowFocusChanged hasWindowFocus false
06-16 08:29:51.527  5792  9099 D AppScoutStateMachine: 5792-ScoutStateMachinecreated
06-16 08:29:51.557  5792  5792 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x65238da, mIsProjectionMode = false
06-16 08:29:51.557  5792  5792 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
06-16 08:29:51.557  5792  5792 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
06-16 08:29:51.557  5792  5792 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
06-16 08:29:51.578  5792  5792 D DecorView[]: onWindowFocusChanged hasWindowFocus true
06-16 08:29:51.580  5792  9099 I OpenGLRenderer: Davey! duration=671551ms; Flags=1, FrameTimelineVsyncId=13673073, IntendedVsync=377175647777580, Vsync=377175647777580, InputEventId=948017482, HandleInputStart=377175648372779, AnimationStart=377175648374290, PerformTraversalsStart=377175648374967, DrawStart=377175681190592, FrameDeadline=377175681110912, FrameInterval=377175648360644, FrameStartTime=16666666, SyncQueued=377175681375852, SyncStart=377175681483665, IssueDrawCommandsStart=377175681670019, SwapBuffers=377175688024238, FrameCompleted=377847199785336, DequeueBufferDuration=4869531, QueueBufferDuration=995209, GpuCompleted=377847199785336, SwapBuffersCompleted=377175689880227, DisplayPresentTime=17695,
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: M2101K7AG
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.17.0 (Suggested: 2024.17.0)
Patches version: v4.9.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Compiled 16 dex files
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 8 free bytes and 8B until OOM, target footprint 536870912, growth limit 536870912
	at com.android.tools.smali.dexlib2.dexbacked.DexBuffer.readerAt(Unknown Source:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedAnnotation.getElements(Unknown Source:8)
	at com.android.tools.smali.dexlib2.base.BaseAnnotation.equals(Unknown Source:31)
	at java.util.HashMap.getNode(HashMap.java:568)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:464)
	at com.android.tools.smali.dexlib2.writer.pool.BaseOffsetPool.getItemOffset(Unknown Source:2)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeAnnotationSets(Unknown Source:100)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:80)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by dushmanta05** [comment]
Also, I'm not sure if I should create the issue in `revanced-patches`! Since it was in the manager app, I chose to report here.

**Comment by oSumAtrIX** [comment]
#1905

**Comment by dushmanta05** [comment]
Sorry! My bad I thought the error was related Reddit so didn't check out of memory. Thanks.
