### ISSUE TITLE
bug: Can't compile

### ISSUE THREAD

**Issue by sogata-aw** [ReVanced/revanced-manager#1952]
### Bug description

I tried to patch youtube in version 19.16.39 but it show me this log.

### Version of ReVanced Manager and version & name of app you are patching

1.21.0-dev.3

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: 2201117TY
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.9.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 58 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 10485776 byte allocation with 4879040 free bytes and 4764KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3578)
	at com.google.common.io.ByteStreams.combineBuffers(Unknown Source:23)
	at com.google.common.io.ByteStreams.toByteArrayInternal(Unknown Source:45)
	at com.google.common.io.ByteStreams.toByteArray(SourceFile:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromStream(Unknown Source:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.OverflowToDiskByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.ChunkBasedByteStorage.fromSource(Unknown Source:29)
	at com.android.tools.build.apkzlib.zip.ZFile.mergeFrom(Unknown Source:200)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:148)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
#1905
