### ISSUE TITLE
No cast icon

### ISSUE THREAD

**Issue by JustCryen** [revanced/revanced-manager#200]
### Type

Other

### Branch

Flutter

### Bug description

The cast icon is not available in the main menu or above the video.
Fortunately you can still use the cast options in the settings.

(I'm not sure if the log is at all relevant to the bug but that's the only log I have and attaching a log is required to post a bug report.)

### Steps to reproduce

1. Install the 0.7 version of ReVanced Manager (0.8 and 0.9 failed to patch and crashed)
2. Exclude Hide Cast Button patch (and possibly some more, see attached screenshot for patch list)
3. Patch the supported version of YT
4. Cast button still missing

### Relevant log output

```shell
--------- beginning of crash
09-17 23:28:10.410 16583 16583 E AndroidRuntime: FATAL EXCEPTION: main
09-17 23:28:10.410 16583 16583 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 16583
09-17 23:28:10.410 16583 16583 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=209, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4580)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4612)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:248)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7865)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=209, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5159)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4560)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	... 11 more
09-17 23:28:10.410 16583 16583 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8410)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5152)
09-17 23:28:10.410 16583 16583 E AndroidRuntime: 	... 12 more
```

### Screenshots or videos

![Screenshot_20220918-125702094_1](https://user-images.githubusercontent.com/41633661/190899112-668615fc-2261-4987-befb-57c764f604a4.jpg)

**Comment by pietryszak** [comment]
Check that on 0.0.13

**Comment by Canny1913** [comment]
Intended behavior and wrong repository.

**Comment by JustCryen** [comment]
Ah, sorry about that.
I've just read that it's an issue with non rooted installations and not the manager malfunctioning (as I thought)
Anyway, I don't really think it should be called an "intended behaviour" because casting works for me on V1 protocol (for example STN) so in my opinion it should be looked into and not dismissed outright.

**Comment by Canny1913** [comment]
- https://github.com/revanced/revanced-patches/issues/243
