### ISSUE TITLE
bug: Error occurred while patching

### ISSUE THREAD

**Issue by Mehedi-Oz** [ReVanced/revanced-manager#2007]
### Bug description

I have tried 4-5 times to patch the YouTube app, but each time it gets cancelled.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.20.1

Youtube: 19.16.39

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of system
06-26 00:58:48.449  4343  4343 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onCreate took 1516ms
06-26 00:58:48.567  4343  4343 W Looper  : PerfMonitor longMsg : seq=3 plan=00:58:46.478 late=244ms wall=1844ms h=android.app.ActivityThread$H w=159 procState=-1
06-26 00:58:48.569  4343  4343 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=2089ms  procState=-1  historyMsgCount=3 (msgIndex=3 wall=1844ms seq=3 late=244ms h=android.app.ActivityThread$H w=159)
06-26 00:58:48.573  4343  4343 D FramePredict: FramePredict init: false
06-26 00:58:50.872  4343  4343 W Looper  : PerfMonitor longMsg : seq=11 plan=00:58:48.576 late=116ms wall=2179ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 00:58:50.880  4343  4343 W Looper  : PerfMonitor doFrame : time=3ms vsyncFrame=0 latency=2284ms procState=-1 historyMsgCount=6 (msgIndex=5 wall=2179ms seq=11 late=116ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 00:58:52.541  4343  5605 W BpBinder: PerfMonitor binderTransact :  time=938ms interface=android.content.IContentProvider code=1
06-26 00:58:53.219  4343  4343 W Looper  : PerfMonitor longMsg : seq=28 plan=00:58:51.050 late=0ms wall=2168ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 00:58:53.222  4343  4343 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=2156ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=2168ms seq=28 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 00:58:55.646  4343  4343 W Looper  : PerfMonitor longMsg : seq=42 plan=00:58:53.308 late=2ms wall=2335ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 00:58:55.739  4343  4343 W Looper  : PerfMonitor doFrame : time=65ms vsyncFrame=0 latency=2360ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=2335ms seq=42 late=2ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 00:58:56.108  4343  4343 W BpBinder: PerfMonitor binderTransact :  time=315ms interface=com.android.internal.view.IInputMethodManager code=9
06-26 00:58:58.385  4343  4343 W Looper  : PerfMonitor longMsg : seq=58 plan=00:58:56.470 late=1ms wall=1914ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 00:59:00.181  4343  6275 W BpBinder: PerfMonitor binderTransact :  time=1737ms interface=android.os.storage.IStorageManager code=35
06-26 00:59:03.262  4343  4343 W MiuiMagicPointerUtilsStubHeadImpl: MiuiMagicPointerUtilsStubHeadImpl has been initialized !!
06-26 00:59:16.323  4343  4343 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
06-26 00:59:16.472  4343  4343 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onActivityResult took 149ms
06-26 00:59:19.936  4343  4343 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
06-26 00:59:19.939  4343  4343 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
06-26 00:59:24.323  4343  4343 W Looper  : PerfMonitor longMsg : seq=214 plan=00:59:22.830 late=8ms wall=1483ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:19.883  4343  4343 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 124ms
06-26 01:02:24.765  4343  4343 W Looper  : PerfMonitor longMsg : seq=374 plan=01:02:23.471 late=30ms wall=1263ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:24.768  4343  4343 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=1262ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=1263ms seq=374 late=30ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:26.154  4343  4343 W Looper  : PerfMonitor longMsg : seq=385 plan=01:02:24.840 late=1ms wall=1312ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:26.155  4343  4343 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=1304ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=1312ms seq=385 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:27.561  4343  4343 W Looper  : PerfMonitor longMsg : seq=394 plan=01:02:26.183 late=1ms wall=1377ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:27.599  4343  4343 W Looper  : PerfMonitor doFrame : time=34ms vsyncFrame=0 latency=1382ms procState=-1 historyMsgCount=2 (msgIndex=2 wall=1377ms seq=394 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:29.001  4343  4343 W Looper  : PerfMonitor longMsg : seq=404 plan=01:02:26.735 late=944ms wall=1322ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:29.011  4343  4343 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=1360ms procState=-1 historyMsgCount=3 (msgIndex=3 wall=1322ms seq=404 late=944ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:45.414  4343  4343 W Looper  : PerfMonitor longMsg : seq=537 plan=01:02:43.359 late=41ms wall=2013ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:45.418  4343  4343 W Looper  : PerfMonitor doFrame : time=4ms vsyncFrame=0 latency=2053ms procState=-1 historyMsgCount=6 (msgIndex=6 wall=2013ms seq=537 late=41ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:46.036  4343  4343 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=600ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=614ms seq=541 late=7ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:48.880  4343  4343 W Looper  : PerfMonitor longMsg : seq=547 plan=01:02:46.076 late=1ms wall=2802ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:48.882  4343  4343 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=2797ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=2802ms seq=547 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:48.889  4343  4343 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=6ms latency=604ms  procState=-1  historyMsgCount=3 (msgIndex=1 wall=2802ms seq=547 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:48.891  4343  4343 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=1ms latency=599ms  procState=-1  historyMsgCount=4 (msgIndex=1 wall=2802ms seq=547 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:48.911  4343  4343 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=20ms latency=543ms  procState=-1  historyMsgCount=7 (msgIndex=1 wall=2802ms seq=547 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:52.487  4343  4343 W Looper  : PerfMonitor longMsg : seq=562 plan=01:02:48.928 late=3ms wall=3555ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:02:52.509  4343  4343 W Looper  : PerfMonitor doFrame : time=14ms vsyncFrame=0 latency=3556ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=3555ms seq=562 late=3ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:57.919 18203 18203 D FramePredict: FramePredict init: false
06-26 01:02:58.598 18203 18203 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=664ms procState=-1 historyMsgCount=6 (msgIndex=5 wall=630ms seq=11 late=46ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:02:59.273 18203 18203 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=628ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=637ms seq=23 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:03:00.044 18203 18203 W Looper  : PerfMonitor doFrame : time=31ms vsyncFrame=0 latency=724ms procState=-1 historyMsgCount=3 (msgIndex=2 wall=719ms seq=32 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:03:00.810 18203 18203 W Looper  : PerfMonitor doFrame : time=2ms vsyncFrame=0 latency=752ms procState=-1 historyMsgCount=4 (msgIndex=4 wall=735ms seq=43 late=332ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:03:02.603 18203 18203 W MiuiMagicPointerUtilsStubHeadImpl: MiuiMagicPointerUtilsStubHeadImpl has been initialized !!
06-26 01:03:24.602 18203 18203 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
06-26 01:03:25.546 18203 18203 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
06-26 01:03:25.550 18203 18203 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
06-26 01:03:27.549 18203 18203 W Looper  : PerfMonitor longMsg : seq=246 plan=01:03:26.458 late=3ms wall=1085ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:03:31.385 20664 20664 D FramePredict: FramePredict init: false
06-26 01:03:32.123 20664 20664 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=721ms procState=-1 historyMsgCount=6 (msgIndex=5 wall=687ms seq=11 late=46ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:03:32.819 20664 20664 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=651ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=658ms seq=23 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:03:33.770 20664 20664 W Looper  : PerfMonitor doFrame : time=25ms vsyncFrame=0 latency=900ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=905ms seq=33 late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:03:34.541 20664 20664 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=762ms procState=-1 historyMsgCount=4 (msgIndex=3 wall=735ms seq=43 late=680ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:03:37.899 20664 20664 W MiuiMagicPointerUtilsStubHeadImpl: MiuiMagicPointerUtilsStubHeadImpl has been initialized !!
06-26 01:03:39.691 20664 20664 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
06-26 01:03:40.487 20664 20664 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
06-26 01:03:40.489 20664 20664 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
06-26 01:04:20.352 20664 20664 W Looper  : PerfMonitor longMsg : seq=382 plan=01:04:19.003 late=4ms wall=1344ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
06-26 01:12:04.356 32189 32189 D FramePredict: FramePredict init: false
06-26 01:12:04.873 32189 32189 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=506ms procState=-1 historyMsgCount=3
06-26 01:12:05.462 32189 32189 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=552ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=553ms seq=23 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:12:06.102 32189 32189 W Looper  : PerfMonitor doFrame : time=19ms vsyncFrame=0 latency=584ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=589ms seq=33 late=3ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:12:06.103 32189 32189 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=1ms latency=599ms  procState=-1  historyMsgCount=6 (msgIndex=1 wall=589ms seq=33 late=3ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:12:06.104 32189 32189 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=1ms latency=599ms  procState=-1  historyMsgCount=7 (msgIndex=1 wall=589ms seq=33 late=3ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:12:06.124 32189 32189 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=5ms latency=559ms  procState=-1  historyMsgCount=14 (msgIndex=1 wall=589ms seq=33 late=3ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:12:06.136 32189 32189 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=11ms latency=354ms  procState=-1  historyMsgCount=16 (msgIndex=1 wall=589ms seq=33 late=3ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
06-26 01:12:11.298 32189 32189 W MiuiMagicPointerUtilsStubHeadImpl: MiuiMagicPointerUtilsStubHeadImpl has been initialized !!
06-26 01:12:15.583 32189 32189 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
06-26 01:12:16.065 32189 32189 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
06-26 01:12:16.066 32189 32189 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
06-26 01:21:11.390 32189 32189 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
06-26 01:21:12.124 32189 32189 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
06-26 01:21:12.126 32189 32189 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/com.google.android.youtube_19.16.39-1545731520_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #443
--------- beginning of main
06-26 01:36:21.117 32189 32189 D VRI[MainActivity]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4013 android.view.ViewRootImpl.doTraversal:2725 android.view.ViewRootImpl$TraversalRunnable.run:9812 android.view.Choreographer$CallbackRecord.run:1505 android.view.Choreographer$CallbackRecord.run:1513 
06-26 01:36:21.117 32189 32189 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xf6667e5, mIsProjectionMode = false
06-26 01:36:21.118 32189 32189 D VRI[MainActivity]: vri.Setup new sync id=14 syncSeqId=0
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=0
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=1
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=2
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=3
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=4
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=5
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=6
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=7
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=8
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=9
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=10
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=11
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=12
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=13
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=14
06-26 01:36:21.118 32189 32189 E SurfaceSyncer: Failed to find sync for id=15
06-26 01:36:21.139 32189 32189 D VRI[MainActivity]: vri.reportDrawFinished syncSeqId=0 android.view.ViewRootImpl.lambda$createSyncIfNeeded$4$android-view-ViewRootImpl:4081 android.view.ViewRootImpl$$ExternalSyntheticLambda2.run:6 android.os.Handler.handleCallback:942 android.os.Handler.dispatchMessage:99 android.os.Looper.loopOnce:211 
06-26 01:36:21.182 32189 32189 D DecorView[]: onWindowFocusChanged hasWindowFocus true
06-26 01:36:21.183 32189 32189 I HandWritingStubImpl: refreshLastKeyboardType: 1
06-26 01:36:21.183 32189 32189 I HandWritingStubImpl: getCurrentKeyboardType: 1
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: 2201117TG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.10.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 58 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 8388624 byte allocation with 7428568 free bytes and 7254KB until OOM, target footprint 268435456, growth limit 268435456
	at com.google.common.io.ByteStreams.toByteArrayInternal(Unknown Source:29)
	at com.google.common.io.ByteStreams.toByteArray(SourceFile:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromStream(Unknown Source:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.OverflowToDiskByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.ChunkBasedByteStorage.fromSource(Unknown Source:29)
	at com.android.tools.build.apkzlib.zip.ZFile.mergeFrom(Unknown Source:200)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:148)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.OutOfMemoryError: Failed to allocate a 16777232 byte allocation with 10903056 free bytes and 10MB until OOM, target footprint 268435456, growth limit 268435456
		at java.util.Arrays.copyOf(Arrays.java:3578)
		at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
		at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
		at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
		at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage$2.doWrite(Unknown Source:2)
		at com.android.tools.build.apkzlib.bytestorage.AbstractCloseableByteSourceFromOutputStreamBuilder.write(SourceFile:0)
		at com.android.tools.build.apkzlib.bytestorage.OverflowToDiskByteStorage$1.doWrite(Unknown Source:2)
		at com.android.tools.build.apkzlib.bytestorage.AbstractCloseableByteSourceFromOutputStreamBuilder.write(SourceFile:0)
		at com.android.tools.build.apkzlib.bytestorage.ChunkBasedByteStorage$1.doWrite(Unknown Source:39)
		at com.android.tools.build.apkzlib.bytestorage.AbstractCloseableByteSourceFromOutputStreamBuilder.write(SourceFile:0)
		at com.google.common.io.ByteStreams.copy(Unknown Source:21)
		at com.android.tools.build.apkzlib.zip.StoredEntry.loadSourceIntoMemory(Unknown Source:29)
		at com.android.tools.build.apkzlib.zip.ZFile.reAdd(Unknown Source:32)
		at com.android.tools.build.apkzlib.zip.ZFile.packIfNecessary(Unknown Source:90)
		at com.android.tools.build.apkzlib.zip.ZFile.writeAllFilesToZip(Unknown Source:13)
		at com.android.tools.build.apkzlib.zip.ZFile.update(Unknown Source:21)
		at com.android.tools.build.apkzlib.zip.ZFile.close(Unknown Source:9)
		at kotlin.io.CloseableKt.closeFinally(Unknown Source:8)
		at app.revanced.library.ApkUtils.applyTo(Unknown Source:330)
		... 4 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
That's a known issue with your device limiting memory usage. Currently a new version of ReVanced Manager is being developed that should fix the issue but otherwise you can use ReVanced CLI to patch. 

You can get a debug build of a recent version of ReVanced Manager here:
https://github.com/ReVanced/revanced-manager/actions/runs/9653452701/artifacts/1633752362

The experimental toggle in the settings should be turned on and you should be gtg. For support, move to one of our links at https://revanced.app.
