### ISSUE TITLE
bug: Broken downloader crashing the entire app

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#2048]
### Bug description

If the plugin is broken such as demonstrated here, it crashes the app:

![image](https://github.com/user-attachments/assets/99644562-acd8-4152-a519-8c95a86df577)

Ideally downloader function exceptions are caught and gracefully handled.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Please provide logs

**Comment by oSumAtrIX** [comment]
```
07-13 18:47:10.602 10466 10466 E AndroidRuntime: java.lang.IllegalArgumentException: current must not be NaN
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.ProgressBarRangeInfo.<init>(SemanticsProperties.kt:664)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.ProgressBarRangeInfo.<init>(SemanticsProperties.kt:657)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$2$1.invoke(ProgressIndicator.kt:587)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$2$1.invoke(ProgressIndicator.kt:586)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.CoreSemanticsModifierNode.applySemantics(SemanticsModifier.kt:73)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1$1.invoke(LayoutNode.kt:440)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1$1.invoke(LayoutNode.kt:431)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2441)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.node.OwnerSnapshotObserver.observeSemanticsReads$ui_release(OwnerSnapshotObserver.kt:121)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNode.getCollapsedSemantics$ui_release(LayoutNode.kt:431)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNodeKt.SemanticsNode(SemanticsNode.kt:49)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:278)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui_release(SemanticsNode.kt:257)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.getChildren$ui_release(SemanticsNode.kt:338)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.getChildren$ui_release$default(SemanticsNode.kt:322)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.semantics.SemanticsNode.getReplacedChildren$ui_release(SemanticsNode.kt:305)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:196)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:198)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:198)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap(SemanticsUtils.android.kt:231)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.getCurrentSemanticsNodes(AndroidComposeViewAccessibilityDelegateCompat.android.kt:312)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendAccessibilitySemanticsStructureChangeEvents(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2902)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.checkForSemanticsChanges(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2399)
07-13 18:47:10.602 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.semanticsChangeChecker$lambda$60(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2221)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.$r8$lambda$_tH94CmKfDEEVJkcxJ3tWGk0mZ4(Unknown Source:0)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$$ExternalSyntheticLambda3.run(Unknown Source:2)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7918)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-13 18:47:10.603 10466 10466 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by oSumAtrIX** [comment]
Adding assertions around the downloader apis would be good

**Comment by Axelen123** [comment]
The exception occurs in the UI and not in the downloader code. While setting bytesTotal to zero is incorrect behavior, I do agree that it must not cause manager to misbehave.

**Comment by oSumAtrIX** [comment]
An assertion for the progress api could be that total  >= current  && current >= 0

**Comment by Axelen123** [comment]
I have added assertions for all invalid values
