### ISSUE TITLE
bug: YouTube fails to patch on Android 15

### ISSUE THREAD

**Issue by scarlettekk** [ReVanced/revanced-manager#2073]
### Bug description

YouTube fails to patch during the compiling modified resources stage. I've tested it with multiple versions of Revanced manager and both regular and APK select mode so it might be related to the system version? Android 15 (AP31.240517.031) on Pixel 8 Pro 

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager 1.20.1
YouTube 19.16.39

### Installation method

Mount

### ReVanced Manager logs

```shell
--------- beginning of crash
07-20 00:58:11.453 32378 32378 E AndroidRuntime: FATAL EXCEPTION: main
07-20 00:58:11.453 32378 32378 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 32378
07-20 00:58:11.453 32378 32378 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4780)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8699)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: Caused by: java.lang.NullPointerException
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(Unknown Source:63)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4771)
07-20 00:58:11.453 32378 32378 E AndroidRuntime: 	... 9 more
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: Pixel 8 Pro
Android version: 15
Supported architectures: arm64-v8a
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.11.0
Patches added: Change header, Custom branding, Remove player controls background
Patches removed: Downloads, Disable precise seeking gesture, Swipe controls, Hide captions button, Navigation buttons, Hide player buttons, Comments, Hide crowdfunding box, Hide endscreen cards, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Wide searchbar, Restore old seekbar thumbnails, Spoof app version, Enable tablet layout, Alternative thumbnails, Always repeat, Enable debugging, Spoof device dimensions, Disable zoom haptics, GmsCore support, Open links externally
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 31 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~1XyZ8U_VUg4F0ZLdAxqPMg==/app.revanced.manager.flutter-FPSw0zTzw5RXAfRR-6fJ6w==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6783843908562983747.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~1XyZ8U_VUg4F0ZLdAxqPMg==/app.revanced.manager.flutter-FPSw0zTzw5RXAfRR-6fJ6w==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6783843908562983747.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OYKULD/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Patch a full APK.

**Comment by scarlettekk** [comment]
I am not using APK bundles, if that's what you mean. I've also tried to patch an APK from storage, if that's what you mean. However, I do find the issue is resolved by using all patches except gmscore instead of picking a custom selection, so it must be related to that. Still strange that it started out of nowhere

**Comment by oSumAtrIX** [comment]
Your custom selection as seen in the logs should not cause the error,  but trying to patch a split apk

**Comment by scarlettekk** [comment]
Screen recording demonstrating the failure when using the custom patch set on a non bundle APK 

https://github.com/user-attachments/assets/abea150c-9d33-435e-9796-8155d5c6ba4c

**Comment by oSumAtrIX** [comment]
Did you touch the patch options of the patches Change header, Custom branding

**Comment by scarlettekk** [comment]
I leave them both enabled which I believe is the default

**Comment by oSumAtrIX** [comment]
Both are disabled by default. Did you touch their patch options?

**Comment by scarlettekk** [comment]
I didn't change their patch options. I also tried patching with those patches disabled and it still failed, so maybe the issue is in another patch

**Comment by oSumAtrIX** [comment]
In that case, follow this: 
![image](https://github.com/user-attachments/assets/0dff6945-f01e-4908-b5ea-7d2501fccac2)
