### ISSUE TITLE
Error: Patching Failed

### ISSUE THREAD

**Issue by LotusCreep** [ReVanced/revanced-manager#2086]
### Bug description

When patching youtube from storage apk, after compiling modified resources, it loads for some time and then gives the error.

### Version of ReVanced Manager and version & name of app you are patching

Revanced version: 1.20.1
Youtube Version: 19.16.39

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of main
07-27 10:42:43.691 19740 19740 I SurfaceView: onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 G.E...... ......I. 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:42:43.716 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)4 dur=14 res=0x1 s={false 0} ch=false
07-27 10:42:43.717 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=true
07-27 10:42:43.717 19740 19740 I SurfaceView: windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 G.E...... ......I. 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:42:43.742 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=false
07-27 10:42:43.748 19740 19740 I SurfaceView: onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:42:43.757 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)0 dur=8 res=0x7 s={true 495986618368} ch=true
07-27 10:42:43.761 19740 19761 I mali_winsys: new_window_surface() [1080x2220] return: 0x3000
07-27 10:42:43.764 19740 19740 I SurfaceView: surfaceCreated 1 #5 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220}
07-27 10:42:43.768 19740 19767 I mali_winsys: new_window_surface() [1080x2220] return: 0x3000
07-27 10:42:43.772 19740 19740 I SurfaceView: surfaceChanged (1080,2220) 1 #5 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220}
07-27 10:42:43.792 19740 20606 I OpenGLRenderer: doUpdatePositionAsync is called and callVoidMethod
07-27 10:42:43.804 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
07-27 10:42:43.804 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:42:43.804 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:42:43.807 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:42:43.807 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:42:43.807 19740 19740 V InputMethodManager: Starting input: tba=app.revanced.manager.flutter ic=null mNaviBarColor 0 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
07-27 10:42:43.807 19740 19740 D InputMethodManager: startInputInner - Id : 0
07-27 10:42:43.807 19740 19740 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
07-27 10:42:44.509 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:42:44.730 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:42:45.023 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:42:45.165 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:42:45.449 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:42:45.683 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:42:45.909 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:42:46.117 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:42:46.697 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:42:46.969 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:42:47.833 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:42:48.348 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:42:52.879 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:42:54.170 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:42:58.669 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:43:07.047 19740 19740 I SurfaceView: onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:43:07.048 19740 19740 I SurfaceView: surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220}
07-27 10:43:07.061 19740 19767 I mali_egl: eglDestroySurface() in
07-27 10:43:07.069 19740 19767 I mali_winsys: delete_surface() [1080x2220] return
07-27 10:43:07.069 19740 19767 I mali_egl: eglDestroySurface() out
07-27 10:43:07.069 19740 19767 W libEGL  : EGLNativeWindowType 0x738825c010 disconnect failed
07-27 10:43:07.070 19740 19740 I SurfaceView: remove() io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220} Surface(name=SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@8c3d999@2)/@0xf6615fe
07-27 10:43:07.074 19740 19761 I mali_egl: eglDestroySurface() in
07-27 10:43:07.076 19740 19761 I mali_winsys: delete_surface() [1080x2220] return
07-27 10:43:07.076 19740 19761 I mali_egl: eglDestroySurface() out
07-27 10:43:07.076 19740 19761 W libEGL  : EGLNativeWindowType 0x73fea263d0 disconnect failed
07-27 10:43:07.080 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)8 dur=3 res=0x5 s={false 0} ch=true
07-27 10:43:07.085 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
07-27 10:43:07.085 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:43:07.085 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:43:07.086 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(true) old=false
07-27 10:43:07.086 19740 19740 I SurfaceView: windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:43:07.092 19740 19740 D InputTransport: Input channel destroyed: 'ClientS', fd=98
07-27 10:47:14.757 19740 19740 I SurfaceView: onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 G.E...... ......I. 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:47:14.767 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)4 dur=9 res=0x1 s={false 0} ch=false
07-27 10:47:14.767 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=true
07-27 10:47:14.768 19740 19740 I SurfaceView: windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 G.E...... ......I. 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:47:14.771 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=false
07-27 10:47:14.773 19740 19740 I SurfaceView: onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:47:14.783 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)0 dur=8 res=0x7 s={true 496205410304} ch=true
07-27 10:47:14.786 19740 19761 I mali_winsys: new_window_surface() [1080x2220] return: 0x3000
07-27 10:47:14.788 19740 19740 I SurfaceView: surfaceCreated 1 #5 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220}
07-27 10:47:14.790 19740 19767 I mali_winsys: new_window_surface() [1080x2220] return: 0x3000
07-27 10:47:14.791 19740 19740 I SurfaceView: surfaceChanged (1080,2220) 1 #5 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220}
07-27 10:47:14.798 19740 20607 I OpenGLRenderer: doUpdatePositionAsync is called and callVoidMethod
07-27 10:47:14.804 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
07-27 10:47:14.804 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:47:14.804 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:47:14.804 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:47:14.804 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:47:14.805 19740 19740 V InputMethodManager: Starting input: tba=app.revanced.manager.flutter ic=null mNaviBarColor 0 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
07-27 10:47:14.805 19740 19740 D InputMethodManager: startInputInner - Id : 0
07-27 10:47:14.805 19740 19740 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
07-27 10:47:16.299 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:16.453 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme key 0
07-27 10:47:16.456 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme key 1
07-27 10:47:19.210 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:19.282 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:20.974 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:21.211 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:22.128 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:22.339 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:22.885 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:23.058 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:23.764 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:24.053 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:25.877 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:26.208 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:26.642 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:26.893 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:27.177 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:27.385 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:27.695 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:28.120 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:28.758 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:28.989 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:30.046 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:30.142 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:30.272 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
07-27 10:47:30.273 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:47:30.273 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:47:30.966 19740 19740 D InputTransport: Input channel destroyed: 'ClientS', fd=98
07-27 10:47:38.359 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=false
07-27 10:47:38.371 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)0 dur=2 res=0x1 s={true 496205410304} ch=false
07-27 10:47:38.372 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
07-27 10:47:38.373 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:47:38.373 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:47:38.373 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:47:38.373 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:47:38.373 19740 19740 V InputMethodManager: Starting input: tba=app.revanced.manager.flutter ic=null mNaviBarColor 0 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
07-27 10:47:38.373 19740 19740 D InputMethodManager: startInputInner - Id : 0
07-27 10:47:38.373 19740 19740 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
07-27 10:47:40.909 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:41.729 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:41.972 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:42.130 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:44.832 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:45.396 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:46.127 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:47:46.231 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:47:46.337 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
07-27 10:47:46.337 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:47:46.337 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:47:46.494 19740 19740 D InputTransport: Input channel destroyed: 'ClientS', fd=98
07-27 10:48:09.978 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=false
07-27 10:48:09.996 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)0 dur=3 res=0x1 s={true 496205410304} ch=false
07-27 10:48:09.997 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
07-27 10:48:09.997 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:48:09.997 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:48:09.997 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:48:09.997 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:48:09.997 19740 19740 V InputMethodManager: Starting input: tba=app.revanced.manager.flutter ic=null mNaviBarColor 0 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
07-27 10:48:10.003 19740 19740 D InputMethodManager: startInputInner - Id : 0
07-27 10:48:10.003 19740 19740 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
07-27 10:48:10.975 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:48:11.051 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
07-27 10:48:11.147 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
07-27 10:48:11.147 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:48:11.147 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:48:11.311 19740 19740 D InputTransport: Input channel destroyed: 'ClientS', fd=98
07-27 10:48:16.808 19740 19740 I SurfaceView: onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:48:16.809 19740 19740 I SurfaceView: surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220}
07-27 10:48:16.811 19740 19767 I mali_egl: eglDestroySurface() in
07-27 10:48:16.813 19740 19767 I mali_winsys: delete_surface() [1080x2220] return
07-27 10:48:16.813 19740 19767 I mali_egl: eglDestroySurface() out
07-27 10:48:16.813 19740 19767 W libEGL  : EGLNativeWindowType 0x7403452010 disconnect failed
07-27 10:48:16.814 19740 19740 I SurfaceView: remove() io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220} Surface(name=SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@8c3d999@3)/@0xc47c7f3
07-27 10:48:16.816 19740 19761 I mali_egl: eglDestroySurface() in
07-27 10:48:16.818 19740 19761 I mali_winsys: delete_surface() [1080x2220] return
07-27 10:48:16.819 19740 19761 I mali_egl: eglDestroySurface() out
07-27 10:48:16.819 19740 19761 W libEGL  : EGLNativeWindowType 0x73fea263d0 disconnect failed
07-27 10:48:16.830 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)8 dur=11 res=0x5 s={false 0} ch=true
07-27 10:48:16.911 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(true) old=false
07-27 10:48:16.912 19740 19740 I SurfaceView: windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ........ 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:48:21.036 19740 19740 I SurfaceView: onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 G.E...... ......I. 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:48:21.044 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)4 dur=7 res=0x1 s={false 0} ch=false
07-27 10:48:21.045 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=true
07-27 10:48:21.045 19740 19740 I SurfaceView: windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{8c3d999 G.E...... ......I. 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:48:21.047 19740 19740 I ViewRootImpl@114c068[MainActivity]: stopped(false) old=false
07-27 10:48:21.052 19740 19740 I SurfaceView: onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220} of ViewRootImpl@114c068[MainActivity]
07-27 10:48:21.058 19740 19740 I ViewRootImpl@114c068[MainActivity]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)0 dur=4 res=0x7 s={true 495986618368} ch=true
07-27 10:48:21.060 19740 19761 I mali_winsys: new_window_surface() [1080x2220] return: 0x3000
07-27 10:48:21.064 19740 19740 I SurfaceView: surfaceCreated 1 #5 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220}
07-27 10:48:21.065 19740 19767 I mali_winsys: new_window_surface() [1080x2220] return: 0x3000
07-27 10:48:21.066 19740 19740 I SurfaceView: surfaceChanged (1080,2220) 1 #5 io.flutter.embedding.android.FlutterSurfaceView{8c3d999 V.E...... ......ID 0,0-1080,2220}
07-27 10:48:21.068 19740 20606 I OpenGLRenderer: doUpdatePositionAsync is called and callVoidMethod
07-27 10:48:21.093 19740 19740 I ViewRootImpl@114c068[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
07-27 10:48:21.093 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:48:21.093 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:48:21.093 19740 19740 D InputMethodManager: prepareNavigationBarInfo() DecorView@49b064e[MainActivity]
07-27 10:48:21.094 19740 19740 D InputMethodManager: getNavigationBarColor() 0
07-27 10:48:21.094 19740 19740 V InputMethodManager: Starting input: tba=app.revanced.manager.flutter ic=null mNaviBarColor 0 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
07-27 10:48:21.094 19740 19740 D InputMethodManager: startInputInner - Id : 0
07-27 10:48:21.094 19740 19740 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
07-27 10:48:22.232 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 0
07-27 10:48:22.312 19740 19740 I ViewRootImpl@114c068[MainActivity]: ViewPostIme pointer 1
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: SM-N960F
Android version: 10
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.11.0
Patches added: Change header [Header: premium*header], Custom branding, Remove player controls background
Patches removed: Downloads, Seekbar tapping, Swipe controls, Hide captions button, Navigation buttons, Hide crowdfunding box, Hide floating microphone button, Hide layout components, Hide seekbar, Return YouTube Dislike, Spoof app version, Enable tablet layout, Alternative thumbnails, Announcements, Always repeat, Spoof device dimensions, Bypass URL redirects
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 44 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/app.revanced.manager.flutter-gTgo9Voq7kCq_hNb3XcgKQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL245362062107791226.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:919)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/app.revanced.manager.flutter-gTgo9Voq7kCq_hNb3XcgKQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL245362062107791226.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PIFUJG/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Did you patch a full apk?

**Comment by ziomek3120** [comment]
Try disabling the player flyout menu
