### ISSUE TITLE
bug: Patch Application Failure: AndrolibException during Resource Compilation on Android 14

### ISSUE THREAD

**Issue by edw4rb** [ReVanced/revanced-manager#2129]
### Bug description

When attempting to apply patches to YouTube (v19.16.39) using ReVanced Manager (v1.21.1) on a device running Android 14, the patching process fails during the resource compilation step. The error originates from AaptInvoker throwing an AndrolibException, resulting in an unsuccessful patch operation.

Steps to Reproduce:

Open ReVanced Manager (v1.21.1) on a device with Android 14.
Select the YouTube app (v19.16.39) as the target for patching.
Choose the default patch set with the following patches removed: Disable precise seeking gesture, Disable fullscreen ambient mode, etc.
Start the patching process.
Expected Result: The patches should be applied successfully, resulting in a patched YouTube APK.

Actual Result: The patching process fails with the following error:

`PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/out.apk' (OS Error: No such file or directory, errno = 2)
`

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.21.1 & Youtube: 19.16.39

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of kernel
08-10 13:00:05.963 25472 25472 W audit   : audit_lost=28777 audit_rate_limit=5 audit_backlog_limit=64
08-10 13:00:05.963 25472 25472 E audit   : rate limit exceeded
08-10 13:00:06.988 26401 26401 W audit   : audit_lost=28823 audit_rate_limit=5 audit_backlog_limit=64
08-10 13:00:06.988 26401 26401 E audit   : rate limit exceeded
08-10 13:00:09.328 25597 25597 I         : process 26102 (DartWorker) no longer affine to cpu7
08-10 13:00:10.443 25597 25597 I         : process 26415 (DartWorker) no longer affine to cpu7
08-10 13:00:10.447 25597 25597 I         : process 26419 (DartWorker) no longer affine to cpu7
08-10 13:00:10.449 25597 25597 I         : process 26414 (DartWorker) no longer affine to cpu7
08-10 13:00:12.486 25597 25597 I         : process 26410 (flutter-worker-) no longer affine to cpu7
08-10 13:00:14.007 26862 26862 W audit   : audit_lost=28849 audit_rate_limit=5 audit_backlog_limit=64
08-10 13:00:14.007 26862 26862 E audit   : rate limit exceeded
--------- beginning of main
08-10 13:05:47.426 25472 25472 D CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10334; state: ENABLED
08-10 13:06:02.317 25472 25472 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
08-10 13:07:12.624 25472 25472 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
08-10 13:08:00.655 25472 25472 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@4bf0e4a
08-10 13:08:27.988 25472 25472 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10334; state: ENABLED
08-10 13:08:32.464 25472 25472 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10334; state: ENABLED
08-10 13:08:33.548 25597 25597 I         : process 29166 (flutter-worker-) no longer affine to cpu6
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.21.1
Model: LE2123
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.12.0
Patches added: Default
Patches removed: Disable precise seeking gesture, Disable fullscreen ambient mode, Hide layout components, Disable rolling number animations, Disable suggested video end screen, Return YouTube Dislike, Restore old seekbar thumbnails, Disable resuming Shorts on startup, Announcements, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Restore old video quality menu
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 46 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~LTmwSpPT7hzJyucK52TZ8Q==/app.revanced.manager.flutter-tWkPmZ7cU-KfS-e-PPNbvw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4083018694701257513.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~LTmwSpPT7hzJyucK52TZ8Q==/app.revanced.manager.flutter-tWkPmZ7cU-KfS-e-PPNbvw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4083018694701257513.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GLOFSP/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Try default patches

**Comment by edw4rb** [comment]
Worked @oSumAtrIX. Thank you so much!

**Comment by edw4rb** [comment]
Worked @oSumAtrIX. Thank you so much!

**Comment by oSumAtrIX** [comment]
Jow

**Comment by oSumAtrIX** [comment]
Now use the old selection again and check if you can reproduce the issue

**Comment by edw4rb** [comment]
Looks like it worked. 

```
- Device Info
ReVanced Manager: 1.21.1
Model: LE2123
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.12.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 59 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```
