### ISSUE TITLE
bug(compose): patch bundle crash

### ISSUE THREAD

**Issue by Mylloon** [ReVanced/revanced-manager#2134]
### Bug description

When adding multiples different bundle from the same repository, the manager crash

### Version of ReVanced Manager and version & name of app you are patching

Revanced Manager Compose from this commit: https://github.com/ReVanced/revanced-manager/actions/runs/10341152990

### Installation method

None

### ReVanced Manager logs

```shell
Tag=0xffffffff, statsUid=-108-11 18:36:22.625 12552 12618 D TrafficStats: tagSocket(159) with statsTag=0xffffffff, statsUid=-108-11 18:36:23.318 12552 12593 D ReVanced Manager: Loaded patch bundle: /data/user/0/app.revanced.manager.debug/app_patch_bundles/742573736/patches.jar08-11 18:36:23.318 12552 12593 W ziparchive: Unable to open '/data/user/0/app.revanced.manager.debug/app_patch_bundles/742573736/patches.dm': No such file or directory08-11 18:36:23.329 12552 12593 E ReVanced Manager: Failed to update bundles08-11 18:36:23.329 12552 12593 E ReVanced Manager: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: patch_bundles.name (code 2067 SQLITE_CONSTRAINT_UNIQUE)08-11 18:36:23.329 12552 12593 E ReVanced Manager: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)08-11 18:36:23.329 12552 12593 E ReVanced Manager: 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:913)08-11 18:36:23.329 12552 12593 E ReVanced Manager: 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)08-11 18:36:23.329 12552 12593 E ReVanced Manager: 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)08-11 18:36:23.329 12552 12593 E ReVanced Manager: 	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.kt:38)08-11 18:36:23.329 12552 12593 E ReVanced Manager: 	at app.revanced.manage
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by Axelen123** [comment]
Fixed in https://github.com/ReVanced/revanced-manager/commit/e992a99783da7f510de1508b3c6252c3fff52f01. The fix required changing the database schema, which means you have to clear app data after updating.
