### ISSUE TITLE
Bug: Stuck at loading

### ISSUE THREAD

**Issue by kasperbjerby** [ReVanced/revanced-manager#2154]
### Bug description

The app wont download the patches no matter what I do, it just keeps saying loading...

![Screenshot_20240820-115732](https://github.com/user-attachments/assets/08cb4634-ac14-4eb5-b36f-2a6c6283da70)

### Version of ReVanced Manager and version & name of app you are patching

Version: 1.21.3-dev.1
Model: Pixel 8 Pro
Android Version: 14
Supported Arch: arm64-v8a

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of main
08-20 11:58:42.523  6837  6837 I manager.flutter: Using CollectorTypeCMC GC.
08-20 11:58:42.526  6837  6837 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
08-20 11:58:42.540  6837  6837 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10491; state: ENABLED
08-20 11:58:42.540  6837  6837 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10491; state: ENABLED
08-20 11:58:42.544  6837  6837 D ApplicationLoaders: Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
08-20 11:58:42.544  6837  6837 D ApplicationLoaders: Returning zygote-cached class loader: /system_ext/framework/androidx.window.sidecar.jar
08-20 11:58:42.551  6837  6837 D nativeloader: Configuring clns-6 for other apk /data/app/~~HJQB-lwHqcQyteaP_4Ovuw==/app.revanced.manager.flutter-Mkkw106KXip8E_WaJzAmmQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~HJQB-lwHqcQyteaP_4Ovuw==/app.revanced.manager.flutter-Mkkw106KXip8E_WaJzAmmQ==/lib/arm64:/data/app/~~HJQB-lwHqcQyteaP_4Ovuw==/app.revanced.manager.flutter-Mkkw106KXip8E_WaJzAmmQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
08-20 11:58:42.555  6837  6837 V GraphicsEnvironment: Currently set values for:
08-20 11:58:42.555  6837  6837 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[com.android.angle, com.linecorp.b612.android, com.campmobile.snow, com.google.android.apps.tachyon]
08-20 11:58:42.555  6837  6837 V GraphicsEnvironment:   angle_gl_driver_selection_values=[angle, native, native, native]
08-20 11:58:42.555  6837  6837 V GraphicsEnvironment: app.revanced.manager.flutter is not listed in per-application setting
08-20 11:58:42.555  6837  6837 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
08-20 11:58:42.558  6837  6837 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10491; state: DISABLED
08-20 11:58:42.566  6837  6872 D vulkan  : searching for layers in '/data/app/~~HJQB-lwHqcQyteaP_4Ovuw==/app.revanced.manager.flutter-Mkkw106KXip8E_WaJzAmmQ==/lib/arm64'
08-20 11:58:42.566  6837  6872 D vulkan  : searching for layers in '/data/app/~~HJQB-lwHqcQyteaP_4Ovuw==/app.revanced.manager.flutter-Mkkw106KXip8E_WaJzAmmQ==/base.apk!/lib/arm64-v8a'
08-20 11:58:42.580  6837  6837 W manager.flutter: type=1400 audit(0.0:1742): avc:  denied  { read } for  name="max_map_count" dev="proc" ino=652670 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.633  6837  6837 D FlutterFileDialogPlugin: onAttachedToEngine - IN
08-20 11:58:42.633  6837  6837 D FlutterFileDialogPlugin: doOnAttachedToEngine - IN
08-20 11:58:42.633  6837  6837 D FlutterFileDialogPlugin: doOnAttachedToEngine - OUT
08-20 11:58:42.633  6837  6837 D FlutterFileDialogPlugin: onAttachedToEngine - OUT
08-20 11:58:42.633  6837  6837 D FlutterFileDialogPlugin: onAttachedToActivity
08-20 11:58:42.633  6837  6837 D FlutterFileDialogPlugin: doOnAttachedToActivity - IN
08-20 11:58:42.633  6837  6837 D FlutterFileDialogPlugin: doOnAttachedToActivity - OUT
08-20 11:58:42.654  6837  6837 I ContentCaptureHelper: Setting logging level to OFF
08-20 11:58:42.658  6837  6837 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10491; state: DISABLED
08-20 11:58:42.672  6837  6837 I WindowExtensionsImpl: Initializing Window Extensions.
08-20 11:58:42.692  6977  6977 W sh      : type=1400 audit(0.0:1743): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.696  6977  6977 W sh      : type=1400 audit(0.0:1744): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.700  6977  6977 W sh      : type=1400 audit(0.0:1745): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.704  6977  6977 W sh      : type=1400 audit(0.0:1746): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.712  6977  6977 W sh      : type=1400 audit(0.0:1747): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.716  6977  6977 W sh      : type=1400 audit(0.0:1748): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.720  6977  6977 W sh      : type=1400 audit(0.0:1749): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:42.931  6837  6837 I Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
08-20 11:58:43.232  6837  6837 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
08-20 11:58:43.245  6837  6837 D permissions_handler: No permissions found in manifest for: []15
08-20 11:58:43.261  6837  6892 I flutter : dynamic_color: Core palette detected.
08-20 11:58:43.631  6837  6837 I Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
08-20 11:58:43.708  8492  8492 W sh      : type=1400 audit(0.0:1828): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:43.720  8520  8520 W sh      : type=1400 audit(0.0:1829): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:43.736  8561  8561 W sh      : type=1400 audit(0.0:1830): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:43.748  8599  8599 W sh      : type=1400 audit(0.0:1831): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:43.760  8633  8633 W sh      : type=1400 audit(0.0:1832): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:43.910  6837  6837 I Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
08-20 11:58:44.984  8967  8967 W sh      : type=1400 audit(0.0:1844): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:45.008  8967  8967 W sh      : type=1400 audit(0.0:1845): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:45.032  8967  8967 W sh      : type=1400 audit(0.0:1846): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:45.056  8967  8967 W sh      : type=1400 audit(0.0:1847): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:45.068  8967  8967 W sh      : type=1400 audit(0.0:1848): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:45.992  9354  9354 W sh      : type=1400 audit(0.0:1867): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:46.048  9371  9371 W sh      : type=1400 audit(0.0:1868): avc:  denied  { read } for  name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c235,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-20 11:58:46.077  6837  6837 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@76e7829
08-20 11:58:46.087  6837  6892 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(invalid_icon, The resource ic_notification could not be found. Please make sure it has been added as a drawable resource to your Android head project., null, null)
08-20 11:58:46.087  6837  6892 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
08-20 11:58:46.087  6837  6892 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
08-20 11:58:46.087  6837  6892 E flutter : <asynchronous suspension>
08-20 11:58:46.087  6837  6892 E flutter : #2      AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:143)
08-20 11:58:46.087  6837  6892 E flutter : <asynchronous suspension>
08-20 11:58:46.087  6837  6892 E flutter : #3      HomeViewModel.initialize (package:revanced_manager/ui/views/home/home_viewmodel.dart:67)
08-20 11:58:46.087  6837  6892 E flutter : <asynchronous suspension>
08-20 11:58:46.087  6837  6892 E flutter : #4      HomeViewModel.forceRefresh (package:revanced_manager/ui/views/home/home_viewmodel.dart:500)
08-20 11:58:46.087  6837  6892 E flutter : <asynchronous suspension>
08-20 11:58:46.087  6837  6892 E flutter : #5      HomeViewModel.initialize (package:revanced_manager/ui/views/home/home_viewmodel.dart:52)
08-20 11:58:46.087  6837  6892 E flutter : <asynchronous suspension>
08-20 11:58:46.087  6837  6892 E flutter : 
08-20 11:58:48.411  6837  9390 D ProfileInstaller: Installing profile for app.revanced.manager.flutter
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by kasperbjerby** [comment]
Fixed it by toggling "Use alternative sources" on, did not input any alternative sources so don't know why that is needed and it still says loading under "ReVanced Manager", but at least it works

**Comment by oSumAtrIX** [comment]
API temporarily down.
