### ISSUE TITLE
bug: Google Photos

### ISSUE THREAD

**Issue by caskera** [ReVanced/revanced-manager#2155]
### Bug description

- Device Info
ReVanced Manager: 1.21.2
Model: Pixel 8
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.95.0.663027175 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~S2VMN5oQ4TmciXTIsTPwlg==/app.revanced.manager.flutter-r9xqjlfBcFQd7g1_POnJtg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/build/resources.zip]
 at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
 at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
 at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
 at app.revanced.patcher.Patcher.get(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~S2VMN5oQ4TmciXTIsTPwlg==/app.revanced.manager.flutter-r9xqjlfBcFQd7g1_POnJtg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/build/resources.zip]
 at brut.util.OS.exec(Unknown Source:75)
 at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
 ... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/out.apk' (OS Error: No such file or directory, errno = 2)

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.21.2
com.google.android.apps.photos v6.95.0.663027175

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: Pixel 8
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.95.0.663027175 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~S2VMN5oQ4TmciXTIsTPwlg==/app.revanced.manager.flutter-r9xqjlfBcFQd7g1_POnJtg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/build/resources.zip]
 at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
 at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
 at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
 at app.revanced.patcher.Patcher.get(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~S2VMN5oQ4TmciXTIsTPwlg==/app.revanced.manager.flutter-r9xqjlfBcFQd7g1_POnJtg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/revanced-temporary-files/apk/build/resources.zip]
 at brut.util.OS.exec(Unknown Source:75)
 at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
 ... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FNYYUX/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [ ] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager.

**Comment by Slv0005** [comment]
any update on this? i have the same problems with pixel 4
