### ISSUE TITLE
bug: trying to patch apps, show a error

### ISSUE THREAD

**Issue by peter9811** [ReVanced/revanced-manager#2157]
### Bug description

I have root, Snapdragon 8 Gen 2, 12 Gb RAM and 512 Gb storage 

### Version of ReVanced Manager and version & name of app you are patching

I tried Facebook, TikTok and others
Manager 1.21.2
And the respective apps using the recommended version lasted

### Installation method

None

### ReVanced Manager logs

```shell
Empty (?)
The file shows 0B
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: NX729J
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.zhiliaoapp.musically v32.5.3 (Suggested: 32.5.3)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 8 patches
Compiling patched dex files
Compiled 22 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1851056 free bytes and 1807KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:124)
	at com.android.tools.smali.util.Utf8Utils.utf8BytesWithUtf16LengthToString(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexReader.readString(Unknown Source:12)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedFieldReference.getName(Unknown Source:30)
	at com.android.tools.smali.dexlib2.writer.pool.FieldPool.getName(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.pool.FieldPool.getName(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeFields(Unknown Source:93)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:83)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OSPEVX/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by peter9811** [comment]
> ![Why_am_i_OutOf_Memory](https://private-user-images.githubusercontent.com/154948822/360715693-eb976fc9-767e-42dd-8af8-98e996096c42.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzM4NzUsIm5iZiI6MTcyNDM3MzU3NSwicGF0aCI6Ii8xNTQ5NDg4MjIvMzYwNzE1NjkzLWViOTc2ZmM5LTc2N2UtNDJkZC04YWY4LTk4ZTk5NjA5NmM0Mi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwMDM5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVhNjFmYWNmM2ExMGM2ZGEzYTJkOTRkMmY5MWM4NzdmYjc0ODRjZjhiYmNmMzNkMmZkMjI2YTI0MzY5MDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sq-zcK1Ta76fijoE7K9KHMBEIB21uoyMfyl6qP4XU28)

I have root, 500+ Gb of storage, and 12 Gb of RAM... and I just did the same patch on my Pixel 7 Pro, which is less powerful and finished okay
