### ISSUE TITLE
bug: patching errors out

### ISSUE THREAD

**Issue by arandomhooman** [ReVanced/revanced-manager#2158]
### Bug description

When trying to patch with spoof client the  manager crashes. There is another report with less info.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced version 1.21.2
Patches version 4.13.3
Patching last supported version of yt

### Installation method

Regular

### ReVanced Manager logs

[revanced-manager_logcat_20240822201922334644.log](https://github.com/user-attachments/files/16720731/revanced-manager_logcat_20240822201922334644.log)

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: SM-T733
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.13.3
Patches added: Change header [Header: premium*header]
Patches removed: Downloads, Miniplayer
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 59 patches
Compiling patched dex files
Compiled 7 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 4117800 free bytes and 4021KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.buildInstruction(Unknown Source:207)
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.readFrom(Unknown Source:43)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(Unknown Source:2)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.tryToComputeNext(Unknown Source:3)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.hasNext(Unknown Source:8)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(Unknown Source:195)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(Unknown Source:213)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:83)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RDYDRM/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager.

**Comment by arandomhooman** [comment]
> For support, move to one of our links at https://revanced.app/

What do you mean, move to what link

**Comment by arandomhooman** [comment]
Can I do this on mobile? This has never happened before, why so it happening now?
