### ISSUE TITLE
bug: EACCES Permission Denied

### ISSUE THREAD

**Issue by Trixarn** [ReVanced/revanced-manager#2159]
### Bug description

Trying to patch latest Soundcloud version from Play Store but doesn't work.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager 1.21.2
App.name com.soundcloud.android 2024.08.19-release

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: Pixel 7 Pro
Android version: 14
Supported architectures: arm64-v8a
Root permissions: Yes

- Patch Info
App: com.soundcloud.android v2024.08.19-release (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 13 dex files
Aligning APK
An error occurred:
java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PNLNEO/in.apk: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
	at com.android.tools.build.apkzlib.zip.ZFile.reopenRw(Unknown Source:105)
	at com.android.tools.build.apkzlib.zip.ZFile.writeAllFilesToZip(Unknown Source:2)
	at com.android.tools.build.apkzlib.zip.ZFile.update(Unknown Source:21)
	at com.android.tools.build.apkzlib.zip.ZFile.close(Unknown Source:9)
	at kotlin.io.CloseableKt.closeFinally(Unknown Source:4)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:323)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:484)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8478)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PNLNEO/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by Trixarn** [comment]
Tried to do it but same problem. It's from the Play Store so I installed it from PureAPK but then it said it was an incompatible app. Tried also with APKMirror and installed with SAI because it's a bundle, but getting `java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 5292272 free bytes and 5168KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.`

**Comment by kitadai31** [comment]
#2135 will fix it
