### ISSUE TITLE
bug: Revanced Manager ERROR Failing when Building apk of GPhotos arm64-v8a

### ISSUE THREAD

**Issue by DomingV** [ReVanced/revanced-manager#2191]
### Bug description

I selected GPhotos arm64-v8a apk from storage. All success except on "Building" stage it fails.

### Version of ReVanced Manager and version & name of app you are patching

1.21.2

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: Infinix X6837
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.59.0.576923577 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~29LVGgbtx4k9CnK5i6y8iQ==/app.revanced.manager.flutter-8DB7k8sptgOSodsIBrHKXQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NAWISO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NAWISO/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~29LVGgbtx4k9CnK5i6y8iQ==/app.revanced.manager.flutter-8DB7k8sptgOSodsIBrHKXQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NAWISO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NAWISO/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NAWISO/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Moved to https://github.com/ReVanced/revanced-patches/issues/3622#issuecomment-2332322389

**Comment by RiezDanz** [comment]
I'm also having this issue, but it was POCO F1 MIUI 12 and Android 10 instead:

- Device Info
ReVanced Manager: 1.22.0
Model: POCOPHONE F1
Android version: 10
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v7.0.0.674947721 (Suggested: Any)
Patches version: v4.15.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/app.revanced.manager.flutter-XsJ_SWpJc6h-BStq-IOUkQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-LWAQPE/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-LWAQPE/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:919)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/app.revanced.manager.flutter-XsJ_SWpJc6h-BStq-IOUkQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-LWAQPE/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-LWAQPE/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-LWAQPE/out.apk' (OS Error: No such file or directory, errno = 2)
