### ISSUE TITLE
bug: PathNotFoundException

### ISSUE THREAD

**Issue by NOoOBBByYT** [ReVanced/revanced-manager#2192]
### Bug description

Errors out when patching YouTube 

### Version of ReVanced Manager and version & name of app you are patching

1.21.2, YouTube 19.16.39

### Installation method

None

### ReVanced Manager logs

```shell
https://drive.google.com/file/d/1-8nk4-B__zEBEJHBHZmVKeunQOD5mWxp/view?usp=drivesdk
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: Pixel 9 Pro XL
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.13.3
Patches added: Enable slide to seek
Patches removed: Copy video URL, Disable precise seeking gesture, Swipe controls, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide layout components, Hide info cards, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Custom player overlay opacity, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Enable tablet layout, Alternative thumbnails, Announcements, Always repeat, Disable zoom haptics, Restore old video quality menu, Open links externally
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 27 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Az8qGtj6rQk4OU4rRNzMZA==/app.revanced.manager.flutter-aSIs_v-73S0UnNuVYmhPZQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7399985664459442230.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Az8qGtj6rQk4OU4rRNzMZA==/app.revanced.manager.flutter-aSIs_v-73S0UnNuVYmhPZQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7399985664459442230.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ILEFVI/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Use default selection of patches. If it works, revert back to your current selection. Report back if the issue still happens

**Comment by amankaif** [comment]
I've tried patching google photos with the default patch list and I get the same PathNotFound exception, the same happens for other apps too.

**Comment by Dinjoralo** [comment]
I'm also having the same issue when trying to apply patches to YouTube. I have tried running with the default list of patches, and a selection of patches that has less of them selected, and both return the same error.

Here are my device logs;
[DinjoVncdDeviceLogs.txt](https://github.com/user-attachments/files/16909009/DinjoVncdDeviceLogs.txt)

**Comment by oSumAtrIX** [comment]
Delete manager data and try again

**Comment by Dinjoralo** [comment]
Deleting data for the Revanced Manager app has resolved my issues. Thank you!

**Comment by WaseemAbbo** [comment]
**I'm also having this issue and I have removed and reinstalled the manager, downloaded the APK again, updated the phone, updated the youtube original app - still no luck. Same error. :(**

- Device Info
ReVanced Manager: 1.21.2
Model: SM-S908B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
An error occurred:
java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FFJDHJ/in.apk
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(SourceFile:0)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(SourceFile:0)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(SourceFile:0)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(Unknown Source:0)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(SourceFile:0)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(SourceFile:0)
	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
	at app.revanced.patcher.data.BytecodeContext.getClasses(Unknown Source:2)
	at app.revanced.patcher.data.BytecodeContext$Integrations.flush(Unknown Source:18)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:162)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:437)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FFJDHJ/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by rajdeepvaghela** [comment]
I am also facing similar issues while patching Google Photos. Though for YouTube and YouTube Music it works.

- Device Info
ReVanced Manager: 1.22.0-dev.3
Model: SM-S928B
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.98.0.670003362 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~H2uId8ro34CejgFQb1kuNA==/app.revanced.manager.flutter-ji_7vDO0Po9hwKaxt69Xow==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRNHUF/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRNHUF/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~H2uId8ro34CejgFQb1kuNA==/app.revanced.manager.flutter-ji_7vDO0Po9hwKaxt69Xow==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRNHUF/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRNHUF/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRNHUF/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by Anujkaushik01** [comment]
I got the same error when applying patches to recent versions of Google photos app. It works with 3 yrs old version of the app (which shows up when using the built-in search function of the manager app). But it is said that the app is compatible patch any version of it. Earlier it just doesn't start compiling the app, directly throws the error but after clearing data of the manager app, it throws an error at end of compiling. 
`- Device Info
ReVanced Manager: 1.21.2
Model: moto g82 5G
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.97.0.670633106 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~H_JQpzylFR701fjAcuwQhQ==/app.revanced.manager.flutter-PW5OaAMmkohGmYdrYStLnQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PPSLJF/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PPSLJF/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~H_JQpzylFR701fjAcuwQhQ==/app.revanced.manager.flutter-PW5OaAMmkohGmYdrYStLnQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PPSLJF/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PPSLJF/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PPSLJF/out.apk' (OS Error: No such file or directory, errno = 2)`

**Comment by oSumAtrIX** [comment]
Moved to https://github.com/ReVanced/revanced-manager/issues/2142 because its the same issue.
