### ISSUE TITLE
bug: can't patch YouTube 

### ISSUE THREAD

**Issue by Jwjshhi** [ReVanced/revanced-manager#2229]
### Bug description

Patching failed
Error coming at the end

### Version of ReVanced Manager and version & name of app you are patching

revanced 1.22.0
YouTube 19.16.39

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.22.0
Model: SM-A137F
Android version: 14
Supported architectures: armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.15.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 2097168 byte allocation with 814200 free bytes and 795KB until OOM, target footprint 268435456, growth limit 268435456
	at com.google.common.io.ByteStreams.toByteArrayInternal(Unknown Source:29)
	at com.google.common.io.ByteStreams.toByteArray(SourceFile:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromStream(Unknown Source:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.OverflowToDiskByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.ChunkBasedByteStorage.fromSource(Unknown Source:29)
	at com.android.tools.build.apkzlib.zip.ZFile.mergeFrom(Unknown Source:195)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:153)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:523)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.OutOfMemoryError: Failed to allocate a 16777232 byte allocation with 14426352 free bytes and 13MB until OOM, target footprint 268435456, growth limit 268435456
		at java.util.Arrays.copyOf(Arrays.java:3585)
		at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
		at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
		at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
		at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage$2.doWrite(Unknown Source:2)
		at com.android.tools.build.apkzlib.bytestorage.AbstractCloseableByteSourceFromOutputStreamBuilder.write(SourceFile:0)
		at com.android.tools.build.apkzlib.bytestorage.OverflowToDiskByteStorage$1.doWrite(Unknown Source:2)
		at com.android.tools.build.apkzlib.bytestorage.AbstractCloseableByteSourceFromOutputStreamBuilder.write(SourceFile:0)
		at com.android.tools.build.apkzlib.bytestorage.ChunkBasedByteStorage$1.doWrite(Unknown Source:39)
		at com.android.tools.build.apkzlib.bytestorage.AbstractCloseableByteSourceFromOutputStreamBuilder.write(SourceFile:0)
		at com.google.common.io.ByteStreams.copy(Unknown Source:21)
		at com.android.tools.build.apkzlib.zip.StoredEntry.loadSourceIntoMemory(Unknown Source:29)
		at com.android.tools.build.apkzlib.zip.ZFile.reAdd(Unknown Source:32)
		at com.android.tools.build.apkzlib.zip.ZFile.packIfNecessary(Unknown Source:90)
		at com.android.tools.build.apkzlib.zip.ZFile.writeAllFilesToZip(Unknown Source:13)
		at com.android.tools.build.apkzlib.zip.ZFile.update(Unknown Source:21)
		at com.android.tools.build.apkzlib.zip.ZFile.close(Unknown Source:9)
		at kotlin.io.CloseableKt.closeFinally(Unknown Source:8)
		at app.revanced.library.ApkUtils.applyTo(Unknown Source:329)
		... 4 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-YUOOXG/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
#1905
