### ISSUE TITLE
bug: Crashed while Repacking APK

### ISSUE THREAD

**Issue by NextGenOP** [revanced/revanced-manager#224]
### Type

Error while running the manager

### Branch

Flutter

### Bug description

Closed itself so patching failed.

### Steps to reproduce

Step 1: Download YouTube.apk from ApkCombo
Step 2: Patch it

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: app.revanced.manager.flutter, PID: 6413
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e330eb9 u0 app.revanced.manager.flutter/de.julianassmann.flutter_background.IsolateHolderService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2006)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Screenshots or videos

![Screenshot_20220919-071514600](https://user-images.githubusercontent.com/60586402/190934351-b9f9ad6c-d639-4453-ba76-78b9d76c9956.jpg)

### Additional context

This screenshot is captured before app crashed.

**Comment by ponces** [comment]
Could you please confirm if v0.0.14 fixed this issue?

**Comment by NextGenOP** [comment]
No,
I got this eror
`FATAL EXCEPTION: main
Process: app.revanced.manager.flutter, PID: 12543
java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4439)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4471)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5014)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4426)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
	at android.app.Activity.dispatchActivityResult(Activity.java:8304)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5007)
	... 12 more`

`FATAL EXCEPTION: Thread-17
Process: app.revanced.manager.flutter, PID: 12593
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~HdkjAkO4Zhp4kFOlJig_sQ==/app.revanced.manager.flutter-fP09p4mePzgCG7PNtvj5mg==/lib/arm64/libaapt.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHOPRG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHOPRG/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:372)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
	at app.revanced.patcher.Patcher.save(Patcher.kt:212)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:214)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~HdkjAkO4Zhp4kFOlJig_sQ==/app.revanced.manager.flutter-fP09p4mePzgCG7PNtvj5mg==/lib/arm64/libaapt.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHOPRG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IHOPRG/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:368)
	... 6 more`

`FATAL EXCEPTION: Thread-16
Process: app.revanced.manager.flutter, PID: 19858
java.lang.NullPointerException: Attempt to invoke interface method 'org.w3c.dom.Node org.w3c.dom.NamedNodeMap.getNamedItem(java.lang.String)' on a null object reference
	at app.revanced.patches.youtube.misc.settings.resource.patch.SettingsResourcePatch.close(SettingsResourcePatch.kt:272)
	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:363)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)`

**Comment by NextGenOP** [comment]
What I do:
-Remove YouTube lib folder (from ApkCombo)
-Sign apk 
-Patch with MicroG Support

**Comment by ponces** [comment]
> -Remove YouTube lib folder (from ApkCombo)
wdym?

**Comment by heyboots** [comment]
I am also getting this app crash while patching, regardless of what version of the manager app I use. It was working a couple days ago so I am unsure what has changed. Picking different sets of patches doesn't seem to make any difference. Here's the log I just exported from the app.

[revanced-manager_logcat_20220919131048687847.log](https://github.com/revanced/revanced-manager/files/9601007/revanced-manager_logcat_20220919131048687847.log)

**Comment by Hedwig7s** [comment]
Gonna bump this as I get it too

I dont have a log to share ATM though

**Comment by forwardslashh** [comment]
> Could you please confirm if v0.0.14 fixed this issue?

For me it crashes on 0.0.18 too, it doesn't load at all

**Comment by NextGenOP** [comment]
> > -Remove YouTube lib folder (from ApkCombo)
> 
> wdym?
> 
> I can't even understand what you are trying to do...

Reducing size of apps, I don't know that this app patching libs. So, just make it faster. Still got error with lib folder.

**Comment by heyboots** [comment]
with the latest update (.22), the app no longer crashes but the log spits out a lot of error code and hangs when trying to repack, then gets stuck at Aborting...

Here's a screenshot and the log
![Screenshot_20220924-093434](https://user-images.githubusercontent.com/5340299/192101037-a3418622-215b-49aa-a5c0-f866ed5d223f.png)
[revanced-manager_logcat_20220924093522271411.log](https://github.com/revanced/revanced-manager/files/9638805/revanced-manager_logcat_20220924093522271411.log)

**Comment by Aunali321** [comment]
@heyboots which app is  that? also youre using split apk not full.

**Comment by heyboots** [comment]
I had youtube vanced installed because revanced hasn't been working.

So, I reverted to the stock version of youtube just now, manually installed the 17.36.37 youtube apk, and tried again, this time selecting my installed youtube and not the file out of my downloads, and got the exact same error. Neither time I got any sort of message in revanced manager about a split apk. I'm rooted on a pixel 6a, if it matters.

Here's the log from the latest try I did just now.

[revanced-manager_logcat_20220924101821341279.log](https://github.com/revanced/revanced-manager/files/9638870/revanced-manager_logcat_20220924101821341279.log)

**Comment by ILoveOpenSourceApplications** [comment]
Sounds like an old manager problem. So closing this.

**Comment by FlooferLand** [comment]
Issue still persists for me, just downloaded Revanced on Android 13 trying to get rid of YouTube video ads as they're incredibly annoying, and it fails the repacking process every time even regardless of what patches I use.

![Screenshot_20230601-125528_ReVanced Manager.png](https://github.com/revanced/revanced-manager/assets/76737186/45b31859-40a3-43a0-b705-9f7a411414fa)
![Screenshot_20230601-125557_ReVanced Manager.png](https://github.com/revanced/revanced-manager/assets/76737186/b88a2979-e4a8-41d3-9678-6cd342f23f32)

**Comment by Julius8900** [comment]
> Issue still persists for me, just downloaded Revanced on Android 13 trying to get rid of YouTube video ads as they're incredibly annoying, and it fails the repacking process every time even regardless of what patches I use

Do you use the recommended version of YouTube? Did you download a bundle APK?

**Comment by FlooferLand** [comment]
.. I downloaded YouTube directly from the app store..?
