### ISSUE TITLE
bug: Unable to patch google photos and banned reddit

### ISSUE THREAD

**Issue by mystogan99** [ReVanced/revanced-manager#2258]
### Bug description

Unable to patch Google Photos. 

Also, I use a patched version of Reddit, and it was working fine for a few days, but then Reddit banned my account out of nowhere. I did not post, comment, or do anything; I was just surfing with the patched version. Is this anyway related to using patched version? I mean don't think so, just wanted to confirm.

### Version of ReVanced Manager and version & name of app you are patching

Revanced manager: 1.22.1-dev.2
Google Photos: 7.3.0.682956182
Reddit: 2024.17.0

### Installation method

Regular

### ReVanced Manager logs

- Device Info
ReVanced Manager: 1.22.1-dev.2
Model: SM-S911B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v7.3.0.682956182 (Suggested: Any)
Patches version: v4.16.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~chxoA8Z8kDrv0cl2_dOzKA==/app.revanced.manager.flutter-HRf0o21_0G_ekBYKzCuzcA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-IGDIBR/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-IGDIBR/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~chxoA8Z8kDrv0cl2_dOzKA==/app.revanced.manager.flutter-HRf0o21_0G_ekBYKzCuzcA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-IGDIBR/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-IGDIBR/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-IGDIBR/out.apk' (OS Error: No such file or directory, errno = 2)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by drooooov** [comment]
Same can't patch the latest google photos version
