### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by PaidThaFossToBeDaBoss** [ReVanced/revanced-manager#2307]
### Bug description

[Bug] Can't Spoof 3rd party Reddit apps (like Sync) in Revanced Manager version: 1.23.0 & 1.23.1.

### Version of ReVanced Manager and version & name of app you are patching

Revanced Manager version: 1.23.0 & 1.23.1.
Sync for reddit v23.06.30-13:39!
[Image](https://github.com/user-attachments/assets/01ab697f-c24f-4314-a114-7f7ec7f1be5e)

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of crash
11-11 18:19:55.159 27936 27936 E AndroidRuntime: FATAL EXCEPTION: main
11-11 18:19:55.159 27936 27936 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 27936
11-11 18:19:55.159 27936 27936 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4459)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8223)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: Caused by: java.lang.NullPointerException
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(SourceFile:23)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4450)
11-11 18:19:55.159 27936 27936 E AndroidRuntime: 	... 9 more
--------- beginning of system
11-11 18:20:43.433 28034 28034 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/com.laurencedawson.reddit_sync_v23.06.30-13_39-23033_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #11
11-11 18:20:43.433 28034 28034 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/com.laurencedawson.reddit_sync_v23.06.30-13_39-23033_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #48
11-11 18:20:43.433 28034 28034 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/com.laurencedawson.reddit_sync_v23.06.30-13_39-23033_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #79
11-11 18:20:43.434 28034 28034 W PackageParser: No actions in intent filter at /data/user/0/app.revanced.manager.flutter/cache/com.laurencedawson.reddit_sync_v23.06.30-13_39-23033_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #124
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by PaidThaFossToBeDaBoss** [comment]
Without the spoofing patch all available patches are useless as 3rd party apps can't load any content at all. I saw you closed it as not planned. Does this mean Revanced won't be offering patches for 3rd party Reddit apps anymore?

**Comment by PaidThaFossToBeDaBoss** [comment]
> Without the spoofing patch all available patches are useless as 3rd party apps can't load any content at all. I saw you closed it as not planned. Does this mean Revanced won't be offering patches for 3rd party Reddit apps anymore?

@oSumAtrIX

**Comment by oSumAtrIX** [comment]
![Image](https://github.com/user-attachments/assets/3b1b3716-27fb-4567-b019-e0259e7e2a66)
