### ISSUE TITLE
bug: Installation canceled

### ISSUE THREAD

**Issue by PowerRangerX** [ReVanced/revanced-manager#2329]
### Bug description

Can not install patched app.

![Image](https://github.com/user-attachments/assets/c1a32241-c29f-4726-8b9a-1157bfa22dae)
![Image](https://github.com/user-attachments/assets/67955abb-2bd3-4cec-bc2d-f5c77f783b14)
![Image](https://github.com/user-attachments/assets/097ac4e6-f3ad-4769-bda8-e5bd934944b5)

```
adb: failed to install youtube-revanced_v19.46.42-patches_v5.2.0.apk:
Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Size must be positive
        at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:2821)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1303)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25123)
        at android.os.Binder.shellCommand(Binder.java:953)
        at android.os.Binder.onTransact(Binder.java:837)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8628)
        at android.os.Binder.execTransactInternal(Binder.java:1187)
        at android.os.Binder.execTransact(Binder.java:114``
```

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager Version: 1.23.2
App Version: com.google.android.youtube v19.46.42

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.23.2
Model: POCO M2 Pro
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.46.42 (Suggested: 19.46.42)
Patches version: v5.2.0
Patches added: Change package name, Custom branding, Enable slide to seek
Patches removed: Copy video URL, Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar thumbnails, Hide player overlay buttons, Disable fullscreen ambient mode, Hide player flyout menu items, Disable rolling number animations, Disable suggested video end screen, Miniplayer, Custom player overlay opacity, Shorts autoplay, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Alternative thumbnails, Bypass image region restrictions, Announcements, Always repeat, Remove background playback restrictions, Spoof device dimensions, Check watch history domain name resolution, Spoof video streams, GmsCore support, Remove tracking query parameter, Restore old video quality menu
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 29 patches
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installation failed
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by PowerRangerX** [comment]
Thnx that worked.
