### ISSUE TITLE
bug: Error compiling on Photos

### ISSUE THREAD

**Issue by isidorosss** [ReVanced/revanced-manager#2356]
### Bug description

[https://pastebin.com/xunZNSWg](url)
I receive errors on compiling of photos. I tried many versions from 7.11 to 6.99.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.23.2
Model: 23049PCD8G
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No
 
- Patch Info
App: com.google.android.apps.photos v7.11.0.705590205 (Suggested: Any)
Patches version: v5.6.0

### Installation method

None

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.23.2
Model: 23049PCD8G
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v7.11.0.705590205 (Suggested: Any)
Patches version: v5.6.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 59408 free bytes and 58KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.util.LinkedHashMap.newNode(LinkedHashMap.java:299)
	at java.util.HashMap.putVal(HashMap.java:636)
	at java.util.HashMap.put(HashMap.java:617)
	at java.util.HashSet.add(HashSet.java:229)
	at brut.androlib.res.data.ResValuesFile.addResource(SourceFile:54)
	at brut.androlib.res.data.ResPackage.listValuesFiles(SourceFile:107)
	at brut.androlib.res.ResourcesDecoder.decodeResources(SourceFile:181)
	at app.revanced.patcher.patch.ResourcePatchContext.decodeResources$revanced_patcher(SourceFile:64)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:96)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-EREOQZ/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager.

**Comment by isidorosss** [comment]
@oSumAtrIX could you please explain why you closed the issue? Did I report the issue in a wrong way? Is there sth I can do to avoid the errors? Thank you very much.
