### ISSUE TITLE
bug: Revanced does not respond while viewing a video

### ISSUE THREAD

**Issue by Matthieu-Sauer** [revanced/revanced-manager#238]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

After patching youtube version 17.36.37 using manager, (non root) everything seems to work until I start a video
When starting the video, only the stream loads (I can see the video and hear it) however I cannot do anything with the app
(can't see comments, can't go back, can't pause the video, can't switch to the next one).

After a few seconds, android pops a window saying revanced in not responding. (only video has loaded in the entire page, I cannot fo to fullscreen mode)

### Steps to reproduce

Download apk 17.36.37 from apkmirror
Patch it using every patch except debug one
install it after patching (non root version)
open the patched youtube and tap on any video

### Android version

12 with MIUI 13.0.13

### Manager version

0.0.16

### Target package name

Youtube

### Target package version.

17.36.37
17.33.42

### Installation type

Non-root

### Patches selected.

All except debug

All except debug, wide search bar, theme, auto-repeat, disable autoplay

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
09-19 16:07:16.796 27142 27142 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-19 16:07:16.904 27142 27142 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.019499999
09-19 16:10:55.164 27142 27142 W Looper  : PerfMonitor doFrame : time=498ms vsyncFrame=0 latency=1ms procState=-1
09-19 16:10:55.355 27142 27142 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 183ms
09-19 18:57:46.249 27142 27142 W Looper  : PerfMonitor longMsg : seq=5360 plan=18:57:44.690 late=0ms wall=1537ms running=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver procState=-1
09-19 18:57:46.250 27142 27142 W Looper  : PerfMonitor doFrame : time=1537ms vsyncFrame=0 latency=0ms procState=-1 historyMsgCount=2 (msgIndex=1 wall=1537ms seq=5360 running=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=1537ms seq=5360 running=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 09:11:59.606  4217  4217 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-20 09:11:59.745  4217  4217 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.019499999
09-20 09:12:18.604  4217  4217 W Looper  : PerfMonitor doFrame : time=417ms vsyncFrame=0 latency=3ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=417ms seq=145 running=9ms runnable=3ms swapin=1ms late=3ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 09:17:19.267  4217  4217 W Looper  : PerfMonitor longMsg : seq=1561 plan=09:17:17.464 late=6ms wall=1793ms running=6ms runnable=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver procState=-1
09-20 09:17:19.268  4217  4217 W Looper  : PerfMonitor doFrame : time=1793ms vsyncFrame=0 latency=6ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=1793ms seq=1561 running=6ms runnable=1ms late=6ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 09:20:16.655  4217  4217 W Looper  : PerfMonitor doFrame : time=440ms vsyncFrame=0 latency=0ms procState=-1 historyMsgCount=4 (msgIndex=1 wall=440ms seq=1707 running=10ms runnable=10ms binder=7ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=440ms seq=1707 running=10ms runnable=10ms binder=7ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=3 wall=440ms seq=1707 running=10ms runnable=10ms binder=7ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=4 wall=440ms seq=1707 running=10ms runnable=10ms binder=7ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 09:20:16.862  4217  4217 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 200ms
09-20 09:37:10.486 14564 14564 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-20 09:37:10.559 14564 14564 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.019499999
09-20 09:37:23.749 14564 14564 W Looper  : PerfMonitor doFrame : time=399ms vsyncFrame=0 latency=2ms procState=-1 historyMsgCount=2 (msgIndex=1 wall=399ms seq=106 running=9ms swapin=2ms late=2ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=399ms seq=106 running=9ms swapin=2ms late=2ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 09:42:38.221 14564 14564 W Looper  : PerfMonitor longMsg : seq=1587 plan=09:42:36.279 late=1ms wall=1929ms running=6ms runnable=2ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver procState=-1
09-20 09:42:38.221 14564 14564 W Looper  : PerfMonitor doFrame : time=1929ms vsyncFrame=0 latency=1ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=1929ms seq=1587 running=6ms runnable=2ms late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 10:05:18.309 14564 14564 W Looper  : PerfMonitor longMsg : seq=3209 plan=10:05:16.763 late=2ms wall=1538ms running=4ms runnable=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver procState=-1
09-20 10:05:18.310 14564 14564 W Looper  : PerfMonitor doFrame : time=1538ms vsyncFrame=0 latency=2ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=1538ms seq=3209 running=4ms runnable=1ms late=2ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 10:07:02.330 14564 14564 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=401ms procState=-1 historyMsgCount=2
09-20 10:07:12.468 14564 14564 W Looper  : PerfMonitor doFrame : time=582ms vsyncFrame=0 latency=1ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=582ms seq=3440 running=4ms runnable=1ms late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=582ms seq=3440 running=4ms runnable=1ms late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=3 wall=582ms seq=3440 running=4ms runnable=1ms late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-20 10:16:12.313 14564 14564 W Looper  : PerfMonitor longMsg : seq=4858 plan=10:16:10.575 late=1ms wall=1731ms running=5ms runnable=2ms swapin=2ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver procState=-1
09-20 10:16:12.314 14564 14564 W Looper  : PerfMonitor doFrame : time=1731ms vsyncFrame=0 latency=1ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=1731ms seq=4858 running=5ms runnable=2ms swapin=2ms late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
--------- beginning of main
09-20 10:33:31.801 14564 14765 D AppScoutStateMachine: 14564-ScoutStateMachinecreated
09-20 10:33:31.950 14564 14564 D DecorView[]: onWindowFocusChanged hasWindowFocus true
09-20 10:33:31.958 14564 14765 I OpenGLRenderer: Davey! duration=1108982ms; Flags=1, FrameTimelineVsyncId=54137292, IntendedVsync=845451899992114, Vsync=845451899992114, InputEventId=0, HandleInputStart=845451911750446, AnimationStart=845451911754196, PerformTraversalsStart=845451911756227, DrawStart=845451956671592, FrameDeadline=845451933325446, FrameInterval=845451911718258, FrameStartTime=16666666, SyncQueued=845451957330654, SyncStart=845451958904664, IssueDrawCommandsStart=845451959198414, SwapBuffers=845451964482581, FrameCompleted=846560883843564, DequeueBufferDuration=1664323, QueueBufferDuration=994011, GpuCompleted=846560883843564, SwapBuffersCompleted=845451965887633, DisplayPresentTime=26881, 
09-20 10:33:33.043 14564 14564 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=846561972, downTime=846561972, deviceId=-1, source=0x101, displayId=0 }
09-20 10:33:33.047 14564 14564 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=846561972, downTime=846561972, deviceId=-1, source=0x101, displayId=0 }
09-20 10:33:35.746 14564 14564 D IconCustomizer: Content Ratio = -1.0
09-20 10:33:35.750 14564 14564 D IconCustomizer: Generate customized icon for com.google.android.youtube.png
09-20 10:33:35.783 14564 14564 D IconCustomizer: Content Ratio = -1.0
09-20 10:33:35.786 14564 14564 D IconCustomizer: Generate customized icon for com.vanced.android.youtube.png
09-20 10:33:35.840 14564 14575 W manager.flutte: Reducing the number of considered missed Gc histogram windows from 103 to 100
09-20 10:33:41.000 14564 14564 W System.err: java.io.IOException: Cannot run program "su": error=13, Permission denied
09-20 10:33:41.000 14564 14564 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-20 10:33:41.000 14564 14564 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-20 10:33:41.000 14564 14564 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-20 10:33:41.000 14564 14564 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-20 10:33:41.000 14564 14564 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-20 10:33:41.000 14564 14564 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-20 10:33:41.000 14564 14564 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 10:33:41.000 14564 14564 W System.err: 	at android.os.Looper.loopOnce(Looper.java:210)
09-20 10:33:41.000 14564 14564 W System.err: 	at android.os.Looper.loop(Looper.java:299)
09-20 10:33:41.000 14564 14564 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8168)
09-20 10:33:41.000 14564 14564 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
09-20 10:33:41.000 14564 14564 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
09-20 10:33:41.000 14564 14564 W System.err: Caused by: java.io.IOException: error=13, Permission denied
09-20 10:33:41.000 14564 14564 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-20 10:33:41.000 14564 14564 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-20 10:33:41.000 14564 14564 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-20 10:33:41.000 14564 14564 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-20 10:33:41.000 14564 14564 W System.err: 	... 19 more
09-20 10:33:43.190 14564 14575 I manager.flutte: Background concurrent copying GC freed 777774(29MB) AllocSpace objects, 0(0B) LOS objects, 29% free, 58MB/82MB, paused 37us,28us total 119.460ms
09-20 10:33:43.610 14564 14575 I manager.flutte: Background concurrent copying GC freed 868855(33MB) AllocSpace objects, 0(0B) LOS objects, 25% free, 70MB/94MB, paused 39us,24us total 146.899ms
09-20 10:33:44.053 14564 14575 I manager.flutte: Background concurrent copying GC freed 1189605(43MB) AllocSpace objects, 0(0B) LOS objects, 20% free, 95MB/119MB, paused 31us,30us total 175.336ms
09-20 10:33:49.063 14564 14575 I manager.flutte: Background concurrent copying GC freed 15342(890KB) AllocSpace objects, 6(10148KB) LOS objects, 17% free, 110MB/134MB, paused 37us,26us total 166.624ms
09-20 10:33:49.897 14564 14575 I manager.flutte: Background concurrent copying GC freed 4486690(121MB) AllocSpace objects, 7(476KB) LOS objects, 20% free, 90MB/114MB, paused 149us,165us total 219.196ms
09-20 10:33:49.897 14564 14577 W System  : A resource failed to call close. 
09-20 10:33:50.071 14564 14575 I manager.flutte: Background young concurrent copying GC freed 3312602(66MB) AllocSpace objects, 0(0B) LOS objects, 19% free, 92MB/114MB, paused 181us,79us total 128.089ms
09-20 10:33:50.641 14564 14575 I manager.flutte: Background concurrent copying GC freed 8087463(161MB) AllocSpace objects, 1(68KB) LOS objects, 11% free, 179MB/203MB, paused 167us,65us total 533.491ms
09-20 10:33:50.940 14564 14575 I manager.flutte: Background young concurrent copying GC freed 7023748(142MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 150MB/174MB, paused 205us,160us total 254.131ms
09-20 10:33:51.884 14564 11360 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.884 14564 11357 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.884 14564 11359 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.885 14564 11358 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.955 14564 14575 I manager.flutte: Background concurrent copying GC freed 13691969(296MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 215MB/239MB, paused 136us,23us total 975.027ms
09-20 10:33:51.955 14564 11357 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.955 14564 11359 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.955 14564 11360 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.955 14564 11358 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:51.955 14564 11357 I manager.flutte: WaitForGcToComplete blocked Alloc on HeapTrim for 71.335ms
09-20 10:33:51.955 14564 11357 I manager.flutte: Starting a blocking GC Alloc
09-20 10:33:51.955 14564 11359 I manager.flutte: WaitForGcToComplete blocked Alloc on HeapTrim for 71.299ms
09-20 10:33:51.955 14564 11359 I manager.flutte: Starting a blocking GC Alloc
09-20 10:33:51.956 14564 11360 I manager.flutte: WaitForGcToComplete blocked Alloc on HeapTrim for 71.643ms
09-20 10:33:51.956 14564 11360 I manager.flutte: Starting a blocking GC Alloc
09-20 10:33:51.972 14564 11358 I manager.flutte: WaitForGcToComplete blocked Alloc on HeapTrim for 87.527ms
09-20 10:33:51.972 14564 11358 I manager.flutte: Starting a blocking GC Alloc
09-20 10:33:52.308 14564 14575 I manager.flutte: Background young concurrent copying GC freed 6954416(158MB) AllocSpace objects, 0(0B) LOS objects, 15% free, 131MB/155MB, paused 139us,159us total 293.788ms
09-20 10:33:53.324 14564 11358 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:53.324 14564 11360 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:53.324 14564 11359 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:53.324 14564 11357 I manager.flutte: Waiting for a blocking GC Alloc
09-20 10:33:53.518 14564 14575 I manager.flutte: Background concurrent copying GC freed 15255370(309MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 202MB/226MB, paused 211us,24us total 1.126s
09-20 10:33:53.518 14564 11358 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 194.236ms
09-20 10:33:53.518 14564 11358 I manager.flutte: Starting a blocking GC Alloc
09-20 10:33:53.518 14564 11360 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 194.501ms
09-20 10:33:53.519 14564 11360 I manager.flutte: Starting a blocking GC Alloc
09-20 10:33:53.519 14564 11359 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 194.682ms... (83 Ko restants)
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
None
```

### Screenshots or videos

![Screenshot_2022-09-20-11-06-33-211_app revanced android youtube](https://user-images.githubusercontent.com/74206586/191217491-b2b31a00-3ae0-42bd-9c2c-f9feefe2dd88.jpg)

![Screenshot_2022-09-20-11-06-48-729_app revanced android youtube](https://user-images.githubusercontent.com/74206586/191217557-0d65f3ef-4482-4b9f-b13e-9d81722edc93.jpg)

![Screenshot_2022-09-20-11-06-40-327_app revanced android youtube](https://user-images.githubusercontent.com/74206586/191217590-21b9df83-e67d-49d8-aac9-5141a6d79829.jpg)

### Additional context

I have no clue if it comes from the manager or the patcher (I hope the manager)
Please tell me if I have to re-open this issue in another repo!

**Comment by Aunali321** [comment]
You need to include microg patch and download vanced microg.

**Comment by Matthieu-Sauer** [comment]
I do have both checked / installed, else I would not even be able to start the app if i'm correct :/

**Comment by Matthieu-Sauer** [comment]
Update:
After some testing, it seems to be related to one of the actived patches. After doing the bare minimum (no-ad, microG support and  spoof) the apps works fine

**Comment by Aunali321** [comment]
Okay. closing.
