### ISSUE TITLE
Youtube don't opening after applying patches

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [revanced/revanced-manager#251]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

I installed a patches for youtube

### Steps to reproduce

1 install revanced manager
2 apply patches from these screen:https://photos.app.goo.gl/eQruaKUsWZ3284Z49
3 open youtube

### Android version

12

### Manager version

0.0.16

### Target package name

Youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

Check these screen:https://photos.app.goo.gl/eQruaKUsWZ3284Z49

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
09-20 22:16:28.677 25300 25498 I OpenGLRenderer: Davey! duration=36272ms; Flags=1, FrameTimelineVsyncId=16711333, IntendedVsync=143801112630759, Vsync=143801120964092, InputEventId=1537978976, HandleInputStart=143801127555559, AnimationStart=143801127556549, PerformTraversalsStart=143801127556914, DrawStart=143801161641653, FrameDeadline=143801137464092, FrameInterval=143801127553216, FrameStartTime=8333333, SyncQueued=143801161834570, SyncStart=143801161925455, IssueDrawCommandsStart=143801162012955, SwapBuffers=143801166203632, FrameCompleted=143837385333983, DequeueBufferDuration=2729688, QueueBufferDuration=935105, GpuCompleted=143837385333983, SwapBuffersCompleted=143801167645820, DisplayPresentTime=301296, 
09-20 22:16:34.746 25300 25498 I OpenGLRenderer: Davey! duration=16948ms; Flags=1, FrameTimelineVsyncId=16715607, IntendedVsync=143826501159759, Vsync=143826501159759, InputEventId=1836363875, HandleInputStart=143826501333883, AnimationStart=143826501335133, PerformTraversalsStart=143826501335498, DrawStart=143826514119873, FrameDeadline=143826525993092, FrameInterval=143826501331644, FrameStartTime=8333333, SyncQueued=143826514195341, SyncStart=143826514290185, IssueDrawCommandsStart=143826514452373, SwapBuffers=143826518182164, FrameCompleted=143843449830543, DequeueBufferDuration=2241615, QueueBufferDuration=753282, GpuCompleted=143843449830543, SwapBuffersCompleted=143826519390810, DisplayPresentTime=302219, 
09-20 22:17:10.399 25300 25336 I OpenGLRenderer: Davey! duration=52601ms; Flags=1, FrameTimelineVsyncId=16715607, IntendedVsync=143826501159759, Vsync=143826501159759, InputEventId=1836363875, HandleInputStart=143826501333883, AnimationStart=143826501335133, PerformTraversalsStart=143826501335498, DrawStart=143826514119873, FrameDeadline=143826534326425, FrameInterval=143826501331644, FrameStartTime=8333333, SyncQueued=143826514195341, SyncStart=143826514290185, IssueDrawCommandsStart=143826514452373, SwapBuffers=143826518182164, FrameCompleted=143879103104801, DequeueBufferDuration=2241615, QueueBufferDuration=753282, GpuCompleted=143879103104801, SwapBuffersCompleted=143826519390810, DisplayPresentTime=302219, 
09-20 22:17:34.794 25300 25336 I OpenGLRenderer: Davey! duration=24454ms; Flags=1, FrameTimelineVsyncId=16724737, IntendedVsync=143879040903351, Vsync=143879074236683, InputEventId=1493930387, HandleInputStart=143879078515790, AnimationStart=143879078517613, PerformTraversalsStart=143879078518446, DrawStart=143879097387769, FrameDeadline=143879065736684, FrameInterval=143879078512040, FrameStartTime=8333333, SyncQueued=143879097468603, SyncStart=143879097575009, IssueDrawCommandsStart=143879097692040, SwapBuffers=143879101155269, FrameCompleted=143903495914739, DequeueBufferDuration=2630937, QueueBufferDuration=794219, GpuCompleted=143903495914739, SwapBuffersCompleted=143879102325582, DisplayPresentTime=303329, 
09-20 22:18:12.838 25300 25316 I OpenGLRenderer: Davey! duration=38094ms; Flags=1, FrameTimelineVsyncId=16729109, IntendedVsync=143903451988494, Vsync=143903451988494, InputEventId=2022262857, HandleInputStart=143903452448125, AnimationStart=143903452449010, PerformTraversalsStart=143903452449479, DrawStart=143903483124948, FrameDeadline=143903476821827, FrameInterval=143903452446145, FrameStartTime=8333333, SyncQueued=143903483280052, SyncStart=143903483382656, IssueDrawCommandsStart=143903483483437, SwapBuffers=143903494539114, FrameCompleted=143941546727381, DequeueBufferDuration=10213802, QueueBufferDuration=1056250, GpuCompleted=143941546727381, SwapBuffersCompleted=143903496084895, DisplayPresentTime=304054, 
09-20 22:19:00.916 25300 25315 I OpenGLRenderer: Davey! duration=86170ms; Flags=1, FrameTimelineVsyncId=16729109, IntendedVsync=143903451988494, Vsync=143903451988494, InputEventId=2022262857, HandleInputStart=143903452448125, AnimationStart=143903452449010, PerformTraversalsStart=143903452449479, DrawStart=143903483124948, FrameDeadline=143903485155160, FrameInterval=143903452446145, FrameStartTime=8333333, SyncQueued=143903483280052, SyncStart=143903483382656, IssueDrawCommandsStart=143903483483437, SwapBuffers=143903494539114, FrameCompleted=143989622625956, DequeueBufferDuration=10213802, QueueBufferDuration=1056250, GpuCompleted=143989622625956, SwapBuffersCompleted=143903496084895, DisplayPresentTime=304054,
```

### Screenshots or videos

https://photos.app.goo.gl/eQruaKUsWZ3284Z49

**Comment by BinaryBenevolence** [comment]
Do you have Vanced microG installed?

**Comment by akkadaya** [comment]
@BinaryBenevolence do you have a link? thanks

**Comment by BinaryBenevolence** [comment]
Yup no problem: https://github.com/TeamVanced/VancedMicroG/releases/tag/v0.2.24.220220-220220001

**Comment by akkadaya** [comment]
Thanks mate, I tried that but YT Revanced still not opening. Is there a way to debug?

**Comment by BinaryBenevolence** [comment]
That's all I know, sorry friend. I'm not a developer. Hope you find some luck getting it to work. I guess I'd try uninstalling and then repatching again if you haven't already.

**Comment by Aunali321** [comment]
All methods of building revanced are currently broken right now (cli,manager,builder). It will be fixed as soon as possible.

**Comment by akkadaya** [comment]
Thanks @BinaryBenevolence @Aunali321. I'm not sure if useful but I got this log cat:

```
2022-09-21 17:19:39.793 18979-19295 OpenGLRenderer          app.revanced.android.youtube         D  RenderThread::requireGlContext()
2022-09-21 17:19:39.807 18979-19295 OpenGLRenderer          app.revanced.android.youtube         D  RenderThread::setGrContext()
2022-09-21 17:19:39.894 18979-18979 YT.MDX.wlc              app.revanced.android.youtube         W  CastAppId for type 0 not found. Defaulting to mainCastAppId.
2022-09-21 17:19:39.899 18979-18979 android.youtub          app.revanced.android.youtube         I  Rejecting re-init on previously-failed class java.lang.Class<com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel>: java.lang.VerifyError: Verifier rejected class com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel: int com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel.r() failed to verify: int com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel.r(): [0x12] instance field access on object that has non-reference type Conflict (declaration of 'com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel' appears in /data/app/~~33QS0kUOJ-3Svx72l9lACg==/app.revanced.android.youtube-oXv27LmUyaYyYaeeFFAn1A==/base.apk)
                                                                                                    (Throwable with no stack trace)
2022-09-21 17:19:39.899 18979-18979 AndroidRuntime          app.revanced.android.youtube         D  Shutting down VM
2022-09-21 17:19:39.899 18979-18979 AndroidRuntime          app.revanced.android.youtube         E  FATAL EXCEPTION: main
                                                                                                    Process: app.revanced.android.youtube, PID: 18979
                                                                                                    java.lang.VerifyError: Verifier rejected class com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel: int com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel.r() failed to verify: int com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel.r(): [0x12] instance field access on object that has non-reference type Conflict (declaration of 'com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel' appears in /data/app/~~33QS0kUOJ-3Svx72l9lACg==/app.revanced.android.youtube-oXv27LmUyaYyYaeeFFAn1A==/base.apk)
                                                                                                    	at urn.b(PG:1)
                                                                                                    	at xhw.O(PG:1)
                                                                                                    	at ehv.c(PG:109)
                                                                                                    	at ehv.a(PG:37)
                                                                                                    	at aqkt.a(PG:1)
                                                                                                    	at ehv.c(PG:110)
                                                                                                    	at ehv.a(PG:37)
                                                                                                    	at aqkt.a(PG:1)
                                                                                                    	at ehv.j(PG:96)
                                                                                                    	at ehv.a(PG:35)
                                                                                                    	at aqkt.a(PG:1)
                                                                                                    	at ejf.run(PG:1)
                                                                                                    	at syy.run(PG:7)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at sci.run(PG:55)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2022-09-21 17:19:39.917 18979-18979 Process                 app.revanced.android.youtube         I  Sending signal. PID: 18979 SIG: 9
```

**Comment by philklc** [comment]
Omit the `custom-playback-speed` and `custom-video-buffer` patches for now and it will launch.
Known issues:
https://github.com/revanced/revanced-patches/issues/569
https://github.com/revanced/revanced-patches/issues/567

**Comment by akkadaya** [comment]
thanks @philklc, it's working now!

**Comment by Bogdan-Torkhov** [comment]
It's not completed,I want all this patches,fix this please.

**Comment by justatestaccountfortdl** [comment]
Just as a reminder, 
```java
@Compatibility(
    [
        Package("com.google.android.youtube", arrayOf("17.49.37", "18.03.36"))
    ]
)
```
It is still presented on 18.03.36.

**Comment by Aunali321** [comment]
> Marked as off-topic is default behaviour of 17 year old 'mod', so if you come here from search engine results just expect unchecking these options having no effects on the recommended youtube versions.

![Screenshot_20230204_125729](https://user-images.githubusercontent.com/48486084/216756385-75e6ef55-1a81-4190-848d-6dd25ca32d6c.jpg)

Works for me. I smell a skill issue : )

**Comment by justatestaccountfortdl** [comment]
What kind of skill issues would you expect in 'select/unselect patches, push & run'? I already checked some working builds on russian bords, and decided to check what patches they apply, so did i, now it works even with revanced manager, but the default ones (for example when you select all and uncheck broken ones as it was suggested - do not). Do you think that the build stage has anything to do with the final result? Well, then i can show you adb log which is going to state the same things https://github.com/revanced/revanced-manager/issues/251#issuecomment-1253308848. No idea what it has to do with 'skill issues' while adb reports make it clear.

All i was trying to state in my previous messages is the fact that some of these patches cannot be applied to even non dpi related builds suggested by you.

Speaking of premium-heading, yep, the error didnt appear on nondpi tho.

**Comment by oSumAtrIX** [comment]
@justatestaccountfortdl This issue is outdated, and the patches in question have been fixed long time ago. You are likely using the fixed ones.

**Comment by justatestaccountfortdl** [comment]
I realize it tho, look, i downloaded revanced manager, downloaded suggested by @Aunali321 nondpi version of youtube, uninstalled updates on original youtube app so it went back to 16.x.x, which lets us apply an update. So i installed the nondpi version of 18.03.36 which is stated as 'stable' and 'compatible' in your manager (i understand that this manager has no active maintainers), then i went to settings in manager and allowed unstable patches or whatever they called, so i selected an application, clicked 'All' and waited till the patches get applied, it works well, well, at least on armv8, then i installed the application via 'install' button, and, tried to open the yt revanced app, it didnt work, so i attached my device to pc, cleared adb logs, tried opening it again, and checked the error, then googled it, hence i ended up with this issue which has suggested turning off some specific patches, so did i, turned off these 3 things, which did not work after uninstall, remove updates, rebuild, install. Hence i was just wondering what kind of patches could cause it. I just do not want to duplicate the issues over the same adb output. It would make no sense.

**Comment by Aunali321** [comment]
> allowed **unstable** patches or whatever they called, so i selected an application, clicked 'All'.

Unstable is self-explanatory isn't it?

Select recommend patches instead of all patches.
