### ISSUE TITLE
bug: v0.0.16 and v0.0.17 crashes while patching YouTube

### ISSUE THREAD

**Issue by kenethc** [revanced/revanced-manager#261]
### Type

Other

### Manager Branch

Flutter

### Bug description

ReVanced Manager v16 and v17 crashes while patching YouTube v17.36.37

### Steps to reproduce

Manager v16 and v17 crashes during patching YouTube
Tested twice on both versions - crashed both times for both. 

### Android version

v12

### Manager version

v0.0.16 and v0.0.17

### Target package name

YouTube 

### Target package version.

v17.36.37

### Installation type

Root

### Patches selected.

All except:
Debugging
MicroG
Video Speed
Video Buffer
Hide Casting button
Hide Shorts button
Always repeat video again

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
09-21 13:16:52.254 27672 27672 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 13:16:52.311 27672 27672 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
09-21 13:16:57.253 27672 27692 W MIUIScout App: Enter APP_SCOUT_WARNING State
09-21 13:16:57.262 27672 27891 W MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at java.lang.Object.wait(Native Method)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at java.lang.Object.wait(Object.java:442)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at java.lang.Thread.join(Thread.java:1531)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.stericson.RootTools.execution.Shell.<init>(Shell.java:85)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at android.os.Handler.handleCallback(Handler.java:938)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at android.os.Handler.dispatchMessage(Handler.java:99)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at android.os.Looper.loopOnce(Looper.java:210)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at android.os.Looper.loop(Looper.java:299)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at android.app.ActivityThread.main(ActivityThread.java:8105)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at java.lang.reflect.Method.invoke(Native Method)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
09-21 13:16:57.262 27672 27891 W MIUIScout App:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
09-21 13:16:58.334 27672 27672 W Looper  : PerfMonitor longMsg : seq=95 plan=13:16:53.489 late=0ms wall=4845ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
09-21 13:16:58.401 27672 27672 W Looper  : PerfMonitor doFrame : time=66ms vsyncFrame=0 latency=4835ms procState=-1 historyMsgCount=2 (msgIndex=1 wall=4845ms seq=95 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
09-21 13:16:58.438 27672 27672 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=6ms latency=4470ms running=0ms  procState=-1  historyMsgCount=6 (msgIndex=1 wall=4845ms seq=95 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=3 wall=66ms seq=97 late=4835ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
09-21 13:16:58.443 27672 27672 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=4ms latency=4475ms running=0ms  procState=-1  historyMsgCount=7 (msgIndex=1 wall=4845ms seq=95 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=3 wall=66ms seq=97 late=4835ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
--------- beginning of crash
09-21 13:19:58.903 27672 28516 E AndroidRuntime: FATAL EXCEPTION: Thread-19
09-21 13:19:58.903 27672 28516 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 27672
09-21 13:19:58.903 27672 28516 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getScanResult()Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult$MethodFingerprintScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in /data/app/~~npJA3NPpK8J_zyXfCHvkPg==/app.revanced.manager.flutter-ReY8AHpk8IEsvUjVH8SaeQ==/base.apk)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 13:19:58.903 27672 28516 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-21 13:19:58.912 27672 28516 D OOMEventManagerFK: checkEventAndDumpForJE: 0
09-21 13:20:17.911 30091 30091 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 13:20:17.980 30091 30091 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
09-21 13:20:36.928 30593 30593 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 13:20:40.760 30593 30593 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
--------- beginning of main
09-21 13:21:07.575 30593 30629 W manager.flutte: Cleared Reference was only reachable from finalizer (only reported once)
09-21 13:29:51.815 14305 14305 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-21 13:29:51.816 14305 14305 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-21 13:29:51.823 14305 14305 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10586; state: ENABLED
09-21 13:29:51.830 14305 14323 D AppScoutStateMachine: 14305-ScoutStateMachinecreated
09-21 13:29:51.835 14305 14305 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
09-21 13:29:51.835 14305 14305 V GraphicsEnvironment: Updatable production driver is not supported on the device.
09-21 13:29:51.836 14305 14305 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 13:29:51.837 14305 14305 D OpenGLRenderer: JNI_OnLoad success
09-21 13:29:51.837 14305 14305 I MiuiForceDarkConfig: setConfig density:3.500000, mainRule:0, secondaryRule:0, tertiaryRule:0
09-21 13:29:51.837 14305 14305 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 13:29:51.837 14305 14305 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: QUALCOMM build                   : 4a124bc, I55aa49cfcc
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: Build Date                       : 06/03/21
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.08
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: Local Branch                     : gfx-a6x.lnx.2.0.1
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: Remote Branch                    : 
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: Remote Branch                    : 
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: Reconstruct Branch               : 
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
09-21 13:29:51.860 14305 14305 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-21 13:29:51.864 14305 14305 I AdrenoGLES-0: PFP: 0x016dc094, ME: 0x00000000
09-21 13:29:51.873 14305 14305 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
09-21 13:29:51.884 14305 14305 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 13:29:51.891 14305 14344 E QXPerf  : Couldn't load BLASTBufferQueue Class
09-21 13:29:51.891 14305 14344 E QXPerf  : Couldn't find UndequeuedBufferCount functions
09-21 13:29:51.893 14305 14305 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 13:29:51.909 14305 14305 D SurfaceView: UPDATE null, mIsCastMode = false
09-21 13:29:51.911 14305 14332 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-21 13:29:51.918 14305 14305 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x886d2d2, mIsProjectionMode = false
09-21 13:29:51.918 14305 14305 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 13:29:51.918 14305 14305 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 13:29:51.918 14305 14305 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 13:29:51.923 14305 14347 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
09-21 13:29:51.923 14305 14347 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 13:29:51.937 14305 14331 I flutter : dynamic_color: Core palette detected.
09-21 13:29:51.957 14305 14347 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-21 13:29:51.957 14305 14347 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 13:29:51.960 14305 14305 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 13:29:51.978 14305 14332 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1440x3200, requested_size=1440x3200 buffer{size=1440x3144 transform=0}
09-21 13:29:52.231 14305 14305 W Thread-7: type=1400 audit(0.0:24660): avc: denied { write } for name="tasks" dev="cgroup" ino=21 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:cgroup:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
09-21 13:29:52.276 14305 14305 W IconCustomizer: can't load transform_config.xml
09-21 13:29:53.552 14305 14305 W MirrorManager: this model don't Support
09-21 13:29:53.575 14305 14347 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-21 13:29:53.575 14305 14347 W SQLiteLog: (28) double-quoted string literal: "A0D1FE75768CD604B012F39FF6EAC33C"
09-21 13:29:53.576 14305 14347 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-21 13:29:53.576 14305 14347 W SQLiteLog: (28) double-quoted string literal: "0D8911B1DDFCA2090CB01B655AA2FF78"
09-21 13:29:53.578 14305 14347 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-21 13:29:53.578 14305 14347 W SQLiteLog: (28) double-quoted string literal: "9B0F608252F9859F06F897721AA42943"
09-21 13:29:53.579 14305 14347 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-21 13:29:53.579 14305 14347 W SQLiteLog: (28) double-quoted string literal: "B0EF685DB778A49604A9EE705B375253"
```

**Comment by Aunali321** [comment]
Issues with revanced patcher. Will be fixed later.
