### ISSUE TITLE
App crash when running on x64 device

### ISSUE THREAD

**Issue by thanasistrisp** [revanced/revanced-manager#262]
### Type

Error while running the manager

### Manager Branch

Flutter

### Bug description

App crash when patch youtube at beginning.

### Steps to reproduce

1. open app
2. patch youtube
3. crash

### Android version

Windows Subsystem for Android -- rooted with magisk

### Manager version

Latest

### Target package name

Youtube

### Target package version.

17.36.37

### Installation type

Root

### Patches selected.

Youtube all patches

### Device logs (exported using Manager settings).

```shell
...
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].
```
--------- beginning of main
09-21 14:12:26.250 32195 32195 W manager.flutte: Unexpected CPU variant for X86 using defaults: x86_64
09-21 14:12:26.252 32195 32195 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-21 14:12:26.266 32195 32195 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10090; state: ENABLED
09-21 14:12:26.277 32195 32195 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
09-21 14:12:26.278 32195 32195 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
09-21 14:12:26.278 32195 32195 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
09-21 14:12:26.279 32195 32195 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 14:12:26.279 32195 32195 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 14:12:26.333 32195 32215 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
09-21 14:12:26.335 32195 32215 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
09-21 14:12:26.339 32195 32215 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
09-21 14:12:26.396 32195 32195 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:26.397 32195 32195 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 134 mapped 0x72bfa2939000
09-21 14:12:26.397 32195 32195 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:26.399 32195 32195 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:26.399 32195 32195 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 43, size: 1060864
09-21 14:12:26.412 32195 32195 E manager.flutte: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
09-21 14:12:26.412 32195 32195 E manager.flutte: open_verbose:121: both vsock and goldfish_pipe paths failed
09-21 14:12:26.413 32195 32220 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:26.413 32195 32220 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 136 mapped 0x72bfa2939000
09-21 14:12:26.413 32195 32220 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:26.416 32195 32220 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:26.416 32195 32220 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 44, size: 1060864
09-21 14:12:26.420 32195 32235 W manager.flutte: IOStream flush timeout
09-21 14:12:26.488 32195 32213 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:26.488 32195 32213 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 138 mapped 0x72bfa2650000
09-21 14:12:26.488 32195 32213 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:26.489 32195 32213 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:26.490 32195 32213 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 45, size: 1060864
09-21 14:12:26.493 32195 32213 W OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
09-21 14:12:26.495 32195 32213 E manager.flutte: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
09-21 14:12:26.495 32195 32213 E manager.flutte: open_verbose:121: both vsock and goldfish_pipe paths failed
09-21 14:12:26.495 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:26.495 32195 32219 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 140 mapped 0x72bfa2650000
09-21 14:12:26.495 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:26.497 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:26.498 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 46, size: 1060864
09-21 14:12:26.505 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:26.505 32195 32219 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 142 mapped 0x72bfa2650000
09-21 14:12:26.505 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:26.507 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:26.507 32195 32219 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 47, size: 1060864
09-21 14:12:26.521 32195 32242 W manager.flutte: IOStream flush timeout
09-21 14:12:26.554 32195 32246 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
09-21 14:12:26.554 32195 32246 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 14:12:27.529 32195 32218 I flutter : dynamic_color: Core palette detected.
09-21 14:12:27.545 32195 32246 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-21 14:12:27.545 32195 32246 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 14:12:27.783 32195 32218 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_regular_d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf'
09-21 14:12:27.854 32195 32218 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Inter_regular_ca30a452e6f1961d934a7c782130cbcba3bbb9b611aae1dac1279d396350b35e.ttf'
09-21 14:12:27.883 32195 32218 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_500_ec3a64e46e2ee5f546845582e1d5409107780cef55bc43b052ee962f9807aee6.ttf'
09-21 14:12:30.293 32195 32195 I Choreographer: Skipped 163 frames!  The application may be doing too much work on its main thread.
09-21 14:12:30.351 32195 32219 D EGL_emulation: app_time_stats: avg=334.03ms min=7.90ms max=1775.52ms count=8
09-21 14:12:30.906 32195 32244 W manager.flutte: IOStream flush timeout
09-21 14:12:30.914 32195 32242 W manager.flutte: IOStream flush timeout
09-21 14:12:30.921 32195 32195 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#0](f:0,a:1) Applying pending transactions on dtor 1
09-21 14:12:33.356 32195 32195 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10090; state: ENABLED
09-21 14:12:33.389 32195 32242 W manager.flutte: IOStream flush timeout
09-21 14:12:34.869 32195 32219 D EGL_emulation: app_time_stats: avg=723.10ms min=18.08ms max=1428.11ms count=2
09-21 14:12:36.978 32195 32219 D EGL_emulation: app_time_stats: avg=2109.30ms min=2109.30ms max=2109.30ms count=1
09-21 14:12:38.057 32195 32219 D EGL_emulation: app_time_stats: avg=29.68ms min=5.66ms max=358.50ms count=35
09-21 14:12:39.061 32195 32219 D EGL_emulation: app_time_stats: avg=44.67ms min=7.60ms max=649.05ms count=22
09-21 14:12:40.802 32195 32219 D EGL_emulation: app_time_stats: avg=68.34ms min=5.64ms max=997.26ms count=25
09-21 14:12:41.809 32195 32219 D EGL_emulation: app_time_stats: avg=19.43ms min=5.82ms max=229.48ms count=49
09-21 14:12:42.543 32195 32195 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10090; state: DISABLED
09-21 14:12:42.610 32195 32218 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/JetBrainsMono_regular_7d41ab308fc765375a9977c24f462964f639e89b8447ac6b149e93dc0e3e7b1c.ttf'
09-21 14:12:42.810 32195 32219 D EGL_emulation: app_time_stats: avg=36.19ms min=7.41ms max=545.03ms count=27
09-21 14:12:45.195 32195 32219 D EGL_emulation: app_time_stats: avg=138.76ms min=5.12ms max=2131.34ms count=17
--------- beginning of crash
09-21 14:12:45.426 32195  1917 E AndroidRuntime: FATAL EXCEPTION: Thread-11
09-21 14:12:45.426 32195  1917 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 32195
09-21 14:12:45.426 32195  1917 E AndroidRuntime: java.util.NoSuchElementException: Array is empty.
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.resolveAapt(Aapt.kt:12)
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.AaptKt.access$resolveAapt(Aapt.kt:1)
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.Aapt.binary(Aapt.kt:8)
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:143)
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 14:12:45.426 32195  1917 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
09-21 14:12:45.432 32195  1917 I Process : Sending signal. PID: 32195 SIG: 9
09-21 14:12:46.522  2034  2034 W manager.flutte: Unexpected CPU variant for X86 using defaults: x86_64
09-21 14:12:46.524  2034  2034 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-21 14:12:46.532  2034  2034 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10090; state: ENABLED
09-21 14:12:46.540  2034  2034 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
09-21 14:12:46.540  2034  2034 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
09-21 14:12:46.540  2034  2034 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
09-21 14:12:46.541  2034  2034 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 14:12:46.541  2034  2034 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 14:12:48.462  2034  2057 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
09-21 14:12:48.463  2034  2057 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
09-21 14:12:48.468  2034  2057 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
09-21 14:12:48.500  2034  2034 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:48.500  2034  2034 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 152 mapped 0x72bfa2939000
09-21 14:12:48.500  2034  2034 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:48.502  2034  2034 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:48.502  2034  2034 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 4c, size: 1060864
09-21 14:12:48.512  2034  2034 E manager.flutte: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
09-21 14:12:48.512  2034  2034 E manager.flutte: open_verbose:121: both vsock and goldfish_pipe paths failed
09-21 14:12:48.513  2034  2063 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:48.513  2034  2063 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 154 mapped 0x72bfa2939000
09-21 14:12:48.513  2034  2063 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:48.514  2034  2063 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:48.515  2034  2063 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 4d, size: 1060864
09-21 14:12:48.520  2034  2077 W manager.flutte: IOStream flush timeout
09-21 14:12:48.590  2034  2055 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:48.590  2034  2055 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 156 mapped 0x72bfa2650000
09-21 14:12:48.590  2034  2055 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:48.592  2034  2055 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:48.592  2034  2055 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 4e, size: 1060864
09-21 14:12:48.596  2034  2055 W OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
09-21 14:12:48.599  2034  2055 E manager.flutte: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
09-21 14:12:48.599  2034  2055 E manager.flutte: open_verbose:121: both vsock and goldfish_pipe paths failed
09-21 14:12:48.600  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:48.600  2034  2062 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 158 mapped 0x72bfa2650000
09-21 14:12:48.601  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:48.603  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:48.603  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 4f, size: 1060864
09-21 14:12:48.622  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp
09-21 14:12:48.622  2034  2062 D goldfish-address-space: virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 160 mapped 0x72bfa2650000
09-21 14:12:48.623  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
09-21 14:12:48.633  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
09-21 14:12:48.633  2034  2062 D manager.flutte: createVirtioGpuAddressSpaceStream: hostmem id: 50, size: 1060864
09-21 14:12:48.641  2034  2080 W manager.flutte: IOStream flush timeout
09-21 14:12:48.657  2034  2085 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
09-21 14:12:48.657  2034  2085 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 14:12:48.704  2034  2061 I flutter : dynamic_color: Core palette detected.
09-21 14:12:48.739  2034  2085 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-21 14:12:48.739  2034  2085 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 14:12:49.904  2034  2062 D EGL_emulation: app_time_stats: avg=49.11ms min=9.71ms max=614.45ms count=20
09-21 14:12:50.914  2034  2062 D EGL_emulation: app_time_stats: avg=35.56ms min=10.53ms max=559.30ms count=28
09-21 14:12:51.928  2034  2062 D EGL_emulation: app_time_stats: avg=16.45ms min=10.66ms max=18.57ms count=61
```

**Comment by scarlettekk** [comment]
This seems to happen on aarch64 (Pixel 6 Android 13) as well.

**Comment by scarlettekk** [comment]
logs: [Google Drive](https://drive.google.com/file/d/1i28tpJBNmnOyAdjoCFA3hZ4yVK6KcVQh/view?usp=drivesdk)

**Comment by scarlettekk** [comment]
nevermind that is fixed as of 0.0.17, didn't prompt to update for whatever reason

**Comment by Aunali321** [comment]
X86_64 is currently not supported.

**Comment by scarlettekk** [comment]
amd64 support probably warrants its own issue as a feature request

**Comment by Aunali321** [comment]
We are unsure if we will support that architecture.
