### ISSUE TITLE
bug: crash during patching

### ISSUE THREAD

**Issue by thevtn** [revanced/revanced-manager#266]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

Crash occurs during patching

### Steps to reproduce

1. Choose your YouTube apk
2. Start patching
3. Crash happened 

### Android version

Android 12

### Manager version

0.0.17

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

Selected all except custom branding and enable debbuging 

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
09-21 14:54:04.934 30711 30711 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 14:54:05.608 30711 30711 W BpBinder: Slow Binder: BpBinder transact took 574 ms, interface=android.view.accessibility.IAccessibilityManager, code=3 oneway=false
09-21 14:54:05.639 30711 30711 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onCreate took 668ms
09-21 14:54:05.668 30711 30711 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=785ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=62ms seq=2 late=17ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=715ms seq=3 late=71ms h=android.app.ActivityThread$H w=159)
--------- beginning of crash
09-21 14:59:05.824 30711 31911 E AndroidRuntime: FATAL EXCEPTION: Thread-7
09-21 14:59:05.824 30711 31911 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 30711
09-21 14:59:05.824 30711 31911 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getPatternScanResult()Lapp/revanced/patcher/fingerprint/method/impl/PatternScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in base.apk)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 14:59:05.824 30711 31911 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-21 14:59:22.691  2232  2232 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 15:08:43.089  2232  5651 E AndroidRuntime: FATAL EXCEPTION: Thread-8
09-21 15:08:43.089  2232  5651 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 2232
09-21 15:08:43.089  2232  5651 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getPatternScanResult()Lapp/revanced/patcher/fingerprint/method/impl/PatternScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in base.apk)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 15:08:43.089  2232  5651 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-21 15:08:48.676  7677  7677 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 15:39:23.678 18391 18391 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 15:46:29.718 18391 21220 E AndroidRuntime: FATAL EXCEPTION: Thread-6
09-21 15:46:29.718 18391 21220 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 18391
09-21 15:46:29.718 18391 21220 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getPatternScanResult()Lapp/revanced/patcher/fingerprint/method/impl/PatternScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in base.apk)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 15:46:29.718 18391 21220 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-21 15:46:31.436 22191 22191 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 15:50:48.002 25296 25296 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 15:53:41.369 25296 25505 E AndroidRuntime: FATAL EXCEPTION: Thread-6
09-21 15:53:41.369 25296 25505 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 25296
09-21 15:53:41.369 25296 25505 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getPatternScanResult()Lapp/revanced/patcher/fingerprint/method/impl/PatternScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in base.apk)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 15:53:41.369 25296 25505 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-21 15:53:52.632 26672 26672 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
--------- beginning of main
09-21 15:58:44.687 26672 26685 D AppScoutStateMachine: 26672-ScoutStateMachinecreated
09-21 15:58:44.708 26672 26672 I BufferQueueConsumer: [](id:68300000000a,api:0,p:-1,c:26672) connect: controlledByApp=false
09-21 15:58:44.708 26672 26672 I BLASTBufferQueue: [ViewRootImpl[MainActivity]#10] constructor()
09-21 15:58:44.708 26672 26691 I BufferQueueProducer: [ViewRootImpl[MainActivity]#10(BLAST Consumer)10](id:68300000000a,api:1,p:26672,c:26672) connect: api=1 producerControlledByApp=true
09-21 15:58:44.710 26672 26672 I BufferQueueConsumer: [](id:68300000000b,api:0,p:-1,c:26672) connect: controlledByApp=false
09-21 15:58:44.711 26672 26672 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#11] constructor()
09-21 15:58:44.712 26672 26697 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#9] destructor()
09-21 15:58:44.712 26672 26697 I BufferQueueConsumer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#9(BLAST Consumer)9](id:683000000009,api:0,p:-1,c:26672) disconnect
09-21 15:58:44.712 26672 26697 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#11(BLAST Consumer)11](id:68300000000b,api:1,p:26672,c:26672) connect: api=1 producerControlledByApp=true
09-21 15:58:44.713 26672 26672 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x3909e8a, mIsProjectionMode = false
09-21 15:58:44.714 26672 26672 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 15:58:44.714 26672 26672 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 15:58:44.714 26672 26672 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 15:58:44.717 26672 26685 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:114555367718935 framenumber:2 blastBufferQueue is dead
09-21 15:58:44.735 26672 26672 D DecorView[]: onWindowFocusChanged hasWindowFocus true
09-21 15:58:44.739 26672 26685 I OpenGLRenderer: Davey! duration=251001ms; Flags=1, FrameTimelineVsyncId=1209280, IntendedVsync=30271367204694, Vsync=30271367204694, InputEventId=736811341, HandleInputStart=30271369423573, AnimationStart=30271369425188, PerformTraversalsStart=30271369425803, DrawStart=30271386582726, FrameDeadline=30271403871361, FrameInterval=30271369404573, FrameStartTime=16666667, SyncQueued=30271386741188, SyncStart=30271386823649, IssueDrawCommandsStart=30271386868803, SwapBuffers=30271395301419, FrameCompleted=30522368888280, DequeueBufferDuration=6787000, QueueBufferDuration=708846, GpuCompleted=30522368888280, SwapBuffersCompleted=30271396343957, DisplayPresentTime=0,
```

### Screenshots or videos

https://user-images.githubusercontent.com/73998182/191513577-c7aafed3-c1d7-4300-90a1-a25706bf1ebd.mp4

**Comment by AndryOut** [comment]
Same for with the old versions, with the last one the installation works without crashing. But when I open youtube crashes

**Comment by Aunali321** [comment]
send new logs.

**Comment by thevtn** [comment]
> send new logs.

```
09-21 19:04:03.759 18218 18218 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 19:06:47.306 18218 18432 E AndroidRuntime: FATAL EXCEPTION: Thread-5
09-21 19:06:47.306 18218 18432 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 18218
09-21 19:06:47.306 18218 18432 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getPatternScanResult()Lapp/revanced/patcher/fingerprint/method/impl/PatternScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in base.apk)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 19:06:47.306 18218 18432 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of main
09-21 19:09:40.311 20094 20094 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-21 19:09:40.315 20094 20094 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-21 19:09:40.339 20094 20109 D AppScoutStateMachine: 20094-ScoutStateMachinecreated
09-21 19:09:40.341 20094 20094 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10773; state: ENABLED
09-21 19:09:40.382 20094 20094 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
09-21 19:09:40.382 20094 20094 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
09-21 19:09:40.384 20094 20094 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
09-21 19:09:40.385 20094 20094 D OpenGLRenderer: JNI_OnLoad success
09-21 19:09:40.385 20094 20094 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
09-21 19:09:40.386 20094 20094 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 19:09:40.386 20094 20094 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 19:09:40.398 20094 20115 D libMEOW : meow new tls: 0xb4000075247fa180
09-21 19:09:40.400 20094 20115 D libMEOW : meow reload base cfg path: na
09-21 19:09:40.400 20094 20115 D libMEOW : meow reload overlay cfg path: na
09-21 19:09:40.401 20094 20115 E QT      : [QT]file does not exist
09-21 19:09:40.401 20094 20115 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
09-21 19:09:40.401 20094 20115 D libMEOW :   plugin 1: [libMEOW_gift.so]:
09-21 19:09:40.402 20094 20115 D libMEOW : meow delete tls: 0xb4000075247fa180
09-21 19:09:40.439 20094 20094 D libMEOW : meow new tls: 0xb4000074c5eeaa00
09-21 19:09:40.439 20094 20094 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
09-21 19:09:40.439 20094 20094 D libMEOW :   plugin 1: [libMEOW_gift.so]:
09-21 19:09:40.444 20094 20094 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-21 19:09:40.447 20094 20094 I GED     : [GT]_get_procNameprocess pid(20094)
09-21 19:09:40.447 20094 20094 I GED     : [GT]_getprocess name(app.revanced.manager.flutter)
09-21 19:09:40.448 20094 20094 I manager.flutte: [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
09-21 19:09:40.449 20094 20094 I GED     : [GT]_get_procNameprocess pid(20094)
09-21 19:09:40.449 20094 20094 I GED     : [GT]_getprocess name(app.revanced.manager.flutter)
09-21 19:09:40.449 20094 20094 I manager.flutte: [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
09-21 19:09:40.451 20094 20120 D libMEOW : meow new tls: 0xb4000074a6227000
09-21 19:09:40.451 20094 20120 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
09-21 19:09:40.451 20094 20120 D libMEOW :   plugin 1: [libMEOW_gift.so]:
09-21 19:09:40.465 20094 20094 I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@1fd7d94
09-21 19:09:40.481 20094 20094 D IS_CTS_MODE: false
09-21 19:09:40.481 20094 20094 D MULTI_WINDOW_SWITCH_ENABLED: false
09-21 19:09:40.482 20094 20094 D IS_CTS_MODE: false
09-21 19:09:40.482 20094 20094 D MULTI_WINDOW_SWITCH_ENABLED: false
09-21 19:09:40.484 20094 20094 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 19:09:40.494 20094 20094 I MsyncFactory: [static] sMsyncFactory = com.mediatek.view.impl.MsyncFactoryImpl@dcf038a
09-21 19:09:40.501 20094 20094 D ViewRootImpl[MainActivity]: hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
09-21 19:09:40.502 20094 20094 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 19:09:40.502 20094 20094 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
09-21 19:09:40.526 20094 20094 I BufferQueueConsumer: [](id:4e7e00000000,api:0,p:-1,c:20094) connect: controlledByApp=false
09-21 19:09:40.527 20094 20094 I BLASTBufferQueue: [ViewRootImpl[MainActivity]#0] constructor()
09-21 19:09:40.528 20094 20113 D libMEOW : meow new tls: 0xb4000075303a78c0
09-21 19:09:40.528 20094 20113 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
09-21 19:09:40.528 20094 20113 D libMEOW :   plugin 1: [libMEOW_gift.so]:
09-21 19:09:40.529 20094 20113 I GED     : [GT]_get_procNameprocess pid(20094)
09-21 19:09:40.529 20094 20113 I GED     : [GT]_getprocess name(app.revanced.manager.flutter)
09-21 19:09:40.529 20094 20113 I manager.flutte: [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
09-21 19:09:40.530 20094 20094 D SurfaceView: UPDATE null, mIsCastMode = false
09-21 19:09:40.533 20094 20094 I BufferQueueConsumer: [](id:4e7e00000001,api:0,p:-1,c:20094) connect: controlledByApp=false
09-21 19:09:40.533 20094 20094 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1] constructor()
09-21 19:09:40.534 20094 20119 D libMEOW : meow new tls: 0xb4000074a5778340
09-21 19:09:40.534 20094 20119 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
09-21 19:09:40.534 20094 20119 D libMEOW :   plugin 1: [libMEOW_gift.so]:
09-21 19:09:40.534 20094 20119 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:4e7e00000001,api:1,p:20094,c:20094) connect: api=1 producerControlledByApp=true
09-21 19:09:40.535 20094 20113 I BufferQueueProducer: [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:4e7e00000000,api:1,p:20094,c:20094) connect: api=1 producerControlledByApp=true
09-21 19:09:40.540 20094 20094 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x6e2424, mIsProjectionMode = false
09-21 19:09:40.540 20094 20094 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 19:09:40.541 20094 20094 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 19:09:40.541 20094 20094 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-21 19:09:40.556 20094 20148 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
09-21 19:09:40.556 20094 20148 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 19:09:41.061 20094 20118 I flutter : dynamic_color: Core palette detected.
09-21 19:09:41.091 20094 20148 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-21 19:09:41.091 20094 20148 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-21 19:09:41.093 20094 20094 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 19:09:41.093 20094 20094 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
09-21 19:09:41.095 20094 20119 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-21 19:09:41.096 20094 20119 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-21 19:09:41.129 20094 20119 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2400, requested_size=1080x2400 buffer{size=1080x2356 transform=0}
09-21 19:09:41.148 20094 20113 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
09-21 19:09:41.148 20094 20113 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
09-21 19:09:41.161 20094 20094 D DecorView[]: onWindowFocusChanged hasWindowFocus true
09-21 19:09:41.203 20094 20094 W System.err: java.io.IOException: Cannot run program "su": error=13, Permission denied
09-21 19:09:41.203 20094 20094 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-21 19:09:41.203 20094 20094 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-21 19:09:41.203 20094 20094 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-21 19:09:41.204 20094 20094 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-21 19:09:41.204 20094 20094 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-21 19:09:41.204 20094 20094 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-21 19:09:41.204 20094 20094 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-21 19:09:41.204 20094 20094 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-21 19:09:41.204 20094 20094 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-21 19:09:41.204 20094 20094 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-21 19:09:41.204 20094 20094 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-21 19:09:41.204 20094 20094 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-21 19:09:41.204 20094 20094 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-21 19:09:41.204 20094 20094 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-21 19:09:41.204 20094 20094 W System.err: 	at android.os.Looper.loopOnce(Looper.java:210)
09-21 19:09:41.204 20094 20094 W System.err: 	at android.os.Looper.loop(Looper.java:299)
09-21 19:09:41.204 20094 20094 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8298)
09-21 19:09:41.204 20094 20094 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 19:09:41.204 20094 20094 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
09-21 19:09:41.204 20094 20094 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
09-21 19:09:41.204 20094 20094 W System.err: Caused by: java.io.IOException: error=13, Permission denied
09-21 19:09:41.204 20094 20094 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-21 19:09:41.204 20094 20094 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-21 19:09:41.204 20094 20094 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-21 19:09:41.204 20094 20094 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-21 19:09:41.204 20094 20094 W System.err: 	... 19 more
09-21 19:09:42.069 20094 20168 I incfs   : Initial API level of the device: 30
09-21 19:09:42.069 20094 20168 W libc    : Access denied finding property "ro.incremental.enable"
09-21 19:09:42.069 20094 20168 I incfs   : ro.incremental.enable: 
09-21 19:09:42.069 20094 20168 I incfs   : IncFs_Features: v1
09-21 19:09:42.256 20094 20148 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-21 19:09:42.256 20094 20148 W SQLiteLog: (28) double-quoted string literal: "93A9AF576E19BC1699B1257D90C20EF9"
09-21 19:09:42.261 20094 20148 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-21 19:09:42.261 20094 20148 W SQLiteLog: (28) double-quoted string literal: "0E6EEF50F06FED6444AB7B4BB0E88C33"
09-21 19:09:42.264 20094 20148 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-21 19:09:42.264 20094 20148 W SQLiteLog: (28) double-quoted string literal: "BE00820C7ED8D980B4A41D0D625579D0"

```

**Comment by Aunali321** [comment]
Please try reinstalling manager. and make sure to use full apk (120mb+).
