### ISSUE TITLE
bug: Integrations not being included for tiktok-feed-filter patch, and tiktok-settings not showing

### ISSUE THREAD

**Issue by octopusknives** [revanced/revanced-manager#275]
### Type

Error while running the manager

### Manager Branch

Flutter

### Bug description

The required integrations from [revanced-integrations](https://github.com/revanced/revanced-integrations) are not being included for tiktok-settings and tiktok-feed-filter patches. The tiktok-settings patch is not showing in the manager. When the tiktok-feed-filter patch is included, it outputs an error relating to tiktok-integrations. 

Patching using the CLI works without issue when the integrations are merged. 

### Steps to reproduce

Include tiktok-feed-filter patch when patching using the manager. The tiktok-feed-filter error can also be reproduced in the CLI by not explicitly including integrations from [revanced-integrations](https://github.com/revanced/revanced-integrations).

### Android version

Android 13 (GrapheneOS 2022092000)

### Manager version

0.0.17

### Target package name

com.ss.android.ugc.trill
com.zhiliahoapp.musically

### Target package version.

26.3.2

### Installation type

Non-root

### Patches selected.

tiktok-ads
tiktok-feed-filter
tiktok-download
tiktok-seekbar
tiktok-force-login

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
09-22 12:17:16.115 12328 12328 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #8
09-22 12:17:16.119 12328 12328 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #190
09-22 12:17:16.146 12328 12328 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1932
09-22 12:17:50.554 12328 12328 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #8
09-22 12:17:50.554 12328 12328 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #190
09-22 12:17:50.561 12328 12328 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1934
09-22 12:20:17.918 21183 21183 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #8
09-22 12:20:17.921 21183 21183 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #190
09-22 12:20:17.931 21183 21183 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1932
09-22 12:22:39.903 21183 21183 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #8
09-22 12:22:39.905 21183 21183 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #190
09-22 12:22:39.915 21183 21183 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1934
09-22 12:49:41.845 24391 24391 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #8
09-22 12:49:41.845 24391 24391 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #190
09-22 12:49:41.852 24391 24391 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.ss.android.ugc.trill_26.3.2-260302_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1934
--------- beginning of crash
09-22 12:58:03.809 24391 30391 E AndroidRuntime: FATAL EXCEPTION: Thread-10
09-22 12:58:03.809 24391 30391 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 24391
09-22 12:58:03.809 24391 30391 E AndroidRuntime: kotlin.io.NoSuchFileException: /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk: The source file doesn't exist.
09-22 12:58:03.809 24391 30391 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
09-22 12:58:03.809 24391 30391 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
09-22 12:58:03.809 24391 30391 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:125)
09-22 12:58:03.809 24391 30391 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-22 12:58:03.809 24391 30391 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-22 12:58:03.809 24391 30391 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-22 13:02:28.918 30400 30400 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #8
09-22 13:02:28.918 30400 30400 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #190
09-22 13:02:28.924 30400 30400 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1932
09-22 13:02:34.303 30400 30400 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #8
09-22 13:02:34.303 30400 30400 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #190
09-22 13:02:34.310 30400 30400 W PackageParser: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_26.3.2-2022603020_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #1932
--------- beginning of main
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=0
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=1
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=2
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=3
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=4
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=5
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=6
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=7
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=8
09-22 13:42:48.508 30400 30400 E SurfaceSyncer: Failed to find sync for id=9
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=0
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=1
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=2
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=3
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=4
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=5
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=6
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=7
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=8
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=9
09-22 13:44:09.968 30400 30400 E SurfaceSyncer: Failed to find sync for id=10
09-22 13:44:49.370 30400 30400 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-22 13:44:49.380 30400 30400 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-22 13:44:49.380 30400 30400 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-22 13:44:49.380 30400 30400 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-22 13:44:49.380 30400 30400 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-22 13:44:49.380 30400 30400 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-22 13:44:49.380 30400 30400 W System.err: 	at android.os.Handler.handleCallback(Handler.java:942)
09-22 13:44:49.380 30400 30400 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-22 13:44:49.380 30400 30400 W System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
09-22 13:44:49.380 30400 30400 W System.err: 	at android.os.Looper.loop(Looper.java:288)
09-22 13:44:49.380 30400 30400 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7904)
09-22 13:44:49.380 30400 30400 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-22 13:44:49.380 30400 30400 W System.err: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
09-22 13:44:49.380 30400 30400 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-22 13:44:49.380 30400 30400 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-22 13:44:49.380 30400 30400 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-22 13:44:49.380 30400 30400 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-22 13:44:49.380 30400 30400 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-22 13:44:49.380 30400 30400 W System.err: 	... 21 more
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=0
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=1
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=2
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=3
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=4
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=5
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=6
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=7
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=8
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=9
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=10
09-22 13:47:52.172 30400 30400 E SurfaceSyncer: Failed to find sync for id=11
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=0
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=1
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=2
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=3
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=4
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=5
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=6
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=7
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=8
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=9
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=10
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=11
09-22 13:48:00.286 30400 30400 E SurfaceSyncer: Failed to find sync for id=12
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Only decoding AndroidManifest.xml because resource patching is disabled
Reading dex files
Applying all patches
Executing 'tiktok-ads' of type: bytecode
[success] tiktok-ads
Executing 'tiktok-integrations' of type: bytecode
[error] tiktok-feed-filter:app.revanced.patcher.patch.PatchResultError: 'tiktok-feed-filter' depends on 'tiktok-integrations' but the following error was raised: Integrations have not been merged yet. This patch can not succeed without the integrations.
Executing 'tiktok-download' of type: bytecode
[success] tiktok-download
Executing 'tiktok-seekbar' of type: bytecode
[success] tiktok-seekbar
Executing 'tiktok-force-login' of type: bytecode
[success] tiktok-force-login
Repacking patched apk
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using nonroot method
```

### Additional context

Issue might be related to this function?
https://github.com/revanced/revanced-manager/blob/f643a314554d340fa6945bc0f1fc3919263bc9ca/lib/services/patcher_api.dart#L90

**Comment by TheJeterLP** [comment]
I can confirm that

**Comment by ponces** [comment]
Fixed on https://github.com/revanced/revanced-manager/commit/f9865166b09b4c1ef7002d60f8668a9ffbabd680.
Closed.
