### ISSUE TITLE
bug: error in sponsorblock 

### ISSUE THREAD

**Issue by AndryOut** [revanced/revanced-manager#278]
### Type

Other

### Manager Branch

Flutter

### Bug description

Sponsor block not working 

### Steps to reproduce

1: Select patches 
2: Install with root
3: I open youtube
4: sponsor block not working in videos 

### Android version

Oxygen os 12

### Manager version

0.0.18

### Target package name

Youtube 

### Target package version.

Only youtube

### Installation type

Root

### Patches selected.

Client spoof
Custom branding 
Custom video buffer 
Downloads
General ads
Hide auto play buttion
Hide cast buttion 
Hide create buttion
Hide short buttion
Minimized playback
Premium heading
Remember video quality
Return youtube dislike
Sponsor block (ERROR IN LOG) 
Swipe controls
Theme
Video ads

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
09-21 14:22:55.066 25756 25756 E AndroidRuntime: FATAL EXCEPTION: main
09-21 14:22:55.066 25756 25756 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 25756
09-21 14:22:55.066 25756 25756 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5514)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5553)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8210)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Reply already submitted
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8471)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5507)
09-21 14:22:55.066 25756 25756 E AndroidRuntime: 	... 13 more
09-21 14:25:55.986 26614 29078 E AndroidRuntime: FATAL EXCEPTION: Thread-12
09-21 14:25:55.986 26614 29078 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 26614
09-21 14:25:55.986 26614 29078 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getScanResult()Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult$MethodFingerprintScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in /data/app/~~3IQLdKb_xXSUSfVSdHjYYQ==/app.revanced.manager.flutter-pgFp6pH_TtWL3TGC4bKmlA==/base.apk)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 14:25:55.986 26614 29078 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: FATAL EXCEPTION: Thread-12
09-21 14:29:06.529 31423 32145 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 31423
09-21 14:29:06.529 31423 32145 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getScanResult()Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult$MethodFingerprintScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in /data/app/~~z7d_JcL7zxedpUvPrqpk4Q==/app.revanced.manager.flutter-XTYXu5juP0iQbYW1K-wBow==/base.apk)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 14:29:06.529 31423 32145 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: FATAL EXCEPTION: Thread-12
09-21 14:31:38.700 32714  1088 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 32714
09-21 14:31:38.700 32714  1088 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getScanResult()Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult$MethodFingerprintScanResult; in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprintResult; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprintResult' appears in /data/app/~~z7d_JcL7zxedpUvPrqpk4Q==/app.revanced.manager.flutter-XTYXu5juP0iQbYW1K-wBow==/base.apk)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:30)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:292)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:307)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
09-21 14:31:38.700 32714  1088 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of system
09-22 20:00:55.453 28543 28543 I Quality : Skipped: false 2 cost 19.749577 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:00:55.485 28543 28543 I Quality : Skipped: false 2 cost 19.213528 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:01:06.884 28543 28543 I Quality : Skipped: false 3 cost 28.802784 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:01:06.936 28543 28543 I Quality : Skipped: false 3 cost 30.864996 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:01:17.955 28543 28543 I Quality : Skipped: false 2 cost 18.154348 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:01:27.797 28543 28543 I Quality : Skipped: false 3 cost 26.474634 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:01:43.917 28543 28543 I Quality : Skipped: false 1 cost 15.345349 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:04:14.930 28543 28543 I Quality : Skipped: false 4 cost 80.984764 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:04:31.884 28543 28543 I Quality : Skipped: false 1 cost 26.012136 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:06:07.321 28543 28543 I Quality : Skipped: false 1 cost 26.004206 refreshRate 0 processName app.revanced.manager.flutter
--------- beginning of main
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: QUALCOMM build                   : 629d727fc2, I97e7a4565c
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: Build Date                       : 03/08/22
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.06
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: Local Branch                     : 
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: Remote Branch                    : 
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: Remote Branch                    : 
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: Reconstruct Branch               : 
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
09-22 20:08:42.000  2567  2567 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-22 20:08:42.003  2567  2567 I AdrenoGLES-0: PFP: 0x016dd091, ME: 0x00000000
09-22 20:08:42.025  2567  2567 I oplus.android.OplusFrameworkFactoryImpl: Unknow feature:IOplusTextViewRTLUtilForUG
09-22 20:08:42.029  2567  2567 D OplusInputMethodUtil: init DEBUG to false, update DEBUG_IME to false
09-22 20:08:42.029  2567  2567 D OplusInputMethodUtil: init DEBUG to false, update DEBUG_IME to false
09-22 20:08:42.038  2567  2567 I Quality : ActivityThread: activityStart delay 74 app.revanced.manager.flutter 2567
09-22 20:08:42.043  2567  2567 D OplusSlideAnimOptHelper: app.revanced.manager.flutter scrollEffectOpt enable = false
09-22 20:08:42.046  2567  2567 D WindowManager: Add to mViews: DecorView@db7f827[MainActivity],pkg= app.revanced.manager.flutter
09-22 20:08:42.047  2567  5330 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-22 20:08:42.048  2567  5330 D ExtensionsLoader: Opened libhwuiextimpl.so
09-22 20:08:42.048  2567  2567 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-22 20:08:42.049  2567  2567 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-22 20:08:42.049  2567  2567 E manager.flutte: ofbOpen failed with error=No such file or directory
09-22 20:08:42.049  2567  2567 E manager.flutte: sysOpen failed with error=No such file or directory
09-22 20:08:42.056  2567  2567 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-22 20:08:42.056  2567  2567 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-22 20:08:42.065  2567  5361 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
09-22 20:08:42.065  2567  5361 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-22 20:08:42.073  2567  2567 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-22 20:08:42.073  2567  2567 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-22 20:08:42.074  2567  2567 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 2376 getDecorView.230160423
09-22 20:08:42.080  2567  5340 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-22 20:08:42.086  2567  2567 I Quality : Skipped: false 1 cost 14.687061 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:08:42.089  2567  5339 I flutter : dynamic_color: Core palette detected.
09-22 20:08:42.106  2567  5361 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-22 20:08:42.106  2567  5361 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-22 20:08:42.124  2567  2602 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
09-22 20:08:42.168  2567  2567 I Quality : Skipped: false 6 cost 54.84463 refreshRate 0 processName app.revanced.manager.flutter
09-22 20:08:42.174  2567  2602 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
09-22 20:08:42.434  2567  5361 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-22 20:08:42.434  2567  5361 W SQLiteLog: (28) double-quoted string literal: "407F7C25830C7E27E26BCEE49D99AC83"
09-22 20:08:42.688  2567  5361 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-22 20:08:42.688  2567  5361 W SQLiteLog: (28) double-quoted string literal: "5BE51EC33AFA03FFCF281174BF8C5826"
09-22 20:08:43.014  2567  2567 V AutofillManager: requestHideFillUi(null): anchor = null
09-22 20:08:44.149  2567  2567 V AutofillManager: requestHideFillUi(null): anchor = null
09-22 20:08:45.546  2567  2567 V AutofillManager: requestHideFillUi(null): anchor = null
09-22 20:08:46.480  2567  2567 V AutofillManager: requestHideFillUi(null): anchor = null
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Decoding resources
Reading dex files
Merging integrations
Applying all patches
Executing 'resource-id-mapping-provider-resource-patch-dependency' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Executing 'general-ads' of type: bytecode
[success] general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
[success] downloads
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'player-type-hook' of type: bytecode
Skipping 'settings' because it has already been applied
Executing 'swipe-controls-resource-patch' of type: resource
Executing 'swipe-controls' of type: bytecode
[success] swipe-controls
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'hide-autoplay-button' of type: bytecode
[success] hide-autoplay-button
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
[success] premium-heading
Skipping 'locale-config-fix' because it has already been applied
Executing 'custom-branding' of type: resource
[success] custom-branding
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-cast-button' of type: bytecode
[success] hide-cast-button
Skipping 'integrations' because it has already been applied
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-create-button' of type: bytecode
[success] hide-create-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-shorts-button' of type: bytecode
[success] hide-shorts-button
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
[success] return-youtube-dislike
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
[error] sponsorblock:app.revanced.patcher.patch.PatchResultError
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
[success] theme
Executing 'client-spoof' of type: bytecode
[success] client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
[success] minimized-playback
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Executing 'remember-video-quality' of type: bytecode
[success] remember-video-quality
Skipping 'settings' because it has already been applied
[success] settings
Skipping 'settings' because it has already been applied
Executing 'custom-video-buffer' of type: bytecode
[success] custom-video-buffer
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using root method
Installed!
```

**Comment by Aunali321** [comment]
Not related to manager.
