### ISSUE TITLE
bug: patching fails when compiling resources: brut.common.BrutException: could not exec (exit code = 135)

### ISSUE THREAD

**Issue by Priw8** [revanced/revanced-manager#295]
### Type

Error while running the manager

### Bug description

Simply attempting to apply any patches to the Youtube app on my device causes the error to occur.

### Steps to reproduce

Select any patch and attempt to patch the Youtube app; given that this does not seem to be reported by anyone else, I suppose this is an issue that occurs specifically on some Android versions.

### Android version

9.1.0.437 (C431E6R2P1) on Huawei y6 2019 (MRD-LX1)

### Manager version

0.0.24

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

MicroG Support (also got the same error when applying a whole lot of patches, so I checked with just one to see if perhaps one of the patches was problematic, but that does not seem to be the case)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
09-25 01:14:03.094 31592 31616 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-25 01:14:03.095 31592 31616 I chatty  : uid=10113(app.revanced.manager.flutter) 1.raster identical 1 line
09-25 01:14:03.095 31592 31616 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-25 01:14:03.097 31592 31592 D ViewRootImpl[MainActivity]: surface should not be released
09-25 01:14:03.142 31592 31626 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-25 01:14:05.298 31592 31592 D ZrHung.AppEyeUiProbe: notify runnable to start.
09-25 01:14:05.299 31592 31609 D ZrHung.AppEyeUiProbe: restart watching
09-25 01:14:05.311 31592 31592 I HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=true, mForcedNavigationBarColor=true, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
09-25 01:14:05.373 31592 31592 E BpSurfaceComposerClient: Failed to transact (-1)
09-25 01:14:05.374 31592 31592 E BpSurfaceComposerClient: Failed to transact (-1)
09-25 01:14:05.380 31592 31592 W InputMethodManager: startInputReason = 1
09-25 01:14:05.437 31592 31592 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
09-25 01:14:07.106 31592 31592 V AudioManager: playSoundEffect   effectType: 0
09-25 01:14:07.106 31592 31592 V AudioManager: querySoundEffectsEnabled...
09-25 01:14:10.929 31592 31592 V AudioManager: playSoundEffect   effectType: 0
09-25 01:14:10.929 31592 31592 V AudioManager: querySoundEffectsEnabled...
09-25 01:14:19.152 31592 31592 V AudioManager: playSoundEffect   effectType: 0
09-25 01:14:19.152 31592 31592 V AudioManager: querySoundEffectsEnabled...
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Decoding resources
Reading dex files
Merging integrations
Applying all patches
Executing 'locale-config-fix' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Executing 'resource-id-mapping-provider-resource-patch-dependency' of type: resource
Executing 'settings-resource-patch' of type: resource
Executing 'microg-resource-patch' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Skipping 'settings-resource-patch' because it has already been applied
Executing 'settings' of type: bytecode
Executing 'hide-cast-button' of type: bytecode
Executing 'client-spoof' of type: bytecode
Executing 'microg-support' of type: bytecode
[success] microg-support
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-V2dWGu86ByQl-O2msesSkg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3199355558181288158.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:212)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wccTULXVMEyc2aADBAF6-IxCNto(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:784)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-V2dWGu86ByQl-O2msesSkg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3199355558181288158.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ADYKXN/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Can you try again with 0.0.22 and share results?

**Comment by Priw8** [comment]
0.0.22 results in the same behaviour; however, I took at look at the [prerequisites](https://github.com/revanced/revanced-manager#prerequisites) and realized I'm running armv7, which is not supported. If this is the expected error in such cases, I suppose the issue can be closed - sorry for the trouble!

**Comment by MohamedRef** [comment]
I have the same error on armv7 
So that means we can't use revanced on all armv7 devices? 
Is there an intention to give support to it in the future or not?

**Comment by Priw8** [comment]
> I have the same error on armv7
So that means we can't use revanced on all armv7 devices?
Is there an intention to give support to it in the future or not?

Well, it's just the manager that needs it - revanced itself works fine if you patch yt with revanced-cli (or get someone else to send you the apk, I suppose)

**Comment by MohamedRef** [comment]
> send

I thought i have deleted the comment because i already knew the answer.. 
J 

I used cli before and worked well . I will depend on that for now thanks .
