### ISSUE TITLE
Patcher aborting

### ISSUE THREAD

**Issue by UnkreativerNutzername** [revanced/revanced-manager#302]
### Type

Error while running the manager

### Bug description

Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborting
Error:
kotlin.io.NoSuchFileException: /data/local/tmp/revanced-manager/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:125)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wccTULXVMEyc2aADBAF6-IxCNto(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)

### Steps to reproduce

1. Downloaded the recommended youtube APK
2. Open the Manager
3. Select the right APK
4. Choose the patches
5. Let the patcher do its job

### Android version

13

### Manager version

0.0.24

### Target package name

YouTube

### Target package version.

17.36.37

### Installation type

Root

### Patches selected.

All except App debugging and MicroG

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborting
Error:
kotlin.io.NoSuchFileException: /data/local/tmp/revanced-manager/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:125)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wccTULXVMEyc2aADBAF6-IxCNto(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborting
Error:
kotlin.io.NoSuchFileException: /data/local/tmp/revanced-manager/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:125)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wccTULXVMEyc2aADBAF6-IxCNto(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

![Screenshot_20220926-000216](https://user-images.githubusercontent.com/103318149/192167547-e9a9a4c9-1f76-41fd-9e81-5fd4f30eda06.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Install YouTube (same version you are trying to patch) and try again.

**Comment by blusiu** [comment]
> Install YouTube (same version you are trying to patch) and try again.
![Screenshot_20220926-183341](https://user-images.githubusercontent.com/113230987/192230949-05664377-b079-4a9f-8bc7-1d4a75bf000a.png)
![Screenshot_20220926-183333](https://user-images.githubusercontent.com/113230987/192230955-7cf367ca-338d-4131-a4f5-d2c18e30a70c.png)

im having the same issue, would you mind elaborating?

**Comment by tryigit** [comment]
The problem continues on reddit.

![Screenshot_2022-09-27-01-18-25-143_app.revanced.manager.flutter.jpg](https://user-images.githubusercontent.com/40565628/192390545-3c912f7a-b5bb-400a-be1b-7f16292cdbf5.jpg)

**Comment by Hebgbs** [comment]
I could have almost every patch selected and it'd build successfully but once I add MicroG it fails.

**Comment by Aunali321** [comment]
Don't include microg for root. It's only for nonroot.

**Comment by derandiunddasbo** [comment]
I had the same error after messing with downgrading YouTube with Titanium Backup after the Play Store auto update (which I forgot to disable, after patching) installed an unpatched update.

I resolved it by deleting the /data/local/tmp/revanced-manager/ folder with a file manager. After that the patcher worked fine again.

Disclaimer: I'm not sure if root access is needed to delete this folder, so your mileage may vary. 🙂

**Comment by ryan7zoom** [comment]
I solved it by going inside data/adb/revanced and deleting both apks. One of them was base.apk and the other was original.apk.
Then the manager was able to patch again.
