### ISSUE TITLE
Aborting

### ISSUE THREAD

**Issue by hgunduz295** [revanced/revanced-manager#331]
### Type

Error while running the manager

### Bug description

![Screenshot_20220929-220152](https://user-images.githubusercontent.com/36344949/193119807-30c68137-e5f9-4d64-8405-e49b4a47a835.jpg)
Log file is here
https://www18.zippyshare.com/v/ejDBhCLi/file.html

### Steps to reproduce

Patching step

### Android version

12

### Manager version

26

### Target package name

Youtube

### Target package version.

17.38.35

### Installation type

Root

### Patches selected.

General ads, minimized playback ,video ads,sponsorblock,return youtube dislike

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Decoding resources
Reading dex files
Merging integrations
Applying all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Executing 'general-ads' of type: bytecode
[error] general-ads:app.revanced.patcher.patch.PatchResultError: length=19; index=-1
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
[success] downloads
Skipping 'locale-config-fix' because it has already been applied
Executing 'custom-branding' of type: resource
[success] custom-branding
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'old-quality-layout' of type: bytecode
[success] old-quality-layout
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
[success] return-youtube-dislike
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
[error] sponsorblock:app.revanced.patcher.patch.PatchResultError
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
[success] theme
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watermark' of type: bytecode
[success] hide-watermark
Executing 'client-spoof' of type: bytecode
[success] client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
[success] minimized-playback
Skipping 'settings' because it has already been applied
[success] settings
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~_u5ZqRRf-UpVh3EKRRfhpw==/app.revanced.manager.flutter-pRexI56NybCBpqT8bQAnVA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:212)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wccTULXVMEyc2aADBAF6-IxCNto(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~_u5ZqRRf-UpVh3EKRRfhpw==/app.revanced.manager.flutter-pRexI56NybCBpqT8bQAnVA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Decoding resources
Reading dex files
Merging integrations
Applying all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Executing 'general-ads' of type: bytecode
[error] general-ads:app.revanced.patcher.patch.PatchResultError: length=19; index=-1
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
[success] downloads
Skipping 'locale-config-fix' because it has already been applied
Executing 'custom-branding' of type: resource
[success] custom-branding
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'old-quality-layout' of type: bytecode
[success] old-quality-layout
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
[success] return-youtube-dislike
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
[error] sponsorblock:app.revanced.patcher.patch.PatchResultError
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
[success] theme
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watermark' of type: bytecode
[success] hide-watermark
Executing 'client-spoof' of type: bytecode
[success] client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
[success] minimized-playback
Skipping 'settings' because it has already been applied
[success] settings
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~_u5ZqRRf-UpVh3EKRRfhpw==/app.revanced.manager.flutter-pRexI56NybCBpqT8bQAnVA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:212)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wccTULXVMEyc2aADBAF6-IxCNto(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~_u5ZqRRf-UpVh3EKRRfhpw==/app.revanced.manager.flutter-pRexI56NybCBpqT8bQAnVA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DQEOTX/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Screenshots or videos

![Screenshot_20220929-220152](https://user-images.githubusercontent.com/36344949/193120786-bbd74cc8-e390-4742-b137-15b359cdad3a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Uninstall youtube (uninstall updates if you can't).
Download full recommended yt apk from apkmirror (17.36.37)(120mb+)
Install it.
Select it from applications list.
Exclude microg patch for root.
Click Install as Root after its done patching.

**Comment by FieryMewtwo** [comment]
Having this same issue with YT Music (using the recommended version)

**Comment by Jstanford5216** [comment]
Also having this with YouTube for 17.36.37 even after reinstalling and clearing everything

**Comment by Aunali321** [comment]
Should be fixed in latest version.

**Comment by hgunduz295** [comment]
![Screenshot_20221005-172318](https://user-images.githubusercontent.com/36344949/194085171-c47596f7-7514-415b-924a-65cf5fc3e139.jpg)
Maybe  problem is here  decoding because in this ss it says no need  decoding resources but  it did resources  after  merging integrations

**Comment by Aurobindoji** [comment]
Same problem while patching Reddit 
Stuck at "writing modified Dex files"
After few minutes....
"Aborting..."

**Comment by Alprnn357** [comment]
> Having this same issue with YT Music (using the recommended version)

I'm also having same issue with YT Music Recommended version.
@hgunduz295 Which architecture your os run with? armv7 or armv8?

**Comment by hgunduz295** [comment]
Armv8

**Comment by hgunduz295** [comment]
Even  17.36.37 have  abort problem with latest revanced manager

**Comment by fozter** [comment]
Getting the same results.
Running 0.32, yt 17.36.36 full apk and rooted.
reisxd's builder still works tho.

**Comment by Aurobindoji** [comment]
![Screenshot_2022-10-18-21-41-45-489_app revanced manager flutter](https://user-images.githubusercontent.com/114210081/196485676-959d434c-3d7e-4471-88cc-0e98970b81dd.jpg)
Latest build 0.0.34

**Comment by Ushie** [comment]
Why was this closed? has it stopped Aborting?

**Comment by Aurobindoji** [comment]
![Screenshot_2022-10-23-10-16-56-218_app revanced manager flutter](https://user-images.githubusercontent.com/114210081/197374327-62b6935b-0972-4824-9405-1e34ed34ca56.jpg)
Problem still persists
V0.0.36

**Comment by Aurobindoji** [comment]
Latest manager build 0.0.39
Aborting while patching Reddit apk from apkmirror
MIUI 12.5
REDMI 8A dual

Log --

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Executing all patches
Executing 'general-reddit-ads' of type: bytecode
Applied general-reddit-ads
Executing 'premium-icon-reddit' of type: bytecode
Applied premium-icon-reddit
Repacking patched apk
Not compiling resources because resource patching is not required
Creating new dex file
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.OutOfMemoryError: Failed to allocate a 9508512 byte allocation with 9475984 free bytes and 9253KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3161)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
