### ISSUE TITLE
bug: cannot select installed app

### ISSUE THREAD

**Issue by mohamedamrnady** [revanced/revanced-manager#341]
### Type

Other

### Bug description

Cannot select an installed app or use patches when select an external apk

### Steps to reproduce

Run the app, go to patcher section, go to select application, no apps there, click storage and choose an apk, no available patches for apk

### Android version

13 arm64_v8a

### Manager version

0.0.28

### Target package name

Twitter (com.twitter.android)

### Target package version.

9.63.0-alpha.7

### Installation type

Non-root

### Patches selected.

None

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
10-01 22:08:28.416 31034 31034 W PackageParser: Failed to parse /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.twitter.android_9.63.0-alpha.7-29630207_1arch_2dpi_2lang_a80b818526f1c940d8756c915f1076f2_apkmirror.com.apkm
10-01 22:08:28.416 31034 31034 W PackageParser: java.io.FileNotFoundException: AndroidManifest.xml
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.res.ApkAssets.nativeOpenXml(Native Method)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.res.ApkAssets.openXml(ApkAssets.java:380)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1497)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1464)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:970)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1179)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1093)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8067)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8044)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at fr.g123k.deviceapps.DeviceAppsPlugin.getAppFromStorage(DeviceAppsPlugin.java:260)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at fr.g123k.deviceapps.DeviceAppsPlugin.onMethodCall(DeviceAppsPlugin.java:113)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.os.Handler.handleCallback(Handler.java:942)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.os.Looper.loopOnce(Looper.java:201)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.os.Looper.loop(Looper.java:288)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at android.app.ActivityThread.main(ActivityThread.java:7893)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-01 22:08:28.416 31034 31034 W PackageParser: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-01 22:09:01.414 31034 31034 W PackageParser: Failed to parse /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.twitter.android_9.63.0-alpha.7-29630207_1arch_2dpi_2lang_a80b818526f1c940d8756c915f1076f2_apkmirror.com.apkm
10-01 22:09:01.414 31034 31034 W PackageParser: java.io.FileNotFoundException: AndroidManifest.xml
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.res.ApkAssets.nativeOpenXml(Native Method)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.res.ApkAssets.openXml(ApkAssets.java:380)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1497)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1464)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:970)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1179)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1093)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8067)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8044)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at fr.g123k.deviceapps.DeviceAppsPlugin.getAppFromStorage(DeviceAppsPlugin.java:260)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at fr.g123k.deviceapps.DeviceAppsPlugin.onMethodCall(DeviceAppsPlugin.java:113)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.os.Handler.handleCallback(Handler.java:942)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.os.Looper.loopOnce(Looper.java:201)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.os.Looper.loop(Looper.java:288)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at android.app.ActivityThread.main(ActivityThread.java:7893)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-01 22:09:01.414 31034 31034 W PackageParser: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-01 22:09:41.571 31034 31034 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/base.apk Binary XML file line #80
--------- beginning of main
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=0
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=1
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=2
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=3
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=4
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=5
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=6
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=7
10-01 22:14:04.424 31034 31034 E SurfaceSyncer: Failed to find sync for id=8
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=0
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=1
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=2
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=3
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=4
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=5
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=6
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=7
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=8
10-01 22:14:41.540 31034 31034 E SurfaceSyncer: Failed to find sync for id=9
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
None
```

### Screenshots or videos

None

### Solution

Don't know

### Additional context

Manager was working fine on Android 12.1, then the issue appeared after updating a couple of weeks ago

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
It seems that Twitter Alpha and Beta releases only have Split APKs/Bundles (as seen in your logs, you're using .apkm which is a bundle), this isn't supported, you should select a release version instead and then select APK, not bundle, will show screenshots below 

![image](https://user-images.githubusercontent.com/79272171/193433976-96bd68b4-9215-467a-8891-6c4890e17284.png)
![image](https://user-images.githubusercontent.com/79272171/193433983-1219a261-73be-4047-af61-89325e2081f4.png)

**Comment by Aunali321** [comment]
Cannot find AndroidManifest.xml. You're using split apk. Use release build of Twitter and make sure it's full apk. (100mb+).

**Comment by mohamedamrnady** [comment]
Tried with 9.61.0-release.0 version and it didn't work too.

**Comment by mohamedamrnady** [comment]
> 

All permissions are granted.
