### ISSUE TITLE
Latest TikTok doesn't work

### ISSUE THREAD

**Issue by LorisTecnology** [revanced/revanced-manager#343]
### Type

Error while running the manager

### Bug description

When running the pathcher on the latest tik tok version (26.4.3) i got "aborting process" error

### Steps to reproduce

Install the latest tik tok
Select all patches on "revanced manager"

### Android version

ArrowOs Android 11

### Manager version

0.0.28

### Target package name

Tik Tok

### Target package version.

26.4.3

### Installation type

Root

### Patches selected.

All Avaible

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
10-02 19:54:44.799  8074  8074 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
10-02 19:54:44.801  8074  8074 W manager.flutte: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
10-02 19:54:44.838  8074  8074 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-02 19:54:44.838  8074  8074 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: QUALCOMM build                   : 2f950bf, I802c3b73eb
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: Build Date                       : 06/29/21
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.12
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: Local Branch                     : 
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: Remote Branch                    : 
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: Remote Branch                    : 
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: Reconstruct Branch               : 
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
10-02 19:54:44.930  8074  8074 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-02 19:54:44.932  8074  8074 E cutils-trace: Error opening trace file: No such file or directory (2)
10-02 19:54:44.958  8074  8074 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
10-02 19:54:44.998  8074  8074 I TetheringManager: registerTetheringEventCallback:app.revanced.manager.flutter
10-02 19:54:45.195  8074  8122 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
10-02 19:54:45.196  8074  8122 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-02 19:54:45.222  8074  8108 I flutter : dynamic_color: Dynamic color not detected on this device.
10-02 19:54:45.264  8074  8122 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
10-02 19:54:45.264  8074  8122 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-02 19:54:46.954  8074  8122 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
10-02 19:54:46.954  8074  8122 W SQLiteLog: (28) double-quoted string literal: "CCDCB2BDA20134936E659B1478EFB223"
10-02 19:54:47.287  8074  8122 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
10-02 19:54:47.287  8074  8122 W SQLiteLog: (28) double-quoted string literal: "0D8911B1DDFCA2090CB01B655AA2FF78"
10-02 19:54:47.413  8074  8122 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
10-02 19:54:47.413  8074  8122 W SQLiteLog: (28) double-quoted string literal: "BEF3EFF191D42CA764117E8164896420"
10-02 19:54:47.619  8074  8122 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
10-02 19:54:47.619  8074  8122 W SQLiteLog: (28) double-quoted string literal: "9B5A5A56452E8D8BC631FBF6F9537EBB"
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborting
Error:
kotlin.io.NoSuchFileException: /data/local/tmp/revanced-manager/com.zhiliaoapp.musically/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:126)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Download recommend version from apkmirror. Make sure it's full apk and not bundle.

**Comment by LorisTecnology** [comment]
did that
issue fixed itself

**Comment by Yoylerozu** [comment]
> Download recommend version from apkmirror. Make sure it's full apk and not bundle.

What is the recommended version?
