### ISSUE TITLE
bug: Cant download pacthes

### ISSUE THREAD

**Issue by eugene32155500** [revanced/revanced-manager#356]
### Type

Other

### Bug description

can't download patches

### Steps to reproduce

idk

### Android version

12

### Manager version

0.0.28

### Target package name

spotify and TikTok 

### Target package version.

spotify: 8.7.36.923
tiktok: 26.2.3

### Installation type

Non-root

### Patches selected.

all pathces for spotify and tiktok

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
10-06 11:45:18.777 25803 25803 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
10-06 11:45:19.003 25803 25803 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
10-06 11:45:19.091 25803 25803 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=389ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=105ms seq=2 h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=279ms seq=3 h=android.app.ActivityThread$H w=159)
10-06 11:45:20.962 25803 25803 W Looper  : PerfMonitor doFrame : time=22ms vsyncFrame=0 latency=516ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=518ms seq=142 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=518ms seq=142 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-06 11:45:52.612 25803 25803 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 109ms
10-06 11:45:54.331 25803 25803 W Looper  : PerfMonitor doFrame : time=18ms vsyncFrame=0 latency=548ms procState=-1 historyMsgCount=4 (msgIndex=4 wall=524ms seq=366 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-06 11:48:21.682 28221 28221 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
10-06 11:48:21.798 28221 28221 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
10-06 11:48:22.504 28221 28221 W Looper  : PerfMonitor doFrame : time=8ms vsyncFrame=0 latency=388ms procState=-1 historyMsgCount=5
10-06 11:49:25.485 28221 28221 W Looper  : PerfMonitor longMsg : seq=379 plan=11:49:24.101 late=0ms wall=1382ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
10-06 11:49:27.102 28221 28221 W Looper  : PerfMonitor longMsg : seq=387 plan=11:49:25.534 late=22ms wall=1546ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
10-06 12:02:54.656  6908  6908 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
10-06 12:02:54.914  6908  6908 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
10-06 12:02:54.983  6908  6908 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=474ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=189ms seq=2 h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=278ms seq=3 h=android.app.ActivityThread$H w=159)
10-06 12:06:40.732 10013 10013 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
10-06 12:06:40.860 10013 10013 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
10-06 12:06:40.920 10013 10013 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=321ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=132ms seq=2 h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=175ms seq=3 h=android.app.ActivityThread$H w=159)
10-06 12:06:41.737 10013 10013 W Looper  : PerfMonitor doFrame : time=26ms vsyncFrame=0 latency=547ms procState=-1 historyMsgCount=3 (msgIndex=3 wall=370ms seq=43 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-06 12:09:24.119 10013 10013 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=310ms procState=-1 historyMsgCount=2
--------- beginning of main
10-06 12:33:05.448 19363 19363 D installd: Mismatched cache GID/mode at /data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/oat: found 20026/1472 but expected 10026/505
10-06 12:33:05.450 19363 19363 I installd: installd cannot open oat file during dexopt/data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/oat/arm64/ae7ea190-4553-11ed-b0f8-17cc09447f34.odex: No such file or directory
10-06 12:33:05.634 19363 19363 W dexoptanalyzer: Current thread not detached in Runtime shutdown
10-06 12:45:23.280 21722 21722 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
10-06 12:45:23.289 21722 21722 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
10-06 12:45:23.316 21722 21722 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10026; state: ENABLED
10-06 12:45:23.342 21722 21746 D AppScoutStateMachine: 21722-ScoutStateMachinecreated
10-06 12:45:23.401 21722 21722 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
10-06 12:45:23.401 21722 21722 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
10-06 12:45:23.403 21722 21722 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
10-06 12:45:23.405 21722 21722 D OpenGLRenderer: JNI_OnLoad success
10-06 12:45:23.405 21722 21722 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
10-06 12:45:23.405 21722 21722 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-06 12:45:23.405 21722 21722 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-06 12:45:23.432 21722 21765 D libMEOW : meow new tls: 0xb40000746669a100
10-06 12:45:23.434 21722 21765 D libMEOW : meow reload base cfg path: na
10-06 12:45:23.434 21722 21765 D libMEOW : meow reload overlay cfg path: na
10-06 12:45:23.434 21722 21765 W QT      : qt_process_init() called
10-06 12:45:23.434 21722 21765 E QT      : [QT]file does not exist
10-06 12:45:23.434 21722 21765 W QT      : Support!!
10-06 12:45:23.435 21722 21765 E QT      : [QT]file does not exist
10-06 12:45:23.435 21722 21765 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
10-06 12:45:23.435 21722 21765 D libMEOW :   plugin 1: [libMEOW_gift.so]:
10-06 12:45:23.436 21722 21765 D libMEOW : meow delete tls: 0xb40000746669a100
10-06 12:45:23.535 21722 21722 W manager.flutter: type=1400 audit(0.0:27648): avc: denied { read } for name="max_map_count" dev="proc" ino=1122349 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
10-06 12:45:23.551 21722 21722 D libMEOW : meow new tls: 0xb4000073e45de900
10-06 12:45:23.551 21722 21722 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
10-06 12:45:23.551 21722 21722 D libMEOW :   plugin 1: [libMEOW_gift.so]:
10-06 12:45:23.556 21722 21722 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
10-06 12:45:23.569 21722 21783 D libMEOW : meow new tls: 0xb4000073d7df2840
10-06 12:45:23.569 21722 21783 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
10-06 12:45:23.569 21722 21783 D libMEOW :   plugin 1: [libMEOW_gift.so]:
10-06 12:45:23.583 21722 21722 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
10-06 12:45:23.586 21722 21722 I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@5e63b98
10-06 12:45:23.596 21722 21722 D IS_CTS_MODE: false
10-06 12:45:23.596 21722 21722 D MULTI_WINDOW_SWITCH_ENABLED: false
10-06 12:45:23.596 21722 21722 D IS_CTS_MODE: false
10-06 12:45:23.596 21722 21722 D MULTI_WINDOW_SWITCH_ENABLED: false
10-06 12:45:23.596 21722 21722 D IS_CTS_MODE: false
10-06 12:45:23.597 21722 21722 D MULTI_WINDOW_SWITCH_ENABLED: false
10-06 12:45:23.610 21722 21722 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-06 12:45:23.643 21722 21722 D ViewRootImpl[MainActivity]: hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
10-06 12:45:23.644 21722 21722 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-06 12:45:23.644 21722 21722 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
10-06 12:45:23.657 21722 21722 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=344ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=103ms seq=2 h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=237ms seq=3 h=android.app.ActivityThread$H w=159)
10-06 12:45:23.691 21722 21722 I BufferQueueConsumer: [](id:54da00000000,api:0,p:-1,c:21722) connect: controlledByApp=false
10-06 12:45:23.696 21722 21722 I BLASTBufferQueue: [ViewRootImpl[MainActivity]#0] constructor()
10-06 12:45:23.697 21722 21761 D libMEOW : meow new tls: 0xb4000073d7ff6500
10-06 12:45:23.697 21722 21761 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
10-06 12:45:23.697 21722 21761 D libMEOW :   plugin 1: [libMEOW_gift.so]:
10-06 12:45:23.700 21722 21722 D SurfaceView: UPDATE null, mIsCastMode = false
10-06 12:45:23.701 21722 21722 I BufferQueueConsumer: [](id:54da00000001,api:0,p:-1,c:21722) connect: controlledByApp=false
10-06 12:45:23.702 21722 21722 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1] constructor()
10-06 12:45:23.703 21722 21782 D libMEOW : meow new tls: 0xb400007466780b80
10-06 12:45:23.703 21722 21782 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
10-06 12:45:23.703 21722 21782 D libMEOW :   plugin 1: [libMEOW_gift.so]:
10-06 12:45:23.704 21722 21782 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:54da00000001,api:1,p:21722,c:21722) connect: api=1 producerControlledByApp=true
10-06 12:45:23.714 21722 21722 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xfac03d4, mIsProjectionMode = false
10-06 12:45:23.714 21722 21722 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-06 12:45:23.715 21722 21722 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-06 12:45:23.715 21722 21722 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-06 12:45:23.724 21722 21761 I BufferQueueProducer: [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:54da00000000,api:1,p:21722,c:21722) connect: api=1 producerControlledByApp=true
10-06 12:45:24.042 21722 21857 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
10-06 12:45:24.042 21722 21857 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-06 12:45:24.080 21722 21781 I flutter : dynamic_color: Core palette detected.
10-06 12:45:24.137 21722 21722 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-06 12:45:24.137 21722 21722 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
10-06 12:45:24.141 21722 21782 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:54da00000001,api:1,p:21722,c:21722) disconnect: api 1
10-06 12:45:24.142 21722 21782 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:54da00000001,api:1,p:21722,c:21722) connect: api=1 producerControlledByApp=true
10-06 12:45:24.165 21722 21857 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
10-06 12:45:24.165 21722 21857 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-06 12:45:24.181 21722 21782 E ion     : ioctl c0044901 failed with code -1: Invalid argument
10-06 12:45:24.181 21722 21782 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
10-06 12:45:24.203 21925 21925 W sh      : type=1400 audit(0.0:27652): avc: denied { search } for name="mm" dev="sysfs" ino=7022 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-06 12:45:24.539 22094 22094 W ls      : type=1400 audit(0.0:27689): avc: denied { search } for name="mm" dev="sysfs" ino=7022 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-06 12:45:24.559 22083 22083 W sh      : type=1400 audit(0.0:27690): avc: denied { read } for name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-06 12:45:24.583 22110 22110 W sh      : type=1400 audit(0.0:27691): avc: denied { search } for name="mm" dev="sysfs" ino=7022 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-06 12:45:24.611 22120 22120 W ls      : type=1400 audit(0.0:27693): avc: denied { search } for name="mm" dev="sysfs" ino=7022 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-06 12:45:24.877 21722 21722 I Choreographer: Skipped 61 frames!  The application may be doing too much work on its main thread.
10-06 12:45:24.893 21722 21761 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
10-06 12:45:24.893 21722 21761 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
10-06 12:45:24.894 21722 21761 I libPerfCtl: fbcNotifySwapBuffers ret=0
10-06 12:45:24.902 21722 21722 W Looper  : PerfMonitor doFrame : time=25ms vsyncFrame=0 latency=685ms procState=-1 historyMsgCount=2 (msgIndex=1 wall=687ms seq=70 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=687ms seq=70 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-06 12:45:24.910 21722 22238 I OpenGLRenderer: Davey! duration=705ms; Flags=1, FrameTimelineVsyncId=438207, IntendedVsync=4655381295690, Vsync=4656059073461, InputEventId=0, HandleInputStart=4656067093814, AnimationStart=4656067094507, PerformTraversalsStart=4656067095045, DrawStart=4656069520276, FrameDeadline=4655401295690, FrameInterval=4656066982122, FrameStartTime=11111111, SyncQueued=4656070057891, SyncStart=4656070133199, IssueDrawCommandsStart=4656071329276, SwapBuffers=4656082827430, FrameCompleted=4656086698507, DequeueBufferDuration=6398846, QueueBufferDuration=1047385, GpuCompleted=4656086589276, SwapBuffersCompleted=4656086698507, DisplayPresentTime=0, 
10-06 12:45:24.920 21722 21722 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-06 12:45:26.749 21722 22324 I incfs   : Initial API level of the device: 30
10-06 12:45:26.743 21722 21722 W pool-2-thread-1: type=1400 audit(0.0:27723): avc: denied { read } for name="u:object_r:incremental_prop:s0" dev="tmpfs" ino=9466 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:incremental_prop:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
10-06 12:45:26.749 21722 22324 W libc    : Access denied finding property "ro.incremental.enable"
10-06 12:45:26.749 21722 22324 I incfs   : ro.incremental.enable: 
10-06 12:45:26.750 21722 22324 I incfs   : IncFs_Features: v1
10-06 12:45:26.743 21722 21722 W pool-2-thread-1: type=1400 audit(0.0:27724): avc: denied { ioctl } for path="/data/app/~~1Qv76FQZA2kzFUb6o9HzCQ==/net.apex_designs.payback2-UDImwb53oJ28NORShH06Qw==/base.apk" dev="incremental-fs" ino=417357 ioctlcmd=0x6722 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
10-06 12:45:26.763 21722 21722 W pool-2-thread-1: type=1400 audit(0.0:27725): avc: denied { ioctl } for path="/data/app/~~1Qv76FQZA2kzFUb6o9HzCQ==/net.apex_designs.payback2-UDImwb53oJ28NORShH06Qw==/split_config.en.apk" dev="incremental-fs" ino=417988 ioctlcmd=0x6722 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
10-06 12:45:26.767 21722 21722 W pool-2-thread-1: type=1400 audit(0.0:27726): avc: denied { ioctl } for path="/data/app/~~1Qv76FQZA2kzFUb6o9HzCQ==/net.apex_designs.payback2-UDImwb53oJ28NORShH06Qw==/split_config.lt.apk" dev="incremental-fs" ino=417380 ioctlcmd=0x6722 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
10-06 12:45:26.767 21722 21722 W pool-2-thread-1: type=1400 audit(0.0:27727): avc: denied { ioctl } for path="/data/app/~~1Qv76FQZA2kzFUb6o9HzCQ==/net.apex_designs.payback2-UDImwb53oJ28NORShH06Qw==/split_config.ru.apk" dev="incremental-fs" ino=417734 ioctlcmd=0x6722 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
10-06 12:45:32.085 21722 21857 W SQLiteLog: (28) double-quoted string literal: "BCDEE9810724C1379F24A4212340CE97"
10-06 12:45:32.085 21722 21857 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-06 12:45:32.869 21722 21722 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=4664050, downTime=4664050, deviceId=-1, source=0x101, displayId=0 }
10-06 12:45:32.880 21722 21722 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=4664050, downTime=4664050, deviceId=-1, source=0x101, displayId=0 }
10-06 12:46:20.178 21722 21722 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-06 12:46:20.744 21722 21782 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:54da00000001,api:1,p:21722,c:21722) disconnect: api 1
10-06 12:46:20.746 21722 21722 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:54da00000001,api:0,p:-1,c:21722) disconnect: api -1
10-06 12:46:20.751 21722 21761 I BufferQueueProducer: [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:54da00000000,api:1,p:21722,c:21722) disconnect: api 1
10-06 12:46:20.751 21722 21761 I BLASTBufferQueue: [ViewRootImpl[MainActivity]#0] destructor()
10-06 12:46:20.751 21722 21761 I BufferQueueConsumer: [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:54da00000000,api:0,p:-1,c:21722) disconnect
10-06 12:46:20.768 21722 21997 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:93295279603714 framenumber:1 blastBufferQueue is dead
10-06 12:47:49.761 21722 21743 D AppScoutStateMachine: 21722-ScoutStateMachinecreated
10-06 12:47:49.794 21722 21722 I BufferQueueConsumer: [](id:54da00000002,api:0,p:-1,c:21722) connect: controlledByApp=false
10-06 12:47:49.795 21722 21722 I BLASTBufferQueue: [ViewRootImpl[MainActivity]#2] constructor()
10-06 12:47:49.796 21722 21761 I BufferQueueProducer: [ViewRootImpl[MainActivity]#2(BLAST Consumer)2](id:54da00000002,api:1,p:21722,c:21722) connect: api=1 producerControlledByApp=true
10-06 12:47:49.797 21722 21722 I BufferQueueConsumer: [](id:54da00000003,api:0,p:-1,c:21722) connect: controlledByApp=false
10-06 12:47:49.798 21722 21722 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#3] constructor()
10-06 12:47:49.799 21722 21782 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1] destructor()
10-06 12:47:49.799 21722 21782 I BufferQueueConsumer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:54da00000001,api:0,p:-1,c:21722) disconnect
10-06 12:47:49.801 21722 21782 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#3(BLAST Consumer)3](id:54da00000003,api:1,p:21722,c:21722) connect: api=1 producerControlledByApp=true
10-06 12:47:49.804 21722 21722 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x9270ba7, mIsProjectionMode = false
10-06 12:47:49.804 21722 21722 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-06 12:47:49.805 21722 21722 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-06 12:47:49.805 21722 21722 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-06 12:47:49.810 21722 21743 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:93295279603712 framenumber:946 blastBufferQueue is dead
10-06 12:47:49.814 21722 21761 I libPerfCtl: fbcNotifySwapBuffers ret=0
10-06 12:47:49.823 21722 21722 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-06 12:47:49.824 21722 21743 I OpenGLRenderer: Davey! duration=145625ms; Flags=1, FrameTimelineVsyncId=438207, IntendedVsync=4655381295690, Vsync=4656059073461, InputEventId=0, HandleInputStart=4656067093814, AnimationStart=4656067094507, PerformTraversalsStart=4656067095045, DrawStart=4656069520276, FrameDeadline=4655412406801, FrameInterval=4656066982122, FrameStartTime=11111111, SyncQueued=4656070057891, SyncStart=4656070133199, IssueDrawCommandsStart=4656071329276, SwapBuffers=4656082827430, FrameCompleted=4801007340669, DequeueBufferDuration=6398846, QueueBufferDuration=1047385, GpuCompleted=4801007340669, SwapBuffersCompleted=4656086698507, DisplayPresentTime=0, 
10-06 12:47:51.843 23982 23982 W logcat  : type=1400 audit(0.0:27903): avc: denied { search } for name="mm" dev="sysfs" ino=7022 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-06 12:47:52.905 21722 21722 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-06 12:48:17.611 21722 21722 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-06 12:48:17.703 21722 21761 I libPerfCtl: fbcNotifySwapBuffers ret=0
10-06 12:48:37.659 24669 24669 W logcat  : type=1400 audit(0.0:27925): avc: denied { search } for name="mm" dev="sysfs" ino=7022 scontext=u:r:untrusted_app:s0:c26,c256,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
tiktok:

Initializing installer
Creating working directory
An error occurred! Aborting
Error:
java.lang.ClassNotFoundException: Didn't find class "app.revanced.patches.ecmwf.misc.subscription.patch.SubscriptionUnlockPatch" on path: DexPathList[[zip file "/data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/ae7ea190-4553-11ed-b0f8-17cc09447f34.bin"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:13)
	at app.revanced.patcher.util.patch.impl.DexPatchBundle.loadPatches(DexPatchBundle.kt:13)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:111)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/patcher/patch/BytecodePatch;
		at java.lang.VMClassLoader.findLoadedClass(Native Method)
		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
		... 7 more
	Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.BytecodePatch
		... 10 more
  Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.BytecodePatch
		... 10 more
spotify:
Initializing installer
Creating working directory
An error occurred! Aborting
Error:
java.lang.ClassNotFoundException: Didn't find class "app.revanced.patches.ecmwf.misc.subscription.patch.SubscriptionUnlockPatch" on path: DexPathList[[zip file "/data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/ae7ea190-4553-11ed-b0f8-17cc09447f34.bin"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:13)
	at app.revanced.patcher.util.patch.impl.DexPatchBundle.loadPatches(DexPatchBundle.kt:13)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:111)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/patcher/patch/BytecodePatch;
		at java.lang.VMClassLoader.findLoadedClass(Native Method)
		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
		... 7 more
	Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.BytecodePatch
		... 10 more
```

### Screenshots or videos

.

### Solution

idk

### Additional context

no

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Fixed in 0.0.29.
