### ISSUE TITLE
Aborting while patching

### ISSUE THREAD

**Issue by NyxNoirXD** [ReVanced/revanced-manager#359]
### Type

Error while running the manager

### Bug description

Can't patch YouTube application - aboarting with errors

### Steps to reproduce

Select recommend YouTube applications and patch.

### Android version

10

### Manager version

Version 0.0.28

### Target package name

com.google.android.youtube

### Target package version.

V17.36.37

### Installation type

Root

### Patches selected.

![Screenshot_2022-10-06-20-02-53-15](https://user-images.githubusercontent.com/88641063/194344595-26f9b327-b342-4a3b-8549-85c237157355.jpg)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
10-06 20:20:36.841  8271  8271 W manager.flutter: type=1400 audit(0.0:29339): avc: denied { read } for name="max_map_count" dev="proc" ino=8398757 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
10-06 20:20:38.393  8396  8396 W sh      : type=1400 audit(0.0:29341): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:20:38.413  8396  8396 W sh      : type=1400 audit(0.0:29342): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:20:38.429  8396  8396 W sh      : type=1400 audit(0.0:29343): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:20:38.445  8396  8396 W sh      : type=1400 audit(0.0:29344): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:21:15.713  8396  8396 W sh      : type=1400 audit(0.0:29361): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:21:15.749  8396  8396 W sh      : type=1400 audit(0.0:29362): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:21:15.797  8396  8396 W sh      : type=1400 audit(0.0:29363): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:21:15.841  8396  8396 W sh      : type=1400 audit(0.0:29364): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
10-06 20:21:15.861  8396  8396 W sh      : type=1400 audit(0.0:29365): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
An error occurred! Aborting
Error:
java.lang.ClassNotFoundException: Didn't find class "app.revanced.patches.ecmwf.misc.subscription.patch.SubscriptionUnlockPatch" on path: DexPathList[[zip file "/data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/92d39170-4581-11ed-93ea-97f77ef95b5e.bin"],nativeLibraryDirectories=[/system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:13)
	at app.revanced.patcher.util.patch.impl.DexPatchBundle.loadPatches(DexPatchBundle.kt:13)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:111)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/patcher/patch/BytecodePatch;
		at java.lang.VMClassLoader.findLoadedClass(Native Method)
		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
		... 7 more
	Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.BytecodePatch
		... 10 more
```

### Screenshots or videos

![IMG_20221006_200458](https://user-images.githubusercontent.com/88641063/194346586-1324ca49-a617-4c24-9f82-bdbea70186a4.jpg)
![IMG_20221006_200419](https://user-images.githubusercontent.com/88641063/194346624-d8cb259f-ce53-4226-a239-58ccc3ad4d23.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by smgchosen** [comment]
Hi. Exactly same problem since one week and only with YouTube. 0.30, 0.31, 0.32 same result. 
![Screenshot_20221013_163212](https://user-images.githubusercontent.com/55053403/195625638-b6b54c3b-94b9-40a6-809c-f302d8681d56.jpg)
