### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by tryigit** [revanced/revanced-manager#368]
### Type

Other

### Bug description

As far as I've tried on twitter and tiktok app, there are signature conflict errors.
There is no problem with the 2nd Package name version in Tiktok.

### Steps to reproduce

1- Create RE apk file.
2- Try to install without root by any method.

### Android version

12

### Manager version

0.0.29

### Target package name

com.zhiliaoapp.musically
com.twitter.android

### Target package version.

26.3.4
9.62.0

### Installation type

Non-root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
Its in the image
```

### Screenshots or videos

![Screenshot_2022-10-07-23-14-23-894_io github muntashirakon AppManager-edit](https://user-images.githubusercontent.com/40565628/194646484-4e2b65a8-911e-4cd1-9d0c-47dad0e200d7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Image says it. Delete orginal tiktok before installing patched apk.

**Comment by tryigit** [comment]
> Image says it. Delete orginal tiktok before installing patched apk.

but what if I already have signature verification turned off on my phone and won't get any updates automatically? Is it not a problem to constantly log in and adjust?

**Comment by tryigit** [comment]
> Image says it. Delete orginal tiktok before installing patched apk.

I also tried the method you said and the application does not open.

Log:
com.bytedance.librarian.LibrarianUnsatisfiedLinkError: can not ensure abi for libflipped.so, check arm64, apks [/data/app/~~ltIhfTIl0R8KShJjfdDEyw==/com.zhiliaoapp.musically-LKDuZFUZKYF-872PxATTug==/base.apk#8295:52789780|]
	at com.bytedance.librarian.LibrarianImpl.LIZLLL(SourceFile:17105001)
	at com.bytedance.librarian.LibrarianImpl.LIZLLL(SourceFile:17170441)
	at com.bytedance.librarian.LibrarianImpl.LIZ(SourceFile:33882132)
	at com.bytedance.librarian.LibrarianImpl.LIZ(SourceFile:50528274)
	at com.bytedance.librarian.LibrarianImpl.LIZIZ(SourceFile:33947696)
	at com.bytedance.librarian.LibrarianImpl.LIZ(SourceFile:34144304)
	at com.bytedance.librarian.Librarian.LIZ(SourceFile:50659349)
	at com.bytedance.librarian.Librarian.LIZ(SourceFile:16842754)
	at com.bytedance.mira.plugin.hook.flipped.compat.FlippedV2Impl.<clinit>(SourceFile:196620)
	at X.9RI.LIZ(SourceFile:262162)
	at X.QNT.LIZ(SourceFile:17301530)
	at com.ss.android.ugc.aweme.app.host.AwemeHostApplication.attachBaseContext(SourceFile:17039381)
	at android.app.Application.attach(Application.java:349)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1201)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1382)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7090)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
