### ISSUE TITLE
Error during compiling resources

### ISSUE THREAD

**Issue by Loup-Garou911XD** [revanced/revanced-manager#380]
### Type

Error at runtime

### Bug description

When selected all patches excluding microG support,patching fails while compiling resources

### Steps to reproduce

Step 1:Select app in the patcher tab
Step 2:Select all patches
Step 3:Deselect microG
Step 4:Click Patch

### Android version

Android 10 MiUi 12.0.19

### Manager version

Version: 0.0.30
Android Version: 10
Arch: armeabi-v7a

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Root

### Patches selected.

All except microG

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
10-10 01:12:48.976 28376 28376 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 605ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 228ms (seq=2 running=154ms io=56ms late=8ms h=android.app.ActivityThread$H w=110), msg 3 took 372ms (seq=3 running=195ms runnable=3ms io=30ms late=232ms h=android.app.ActivityThread$H w=159)
10-10 01:12:50.675 28376 28376 W Looper  : Slow Looper main: doFrame is 384ms late because of 2 msg, msg 1 took 387ms (seq=102 running=11ms late=4ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-10 01:13:05.361 28376 28376 W Looper  : Slow Looper main: Long Msg: seq=112 plan=01:12:50.632  late=220ms wall=14509ms running=4ms io=2ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
10-10 01:13:05.362 28376 28376 W Looper  : Slow Looper main: MotionEvent is 13054ms late (event_seq=0, action=ACTION_DOWN) because of 1 msg, msg 1 took 14509ms (seq=112 running=4ms io=2ms late=220ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-10 01:13:05.362 28376 28376 W InputEventReceiver: App Input: 13054ms before dispatchInputEvent (MotionEvent: event_seq=0, seq=59555, action=ACTION_DOWN)
10-10 01:13:05.368 28376 28376 W InputEventReceiver: App Input: 12987ms before dispatchInputEvent (MotionEvent: event_seq=2, seq=59561, action=ACTION_UP)
10-10 01:13:05.412 28376 28376 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 12863ms late (wall=1ms running=1ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 7 msg, msg 1 took 14509ms (seq=112 running=4ms io=2ms late=220ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-10 01:13:05.418 28376 28376 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 12855ms late (wall=6ms running=2ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.PauseActivityItem }) because of 8 msg, msg 1 took 14509ms (seq=112 running=4ms io=2ms late=220ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-10 01:13:05.434 28376 28376 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 10774ms late (wall=11ms running=4ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.StopActivityItem }) because of 13 msg, msg 1 took 14509ms (seq=112 running=4ms io=2ms late=220ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-10 01:13:05.442 28376 28376 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 6278ms late (wall=4ms running=3ms ClientTransaction{ callbacks=[android.app.servertransaction.WindowVisibilityItem] }) because of 24 msg, msg 1 took 14509ms (seq=112 running=4ms io=2ms late=220ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-10 01:13:05.449 28376 28376 I Timeline: Timeline: Activity_launch_request time:2399783
10-10 01:13:25.669 28376 28376 I Timeline: Timeline: Activity_launch_request time:2420003
10-10 01:19:29.239 31478 31478 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 526ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 223ms (seq=2 running=163ms runnable=1ms io=42ms late=7ms h=android.app.ActivityThread$H w=110), msg 3 took 300ms (seq=3 running=144ms runnable=1ms io=46ms late=226ms h=android.app.ActivityThread$H w=159)
10-10 01:54:10.059 31478 31478 W Looper  : Slow Looper main: doFrame is 316ms late because of 1 msg, msg 1 took 315ms (seq=1020 running=5ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-10 02:15:44.310  9953  9953 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 609ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 209ms (seq=2 running=160ms runnable=2ms io=29ms late=5ms h=android.app.ActivityThread$H w=110), msg 3 took 396ms (seq=3 running=166ms runnable=2ms io=99ms late=212ms h=android.app.ActivityThread$H w=159)
10-10 02:30:24.926 12503 12503 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 483ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 181ms (seq=2 running=156ms runnable=1ms io=8ms late=7ms h=android.app.ActivityThread$H w=110), msg 3 took 300ms (seq=3 running=157ms runnable=1ms io=60ms reclaim=1ms late=183ms h=android.app.ActivityThread$H w=159)
10-10 02:41:40.798 13868 13868 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 495ms late (wall=1ms running=1ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 190ms (seq=2 running=158ms runnable=2ms io=14ms late=8ms h=android.app.ActivityThread$H w=110), msg 3 took 302ms (seq=3 running=153ms runnable=1ms io=55ms late=194ms h=android.app.ActivityThread$H w=159)
10-10 02:53:28.404 16877 16877 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 335ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 2 msg, msg 1 took 171ms (seq=2 running=150ms runnable=2ms io=7ms late=7ms h=android.app.ActivityThread$H w=110), msg 2 took 285ms (seq=3 running=148ms io=41ms reclaim=2ms late=50ms h=android.app.ActivityThread$H w=159)
10-10 11:24:03.978  5693  5693 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 549ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 219ms (seq=2 running=165ms runnable=1ms io=38ms late=7ms h=android.app.ActivityThread$H w=110), msg 3 took 325ms (seq=3 running=169ms runnable=1ms io=49ms reclaim=1ms late=223ms h=android.app.ActivityThread$H w=159)
10-10 12:03:50.280 13078 13078 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 437ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 200ms (seq=2 running=157ms io=28ms late=7ms h=android.app.ActivityThread$H w=110), msg 3 took 234ms (seq=3 running=151ms runnable=1ms io=15ms late=203ms h=android.app.ActivityThread$H w=159)
10-10 12:51:07.891 17535 17535 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 583ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 232ms (seq=2 running=173ms runnable=1ms io=42ms late=10ms h=android.app.ActivityThread$H w=110), msg 3 took 346ms (seq=3 running=155ms runnable=2ms io=78ms late=237ms h=android.app.ActivityThread$H w=159)
10-10 12:51:16.349 17535 17535 I Timeline: Timeline: Activity_launch_request time:31309952
10-10 13:04:03.495 17535 17535 I Timeline: Timeline: Activity_launch_request time:32077098
--------- beginning of main
10-10 13:04:40.284 17535 17535 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@8561212, this = DecorView@2135de3[MainActivity]
10-10 13:04:40.298 17535 17555 D Surface : Surface::connect(this=0xdb15b800,api=1)
10-10 13:04:40.301 17535 17555 D Surface : Surface::setBufferCount(this=0xdb15b800,bufferCount=3)
10-10 13:04:40.313 17535 17561 D Surface : Surface::connect(this=0xdb49f800,api=1)
10-10 13:04:40.321 17535 17535 D ViewRootImpl: setSurfaceViewCreated, created:true
10-10 13:04:41.312 17535 17535 D ViewRootImpl: [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=32114898, downTime=32114898, deviceId=-1, source=0x101, displayId=-1 }
10-10 13:04:41.318 17535 17535 D ViewRootImpl: [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=32114898, downTime=32114898, deviceId=-1, source=0x101, displayId=-1 }
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Executing 'general-ads' of type: bytecode
[success] general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-infocard-suggestions' of type: bytecode
[success] hide-infocard-suggestions
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
[success] downloads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'seekbar-tapping' of type: bytecode
[success] seekbar-tapping
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'player-type-hook' of type: bytecode
Skipping 'settings' because it has already been applied
Executing 'swipe-controls-resource-patch' of type: resource
Executing 'swipe-controls' of type: bytecode
[success] swipe-controls
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-auto-captions' of type: bytecode
[success] disable-auto-captions
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'hide-autoplay-button' of type: bytecode
[success] hide-autoplay-button
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
[success] premium-heading
Skipping 'locale-config-fix' because it has already been applied
Executing 'custom-branding' of type: resource
[success] custom-branding
Skipping 'resource-mapping' because it has already been applied
Skipping 'general-ads' because it has already been applied
Executing 'hide-video-buttons' of type: resource
[success] hide-video-buttons
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-cast-button' of type: bytecode
[success] hide-cast-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-fullscreen-panels' of type: bytecode
[success] disable-fullscreen-panels
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-time-and-seekbar' of type: bytecode
[success] hide-time-and-seekbar
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'old-quality-layout' of type: bytecode
[success] old-quality-layout
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'hide-email-address' of type: bytecode
[success] hide-email-address
Skipping 'integrations' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-create-button' of type: bytecode
[success] hide-create-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-shorts-button' of type: bytecode
[success] hide-shorts-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-auto-player-popup-panels' of type: bytecode
[success] disable-auto-player-popup-panels
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
[success] return-youtube-dislike
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
[success] sponsorblock
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-startup-shorts-player' of type: bytecode
[success] disable-startup-shorts-player
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'tablet-mini-player' of type: bytecode
[success] tablet-mini-player
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
[success] theme
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watermark' of type: bytecode
[success] hide-watermark
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'enable-wide-searchbar' of type: bytecode
[success] enable-wide-searchbar
Skipping 'integrations' because it has already been applied
Executing 'always-autorepeat' of type: bytecode
[success] always-autorepeat
Executing 'client-spoof' of type: bytecode
[success] client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'custom-playback-speed' of type: bytecode
[success] custom-playback-speed
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'enable-debugging' of type: resource
[success] enable-debugging
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hdr-auto-brightness' of type: bytecode
[success] hdr-auto-brightness
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
[success] minimized-playback
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'remember-video-quality' of type: bytecode
[success] remember-video-quality
Skipping 'settings' because it has already been applied
[success] settings
Skipping 'settings' because it has already been applied
Executing 'custom-video-buffer' of type: bytecode
[success] custom-video-buffer
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-_fVOwk7GeRPdGjFrRJ2M3w==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7558081598257033432.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:149)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-_fVOwk7GeRPdGjFrRJ2M3w==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7558081598257033432.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FKNPXK/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Armv7 is not supported yet as mentioned in readme.
