### ISSUE TITLE
bug: Crash after 5-10 minutes of minimized playback 

### ISSUE THREAD

**Issue by angousana** [revanced/revanced-manager#397]
### Type

Other

### Bug description

I discovered revanced just today and thought it's better than the old vanced so i uninstalled vanced and now i discovered a bug. After 5-10 minutes of "minimized playback" revanced just closes but if i just keep the app in foreground then it's fine.. I've tried disabling miui optimization battry optimization and such but to no success there was no issue like this on old vanced... Please fix this issue. I'm having a really bad time

### Steps to reproduce

I've explained everything in bug description. Please fix this issue.

### Android version

12

### Manager version

0.0.32

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

Always Autorepeat
Client Spoof
Custom Branding
Disable Auto Player Popup Panels
Disable Fullscreen Panels
Downloads
General Ads
Hdr Auto Brightness
Hide Autoplay Button
Hide Cast Button
Hide Create Button
Hide Video Buttons
Hide Watermark
MicroG Support
Minimized Playback
Premium Heading
Remember Video Quality
Return Youtube Dislike
Sponsorblock
Swipe Controls
Video Ads
Theme
Tablet Mini Player
Custom Playback Speed
Settings

### Device logs (exported using Manager settings).

```shell
Error
java.lang.SecurityException: Permission Denial: reading com.zt.shareextend.ShareExtendProvider uri content://app.revanced.manager.flutter.shareextend.fileprovider/%252Fdata%252Fuser%252F0%252Fapp.revanced.manager.flutter%252Fcache%252Flogs%252Frevanced-manager_logcat_20221015201015918385.log from pid=8631, uid=10232 requires the provider be exported, or grantUriPermission()
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2455)
	at android.os.Parcel.createException(Parcel.java:2439)
	at android.os.Parcel.readException(Parcel.java:2422)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1842)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1518)
	at l.۫ۛۙ.ۗۤ(P16H:168)
	at l.ۥۗۙ.۫ۤ(618A:234)
	at l.ۤۡۨ.ۧ(JB3G:118)
	at l.ۤۡۨ.ۧ(Native Method)
	at l.۠ۗۨ.call(LATT:330)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not a manager issue. Open the issue in revanced-patches thanks!
