### ISSUE TITLE
bug: Aborting while patch youtube

### ISSUE THREAD

**Issue by XstepAhead** [revanced/revanced-manager#426]
### Type

Error while running the manager

### Bug description

Aborting while patching

### Steps to reproduce

-

### Android version

Android 10

### Manager version

0.0.36

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Root

### Patches selected.

Forgot but i remember
General ads
Minimal play
Sponsor block

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
10-22 12:53:12.646 25897 25897 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
10-22 12:53:58.830 25897 25897 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
10-22 12:55:58.063 25897 25897 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
10-22 13:03:42.850 25897 25897 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
10-22 13:04:39.263 25897 25897 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
--------- beginning of main
10-22 13:12:21.903 25897 25916 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
10-22 13:12:27.006 25897 25909 I manager.flutte: CollectorTransition concurrent copying GC freed 22055(848KB) AllocSpace objects, 0(0B) LOS objects, 78% free, 6598KB/30MB, paused 258us total 105.322ms
10-22 13:12:30.528 25897 25916 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
10-22 13:12:48.428 25897 25897 W manager.flutte: resources.arsc in APK '/system/priv-app/youtube/base.apk' is compressed.
10-22 13:12:50.215 25897 25916 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
10-22 13:13:18.408 25897 25916 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'general-resource-ads' of type: resource
Executing 'general-ads' of type: bytecode
[success] general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
[success] premium-heading
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'sponsorblock' of type: bytecode
[success] sponsorblock
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
[success] minimized-playback
Skipping 'settings' because it has already been applied
[success] settings
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-nqaE-bGg88ZZE0_UewkMTA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL189657960993473462.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:149)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-nqaE-bGg88ZZE0_UewkMTA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL189657960993473462.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NTDUWE/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Armv7 not supported.
