### ISSUE TITLE
bug: patch failure

### ISSUE THREAD

**Issue by hg13bs** [revanced/revanced-manager#447]
### Type

Other

### Bug description

always fails when patching youtube with the patches I've selected

### Steps to reproduce

1. get latest version of revanced (0.0.36)
2. patch yt while it's version is at 17.36.37
3. select patches from patches selected

### Android version

10

### Manager version

0.0.36

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Root

### Patches selected.

client spoof
custom branding
downloads
enable debugging
general ads
premium heading
return yt dislike
video ads

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
10-28 04:03:35.715 32282 32282 W 2.raster: type=1400 audit(0.0:3897): avc: denied { read write } for path="/dev/mali0" dev="tmpfs" ino=2463 scontext=u:r:untrusted_app:s0:c67,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file app=app.revanced.manager.flutter
10-28 04:03:35.715 32282 32282 W 2.raster: type=1300 audit(0.0:3897): arch=40000028 syscall=192 per=800008 success=yes exit=-1640488960 a0=0 a1=8000 a2=3 a3=1 items=0 ppid=3826 ppcomm=main auid=4294967295 uid=10067 gid=10067 euid=10067 suid=10067 fsuid=10067 egid=10067 sgid=10067 fsgid=10067 ses=4294967295 tty=(none) exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c67,c256,c512,c768 key=(null) app=app.revanced.manager.flutter
10-28 04:03:37.546 29407 32282 W libEGL  : EGLNativeWindowType 0x783a7008 disconnect failed
10-28 04:03:37.553 29407 29429 W libEGL  : EGLNativeWindowType 0x9f052108 disconnect failed
10-28 04:03:43.411 29407 29423 W System  : A resource failed to call close. 
10-28 04:05:18.325 29429 29429 W RenderThread: type=1400 audit(0.0:3951): avc: denied { ioctl } for path="/dev/mali0" dev="tmpfs" ino=2463 ioctlcmd=8018 scontext=u:r:untrusted_app:s0:c67,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file app=app.revanced.manager.flutter
10-28 04:05:18.336 29407 29429 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
10-28 04:05:18.355 29407 32282 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
10-28 04:05:18.325 29429 29429 W RenderThread: type=1300 audit(0.0:3951): arch=40000028 syscall=54 per=800008 success=yes exit=74 a0=39 a1=40208018 a2=7e91afa8 a3=4e7 items=0 ppid=3826 ppcomm=main auid=4294967295 uid=10067 gid=10067 euid=10067 suid=10067 fsuid=10067 egid=10067 sgid=10067 fsgid=10067 ses=4294967295 tty=(none) exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c67,c256,c512,c768 key=(null) app=app.revanced.manager.flutter
10-28 04:05:18.380 32282 32282 W 2.raster: type=1400 audit(0.0:3952): avc: denied { read write } for path="/dev/mali0" dev="tmpfs" ino=2463 scontext=u:r:untrusted_app:s0:c67,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file app=app.revanced.manager.flutter
10-28 04:05:22.762 29407 32282 W libEGL  : EGLNativeWindowType 0x79a09008 disconnect failed
10-28 04:05:22.771 29407 29429 W libEGL  : EGLNativeWindowType 0x9f052108 disconnect failed
10-28 04:08:19.342 29407 29429 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
10-28 04:08:19.335 29429 29429 W RenderThread: type=1400 audit(0.0:4086): avc: denied { ioctl } for path="/dev/mali0" dev="tmpfs" ino=2463 ioctlcmd=8018 scontext=u:r:untrusted_app:s0:c67,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file app=app.revanced.manager.flutter
10-28 04:08:19.335 29429 29429 W RenderThread: type=1300 audit(0.0:4086): arch=40000028 syscall=54 per=800008 success=yes exit=74 a0=39 a1=40208018 a2=7e91afa8 a3=4e7 items=0 ppid=3826 ppcomm=main auid=4294967295 uid=10067 gid=10067 euid=10067 suid=10067 fsuid=10067 egid=10067 sgid=10067 fsgid=10067 ses=4294967295 tty=(none) exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c67,c256,c512,c768 key=(null) app=app.revanced.manager.flutter
10-28 04:08:19.359 29407 32282 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
10-28 04:08:19.385 29429 29429 W RenderThread: type=1400 audit(0.0:4087): avc: denied { read write } for path="/dev/mali0" dev="tmpfs" ino=2463 scontext=u:r:untrusted_app:s0:c67,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file app=app.revanced.manager.flutter
10-28 04:08:24.125 11102 11102 W logcat  : type=1400 audit(0.0:4088): avc: denied { read } for name="mediaserver" dev="mmcblk0p18" ino=719 scontext=u:r:untrusted_app:s0:c67,c256,c512,c768 tcontext=u:object_r:mediaserver_exec:s0 tclass=file app=app.revanced.manager.flutter
10-28 04:08:24.125 11102 11102 W logcat  : type=1300 audit(0.0:4088): arch=40000028 syscall=334 per=800008 success=yes exit=0 a0=ffffff9c a1=b28d90a0 a2=4 a3=0 items=1 ppid=29407 ppcomm=manager.flutter auid=4294967295 uid=10067 gid=10067 euid=10067 suid=10067 fsuid=10067 egid=10067 sgid=10067 fsgid=10067 ses=4294967295 tty=(none) exe="/system/bin/logcat" subj=u:r:untrusted_app:s0:c67,c256,c512,c768 key=(null) app=app.revanced.manager.flutter
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'general-resource-ads' of type: resource
Executing 'general-ads' of type: bytecode
[success] general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
[success] downloads
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
[success] premium-heading
Skipping 'locale-config-fix' because it has already been applied
Executing 'custom-branding' of type: resource
[success] custom-branding
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
[success] return-youtube-dislike
Executing 'client-spoof' of type: bytecode
[success] client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'enable-debugging' of type: resource
[success] enable-debugging
Skipping 'settings' because it has already been applied
[success] settings
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-YFry65bOdeagCq0Kxdavgg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4036158793178371257.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:149)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-YFry65bOdeagCq0Kxdavgg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1531571648, --version-name, 17.36.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4036158793178371257.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ECGPZY/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Screenshots or videos

![Screenshot_20221028-035813_ReVanced_Manager](https://user-images.githubusercontent.com/108540686/198430569-eea27783-d2f0-431f-a0f8-e320092d3b25.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Armv7 isn't yet compatible eith the Manager.
