### ISSUE TITLE
bug: Aborting when Repacking APK

### ISSUE THREAD

**Issue by MyatkinCat** [revanced/revanced-manager#473]
### Type

Error while running the manager

### Bug description

Trying to patch Youtube APK with any selected patches leads to this error

### Steps to reproduce

1. Download and install ReVanced Manager
2. Download Youtube
3. Select Youtube APK in Manager
4. Select patches (video-ads in this case)
5. Try to patch

### Android version

PixelExperience 12.1

### Manager version

0.0.39

### Target package name

com.google.android.youtube

### Target package version.

17.43.36

### Installation type

Root

### Patches selected.

video-ads

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
11-02 19:14:01.412  9705  9705 W Choreographer: Frame time is 0.01459 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
11-02 19:14:01.471  9705 10720 I OpenGLRenderer: Davey! duration=509120ms; Flags=1, FrameTimelineVsyncId=814704, IntendedVsync=26381428232751, Vsync=26381428232751, InputEventId=948958455, HandleInputStart=26381428811187, AnimationStart=26381428817648, PerformTraversalsStart=26381428822725, DrawStart=26381446818725, FrameDeadline=26381461566085, FrameInterval=26381428800956, FrameStartTime=16666667, SyncQueued=26381447026571, SyncStart=26381448877340, IssueDrawCommandsStart=26381449102725, SwapBuffers=26381450216802, FrameCompleted=26890550475525, DequeueBufferDuration=0, QueueBufferDuration=2066538, GpuCompleted=26890550475525, SwapBuffersCompleted=26381453070725, DisplayPresentTime=0, 
11-02 19:14:57.866  9705 11202 I OpenGLRenderer: Davey! duration=121761ms; Flags=1, FrameTimelineVsyncId=818286, IntendedVsync=26825165844932, Vsync=26825165844932, InputEventId=0, HandleInputStart=26825166226598, AnimationStart=26825166231213, PerformTraversalsStart=26825166235367, DrawStart=26825206298367, FrameDeadline=26825199178266, FrameInterval=26825166220444, FrameStartTime=16666667, SyncQueued=26825206671675, SyncStart=26825209582136, IssueDrawCommandsStart=26825209737367, SwapBuffers=26825210571059, FrameCompleted=26946930073528, DequeueBufferDuration=0, QueueBufferDuration=2040846, GpuCompleted=26946930073528, SwapBuffersCompleted=26825213718290, DisplayPresentTime=0, 
11-02 19:15:03.411  9705  9705 W Choreographer: Frame time is 0.127923 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Executing 'resource-mapping' of type: resource
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'player-controller-hook' of type: bytecode
Skipping 'settings' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'fix-playback' of type: resource
Executing 'video-ads' of type: bytecode
Applied video-ads
Skipping 'settings' because it has already been applied
Applied settings
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/~~wY3qjOGNl4GkMB24bzzDYw==/app.revanced.manager.flutter-WPWU2HPiIuJMdLIFT19L2g==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532487104, --version-name, 17.43.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4619478752519632633.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:149)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$E2jhTFrLKJQp09EHxMNmoL-t4AE(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:920)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/~~wY3qjOGNl4GkMB24bzzDYw==/app.revanced.manager.flutter-WPWU2HPiIuJMdLIFT19L2g==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532487104, --version-name, 17.43.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4619478752519632633.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FVDDVU/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Screenshots or videos

![Screenshot_20221102-191505_ReVanced Manager](https://user-images.githubusercontent.com/70258889/199543463-ea6c6910-59f9-479b-b5ae-180b0f43b270.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
ARMv7 devices are currently not supported, you can track the issue here #268
