### ISSUE TITLE
bug: apk seems unavailable after successful patching

### ISSUE THREAD

**Issue by Supersebi3** [revanced/revanced-manager#478]
i tried to patch youtube 17.43.36 using manager version 0.0.39 on an EMUI 10 system. the patching process went just fine, but after patching, nothing seems to work.

pressing the install button opens the installer and it seems to run fine until the end, at which point it simply fails saying "App not installed."

trying to share the apk through various different apps also doesnt work. Telegram recognizes an "unsupported file type", while solid explorer fails to save the file anywhere. this leads me to believe that for whatever reason, the apk file is completely inaccessible.

the same sharing issue also happens with the log file, so i cant give log texts here. i doubt they would be helpful anyway though since the patching process went just fine. i believe this is simply an issue with the way the file distribution is currently set up which makes it fail on android 10/emui 10 for some reason. 

oh yeah, also i was doing nonroot the entire time and the installer did recognize the app as revanced, not plain youtube.

**Comment by Supersebi3** [comment]
i just tried the same thing except installing through SAI, which gave me the following error message:

> com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkLocalPath(DefaultApkSource.java:47)
	at com.aefyr.sai.model.apksource.FilterApkSource.getApkLocalPath(FilterApkSource.java:60)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:28)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by Supersebi3** [comment]
i have managed to install the patched apk, albeit through a rather arduous process.

1. after patching the app, use "share apk" to send the file to yourself on WhatsApp.
2. in a file explorer (i use Solid explorer) go to Internal Storage/WhatsApp/WhatsApp Documents and find the file you just sent. it will have a generic name and no extension, but you can identify it by date and file size. 
3. copy the to a convenient location and rename it so it has a .apk extension
4. install this APK file (you may have to install an older version of revanced due to non-matching signatures)

regardless, this issue still stands as the regular "install" button in the manager clearly does not do what it is supposed to.

**Comment by MaXfAa** [comment]
Oh it seems that the "bug" label is missing...

**Comment by Xnehaxixh** [comment]
I'm facing the same problem on `0.0.39`.

After pressing Install, nothing happens. Same happens when I click on the Share APK button.

OS: Android 10 (RUI 1)

**Comment by ILoveOpenSourceAppications** [comment]
Do these issues still exist? Were they just related to the patching methods? Is this still a relevant bug? Can't this be closed?

**Comment by stella-sf** [comment]
@ILoveOpenSourceAppications the issue doesnt exist for me anymore, but ive also switched phones so i couldnt tell you if its fixed completely. can probably be closed tho

**Comment by xparadoxical** [comment]
This is still an issue on v0.0.57.

I'm using root. I have a patched YT v17.49.37 installed that I want to easily update to a new patched version without having to configure all settings (yt, revanced, RYD, sponsorblock) in the app yet again (I have went through this after encountering this issue on like December or January and uninstalling the app, don't want to again).

- I downloaded a YT apk, the currently recommended version 18.05.40, from ApkMirror that was not labeled as `BUNDLE`,
- I patched it with Manager.
Then:
- `Install as Root` - can't, "the original APK was selected from storage"
- `Install` - can't, "non-root install is not possible with the current patches selection"
The only other option is to install the apk manually. So I exported the apk. Now:
- the MIUI installer shows that it's going to update "YouTube ReVanced" from files, from version 17.49.37 to 17.49.37 (the filename indicates v18.05.40), and fails with the reason "Application signature conflict" (rough translation from Polish),
- in Total Commander, after choosing "Install" or "Open" the system installer instantly closes,
- SAI refuses to install com.google.android.youtube v17.49.37 (once again, the filename indicates v18.05.40) as the `DISPLAY_NAME column is null`.

Besides that, the newly patched apk has different names and icons in different places:
- file managers: default yt icon
- MIUI app installer: revanced icon and name
- SAI: default apk icon (dark green with a robot face), name "com.google.android.youtube"
idk if this is caused by the currently installed patched yt app having the default yt icon and name.

**Comment by oSumAtrIX** [comment]
Please attach a full, complete and detailed recording of your issue

**Comment by xparadoxical** [comment]
[recording](https://www.mediafire.com/file/3i5isg15rtfmnic/Screenrecorder-2023-04-16-01-15-49-887_0_COMPRESSED.mp4/file) warning: 70MB, most of the 10 minutes is manager patching the apk

**Comment by oSumAtrIX** [comment]
Include the recommended set of patches, you are missing microg-support.

**Comment by annsabbasi** [comment]
how did you guys solved the issue can you also tell me ?? Im also having the same error's

com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkLocalPath(DefaultApkSource.java:47)
	at com.aefyr.sai.model.apksource.FilterApkSource.getApkLocalPath(FilterApkSource.java:60)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:28)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:94)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$com-aefyr-sai-installer2-impl-rootless-RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:71)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)

**Comment by oSumAtrIX** [comment]
This is not a support channel, move to one of our social media places on https://revanced.app
