### ISSUE TITLE
bug: after any patch YouTube doesn't launch

### ISSUE THREAD

**Issue by asamofal** [revanced/revanced-manager#491]
### Type

Error at runtime

### Bug description

Patching looks fine (just one patch selected). Installation via root method looks fine too but then the app can't be launched, just crashed at the start. 

Any ideas?

### Steps to reproduce

1. Patch Youtube with any single patch and install.
2. Launch the app.

### Android version

12

### Manager version

0.0.39

### Target package name

YouTube

### Target package version.

17.43.36

### Installation type

Root

### Patches selected.

Any. 

### Device logs (exported using Manager settings).

```shell
time: 1667937841737
device fp:OnePlus/OnePlus5T/OnePlus5T:10/QKQ1.191014.012/2010292059:user/release-keys
product board:msm8998
derpfest vers:12-Official-Shinju-dumpling-20220814
msg: ehd: libelements.so
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: java.lang.RuntimeException: EntityStore failed loading from .so
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7866)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: EntityStore failed loading from .so
	at vbs.d(PG:4)
	at vbs.a(PG:1)
	at flc.b(PG:1)
	at flc.<init>(PG:1)
	at ffg.j(PG:1)
	at equ.o(PG:76)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at equ.o(PG:81)
	at equ.a(PG:39)
	at equ.o(PG:82)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at epq.e(PG:18)
	at epq.a(PG:32)
	at arjc.a(PG:1)
	at epq.b(PG:75)
	at epq.a(PG:43)
	at arjc.a(PG:1)
	at epq.b(PG:9)
	at epq.a(PG:43)
	at arjc.a(PG:1)
	at epq.m(PG:60)
	at epq.a(PG:38)
	at arjc.a(PG:1)
	at epq.m(PG:61)
	at epq.a(PG:38)
	at arjc.a(PG:1)
	at epq.o(PG:91)
	at epq.a(PG:36)
	at arjc.a(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:22)
	at jln.a(PG:38)
	at qt.onCreate(PG:3)
	at bu.onCreate(PG:1)
	at fam.onCreate(PG:8)
	at lja.onCreate(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	... 12 more
Caused by: ehd: libelements.so
	at epc.I(PG:51)
	at tmy.am(PG:7)
	at esd.a(PG:1)
	at agqf.e(PG:8)
	at agqf.f(PG:5)
	at agqf.c(PG:1)
	at ogh.a(PG:1)
	at vbo.<init>(PG:1)
	at vbw.<init>(PG:6)
	at vbs.g(PG:4)
	at vbs.d(PG:1)
	at vbs.a(PG:1)
	at flc.b(PG:1)
	at flc.<init>(PG:1)
	at ffg.j(PG:1)
	at equ.o(PG:76)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at equ.o(PG:81)
	at equ.a(PG:39)
	at equ.o(PG:82)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at icp.<init>(PG:2)
	at icd.g(PG:1)
	at equ.d(PG:49)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at ese.run(PG:151)
	at tma.run(PG:7)
	at ocy.run(PG:5)
	at odc.run(PG:23)
	at nlt.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.s.run(PG:15)
	at java.lang.Thread.run(Thread.java:1013)
```
```


### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Executing 'resource-mapping' of type: resource
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-information' of type: bytecode
Skipping 'settings' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'fix-playback' of type: resource
Executing 'video-ads' of type: bytecode
Applied video-ads
Skipping 'settings' because it has already been applied
Applied settings
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using root method
Installed!
```
```


### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by briantho** [comment]
i'm having the same issue using revanced manager 0.0.39 and youtube 17.43.36. 

I'm rooted and every time i try the root version everything looks like it works, but youtube keeps crashing. I'm running android 11 on a rooted asus zenfone 6. Is there something I'm missing, or is the root method broken?

**Comment by howarddo2208** [comment]
I got it too with the MicroG method, cannot launch. Might be some error with the new version, the 17.36.37 one I patched before works until I try the latest version this happened.

**Comment by geugenm** [comment]
The same situation on rooted Xiaomi Redmi Note 8 Pro with 0.0.39 manager and 17.43.36 version of YT on Android 11.

**Comment by zeko9381** [comment]
I had the same issue if I installed YouTube from Google Play, but worked fine if I downloaded the apk from ApkPure.

**Comment by dr3mro** [comment]
SAME HERE

**Comment by BRUHItsABunny** [comment]
Try updating YouTube via APKPure, enable experimental patches in revanced and then delete the keystore, logs and temp directory

After weeks of not being able to patch even the recommended version of YT, now for unknown reasons after the above steps, suddenly the latest version works (even though it's not the recommended version)

**Comment by boehs** [comment]
Enabling experimental patches confirmed to work!

**Comment by donmega** [comment]
I also had the same exact problem. Experimental patches worked for me too!

**Comment by matthoendorf** [comment]
Experimental patches do not resolve it for me

**Comment by briantho** [comment]
> Experimental patches do not resolve it for me

same for me. experimental patches don't work. also, are you using root method, or regular install?

I only tried the root method. does the regular install work?

**Comment by asamofal** [comment]
Experimental patches don't solve the problem for me too (with the PlayMarket version of Youtube).

**Comment by Y-T-G** [comment]
The error I get in my logcat is this:


```

11-15 22:16:37.433  7951  8123 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1                                                                          
11-15 22:16:37.433  7951  8123 E AndroidRuntime: Process: com.google.android.youtube, PID: 7951                                                         
11-15 22:16:37.433  7951  8123 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()                         
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)                                              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)                        
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:250)                            
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:269)                                     
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)                                
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)                                                       
11-15 22:16:37.433  7951  8123 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.google.android.youtube:drawable/mr_button_dark_static with resource ID #0x7f080623                        
11-15 22:16:37.433  7951  8123 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mr_button_dark_static.xml from drawable resource ID #0x7f080623                                      
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:900)              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:691)                       
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:307)               
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.Resources.loadDrawable(Resources.java:1017)                              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.Resources.getDrawableForDensity(Resources.java:1005)                     
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.Resources.getDrawable(Resources.java:944)                                
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.Context.getDrawable(Context.java:763)                                        
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at agx.a(PG:1)      
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at or.d(PG:14)      
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at or.c(PG:1)       
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at fc.b(PG:1)       
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at cba.doInBackground(PG:3)                                                                     
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)                                              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:264)                                     
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)                                
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)                                                       
11-15 22:16:37.433  7951  8123 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable                             
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:195) 
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:126)              
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:145)                                                                           
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1414)          
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1373)               
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.ResourcesImpl.createFromXmlForDensity(ResourcesImpl.java:1516)           
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:934)                    
11-15 22:16:37.433  7951  8123 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:883)
```

**Comment by Y-T-G** [comment]
I fixed it by:
1. Installing the apk from [here](https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-43-36-release/youtube-17-43-36-2-android-apk-download/)
2. Enabling experimental patches
3. Patching and installing as root.

**Comment by piotr25691** [comment]
> I got it too with the MicroG method, cannot launch. Might be some error with the new version, the 17.36.37 one I patched before works until I try the latest version this happened.

Also, the newer version 17.45.36 also works.

**Comment by DarkSkull91** [comment]
I notice that the first time the won't start but the secondo time, it starts. 
I'm running Android 12, revanced 0.0.44, YouTube v17.45.36 but also with Twitter (first time no, second time yes).
