### ISSUE TITLE
crash: UnsatisfiedLinkError: dlopen failed: library "libjsapi.so" not found

### ISSUE THREAD

**Issue by Bluscream** [revanced/revanced-manager#513]
### Type

Error at runtime

### Bug description

Today yt revanced suddenly started crashing on me.
No amount of restarts and reinstalls seem to fix it.
there were no changes made to Software and hardware between the time it last worked and doesnt work anymore.

Interestingly enough, I had the same crash on my phone when i first tried installing revanced but with a completely different OS and device

### Steps to reproduce

1. Try installing revanced or youtube
2. start it
3. Crash

### Android version

Android Version: 10

### Manager version

Version: 0.0.39
Model: Lenovo TB-X606F
Arch: arm64-v8a

### Target package name

Vanilla yt

### Target package version.

17.43.36

### Installation type

Root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
FATAL EXCEPTION: main
Process: com.google.android.youtube, PID: 11020
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: java.lang.RuntimeException: EntityStore failed loading from .so
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3441)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: java.lang.RuntimeException: EntityStore failed loading from .so
	at vbs.d(PG:4)
	at vbs.a(PG:1)
	at flc.b(PG:1)
	at flc.<init>(PG:1)
	at ffg.j(PG:1)
	at equ.o(PG:76)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at equ.o(PG:81)
	at equ.a(PG:39)
	at equ.o(PG:82)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at epq.e(PG:18)
	at epq.a(PG:32)
	at arjc.a(PG:1)
	at epq.b(PG:75)
	at epq.a(PG:43)
	at arjc.a(PG:1)
	at epq.b(PG:9)
	at epq.a(PG:43)
	at arjc.a(PG:1)
	at epq.m(PG:60)
	at epq.a(PG:38)
	at arjc.a(PG:1)
	at epq.m(PG:61)
	at epq.a(PG:38)
	at arjc.a(PG:1)
	at epq.o(PG:91)
	at epq.a(PG:36)
	at arjc.a(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:22)
	at jln.a(PG:38)
	at qt.onCreate(PG:3)
	at bu.onCreate(PG:1)
	at fam.onCreate(PG:8)
	at lja.onCreate(PG:1)
	at app.revanced.integrations.swipecontrols.SwipeControlsHostActivity.onCreate(SwipeControlsHostActivity.kt:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
	at android.app.Activity.performCreate(Activity.java:7869)
	at android.app.Activity.performCreate(Activity.java:7858)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3277)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsapi.so" not found
	at java.lang.Runtime.load0(Runtime.java:938)
	at java.lang.System.load(System.java:1631)
	at epc.I(PG:48)
	at tmy.am(PG:7)
	at esd.a(PG:1)
	at agqf.e(PG:8)
	at agqf.f(PG:5)
	at agqf.c(PG:1)
	at ogh.a(PG:1)
	at vbo.<init>(PG:1)
	at vbw.<init>(PG:6)
	at vbs.g(PG:4)
	at vbs.d(PG:1)
	at vbs.a(PG:1)
	at flc.b(PG:1)
	at flc.<init>(PG:1)
	at ffg.j(PG:1)
	at equ.o(PG:76)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at eqv.v(PG:1)
	at eqv.s(PG:1)
	at equ.p(PG:51)
	at equ.a(PG:39)
	at arjj.a(PG:1)
	at eqv.Aa(PG:2)
	at equ.p(PG:55)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at eqv.dm(PG:1)
	at equ.p(PG:62)
	at equ.a(PG:39)
	at arjc.a(PG:1)
	at aaam.c(PG:6)
	at ese.run(PG:160)
	at tma.run(PG:7)
	at ocy.run(PG:5)
	at odc.run(PG:23)
	at nlt.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.s.run(PG:15)
	at java.lang.Thread.run(Thread.java:919)
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
[%2Fdata%2Fuser%2F0%2Fapp.revanced.manager.flutter%2Fcache%2Flogs%2Frevanced-manager_logcat_20221115121351714164.log](https://github.com/revanced/revanced-manager/files/10012086/2Fdata.2Fuser.2F0.2Fapp.revanced.manager.flutter.2Fcache.2Flogs.2Frevanced-manager_logcat_20221115121351714164.log)
```

### Solution

Please explain how to install this libjsapi.so library

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Cypher-Emm** [comment]
Use Latest Version v0.0.40

**Comment by Bluscream** [comment]
> Version: 0.0.39

You mean the manager? I checked for updates and it said up to date

**Comment by rootback123** [comment]
you should check the repository for updates

**Comment by rootback123** [comment]
Don't trust the updater by the manager check here in the repository the latest apk

**Comment by Canny1913** [comment]
both are same wdym

**Comment by rootback123** [comment]
I'm just saying that the email manager update mechanism is uncertain so looking in the repository is not a bad idea

**Comment by Canny1913** [comment]
email manager update mechanism?
both grab the same file from same repository

**Comment by rootback123** [comment]
I wrote it wrong sorry, only the version problem happened to me too I came to the repository and downloaded the latest apk
