### ISSUE TITLE
bug: Youtube crashes when changing wifi hotspot

### ISSUE THREAD

**Issue by geugenm** [revanced/revanced-manager#547]
### Type

Error at runtime

### Bug description

While watching videos, I sometimes switch WiFi hotspots and when connection to another point established Youtube crashes

### Steps to reproduce

Step 1. Start watching video
Step 2. Without leaving YouTube change the wifi hotspot (via notification center)
Step 3. Youtube crashes

### Android version

11 RP1A.200720.011

### Manager version

0.0.40

### Target package name

Youtube

### Target package version.

17.43.36

### Installation type

Root

### Patches selected.

[selected_patches_2022-11-27_15_38_24.txt](https://github.com/revanced/revanced-manager/files/10098347/selected_patches_2022-11-27_15_38_24.txt)

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
11-20 17:30:28.098  7485  7485 E AndroidRuntime: FATAL EXCEPTION: main
11-20 17:30:28.098  7485  7485 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 7485
11-20 17:30:28.098  7485  7485 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4587)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4619)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8043)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5181)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4574)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	... 11 more
11-20 17:30:28.098  7485  7485 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8516)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5174)
11-20 17:30:28.098  7485  7485 E AndroidRuntime: 	... 12 more
--------- beginning of system
11-26 21:55:17.103 31038 31038 I Timeline: Timeline: Activity_launch_request time:278720444
11-26 21:56:49.098 31038 31038 I Timeline: Timeline: Activity_launch_request time:278812439
11-26 21:57:25.805 31038 31094 W BpBinder: Slow Binder: BpBinder transact took 390ms, interface=android.net.IConnectivityManager, code=6 oneway=false
--------- beginning of main
11-27 15:37:57.374  6052  6052 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@be3a024, this = DecorView@a8e578d[MainActivity]
11-27 15:37:57.383  6052  6052 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@be3a024, this = DecorView@a8e578d[MainActivity]
11-27 15:37:57.396  6052  6077 I GED     : [GT]_get_procNameprocess pid(6052)
11-27 15:37:57.397  6052  6077 I GED     : [GT]_getprocess name(app.revanced.manager.flutter)
11-27 15:37:57.397  6052  6077 I manager.flutte: [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
11-27 15:37:57.397  6052  6077 I libMEOW_gift: ctx:0xb400007250f07f78, ARC not Enabled.
11-27 15:38:14.417  6131  6131 W sh      : type=1400 audit(0.0:466928): avc: denied { read } for name="/" dev="sdc40" ino=2 scontext=u:r:untrusted_app:s0:c84,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-27 15:38:14.433  6131  6131 W sh      : type=1400 audit(0.0:466929): avc: denied { read } for name="/" dev="sdc40" ino=2 scontext=u:r:untrusted_app:s0:c84,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-27 15:38:14.441  6131  6131 W sh      : type=1400 audit(0.0:466930): avc: denied { read } for name="/" dev="sdc40" ino=2 scontext=u:r:untrusted_app:s0:c84,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-27 15:38:14.453  6131  6131 W sh      : type=1400 audit(0.0:466931): avc: denied { read } for name="/" dev="sdc40" ino=2 scontext=u:r:untrusted_app:s0:c84,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-27 15:38:14.457  6131  6131 I chatty  : uid=10596(app.revanced.manager.flutter) /system/bin/sh identical 1 line
11-27 15:38:14.465  6131  6131 W sh      : type=1400 audit(0.0:466933): avc: denied { read } for name="/" dev="sdc40" ino=2 scontext=u:r:untrusted_app:s0:c84,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-27 15:38:14.473  6131  6131 W sh      : type=1400 audit(0.0:466934): avc: denied { read } for name="/" dev="sdc40" ino=2 scontext=u:r:untrusted_app:s0:c84,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-27 15:38:14.477  6131  6131 W sh      : type=1400 audit(0.0:466935): avc: denied { read } for name="/" dev="sdc40" ino=2 scontext=u:r:untrusted_app:s0:c84,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-27 15:38:24.794  6052  6052 I Timeline: Timeline: Activity_launch_request time:303109168
11-27 15:38:26.210  6052  6052 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@be3a024, this = DecorView@a8e578d[MainActivity]
11-27 15:38:26.223  6052  6077 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
11-27 15:38:29.085  6052  6052 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@be3a024, this = DecorView@a8e578d[MainActivity]
11-27 15:38:29.086  6052  6052 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@be3a024, this = DecorView@a8e578d[MainActivity]
11-27 15:38:29.171  6052  6052 D CrFileSaverPlugin: Saved file /document/149 via dialog
11-27 15:38:29.179  6052  6052 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
11-27 15:38:29.182  6052  6052 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10596; state: ENABLED
11-27 15:38:29.190  6052  6052 D ViewRootImpl[Toast]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
11-27 15:38:29.200  6052  6052 I InputTransport: Create ARC handle: 0xb4000071da5e9760
11-27 15:38:29.201  6052  6052 I Toast   : Show toast from OpPackageName:app.revanced.manager.flutter, PackageName:app.revanced.manager.flutter
```

### Additional context

Reproduced on MIUI 12.5.3 (Xiaomi Redmi Note 8 pro)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager

**Comment by geugenm** [comment]
The same happens on manager 0.0.42

**Comment by Ushie** [comment]
Acknowledgements are not met, this issue is unrelated to ReVanced Manager.

**Comment by geugenm** [comment]
Should I create a new issue or editing like that will be enough for reopening?

**Comment by geugenm** [comment]
> Acknowledgements are not met, this issue is unrelated to ReVanced Manager.

Should I create a new issue or editing like that will be enough for reopening?

**Comment by Canny1913** [comment]
> > Acknowledgements are not met, this issue is unrelated to ReVanced Manager.
> 
> Should I create a new issue or editing like that will be enough for reopening?

editing is useless since this issue is not related to manager like ushie said

**Comment by geugenm** [comment]
> > > Acknowledgements are not met, this issue is unrelated to ReVanced Manager.
> > 
> > Should I create a new issue or editing like that will be enough for reopening?
> 
> editing is useless since this issue is not related to manager like ushie said
Ok, thanks for the answer! Which repo will be a right place for this issue? The problem is with patched youtube, so maybe its related to revanced-patches?
