### ISSUE TITLE
bug: manager fails to patch youtube

### ISSUE THREAD

**Issue by kazuhiroshigeru** [revanced/revanced-manager#561]
### Type

Error while running the manager

### Bug description

When using the patcher, it fails and aborts the process.
[revanced-manager_patcher_20221204183619407124.log](https://github.com/revanced/revanced-manager/files/10149538/revanced-manager_patcher_20221204183619407124.log)
Log attached.

### Steps to reproduce

open manager
select YT apk
select recommended or all patches
run the patcher
manager fails and aborts the operation.

### Android version

tested under android 10, 11 and 12 on 3 galaxy phones, J4, J5 and A302

### Manager version

latest version 0.0.43

### Target package name

com.google.android.youtube

### Target package version.

17.45.36

### Installation type

Non-root

### Patches selected.

all patches

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied general-ads
Applied video-ads
Applied downloads
Applied seekbar-tapping
Applied swipe-controls
Applied disable-auto-captions
Applied hide-autoplay-button
Applied premium-heading
Applied custom-branding
Applied hide-video-buttons
Applied hide-cast-button
Applied comments
Applied disable-fullscreen-panels
Applied hide-album-cards
Applied hide-artist-card
Applied hide-captions-button
Applied hide-crowdfunding-box
Applied hide-endscreen-cards
Applied hide-info-cards
Applied hide-my-mix
Applied hide-time-and-seekbar
Applied old-quality-layout
Applied hide-email-address
Applied hide-create-button
Applied hide-shorts-button
Applied remove-player-button-background
Applied disable-auto-player-popup-panels
Applied return-youtube-dislike
Applied sponsorblock
Applied disable-startup-shorts-player
Applied tablet-mini-player
Applied theme
Applied hide-watch-in-vr
Applied hide-watermark
Applied enable-wide-searchbar
Applied always-autorepeat
Applied debugging
Applied client-spoof
Applied hdr-auto-brightness
Applied microg-support
Applied minimized-playback
Applied open-links-directly
Applied settings
Applied remember-video-quality
Applied custom-video-speed
Applied custom-video-buffer
Applied disable-zoom-haptics
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-GAHlnVc1pbG_3MgkLgCtqg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532749248, --version-name, 17.45.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6718733864904140638.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:148)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-GAHlnVc1pbG_3MgkLgCtqg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532749248, --version-name, 17.45.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6718733864904140638.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied general-ads
Applied video-ads
Applied downloads
Applied seekbar-tapping
Applied swipe-controls
Applied disable-auto-captions
Applied hide-autoplay-button
Applied premium-heading
Applied custom-branding
Applied hide-video-buttons
Applied hide-cast-button
Applied comments
Applied disable-fullscreen-panels
Applied hide-album-cards
Applied hide-artist-card
Applied hide-captions-button
Applied hide-crowdfunding-box
Applied hide-endscreen-cards
Applied hide-info-cards
Applied hide-my-mix
Applied hide-time-and-seekbar
Applied old-quality-layout
Applied hide-email-address
Applied hide-create-button
Applied hide-shorts-button
Applied remove-player-button-background
Applied disable-auto-player-popup-panels
Applied return-youtube-dislike
Applied sponsorblock
Applied disable-startup-shorts-player
Applied tablet-mini-player
Applied theme
Applied hide-watch-in-vr
Applied hide-watermark
Applied enable-wide-searchbar
Applied always-autorepeat
Applied debugging
Applied client-spoof
Applied hdr-auto-brightness
Applied microg-support
Applied minimized-playback
Applied open-links-directly
Applied settings
Applied remember-video-quality
Applied custom-video-speed
Applied custom-video-buffer
Applied disable-zoom-haptics
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-GAHlnVc1pbG_3MgkLgCtqg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532749248, --version-name, 17.45.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6718733864904140638.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:148)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-GAHlnVc1pbG_3MgkLgCtqg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532749248, --version-name, 17.45.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6718733864904140638.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BBJBTS/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Solution

idk the solution

### Additional context

just attempted to patch using the instructions on the github and discord server

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by AnnoyingWatcher** [comment]
Had the same issue
Seems to be caused by MicroG Support

Disable that patch if you will, or wait for it to be fixed

Tough one, since it's what let's you use revanced without root

**Comment by helpimnotdrowning** [comment]
I'm also having this issue with manager v0.0.44, though Im not using MicroG since I have root.

This is my patch selection for YouTube:
```json
{
    "com.google.android.youtube":[
        "disable-startup-shorts-player",
        "sponsorblock",
        "return-youtube-dislike",
        "theme",
        "hide-watermark",
        "old-quality-layout",
        "general-ads",
        "downloads",
        "seekbar-tapping",
        "open-links-directly",
        "client-spoof",
        "minimized-playback",
        "custom-video-speed",
        "video-ads"
    ]
}
```

**Comment by helpimnotdrowning** [comment]
My issue actually seems to be slightly different (libaapt2 gives a different exit code), so ignore my last comment.

**Comment by Marvinoo** [comment]
I've the same issue using Samsung Galaxy Note III Rooted.

**Comment by tt-thoma** [comment]
Confirmed on Galaxy A13

**Comment by chickendrop89** [comment]
I am having this issue as well while trying to patch "TikTok" or "YouTube" (Redmi Note 11, Android 13, Rooted)

**Comment by oSumAtrIX** [comment]
Armv7 is currently not supported.

**Comment by DarshGupta16** [comment]
> Armv7 is currently not supported.

Is it still possible to get an exported apk from another device and use it?

**Comment by oSumAtrIX** [comment]
Yes
