### ISSUE TITLE
bug: "No applications found" after reinstalling to diagnose other issues

### ISSUE THREAD

**Issue by helpimnotdrowning** [revanced/revanced-manager#571]
### Type

Error while running the manager

### Bug description

After reinstalling Manager, going to the app picker in the patcher shows "No applications found". 

### Steps to reproduce

I truly have no idea. I have reinstalled with this "no applications" bug about twice.

### Android version

11 V600VM20g on an LGv60 LM-V600AM

### Manager version

0.0.44

### Target package name

n/a

### Target package version.

n/a

### Installation type

Root

### Patches selected.

n/a

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
12-08 13:46:43.635 19947 19947 E AndroidRuntime: FATAL EXCEPTION: main
12-08 13:46:43.635 19947 19947 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 19947
12-08 13:46:43.635 19947 19947 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=209, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/799 flg=0x1 }} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5104)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5145)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7867)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8329)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
12-08 13:46:43.635 19947 19947 E AndroidRuntime: 	... 11 more
12-08 13:47:24.540 20773 20773 E AndroidRuntime: FATAL EXCEPTION: main
12-08 13:47:24.540 20773 20773 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 20773
12-08 13:47:24.540 20773 20773 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=209, result=0, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5104)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5145)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7867)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8329)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
12-08 13:47:24.540 20773 20773 E AndroidRuntime: 	... 11 more
--------- beginning of system
12-09 08:09:14.969 27230 27230 I Timeline: Timeline: Activity_idle id: ActivityRecord{58d8430 token=android.os.BinderProxy@40a92a {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} time:218363876
12-09 08:09:15.994 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:16.061 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:16.706 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:16.747 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:17.748 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:17.804 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:18.259 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:18.317 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:18.780 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:18.888 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:18.995 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:19.376 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:19.690 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:20.144 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:23.641 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:09:23.770 27230 27230 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:09:24.656 27230 27230 I ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=218373559, downTime=218373559, deviceId=-1, source=0x101, displayId=-1 } to DecorView@f8ece9e[MainActivity]
12-09 08:09:24.659 27230 27230 I ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=218373561, downTime=218373559, deviceId=-1, source=0x101, displayId=-1 } to DecorView@f8ece9e[MainActivity]
12-09 08:10:02.213 29907 29907 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:10:02.369 29907 29907 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:10:02.865 29907 29907 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
12-09 08:10:02.876 29907 29907 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
12-09 08:10:03.351 29907 29907 I Timeline: Timeline: Activity_idle id: ActivityRecord{f5a20b7 token=android.os.BinderProxy@40a92a {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} time:218412257
12-09 08:10:03.351 29907 29907 I Timeline: Timeline: Activity_idle id: ActivityRecord{f5a20b7 token=android.os.BinderProxy@40a92a {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} time:218412258
```

### Additional context

I reinstalled because I was experiencing an issue where going to the patcher tab at all would result in an blank, off-white screen. Doing this, I was trying to replicate another, third, issue where the Youtube patching process fails in a similar way to #561 (similar in that the error message looks the same, but aapt2 exits with a different error code.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by SVNKoch** [comment]
the repo with the patches was DMCAed at the time of this issue (no patches => no allication that can be patched). It is up again, should work now.
