### ISSUE TITLE
Tiltok patching Failed

### ISSUE THREAD

**Issue by m7md7essen** [revanced/revanced-manager#580]
### Type

Error while running the manager

### Bug description

![Screenshot_2022-12-11-20-46-48-122_app revanced manager flutter](https://user-images.githubusercontent.com/32914068/206923198-86e14e7c-231c-42fa-bf39-7049cae5ace3.jpg)

### Steps to reproduce

![Screenshot_2022-12-11-20-46-48-122_app revanced manager flutter](https://user-images.githubusercontent.com/32914068/206923218-8e5f904c-513b-4457-b8b2-ae91fbf1b946.jpg)

### Android version

12

### Manager version

0.0.46

### Target package name

Tiktok

### Target package version.

any

### Installation type

Non-root

### Patches selected.

all

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-login-requirement
Applied downloads
Applied feed-filter
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied predictive-back-gesture
Applied settings
Applied show-seekbar
Applied sim-spoof
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~sF3yv8erxDitGqQLXTBYmw==/app.revanced.manager.flutter-nPwhKev0ymRbb_JXdbWW-g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VMWMFA/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VMWMFA/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:199)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~sF3yv8erxDitGqQLXTBYmw==/app.revanced.manager.flutter-nPwhKev0ymRbb_JXdbWW-g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VMWMFA/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VMWMFA/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by vhick** [comment]
Same error as mine on tiktok. Here's the full log:

https://pastebin.com/JGu2qLcY

**Comment by MrDodojo** [comment]
Same here
