### ISSUE TITLE
bug: Impossible for me to patch tiktok

### ISSUE THREAD

**Issue by MattiaPARRINELLO** [revanced/revanced-manager#587]
### Type

Error while running the manager

### Bug description

Can't patch tiktok.

![Screenshot_2022-12-13-22-32-43-136_app revanced manager flutter](https://user-images.githubusercontent.com/66528113/207449659-65993b86-fef6-4209-9c12-b79cda9d5e82.jpg)
![Screenshot_2022-12-13-22-32-47-758_app revanced manager flutter](https://user-images.githubusercontent.com/66528113/207449662-c81f0dcc-3bbd-408a-8968-bdcb55e5fb8c.jpg)
![Screenshot_2022-12-13-22-32-54-753_app revanced manager flutter](https://user-images.githubusercontent.com/66528113/207449667-36ad0e07-8109-421b-82fc-12316b386ee7.jpg)

### Steps to reproduce

1. Select tiktok
2. Select patch
3. Try to apply the patchs

### Android version

11

### Manager version

Tried on 0.48 and 0.47 logs are from the 0.47

### Target package name

Tiktok

### Target package version.

27.3.4

### Installation type

Root

### Patches selected.

- Download
- Hide Adds
- Show Seekbar

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
12-13 22:27:42.407  3668  3668 I ForceDarkHelper: mForceDarkOrigin true
12-13 22:27:42.434  3668  3668 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
12-13 22:27:42.674  3668  3668 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=302ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=2 (msgIndex=1 wall=78ms seq=2 running=35ms runnable=2ms io=30ms binder=15ms late=2ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=229ms seq=3 running=95ms runnable=4ms io=52ms binder=37ms late=73ms h=android.app.ActivityThread$H w=159)
12-13 22:27:47.082  3668  3668 W Looper  : PerfMonitor longMsg : seq=205 plan=22:27:44.227 late=97ms wall=2757ms running=2ms runnable=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=2
12-13 22:27:47.163  3668  3668 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=6ms latency=2439ms running=1ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=68 (msgIndex=1 wall=2757ms seq=205 running=2ms runnable=1ms late=97ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
12-13 22:27:47.166  3668  3668 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=3ms latency=2441ms running=1ms  procState=2 ClientTransaction{ lifecycleRequest=android.app.servertransaction.PauseActivityItem } historyMsgCount=69 (msgIndex=1 wall=2757ms seq=205 running=2ms runnable=1ms late=97ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
12-13 22:27:47.174  3668  3668 I Timeline: Timeline: Activity_launch_request time:17988775
12-13 22:28:01.417  4384  4384 I ForceDarkHelper: mForceDarkOrigin true
12-13 22:28:01.425  4384  4384 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
--------- beginning of crash
12-13 22:28:01.500  4384  4384 E AndroidRuntime: FATAL EXCEPTION: main
12-13 22:28:01.500  4384  4384 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 4384
12-13 22:28:01.500  4384  4384 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4649)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4681)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8131)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5249)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4636)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	... 11 more
12-13 22:28:01.500  4384  4384 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8516)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5242)
12-13 22:28:01.500  4384  4384 E AndroidRuntime: 	... 12 more
12-13 22:28:04.137  4477  4477 I ForceDarkHelper: mForceDarkOrigin true
12-13 22:28:04.145  4477  4477 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
12-13 22:28:16.352  4477  4477 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=1144461 latency=1749ms procState=2 historyMsgCount=92 (msgIndex=6 wall=115ms seq=220 running=115ms late=1235ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=14 wall=52ms seq=228 running=52ms late=1446ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=67 wall=100ms seq=281 running=99ms binder=1ms late=2277ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=87 wall=66ms seq=301 running=68ms binder=1ms late=2789ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
12-13 22:28:27.841  4477  4477 I Timeline: Timeline: Activity_launch_request time:18029442
12-13 22:32:27.541  4477  4477 I Timeline: Timeline: Activity_launch_request time:18269142
12-13 22:32:58.838  4477  4477 I Timeline: Timeline: Activity_launch_request time:18300438
12-13 22:36:55.338  4477  4477 W Activity: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 1017ms
12-13 22:36:55.895  4477  4477 W Looper  : PerfMonitor longMsg : seq=1716 plan=22:36:54.300 late=1ms wall=1592ms running=91ms runnable=86ms io=62ms binder=202ms h=android.app.ActivityThread$H w=160 procState=16
12-13 22:36:55.908  4477  4477 W Looper  : PerfMonitor doFrame : time=11ms vsyncFrame=1206042 latency=1499ms procState=16 historyMsgCount=1 (msgIndex=1 wall=1592ms seq=1716 running=91ms runnable=86ms io=62ms binder=202ms late=1ms h=android.app.ActivityThread$H w=160)
--------- beginning of main
12-13 22:36:58.791  4477  8444 I System.out: [okhttp]:check permission begin!
12-13 22:36:58.791  4477  8444 I System.out: [okhttp]:not MMS!
12-13 22:36:58.791  4477  8444 I System.out: [okhttp]:not Email!
12-13 22:36:58.791  4477  8444 I System.out: [socket]:check permission begin!
12-13 22:36:58.822  4477  8444 I System.out: [OkHttp] sendRequest>>
12-13 22:36:58.822  4477  8444 I System.out: [OkHttp] sendRequest<<
12-13 22:36:59.123  4477  8444 I System.out: [okhttp]:check permission begin!
12-13 22:36:59.123  4477  8444 I System.out: [okhttp]:not MMS!
12-13 22:36:59.123  4477  8444 I System.out: [okhttp]:not Email!
12-13 22:36:59.123  4477  8444 I System.out: [socket]:check permission begin!
12-13 22:36:59.161  4477  8444 I System.out: [OkHttp] sendRequest>>
12-13 22:36:59.161  4477  8444 I System.out: [OkHttp] sendRequest<<
12-13 22:36:59.277  4477  4477 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@f5d75ce, this = DecorView@4d76a93[]
12-13 22:36:59.284  4477  4477 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@f5d75ce, this = DecorView@4d76a93[]
12-13 22:36:59.314  4477  4477 D SurfaceView: UPDATE null, mIsCastMode = false
12-13 22:36:59.323  4477  4526 I libMEOW_gift: ctx:0xb4000078d0562f40, ARC not Enabled.
12-13 22:36:59.324  4477  8289 D libMEOW : applied 1 plugins for [app.revanced.manager.flutter]:
12-13 22:36:59.325  4477  8289 D libMEOW :   plugin 1: [libMEOW_gift.so]:
12-13 22:36:59.336  4477  4477 D ViewRootImpl: setSurfaceViewCreated, created:true
12-13 22:36:59.338  4477  4477 D SurfaceView: UPDATE Surface(name=SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity)/@0xa8729cb, mIsProjectionMode = false
12-13 22:36:59.479  4477  8444 I System.out: [okhttp]:check permission begin!
12-13 22:36:59.479  4477  8444 I System.out: [okhttp]:not MMS!
12-13 22:36:59.479  4477  8444 I System.out: [okhttp]:not Email!
12-13 22:36:59.480  4477  8444 I System.out: [socket]:check permission begin!
12-13 22:36:59.515  4477  8444 I System.out: [OkHttp] sendRequest>>
12-13 22:36:59.515  4477  8444 I System.out: [OkHttp] sendRequest<<
12-13 22:37:04.507  8810  8810 W logcat  : type=1400 audit(0.0:49705): avc: denied { search } for name="mm" dev="sysfs" ino=6722 scontext=u:r:untrusted_app:s0:c144,c257,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
In the message
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by IoIxD** [comment]
The issue is related to having previously disabled the YouTube app and forgotten.
