### ISSUE TITLE
Erro ao patchear YouTube Music

### ISSUE THREAD

**Issue by Th3uzzz** [revanced/revanced-manager#588]
### Type

Error at runtime

### Bug description

![Screenshot_20221213-225413_ReVanced Manager](https://user-images.githubusercontent.com/99697790/207485815-e309bd52-75a2-4704-8fc0-ad658348ad7f.png)

### Steps to reproduce

Install YouTube Music from play store, open revanced select music app (Experimental patches active) Check all patch options except Micro G Support and you're done.

### Android version

13

### Manager version

0.0.48

### Target package name

com.google.android.apps.youtube.music

### Target package version.

![Screenshot_20221213-225957_crDroid Home](https://user-images.githubusercontent.com/99697790/207486611-53877d0b-b2d2-4774-b63d-65996f110b44.png)

### Installation type

Root

### Patches selected.

![Screenshot_20221213-230044_ReVanced Manager](https://user-images.githubusercontent.com/99697790/207486700-2cb5b0b5-9764-404e-b0b9-57f43192dc34.png)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
12-13 23:00:32.408 15022 15022 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
12-13 23:00:32.429 15022 15022 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10279; state: ENABLED
12-13 23:00:32.460 15022 15022 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
12-13 23:00:32.460 15022 15022 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
12-13 23:00:32.460 15022 15022 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
12-13 23:00:32.463 15022 15022 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-13 23:00:32.463 15022 15022 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-13 23:00:32.525 15022 15022 I AdrenoGLES: QUALCOMM build                   : 389f9e1, I4b4012dc33
12-13 23:00:32.525 15022 15022 I AdrenoGLES: Build Date                       : 11/12/20
12-13 23:00:32.525 15022 15022 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.10
12-13 23:00:32.525 15022 15022 I AdrenoGLES: Local Branch                     : 
12-13 23:00:32.525 15022 15022 I AdrenoGLES: Remote Branch                    : 
12-13 23:00:32.525 15022 15022 I AdrenoGLES: Remote Branch                    : 
12-13 23:00:32.525 15022 15022 I AdrenoGLES: Reconstruct Branch               : 
12-13 23:00:32.525 15022 15022 I AdrenoGLES: Build Config                     : S L 8.0.12 AArch64
12-13 23:00:32.529 15022 15022 I AdrenoGLES: PFP: 0x005ff11a, ME: 0x005ff066
12-13 23:00:32.695 15022 15047 I flutter : ReVanced API: Using CronetEngine + true
12-13 23:00:32.713 15022 15062 W SQLiteLog: (28) double-quoted string literal: "221F04DDCF86133E6D2E6344BA97034F"
12-13 23:00:32.713 15022 15062 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
12-13 23:00:32.875 15022 15048 I Gralloc4: mapper 4.x is not supported
12-13 23:00:32.875 15022 15048 W Gralloc3: mapper 3.x is not supported
12-13 23:00:32.878 15022 15048 W Gralloc4: allocator 4.x is not supported
12-13 23:00:32.878 15022 15048 W Gralloc3: allocator 3.x is not supported
12-13 23:00:32.879 15022 15048 I Gralloc2: Adding additional valid usage bits: 0x202000
12-13 23:00:32.883 15022 15062 W SQLiteLog: (28) double-quoted string literal: "129C81370C8C8A20B85E5575BDF12E85"
12-13 23:00:32.883 15022 15062 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
12-13 23:00:32.909 15022 15048 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2340, requested_size=1080x2340 buffer{size=1080x2277 transform=0}
12-13 23:00:32.956 15022 15048 E cutils-trace: Error opening trace file: No such file or directory (2)
12-13 23:00:32.961 15022 15067 D TrafficStats: tagSocket(108) with statsTag=0xffffffff, statsUid=-1
12-13 23:00:33.046 15022 15022 E SurfaceSyncer: Failed to find sync for id=0
12-13 23:00:33.047 15022 15022 E SurfaceSyncer: Failed to find sync for id=1
12-13 23:00:33.056 15022 15042 W Parcel  : Expecting binder but got null!
12-13 23:00:33.507 15022 15067 D TrafficStats: tagSocket(108) with statsTag=0xffffffff, statsUid=-1
12-13 23:00:33.962 15022 15067 D TrafficStats: tagSocket(108) with statsTag=0xffffffff, statsUid=-1
12-13 23:00:44.097 15022 15034 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
12-13 23:01:19.142 15022 15022 E SurfaceSyncer: Failed to find sync for id=0
12-13 23:01:19.142 15022 15022 E SurfaceSyncer: Failed to find sync for id=1
12-13 23:01:19.143 15022 15022 E SurfaceSyncer: Failed to find sync for id=2
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
An error occurred! Aborting
Error:
org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: Could not find entry classes.dex in /data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/a92185e0-7b50-11ed-9d0f-276a2ec2fd2e.bin.
	at org.jf.dexlib2.DexFileFactory$DexEntryFinder.findEntry(DexFileFactory.java:393)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:88)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:61)
	at app.revanced.patcher.util.patch.PatchBundle$Dex.loadPatches(PatchBundle.kt:71)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:176)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

![Screenshot_20221213-225413_ReVanced Manager](https://user-images.githubusercontent.com/99697790/207487409-7dfbcb92-102d-404f-aeb7-749f7cd00c46.png)

### Solution

none so far

### Additional context

I've always used this same method in previous revanced versions and never had such a problem. So far only in version 0.0.48

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by GitGoodBhaskar** [comment]
It's giving an error for me as well. 
For YouTube application.

**Comment by Zeynex** [comment]
Getting this for twitter and reddit [even tho i dont get the point in posting the application since it feels like a patcher issue]

**Comment by thegravity98** [comment]
> since it feels like a patcher issue]

Yeah started happening after Revanced patches V2.143.0

**Comment by oSumAtrIX** [comment]
Should be fixed now.

**Comment by thegravity98** [comment]
> Should be fixed now.

Release new update v0.0.50 ?

49 doesn't work/fix
