### ISSUE TITLE
Tiktok Patching failed

### ISSUE THREAD

**Issue by m7md7essen** [revanced/revanced-manager#598]
### Type

Error while running the manager

### Bug description

Tiktok patching failed

### Steps to reproduce

Step1: select an application

Step2: Select any patch

Step3: Click patch button

### Android version

12

### Manager version

0.0.51

### Target package name

com.zhiliaoapp.musically

### Target package version.

27.4.3

### Installation type

Non-root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: Hardcode offset changed.
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied predictive-back-gesture
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Failed to apply sim-spoof: 'sim-spoof' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~tYONif3roxQMdDvbcBW3kw==/app.revanced.manager.flutter-Dt4BHEn8xZxYQuDeymWM-A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~tYONif3roxQMdDvbcBW3kw==/app.revanced.manager.flutter-Dt4BHEn8xZxYQuDeymWM-A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: Hardcode offset changed.
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied predictive-back-gesture
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Failed to apply sim-spoof: 'sim-spoof' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~tYONif3roxQMdDvbcBW3kw==/app.revanced.manager.flutter-Dt4BHEn8xZxYQuDeymWM-A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~tYONif3roxQMdDvbcBW3kw==/app.revanced.manager.flutter-Dt4BHEn8xZxYQuDeymWM-A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QQDSIG/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Screenshots or videos

![Screenshot_2022-12-16-13-38-39-144_app revanced manager flutter](https://user-images.githubusercontent.com/32914068/208091340-892c0514-69c7-4686-9076-7dc6e84a1f8e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by tt-thoma** [comment]
Same bug as the YouTube patch one. The "Flutter" object is having problems.

**Comment by HeyItsJono** [comment]
I'm getting this on the latest manager version too, is there any fix available?

**Comment by m7md7essen** [comment]
I'm getting this on the latest manager version 0.0.52 too, is there any fix available?
