### ISSUE TITLE
bug: youtube error

### ISSUE THREAD

**Issue by TidalMist** [revanced/revanced-manager#613]
### Type

Error at runtime

### Bug description

youtube patch using revanced manager

I have another version of youtube revanced (rvx lite) installed

no google services

### Steps to reproduce

download revanced manager 0.0.52, install, grant install and ignore battery optimization permissions.
download youtube 17.49.37 nodpi from apkmirror, install.
in manager select youtube, recommended patches , remove custom branding patch,  patch..

### Android version

Model: DUA-LX9
Android Version: 10
Arch: armeabi-v7a

### Manager version

0.0.52

### Target package name

apkmirror YouTube

### Target package version.

17.49.37 nodpi

### Installation type

Non-root

### Patches selected.

recommended patches and removed custom branding

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
12-19 12:06:47.783 11487 11487 W HwApsManager: HwApsManagerService, registerCallback, start !
12-19 12:09:13.076 12637 12637 W HwApsManager: HwApsManagerService, registerCallback, start !
12-19 12:09:48.839 13237 13237 W HwApsManager: HwApsManagerService, registerCallback, start !
12-19 12:10:57.459 14176 14176 W HwApsManager: HwApsManagerService, registerCallback, start !
--------- beginning of main
12-19 12:19:13.483 14176 14189 I manager.flutte: Background young concurrent copying GC freed 974886(22MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 128MB/148MB, paused 522us total 107.823ms
12-19 12:19:13.931 14176 14189 I manager.flutte: Background young concurrent copying GC freed 974550(22MB) AllocSpace objects, 1(16KB) LOS objects, 13% free, 128MB/148MB, paused 609us total 102.643ms
12-19 12:19:18.820 14176 14189 I manager.flutte: Background young concurrent copying GC freed 970931(22MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 128MB/148MB, paused 535us total 109.462ms
12-19 12:19:21.485 14176 14189 I manager.flutte: Background young concurrent copying GC freed 959077(22MB) AllocSpace objects, 2(180KB) LOS objects, 13% free, 128MB/148MB, paused 481us total 103.723ms
12-19 12:19:24.224 14176 14189 I manager.flutte: Background young concurrent copying GC freed 959072(22MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 128MB/148MB, paused 614us total 103.502ms
12-19 12:19:26.536 14176 14189 I manager.flutte: Background young concurrent copying GC freed 948009(21MB) AllocSpace objects, 2(180KB) LOS objects, 13% free, 128MB/148MB, paused 406us total 100.323ms
12-19 12:19:29.374 14176 14189 I manager.flutte: Background young concurrent copying GC freed 721818(21MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 129MB/148MB, paused 532us total 109.947ms
12-19 12:19:29.800 14176 14189 I manager.flutte: Background young concurrent copying GC freed 816460(21MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 129MB/148MB, paused 505us total 109.883ms
12-19 12:19:31.877 14176 14189 I manager.flutte: Background young concurrent copying GC freed 738403(20MB) AllocSpace objects, 2(180KB) LOS objects, 12% free, 130MB/148MB, paused 427us total 101.421ms
12-19 12:19:37.410 14176 14189 I manager.flutte: Background young concurrent copying GC freed 900918(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 443us total 105.652ms
12-19 12:19:39.117 14176 14189 I manager.flutte: Background young concurrent copying GC freed 891032(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 129MB/148MB, paused 452us total 102.532ms
12-19 12:19:40.069 14176 14189 I manager.flutte: Background young concurrent copying GC freed 904658(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 557us total 107.313ms
12-19 12:19:40.551 14176 14189 I manager.flutte: Background young concurrent copying GC freed 896499(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 671us total 116.247ms
12-19 12:19:45.386 14176 14189 I manager.flutte: Background young concurrent copying GC freed 896418(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 545us total 107.700ms
12-19 12:19:50.659 14176 14189 I manager.flutte: Background young concurrent copying GC freed 893788(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 569us total 105.757ms
12-19 12:19:55.863 14176 14189 I manager.flutte: Background young concurrent copying GC freed 894664(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 524us total 107.874ms
12-19 12:20:01.167 14176 14189 I manager.flutte: Background young concurrent copying GC freed 851979(20MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 838us total 118.643ms
12-19 12:20:01.696 14176 14189 I manager.flutte: Background young concurrent copying GC freed 896008(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 502us total 102ms
12-19 12:20:02.605 14176 14189 I manager.flutte: Background young concurrent copying GC freed 885450(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 422us total 100.584ms
12-19 12:20:06.516 14176 14189 I manager.flutte: Background young concurrent copying GC freed 834731(20MB) AllocSpace objects, 1(36KB) LOS objects, 12% free, 129MB/148MB, paused 534us total 113.529ms
12-19 12:20:11.015 14176 14189 I manager.flutte: Background young concurrent copying GC freed 817338(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 129MB/148MB, paused 695us total 102.586ms
12-19 12:20:11.748 14176 14189 I manager.flutte: Background young concurrent copying GC freed 814613(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 129MB/148MB, paused 528us total 108.517ms
12-19 12:20:13.910 14176 14189 I manager.flutte: Background young concurrent copying GC freed 823552(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 129MB/148MB, paused 529us total 109.362ms
12-19 12:20:16.912 14176 14189 I manager.flutte: Background young concurrent copying GC freed 797968(19MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 129MB/148MB, paused 650us total 107.641ms
12-19 12:20:22.043 14176 14189 I manager.flutte: Background young concurrent copying GC freed 948283(20MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 130MB/148MB, paused 543us total 105.836ms
12-19 12:20:27.370 14176 14189 I manager.flutte: Background young concurrent copying GC freed 906014(20MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 130MB/148MB, paused 624us total 106.263ms
12-19 12:20:31.340 14176 14189 I manager.flutte: Background young concurrent copying GC freed 876161(20MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 455us total 102.077ms
12-19 12:20:37.762 14176 14189 I manager.flutte: Background young concurrent copying GC freed 896173(19MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 539us total 106.419ms
12-19 12:20:48.456 14176 14189 I manager.flutte: Background young concurrent copying GC freed 867625(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 130MB/148MB, paused 560us total 107.907ms
12-19 12:20:56.142 14176 14189 I manager.flutte: Background young concurrent copying GC freed 815724(19MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 130MB/148MB, paused 432us total 105.968ms
12-19 12:20:59.016 14176 14189 I manager.flutte: Background young concurrent copying GC freed 889676(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 130MB/148MB, paused 543us total 105.469ms
12-19 12:21:01.797 14176 14189 I manager.flutte: Background young concurrent copying GC freed 801259(18MB) AllocSpace objects, 19(684KB) LOS objects, 11% free, 132MB/148MB, paused 404us total 113.763ms
12-19 12:21:09.629 14176 14189 I manager.flutte: Background young concurrent copying GC freed 840236(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 526us total 105.660ms
12-19 12:21:14.467 14176 14189 I manager.flutte: Background young concurrent copying GC freed 838073(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 796us total 102.297ms
12-19 12:21:14.894 14176 14189 I manager.flutte: Background young concurrent copying GC freed 842585(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 652us total 123.292ms
12-19 12:21:20.171 14176 14189 I manager.flutte: Background young concurrent copying GC freed 837635(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 542us total 106.170ms
12-19 12:21:21.458 14176 14189 I manager.flutte: Background young concurrent copying GC freed 836573(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 699us total 112.511ms
12-19 12:21:25.445 14176 14189 I manager.flutte: Background young concurrent copying GC freed 834833(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 533us total 105.422ms
12-19 12:21:27.061 14176 14189 I manager.flutte: Background young concurrent copying GC freed 831020(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 656us total 100.740ms
12-19 12:21:30.720 14176 14189 I manager.flutte: Background young concurrent copying GC freed 837647(19MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 131MB/148MB, paused 548us total 106.737ms
12-19 12:21:36.715 14176 14189 I manager.flutte: Background young concurrent copying GC freed 828419(17MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 134MB/148MB, paused 439us total 175.159ms
12-19 12:21:42.447 14176 14189 I manager.flutte: Background young concurrent copying GC freed 776085(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 132MB/148MB, paused 404us total 100.624ms
12-19 12:21:46.391 14176 14189 I manager.flutte: Background young concurrent copying GC freed 777828(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 133MB/148MB, paused 595us total 105.608ms
12-19 12:21:52.871 14176 14189 I manager.flutte: Background young concurrent copying GC freed 775221(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 132MB/148MB, paused 447us total 102.685ms
12-19 12:22:02.124 14176 14189 I manager.flutte: Background young concurrent copying GC freed 771988(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 133MB/148MB, paused 540us total 104.663ms
12-19 12:22:07.459 14176 14189 I manager.flutte: Background young concurrent copying GC freed 778108(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 133MB/148MB, paused 537us total 103.157ms
12-19 12:22:18.191 14176 14189 I manager.flutte: Background young concurrent copying GC freed 768435(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 132MB/148MB, paused 648us total 103.526ms
12-19 12:22:28.450 14176 14189 I manager.flutte: Background young concurrent copying GC freed 752327(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 132MB/148MB, paused 545us total 108.027ms
12-19 12:22:28.975 14176 14189 I manager.flutte: Background young concurrent copying GC freed 728624(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 132MB/148MB, paused 510us total 104.586ms
12-19 12:22:30.122 14176 14189 I manager.flutte: Background young concurrent copying GC freed 754891(17MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 133MB/148MB, paused 392us total 101.340ms
12-19 12:24:31.483 14176 14176 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
12-19 12:25:48.954 14176 14199 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
12-19 12:25:52.087 14176 14176 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
12-19 12:25:52.095 14176 14176 W InputMethodManager: startInputReason = 1
12-19 12:26:00.392 14176 14199 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
12-19 12:26:04.759 14176 14199 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
12-19 12:26:06.198 14176 14176 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
12-19 12:26:06.199 14176 14176 W InputMethodManager: startInputReason = 1
12-19 12:26:12.407 14176 14199 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
12-19 12:26:26.303 16245 16245 I manager.flutte: Reinit property: dalvik.vm.checkjni= false
12-19 12:26:26.303 16245 16245 I manager.flutte: ReInitProperties: persist.vm.debug.dumpapi= false
12-19 12:26:26.305 16245 16245 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
12-19 12:26:26.336 16245 16264 I HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
12-19 12:26:26.336 16245 16264 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
12-19 12:26:26.363 16245 16245 I manager.flutte: QarthPatchMonintor::Init
12-19 12:26:26.363 16245 16245 I manager.flutte: 
12-19 12:26:26.363 16245 16245 I manager.flutte: QarthPatchMonintor::StartWatch
12-19 12:26:26.363 16245 16245 I manager.flutte: 
12-19 12:26:26.363 16245 16245 I manager.flutte: QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
12-19 12:26:26.363 16245 16245 I manager.flutte: 
12-19 12:26:26.363 16245 16245 I manager.flutte: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/app.revanced.manager.flutter
12-19 12:26:26.363 16245 16245 I manager.flutte: 
12-19 12:26:26.363 16245 16245 I manager.flutte: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
12-19 12:26:26.363 16245 16245 I manager.flutte: 
12-19 12:26:26.364 16245 16245 I manager.flutte: QarthPatchMonintor::Run
12-19 12:26:26.364 16245 16245 I manager.flutte: 
12-19 12:26:26.364 16245 16267 I manager.flutte: QarthPatchMonintor::Reading
12-19 12:26:26.364 16245 16267 I manager.flutte: 
12-19 12:26:26.364 16245 16267 I manager.flutte: QarthPatchMonintor::CheckNotifyEvent
12-19 12:26:26.364 16245 16267 I manager.flutte: 
12-19 12:26:26.364 16245 16267 I manager.flutte: QarthPatchMonintor::CheckNotifyEvent before read
12-19 12:26:26.364 16245 16267 I manager.flutte: 
12-19 12:26:26.365 16245 16264 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=app.revanced.manager.flutter#11984#256
12-19 12:26:26.365 16245 16264 I HwApiCacheMangerEx: apicache path=/storage/9016-4EF8 state=mounted key=app.revanced.manager.flutter#11984#256
12-19 12:26:26.365 16245 16264 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=0 newCnt=2
12-19 12:26:26.367 16245 16264 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=app.revanced.manager.flutter#11984#0
12-19 12:26:26.367 16245 16264 I HwApiCacheMangerEx: apicache path=/storage/9016-4EF8 state=mounted key=app.revanced.manager.flutter#11984#0
12-19 12:26:26.367 16245 16264 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=2 newCnt=2
12-19 12:26:26.371 16245 16264 I AwareBitmapCacher: init processName:app.revanced.manager.flutter pid=16245 uid=11984
12-19 12:26:26.454 16245 16245 W manager.flutter: type=1400 audit(0.0:27810): avc: denied { read } for pid=16245 name="max_map_count" dev="proc" ino=1287253 scontext=u:r:untrusted_app:s0:c192,c263,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
12-19 12:26:26.472 16245 16245 I iGraphics: [0020080c] pn: app.revanced.manager.flutter, p: 16245
12-19 12:26:26.472 16245 16245 I iGraphics: [0030050c] PV 10
12-19 12:26:26.473 16245 16245 I iGraphics: [0030050c] no element 'igfx'
12-19 12:26:26.473 16245 16245 I iGraphics: [0030050c] LoadCloudParams lib file success.
12-19 12:26:26.478 16245 16245 E GED     : Failed to get GED Log Buf, err(0)
12-19 12:26:26.564 16245 16245 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
12-19 12:26:26.564 16245 16245 I chatty  : uid=11984(app.revanced.manager.flutter) identical 1 line
12-19 12:26:26.565 16245 16245 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
12-19 12:26:26.573 16245 16245 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
12-19 12:26:26.609 16245 16245 I DecorView[]:  old windowMode:0 new windoMode:1
12-19 12:26:26.643 16245 16245 I DecorView[]:  old windowMode:1 new windoMode:1
12-19 12:26:26.663 16245 16287 W HiTouch_HiTouchSensor: depended package hiTouch does n't exist!
12-19 12:26:26.663 16245 16287 I HiTouch_HiTouchSensor: HiTouch restricted: system app HiTouch don't exist.
12-19 12:26:26.786 16245 16274 W Gralloc3: mapper 3.x is not supported
12-19 12:26:26.790 16245 16274 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-19 12:26:26.820 16245 16245 W InputMethodManager: startInputReason = 1
12-19 12:26:26.824 16245 16245 W InputMethodManager: startInputReason = 5
12-19 12:26:26.886 16245 16273 I flutter : ReVanced API: Using default engine + false
12-19 12:26:26.925 16245 16272 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=app.revanced.manager.flutter#11984#256
12-19 12:26:26.925 16245 16272 I HwApiCacheMangerEx: apicache path=/storage/9016-4EF8 state=mounted key=app.revanced.manager.flutter#11984#256
12-19 12:26:26.925 16245 16272 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=2 newCnt=2
12-19 12:26:30.282 16245 16245 W pool-6-thread-1: type=1400 audit(0.0:27811): avc: denied { read } for pid=16245 name="version" dev="proc" ino=4026532104 scontext=u:r:untrusted_app:s0:c192,c263,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0
12-19 12:26:30.436 16245 16245 I ConnectivityManager: requestNetwork and the calling app is: app.revanced.manager.flutter
12-19 12:26:30.446 16245 16245 I DecorView[]:  old windowMode:1 new windoMode:1
12-19 12:26:30.511 16245 16245 I HwViewRootImpl: removeInvalidNode jank list is null
12-19 12:26:30.618 16312 16312 W sh      : type=1400 audit(0.0:27812): avc: denied { read } for pid=16312 name="/" dev="dm-6" ino=44 scontext=u:r:untrusted_app:s0:c192,c263,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
12-19 12:26:30.638 16312 16312 I chatty  : uid=11984(app.revanced.manager.flutter) /system/bin/sh identical 1 line
12-19 12:26:30.658 16312 16312 W sh      : type=1400 audit(0.0:27814): avc: denied { read } for pid=16312 name="/" dev="dm-6" ino=44 scontext=u:r:untrusted_app:s0:c192,c263,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
12-19 12:26:30.682 16312 16312 W sh      : type=1400 audit(0.0:27815): avc: denied { read } for pid=16312 name="/" dev="dm-6" ino=44 scontext=u:r:untrusted_app:s0:c192,c263,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
12-19 12:26:30.702 16312 16312 W sh      : type=1400 audit(0.0:27816): avc: denied { read } for pid=16312 name="/" dev="dm-6" ino=44 scontext=u:r:untrusted_app:s0:c192,c263,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
12-19 12:26:31.513 16245 16245 I Hwaps   : APS: EventAnalyzed: initAPS: version is 10.1.0.18
12-19 12:26:31.513 16245 16245 I hwaps   : HwAps: JNI_OnLoad
12-19 12:26:31.525 16245 16245 W HwApsManager: HwApsManagerService, registerCallback, start !
12-19 12:26:31.527 16245 16245 I Choreographer: Skipped 59 frames!  The application may be doing too much work on its main thread.
12-19 12:26:31.540 16245 16268 I OpenGLRenderer: Davey! duration=1011ms; Flags=1, IntendedVsync=67501640118296, Vsync=67502635898938, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=67502638966330, AnimationStart=67502638987022, PerformTraversalsStart=67502639636868, DrawStart=67502645454637, SyncQueued=67502645697945, SyncStart=67502646038484, IssueDrawCommandsStart=67502646136484, SwapBuffers=67502648948484, FrameCompleted=67502651917176, DequeueBufferDuration=1622000, QueueBufferDuration=1761000, 
12-19 12:26:32.240 16245 16580 W manager.flutte: resources.arsc in APK '/data/app/com.huawei.docs-g-1jJSNyYk4tA9bTZ0TfmA==/base.apk' is compressed.
12-19 12:26:40.632 16245 16268 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
12-19 12:26:41.894 16245 16245 I HwViewRootImpl: removeInvalidNode jank list is null
12-19 12:26:41.914 16245 16245 W InputMethodManager: startInputReason = 1
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied always-autorepeat
Applied client-spoof
Applied comments
Applied custom-video-buffer
Applied custom-video-speed
Applied debugging
Applied disable-auto-captions
Applied disable-auto-player-popup-panels
Applied disable-fullscreen-panels
Applied disable-startup-shorts-player
Applied disable-zoom-haptics
Applied downloads
Applied enable-wide-searchbar
Applied general-ads
Applied hdr-auto-brightness
Applied hide-album-cards
Applied hide-artist-card
Applied hide-autoplay-button
Applied hide-captions-button
Applied hide-cast-button
Applied hide-create-button
Applied hide-crowdfunding-box
Applied hide-email-address
Applied hide-endscreen-cards
Applied hide-info-cards
Applied hide-my-mix
Applied hide-shorts-button
Applied hide-time-and-seekbar
Applied hide-video-buttons
Applied hide-watch-in-vr
Applied hide-watermark
Applied microg-support
Applied minimized-playback
Applied old-quality-layout
Applied open-links-directly
Applied premium-heading
Applied remember-video-quality
Applied remove-player-button-background
Applied return-youtube-dislike
Applied seekbar-tapping
Applied settings
Applied sponsorblock
Applied swipe-controls
Applied tablet-mini-player
Applied video-ads
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-cf9BcECm3PYwwDhYZTaJTw==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1533275584, --version-name, 17.49.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3619967938664486513.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:929)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-cf9BcECm3PYwwDhYZTaJTw==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1533275584, --version-name, 17.49.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3619967938664486513.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DTHCBO/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by TidalMist** [comment]
many months ago on the same smartphone I was able to patch YouTube

**Comment by Ushie** [comment]
#268
