### ISSUE TITLE
Getting error while patching

### ISSUE THREAD

**Issue by greatcoder88** [revanced/revanced-manager#618]
### Type

Error while running the manager

### Bug description

The patching is failing with following error:

Failed to apply downloads: 'downloads' depends on 'downloads-resource-patch' but the following error was raised:
'downloads-resource-patch' depends on settings but the following error was raised: Failed to resolve ThemeSetterAppFingerprint.
..
...
...

### Steps to reproduce

1. Updated the revanced manager to latest (as of now latest is 0.0.52)
2. Try patching the Youtube version 17.49.37 which is the supported version by revanced.
3. Selected patches
- Client Spoof
- Downloads
- General Ads
- Minimized Playback
- Old Quality Layout
- Open Links Directly
- Premium Heading
- Remember Video Quality
- RYD
- Seekbar tapping
- Sponsorblock
- Tablet mini player
- Video Ads

4. Click patch.

### Android version

Android 13

### Manager version

0.0.52

### Target package name

Youtube

### Target package version.

17.49.37

### Installation type

Root

### Patches selected.

- Client Spoof
- Downloads
- General Ads
- Minimized Playback
- Old Quality Layout
- Open Links Directly
- Premium Heading
- Remember Video Quality
- RYD
- Seekbar tapping
- Sponsorblock
- Tablet mini player
- Video Ads

### Device logs (exported using Manager settings).

```shell
12-21 20:40:37.318  6938  6938 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
12-21 20:40:37.319  6938  6938 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
12-21 20:40:37.319  6938  6938 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
12-21 20:40:37.320  6938  6938 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-21 20:40:37.320  6938  6938 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-21 20:40:37.371  6938  6938 W manager.flutter: type=1400 audit(0.0:124): avc: denied { read } for name="max_map_count" dev="proc" ino=324715 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: QUALCOMM build                   : 223000e821, I12e4aa4c5c
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: Build Date                       : 01/22/22
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.17
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: Local Branch                     :
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: Remote Branch                    :
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: Remote Branch                    :
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: Reconstruct Branch               :
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
12-21 20:40:37.384  6938  6938 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
12-21 20:40:37.390  6938  6938 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
12-21 20:40:37.590  6938  6960 I flutter : ReVanced API: Using CronetEngine + true
12-21 20:40:37.611  6938  6974 W SQLiteLog: (28) double-quoted string literal: "221F04DDCF86133E6D2E6344BA97034F"
12-21 20:40:37.611  6938  6974 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
12-21 20:40:37.630  6938  6938 I DynamiteModule: Considering local module com.google.android.gms.cronet_dynamite:0 and remote module com.google.android.gms.cronet_dynamite:1611
12-21 20:40:37.630  6938  6938 I DynamiteModule: Selected remote version of com.google.android.gms.cronet_dynamite, version >= 1611
12-21 20:40:37.630  6938  6938 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
12-21 20:40:37.639  6938  6938 W System  : ClassLoader referenced unknown path:
12-21 20:40:37.648  6938  6938 I DynamiteLoaderV2Impl: [71] com.google.android.gms.cronet_dynamite
12-21 20:40:37.655  6938  6938 W manager.flutter: ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/~~jauWthJJuwPTnS1LBN7X4w==/app.revanced.manager.flutter-wLTynCzKIEGPRJqcDOE8bQ==/base.apk*2113815621:/data/app/~~jauWthJJuwPTnS1LBN7X4w==/app.revanced.manager.flutter-wLTynCzKIEGPRJqcDOE8bQ==/base.apk!classes2.dex*2942373131:/data/app/~~jauWthJJuwPTnS1LBN7X4w==/app.revanced.manager.flutter-wLTynCzKIEGPRJqcDOE8bQ==/base.apk!classes3.dex*78547179])
12-21 20:40:37.668  6938  6938 I cr_CronetLibraryLoader: Cronet version: 108.0.5359.47, arch: aarch64
12-21 20:40:40.735  6938  6938 W pool-8-thread-1: type=1400 audit(0.0:125): avc: denied { read } for name="version" dev="proc" ino=4026532108 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
12-21 20:40:40.819  6938  6974 W SQLiteLog: (28) double-quoted string literal: "129C81370C8C8A20B85E5575BDF12E85"
12-21 20:40:40.819  6938  6974 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
12-21 20:40:40.832  6938  6961 I Gralloc4: Adding additional valid usage bits: 0x8202000
12-21 20:40:40.866  6938  6961 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2400, requested_size=1080x2400 buffer{size=1080x2334 transform=0}
12-21 20:40:40.868  6938  6938 E SurfaceSyncer: Failed to find sync for id=0
12-21 20:40:40.868  6938  6938 E SurfaceSyncer: Failed to find sync for id=1
12-21 20:40:40.889  6938  6955 W Parcel  : Expecting binder but got null!
12-21 20:40:41.271  7018  7018 W sh      : type=1400 audit(0.0:126): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:41.291  7018  7018 W sh      : type=1400 audit(0.0:127): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:41.311  7018  7018 W sh      : type=1400 audit(0.0:128): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:41.322  6938  6991 D TrafficStats: tagSocket(134) with statsTag=0xffffffff, statsUid=-1
12-21 20:40:41.321  7018  7018 W sh      : type=1400 audit(0.0:129): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:41.328  7018  7018 W sh      : type=1400 audit(0.0:130): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:42.190  6938  7080 I incfs   : Initial API level of the device: 30
12-21 20:40:42.191  6938  7080 W libc    : Access denied finding property "ro.incremental.enable"
12-21 20:40:42.191  6938  7080 I incfs   : ro.incremental.enable:
12-21 20:40:42.191  6938  7080 I incfs   : IncFs_Features: v1
12-21 20:40:42.903  6938  6991 D TrafficStats: tagSocket(420) with statsTag=0xffffffff, statsUid=-1
12-21 20:40:43.125  7018  7018 W sh      : type=1400 audit(0.0:136): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:43.141  7018  7018 W sh      : type=1400 audit(0.0:137): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:43.151  7018  7018 W sh      : type=1400 audit(0.0:138): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:43.161  7018  7018 W sh      : type=1400 audit(0.0:139): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:43.175  7018  7018 W sh      : type=1400 audit(0.0:140): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:40:43.648  6938  6974 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
12-21 20:40:43.648  6938  6974 W SQLiteLog: (28) double-quoted string literal: "8FCC77A68FB2404DA497375CF66FE6F5"
12-21 20:40:43.651  6938  6974 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
12-21 20:40:43.651  6938  6974 W SQLiteLog: (28) double-quoted string literal: "52E3D4117D358B6C1795391D7FC64275"
12-21 20:40:43.655  6938  6974 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
12-21 20:40:43.655  6938  6974 W SQLiteLog: (28) double-quoted string literal: "E0F22305E08784542046DAC7B897E6CE"
12-21 20:40:44.598  6938  6991 D TrafficStats: tagSocket(420) with statsTag=0xffffffff, statsUid=-1
12-21 20:40:45.948  6938  6991 D TrafficStats: tagSocket(420) with statsTag=0xffffffff, statsUid=-1
12-21 20:40:46.562  6938  6991 D TrafficStats: tagSocket(420) with statsTag=0xffffffff, statsUid=-1
12-21 20:41:41.575  6938  6938 E SurfaceSyncer: Failed to find sync for id=0
12-21 20:41:41.575  6938  6938 E SurfaceSyncer: Failed to find sync for id=1
12-21 20:41:41.575  6938  6938 E SurfaceSyncer: Failed to find sync for id=2
12-21 20:41:43.052  6938  6962 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: Error registering plugin root, com.gokul.root.RootPlugin
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: java.lang.IllegalStateException: The main shell was already created
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.internal.MainShell.setBuilder(MainShell.java:98)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.Shell.setDefaultBuilder(Shell.java:148)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at com.gokul.root.RootPlugin.onAttachedToEngine(RootPlugin.java:26)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:104)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1086)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at app.revanced.manager.flutter.MainActivity.configureFlutterEngine(MainActivity.kt:32)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8290)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8269)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1388)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.os.Looper.loopOnce(Looper.java:201)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.os.Looper.loop(Looper.java:288)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-21 20:41:43.673  6938  6938 E GeneratedPluginRegistrant: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
12-21 20:41:43.730  6938  7533 I flutter : ReVanced API: Using CronetEngine + true
12-21 20:41:43.775  6938  6938 W pool-13-thread-: type=1400 audit(0.0:160): avc: denied { read } for name="version" dev="proc" ino=4026532108 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
12-21 20:41:43.859  6938  7534 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5](f:0,a:0) rejecting buffer:active_size=1080x2400, requested_size=1080x2400 buffer{size=1080x2334 transform=0}
12-21 20:41:43.860  6938  6938 E SurfaceSyncer: Failed to find sync for id=0
12-21 20:41:43.860  6938  6938 E SurfaceSyncer: Failed to find sync for id=1
12-21 20:41:43.868  6938  6955 W Parcel  : Expecting binder but got null!
12-21 20:41:44.231  6938  7541 D TrafficStats: tagSocket(144) with statsTag=0xffffffff, statsUid=-1
12-21 20:41:44.288  7018  7018 W sh      : type=1400 audit(0.0:161): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:44.315  7018  7018 W sh      : type=1400 audit(0.0:162): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:44.325  7018  7018 W sh      : type=1400 audit(0.0:163): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:44.335  7018  7018 W sh      : type=1400 audit(0.0:164): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:45.030  6938  7541 D TrafficStats: tagSocket(132) with statsTag=0xffffffff, statsUid=-1
12-21 20:41:45.248  6938  6938 W pool-10-thread-: type=1400 audit(0.0:169): avc: denied { ioctl } for path="/data/app/~~FAWP_7uRbzuCfuAjtViaOw==/com.n3twork.tetris-drXNDdM3RDJ6lZ7ZA_racQ==/base.apk" dev="incremental-fs" ino=103789 ioctlcmd=0x6722 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
12-21 20:41:45.718  7018  7018 W sh      : type=1400 audit(0.0:170): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:45.728  7018  7018 W sh      : type=1400 audit(0.0:171): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:45.738  7018  7018 W sh      : type=1400 audit(0.0:172): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:45.745  7018  7018 W sh      : type=1400 audit(0.0:173): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
12-21 20:41:59.814  6938  6938 E SurfaceSyncer: Failed to find sync for id=0
12-21 20:41:59.814  6938  6938 E SurfaceSyncer: Failed to find sync for id=1
12-21 20:41:59.814  6938  6938 E SurfaceSyncer: Failed to find sync for id=2
12-21 20:41:59.869  6938  6938 E SurfaceSyncer: Failed to find sync for id=0
12-21 20:41:59.869  6938  6938 E SurfaceSyncer: Failed to find sync for id=1
12-21 20:41:59.869  6938  6938 E SurfaceSyncer: Failed to find sync for id=2
12-21 20:42:11.300  6938  6938 E SurfaceSyncer: Failed to find sync for id=0
12-21 20:42:11.300  6938  6938 E SurfaceSyncer: Failed to find sync for id=1
12-21 20:42:11.300  6938  6938 E SurfaceSyncer: Failed to find sync for id=2
12-21 20:42:11.300  6938  6938 E SurfaceSyncer: Failed to find sync for id=3
12-21 20:42:11.317  6938  6938 E SurfaceSyncer: Failed to find sync for id=0
12-21 20:42:11.317  6938  6938 E SurfaceSyncer: Failed to find sync for id=1
12-21 20:42:11.317  6938  6938 E SurfaceSyncer: Failed to find sync for id=2
12-21 20:42:11.317  6938  6938 E SurfaceSyncer: Failed to find sync for id=3
```

### Screenshots or videos

![Screenshot_20221220-195456_ReVanced Manager_2](https://user-images.githubusercontent.com/30318201/208942366-be48215a-eecd-4c7c-b07e-6520df7f8b39.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by icanrule** [comment]
I've had the same problem.  Then when I try to install with root it crashes immediately.

**Comment by bigyihsuan** [comment]
Also reported at https://github.com/revanced/revanced-patches/issues/1332

**Comment by bigyihsuan** [comment]
Workaround found: uninstall and reinstall Revanced Manager, and try patching again. The only problem is that the `settings` doesn't show in the patches list.

**Comment by Ushie** [comment]
This was a ReVanced Patches problem, not ReVanced Manager, as to why reinstalling fixed the problem, is because patches were no longer cached, so it got the latest patches

**Comment by hamzaarbeed** [comment]
This issue because you only chose recommended patches. that doesn't include theme 0.0.1
You want to include theme 0.0.1 in the patches to avoid this error

**Comment by hamzaarbeed** [comment]
Reinstall revanced manager. 
Don't give root access for the application.
The problem will be solved.

**Comment by datguypiko** [comment]
Not fixed. Reinstall nor clearing storage or cache helps.
