### ISSUE TITLE
tiktok error

### ISSUE THREAD

**Issue by Wjxfi** [ReVanced/revanced-manager#645]
### Type

Error while running the manager

### Bug description

tiktok aborted

### Steps to reproduce

download tiktok 

### Android version

12

### Manager version

0.0.52

### Target package name

com.zhiliaoapp.musically

### Target package version.

27.8.3

### Installation type

Non-root

### Patches selected.

the logs say

### Device logs (exported using Manager settings).

```shell
I don't know
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Applied downloads
Applied feed-filter
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied settings
Applied show-seekbar
Applied sim-spoof
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.OutOfMemoryError: Failed to allocate a 75873472 byte allocation with 25165824 free bytes and 59MB until OOM, target footprint 499236392, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3670)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
> Hey, why did you say "complete"? with no comment at all

Acknowledgements were not met.

**Comment by oSumAtrIX** [comment]
Simply checking them doesn't change it.
