### ISSUE TITLE
tiktok aborted

### ISSUE THREAD

**Issue by Wjxfi** [revanced/revanced-manager#647]
### Type

Error while running the manager

### Bug description

tiktok aborted

### Steps to reproduce

try to update the tiktok with the revanced manager

### Android version

12

### Manager version

0.0.52

### Target package name

27.8.3

### Target package version.

com.zhiliaoapp.musically

### Installation type

Non-root

### Patches selected.

Applied disable-login-requirement
Applied downloads
Applied feed-filter
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied settings
Applied show-seekbar
Applied sim-spoof

### Device logs (exported using Manager settings).

```shell
not available
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Applied downloads
Applied feed-filter
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied settings
Applied show-seekbar
Applied sim-spoof
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.OutOfMemoryError: Failed to allocate a 75873472 byte allocation with 25165824 free bytes and 59MB until OOM, target footprint 499236392, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3670)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Dupe/Not related to the ReVanced Manager

**Comment by leehwongxing** [comment]
> Dupe/Not related to the ReVanced Manager

why is it not related to Revanced Manager? There is 2 ways of patching, either CLI or Manager, and the Manager only allow ~256mb to alloc memory and its what keeps failing and CLI works for exact same patches on Tiktok and Manager failed

> ![image](https://user-images.githubusercontent.com/32384712/219875104-72820838-1a12-4d86-a5cc-2c662cf5e917.png)
> 
> I guess A SINGLE LINE that make the patching failed on Revanced Manager and successful on CLI, and the patched app indeed working.
