### ISSUE TITLE
bug: Error when patching applications

### ISSUE THREAD

**Issue by HelderRocket** [revanced/revanced-manager#703]
### Type

Error while running the manager

### Bug description

Every time I try to patch an application, it shows the normal patch progress, but after a few minutes it pauses and then proceeds to automatically abort. After that it doesn't advance from there. It happens to me every time I try to patch YT and YT Music apps, in the recommended versions, with the same architecture as my phone.

### Steps to reproduce

1. I download the version of the recommended application for the patches. 2. I proceed to use the tool and select that application. 3. I select all the available patches. 4. Proceed to click continue.

### Android version

8.1

### Manager version

0.0.56

### Target package name

com.google.android.apps.youtube.music

### Target package version.

5.39.52

### Installation type

Non-root

### Patches selected.

All.

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
02-14 12:09:46.699 10818 10818 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_5.39.52-53952230_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #119
02-14 12:09:46.700 10818 10818 W PackageParser: Unknown element under <application>: profileable at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_5.39.52-53952230_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #207
02-14 12:10:42.785 10818 10818 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_5.39.52-53952230_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #119
02-14 12:10:42.786 10818 10818 W PackageParser: Unknown element under <application>: profileable at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_5.39.52-53952230_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk Binary XML file line #207
--------- beginning of main
02-14 12:30:53.201 10818 11910 W OkHttpClient: A connection to https://sentry.rvcd.win/ was leaked. Did you forget to close a response body?
02-14 12:30:53.201 10818 11910 I chatty  : uid=10089(app.revanced.manager.flutter) OkHttp Connecti identical 5 lines
02-14 12:30:53.201 10818 11910 W OkHttpClient: A connection to https://sentry.rvcd.win/ was leaked. Did you forget to close a response body?
02-14 12:32:56.463 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:32:56.465 10818 10860 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
02-14 12:32:56.465 10818 10818 E BpSurfaceComposerClient: Failed to transact (-1)
02-14 12:32:56.465 10818 10818 E BpSurfaceComposerClient: Failed to transact (-1)
02-14 12:32:56.499 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:32:56.500 10818 10860 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
02-14 12:32:56.568 10818 10860 I System.out: Check isMmsSendPdu
02-14 12:32:56.568 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:32:56.574 10818 10860 I System.out: [OkHttp] sendRequest>>
02-14 12:32:56.574 10818 10860 I System.out: [OkHttp] sendRequest<<
02-14 12:32:57.540 12615 12615 W sh      : type=1400 audit(0.0:2200): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:57.600 12615 12615 I chatty  : uid=10089(app.revanced.manager.flutter) /system/bin/sh identical 2 lines
02-14 12:32:57.630 12615 12615 W sh      : type=1400 audit(0.0:2203): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:57.670 12615 12615 W sh      : type=1400 audit(0.0:2204): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:57.760 12615 12615 I chatty  : uid=10089(app.revanced.manager.flutter) /system/bin/sh identical 3 lines
02-14 12:32:57.800 12615 12615 W sh      : type=1400 audit(0.0:2208): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:57.860 12654 12654 W sh      : type=1400 audit(0.0:2209): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:57.930 12668 12668 W sh      : type=1400 audit(0.0:2210): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.000 12682 12682 W sh      : type=1400 audit(0.0:2211): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.070 12696 12696 W sh      : type=1400 audit(0.0:2212): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.140 12710 12710 W sh      : type=1400 audit(0.0:2213): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.220 12724 12724 W sh      : type=1400 audit(0.0:2214): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.290 12738 12738 W sh      : type=1400 audit(0.0:2215): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.360 12752 12752 W sh      : type=1400 audit(0.0:2216): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.430 12766 12766 W sh      : type=1400 audit(0.0:2217): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.500 12780 12780 W sh      : type=1400 audit(0.0:2218): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.570 12794 12794 W sh      : type=1400 audit(0.0:2219): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.640 12808 12808 W sh      : type=1400 audit(0.0:2220): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.720 12822 12822 W sh      : type=1400 audit(0.0:2221): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:32:58.741 10818 10818 I Choreographer: Skipped 75 frames!  The application may be doing too much work on its main thread.
02-14 12:32:58.844 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1463, previously 1563
02-14 12:32:58.844 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1342, previously 1344
02-14 12:32:58.844 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 236, previously 1574
02-14 12:32:58.872 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 607, previously 603
02-14 12:32:58.872 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 39, previously 37
02-14 12:32:58.872 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 178, previously 749
02-14 12:32:58.886 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 4594, previously 5404
02-14 12:32:58.886 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 2659, previously 2662
02-14 12:32:58.886 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 86, previously 153
02-14 12:32:58.886 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 379, previously 2688
02-14 12:32:58.886 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 271, previously 2430
02-14 12:32:58.918 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 692, previously 693
02-14 12:32:58.918 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1339, previously 1346
02-14 12:32:58.918 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 99, previously 97
02-14 12:32:58.918 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 3234, previously 6476
02-14 12:32:58.918 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 297, previously 965
02-14 12:33:04.671 10818 10836 E [EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
02-14 12:33:49.627 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:33:49.629 10818 10860 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
02-14 12:33:49.634 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:33:49.636 10818 10860 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
02-14 12:33:49.859 10818 10860 I System.out: Check isMmsSendPdu
02-14 12:33:49.859 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:33:49.867 10818 10860 I System.out: [OkHttp] sendRequest>>
02-14 12:33:49.867 10818 10860 I System.out: [OkHttp] sendRequest<<
02-14 12:33:50.277 10818 10836 E [EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
02-14 12:33:50.303 10818 10847 E [EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
02-14 12:35:10.222 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:35:10.228 10818 10860 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
02-14 12:35:10.232 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:35:10.233 10818 10860 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
02-14 12:35:10.241 10818 10818 E BpSurfaceComposerClient: Failed to transact (-1)
02-14 12:35:10.241 10818 10818 E BpSurfaceComposerClient: Failed to transact (-1)
02-14 12:35:10.307 10818 10860 I System.out: Check isMmsSendPdu
02-14 12:35:10.308 10818 10860 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
02-14 12:35:10.313 10818 10860 I System.out: [OkHttp] sendRequest>>
02-14 12:35:10.313 10818 10860 I System.out: [OkHttp] sendRequest<<
02-14 12:35:13.080 12906 12906 W sh      : type=1400 audit(0.0:2232): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.300 12906 12906 I chatty  : uid=10089(app.revanced.manager.flutter) /system/bin/sh identical 7 lines
02-14 12:35:13.330 12906 12906 W sh      : type=1400 audit(0.0:2240): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.400 12945 12945 W sh      : type=1400 audit(0.0:2241): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.470 12959 12959 W sh      : type=1400 audit(0.0:2242): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.540 12973 12973 W sh      : type=1400 audit(0.0:2243): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.600 12987 12987 W sh      : type=1400 audit(0.0:2244): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.670 13001 13001 W sh      : type=1400 audit(0.0:2245): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.730 13015 13015 W sh      : type=1400 audit(0.0:2246): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.800 13029 13029 W sh      : type=1400 audit(0.0:2247): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.890 13043 13043 W sh      : type=1400 audit(0.0:2248): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:13.960 13057 13057 W sh      : type=1400 audit(0.0:2249): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:14.020 13071 13071 W sh      : type=1400 audit(0.0:2250): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:14.090 13085 13085 W sh      : type=1400 audit(0.0:2251): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:14.160 13099 13099 W sh      : type=1400 audit(0.0:2252): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:14.220 13113 13113 W sh      : type=1400 audit(0.0:2253): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:14.331 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1463, previously 1563
02-14 12:35:14.331 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1342, previously 1344
02-14 12:35:14.331 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 236, previously 1574
02-14 12:35:14.352 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 607, previously 603
02-14 12:35:14.352 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 39, previously 37
02-14 12:35:14.352 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 178, previously 749
02-14 12:35:14.363 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 4594, previously 5404
02-14 12:35:14.363 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 2659, previously 2662
02-14 12:35:14.363 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 86, previously 153
02-14 12:35:14.363 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 379, previously 2688
02-14 12:35:14.363 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 271, previously 2430
02-14 12:35:14.392 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 692, previously 693
02-14 12:35:14.392 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1339, previously 1346
02-14 12:35:14.392 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 99, previously 97
02-14 12:35:14.392 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 3234, previously 6476
02-14 12:35:14.392 10818 11096 W ResourceType: ResTable_typeSpec entry count inconsistent: given 297, previously 965
02-14 12:35:15.330 13129 13129 W sh      : type=1400 audit(0.0:2254): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.360 13129 13129 W sh      : type=1400 audit(0.0:2255): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.560 13129 13129 I chatty  : uid=10089(app.revanced.manager.flutter) /system/bin/sh identical 6 lines
02-14 12:35:15.590 13129 13129 W sh      : type=1400 audit(0.0:2262): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.650 13167 13167 W sh      : type=1400 audit(0.0:2263): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.720 13181 13181 W sh      : type=1400 audit(0.0:2264): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.780 13195 13195 W sh      : type=1400 audit(0.0:2265): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.850 13209 13209 W sh      : type=1400 audit(0.0:2266): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.920 13223 13223 W sh      : type=1400 audit(0.0:2267): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:15.990 13237 13237 W sh      : type=1400 audit(0.0:2268): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:16.060 13251 13251 W sh      : type=1400 audit(0.0:2269): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:16.130 13265 13265 W sh      : type=1400 audit(0.0:2270): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:16.190 13279 13279 W sh      : type=1400 audit(0.0:2271): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:16.260 13293 13293 W sh      : type=1400 audit(0.0:2272): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:16.330 13307 13307 W sh      : type=1400 audit(0.0:2273): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:16.390 13321 13321 W sh      : type=1400 audit(0.0:2274): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
02-14 12:35:16.460 13335 13335 W sh      : type=1400 audit(0.0:2275): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Deleting existing resource cache directory
Decoding resources
Applied background-play
Applied codecs-unlock
Applied compact-header
Applied exclusive-audio-playback
Applied hide-get-premium
Applied minimized-playback-music
Applied music-microg-support
Applied music-video-ads
Applied predictive-back-gesture
Applied remove-screenshot-restriction
Applied spoof-wifi-connection
Applied tasteBuilder-remover
Applied upgrade-button-remover
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-67-CmC77siZg2hvZEQAUDQ==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 53952230, --version-name, 5.39.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL1227465784654761597.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:144)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:764)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-67-CmC77siZg2hvZEQAUDQ==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 53952230, --version-name, 5.39.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL1227465784654761597.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QMFAXG/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Screenshots or videos

![WhatsApp image 2023-02-14 at 12 30 38](https://user-images.githubusercontent.com/104467221/218813313-ce634c5b-53ce-45d9-8c92-896cedc1d986.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Your architecture is not supported as stated in the README of this repository
