### ISSUE TITLE
bug: It will crash when I grant the allow apps from this source and then back to the app

### ISSUE THREAD

**Issue by xuwanjin** [revanced/revanced-manager#713]
### Type

Error while running the manager

### Bug description

Bug: it will crash when I grant the permission: allow apps from this source .

### Steps to reproduce

1. adb install -r -t revanced-manager-v0.0.56.apk
2. open the revanced-manager app
3. grant the permission:  allow apps from this source .
4. back to the revanced-manager app, it will crash.

### Android version

Android OS: Android 11
device:realme X2

### Manager version

manager version: 0.0.56

### Target package name

No target package,

### Target package version.

No target package version.

### Installation type

Non-root

### Patches selected.

revanced-manager crashed.

### Device logs (exported using Manager settings).

```shell
02-25 10:34:48.379  1870  5244 E SyntheticPasswordManager: fromBytes: data = [B@c067441 data.length = 89
02-25 10:34:48.380 14267 14267 D AndroidRuntime: Shutting down VM
--------- beginning of crash
02-25 10:34:48.381 14267 14267 E AndroidRuntime: FATAL EXCEPTION: main
02-25 10:34:48.381 14267 14267 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 14267
02-25 10:34:48.381 14267 14267 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4772)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4810)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:254)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8243)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5362)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4755)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	... 11 more
02-25 10:34:48.381 14267 14267 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8464)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5355)
02-25 10:34:48.381 14267 14267 E AndroidRuntime: 	... 12 more
02-25 10:34:48.382  1870  2935 D ColorAppStartupMonitor: notifyUnstableAppInfo: Bundle[{unstableTime=1677292488381, reason=crash, userId=0, safecenter=unstable, exceptionMsg=Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference, exceptionClass=java.lang.NullPointerException, packageName=app.revanced.manager.flutter}]
02-25 10:34:48.382  3401  7049 D StartupManager: onUpdateUnstableRecord: unstable crash!
02-25 10:34:48.383  1870  3473 D OplusAmsUtilsFeatrue: detectExceptionsForOIDT type:0
02-25 10:34:48.383  1870  3473 D OplusManager: send on stamp success
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
May I know why you're using adb to install the manager app?

**Comment by ILoveOpenSourceApplications** [comment]
#633

**Comment by ILoveOpenSourceApplications** [comment]
Are you still having this issue or was it resolved?
