### ISSUE TITLE
Revanced Manager Aborting

### ISSUE THREAD

**Issue by sd535682** [revanced/revanced-manager#719]
### Type

Error at runtime

### Bug description

While compiling the Apk

### Steps to reproduce

Step 1 - Select YouTube apk from Internal
Step 2 - Apply all patches

### Android version

Android 13

### Manager version

Latest 0.56

### Target package name

YouTube apk 18.03.36

### Target package version.

YouTube apk 18.03.36

### Installation type

Non-root

### Patches selected.

ALL

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied always-autorepeat
Applied client-spoof
Applied comments
Applied copy-video-url
Applied custom-branding
Applied custom-video-buffer
Applied custom-video-speed
Applied debugging
Applied disable-auto-captions
Applied disable-fullscreen-panels
Applied disable-fullscreen-panels-auto-popup
Applied disable-shorts-on-startup
Applied disable-zoom-haptics
Applied downloads
Applied enable-wide-searchbar
Applied general-ads
Applied hdr-auto-brightness
Applied hide-album-cards
Applied hide-artist-card
Applied hide-autoplay-button
Applied hide-breaking-news-shelf
Applied hide-captions-button
Applied hide-cast-button
Applied hide-create-button
Applied hide-crowdfunding-box
Applied hide-email-address
Applied hide-endscreen-cards
Applied hide-info-cards
Applied hide-my-mix
Applied hide-player-buttons
Applied hide-seekbar
Applied hide-shorts-button
Applied hide-time
Applied hide-video-action-buttons
Applied hide-watch-in-vr
Applied hide-watermark
Applied microg-support
Applied minimized-playback
Applied old-quality-layout
Applied open-links-externally
Applied predictive-back-gesture
Applied premium-heading
Applied remember-playback-rate
Applied remember-video-quality
Applied remove-player-button-background
Applied remove-screenshot-restriction
Applied return-youtube-dislike
Applied seekbar-tapping
Applied sponsorblock
Applied spoof-app-version
Applied spoof-wifi-connection
Applied swipe-controls
Applied tablet-mini-player
Applied theme
Applied video-ads
Repacking patched apk
Compiling resources
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jf.dexlib2.dexbacked.DexBackedClassDef.getType()' on a null object reference
	at org.jf.dexlib2.dexbacked.DexBackedMethod.getDefiningClass(DexBackedMethod.java:120)
	at org.jf.dexlib2.writer.pool.PoolMethod.getDefiningClass(PoolMethod.java:64)
	at org.jf.dexlib2.base.reference.BaseMethodReference.compareTo(BaseMethodReference.java:66)
	at org.jf.dexlib2.base.reference.BaseMethodReference.compareTo(BaseMethodReference.java:43)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:40)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:27)
	at com.google.common.collect.Iterators$MergingIterator.lambda$new$0(Iterators.java:1324)
	at com.google.common.collect.Iterators$MergingIterator$$ExternalSyntheticLambda0.compare(Unknown Source:6)
	at java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:669)
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:645)
	at java.util.PriorityQueue.offer(PriorityQueue.java:344)
	at java.util.PriorityQueue.add(PriorityQueue.java:321)
	at com.google.common.collect.Iterators$MergingIterator.next(Iterators.java:1346)
	at org.jf.dexlib2.writer.DexWriter.writeAnnotationSetRefs(DexWriter.java:879)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:352)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

![Screenshot_20230228-025436_ReVanced_Manager](https://user-images.githubusercontent.com/61840607/221689911-ffac9eaa-5d44-4106-85b1-166ca3de5928.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone, report back which one caused it in an issue on the revanced-patches repository.
