### ISSUE TITLE
Youtube and YouTube music applications do not patch The patching process freezes

### ISSUE THREAD

**Issue by bozander** [revanced/revanced-manager#768]
### Type

Other

### Bug description

Unable to patch youtube and youtube music applications The process freezes at the stage indicated in the screenshot.

### Steps to reproduce

Step 1. Launch Revanced Manager
Step 2. Select patches
Step 3. Select the application to be patched
Strep 4. Start the patching process by pressing the corresponding button

### Android version

Android 13

### Manager version

0.0.57

### Target package name

com.google.android.youtube
com..google.android.apps.youtubemusic

### Target package version.

Youtube 18.12.35
Youtube Music 5.50.53

### Installation type

Root

### Patches selected.

![Screenshot_20230402-213434_ReVanced Manager](https://user-images.githubusercontent.com/61022739/229372302-b6b6fbc4-5213-42f7-8b79-ce1adc6b923d.png)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
04-02 20:19:32.580 22342 22342 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
04-02 20:19:32.634 22342 22342 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
04-02 20:19:32.634 22342 22342 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
04-02 20:19:32.634 22342 22342 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
04-02 20:19:32.658 22342 22342 W manager.flutter: type=1400 audit(0.0:710): avc: denied { read } for name="max_map_count" dev="proc" ino=294306 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: QUALCOMM build                   : db3d445dbc, Ia06b22fa1a
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: Build Date                       : 10/04/21
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: Local Branch                     : 
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: Remote Branch                    : 
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: Remote Branch                    : 
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: Reconstruct Branch               : 
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
04-02 20:19:32.666 22342 22342 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-02 20:19:32.669 22342 22342 I AdrenoGLES-0: PFP: 0x016dd093, ME: 0x00000000
04-02 20:19:32.725 22342 22360 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:19:32.769 22342 22365 I flutter : dynamic_color: Core palette detected.
04-02 20:19:32.796 22342 22366 I Gralloc4: Adding additional valid usage bits: 0x546c08202000
04-02 20:19:32.805 22342 22366 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2400, requested_size=1080x2400 buffer{size=1080x2337 transform=0}
04-02 20:19:32.810 22342 22342 E SurfaceSyncer: Failed to find sync for id=0
04-02 20:19:32.810 22342 22342 E SurfaceSyncer: Failed to find sync for id=1
04-02 20:19:32.813 22342 22360 W Parcel  : Expecting binder but got null!
04-02 20:19:32.826 22394 22394 W sh      : type=1400 audit(0.0:711): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:32.834 22394 22394 W sh      : type=1400 audit(0.0:712): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:32.838 22394 22394 W sh      : type=1400 audit(0.0:713): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:32.842 22394 22394 W sh      : type=1400 audit(0.0:714): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:36.857 22342 22360 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:19:36.859 22342 22342 E SurfaceSyncer: Failed to find sync for id=0
04-02 20:19:36.860 22342 22342 E SurfaceSyncer: Failed to find sync for id=1
04-02 20:19:36.860 22342 22342 E SurfaceSyncer: Failed to find sync for id=2
04-02 20:19:47.704 22342 22360 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:19:47.709 22342 22342 E SurfaceSyncer: Failed to find sync for id=0
04-02 20:19:47.709 22342 22342 E SurfaceSyncer: Failed to find sync for id=1
04-02 20:19:47.709 22342 22342 E SurfaceSyncer: Failed to find sync for id=2
04-02 20:19:47.709 22342 22342 E SurfaceSyncer: Failed to find sync for id=3
04-02 20:19:53.204 22342 22367 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: Error registering plugin root, com.gokul.root.RootPlugin
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: java.lang.IllegalStateException: The main shell was already created
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.internal.MainShell.setBuilder(MainShell.java:98)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.Shell.setDefaultBuilder(Shell.java:148)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at com.gokul.root.RootPlugin.onAttachedToEngine(RootPlugin.java:26)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:104)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1133)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at app.revanced.manager.flutter.MainActivity.configureFlutterEngine(MainActivity.kt:32)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:206)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:495)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8347)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8326)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.os.Looper.loopOnce(Looper.java:201)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.os.Looper.loop(Looper.java:288)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.main(ActivityThread.java:7925)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-02 20:19:54.806 22342 22342 E GeneratedPluginRegistrant: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
04-02 20:19:54.823 22342 22360 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:19:54.868 22342 22777 I flutter : dynamic_color: Core palette detected.
04-02 20:19:54.894 22394 22394 W sh      : type=1400 audit(0.0:1250): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:54.902 22394 22394 W sh      : type=1400 audit(0.0:1251): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:54.906 22394 22394 W sh      : type=1400 audit(0.0:1252): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:54.914 22394 22394 W sh      : type=1400 audit(0.0:1253): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:54.918 22394 22394 W sh      : type=1400 audit(0.0:1254): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:19:54.941 22342 22342 E SurfaceSyncer: Failed to find sync for id=0
04-02 20:19:54.941 22342 22342 E SurfaceSyncer: Failed to find sync for id=1
04-02 20:19:54.943 22342 22360 W Parcel  : Expecting binder but got null!
04-02 20:20:16.764 22342 22360 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:20:16.768 22342 22342 E SurfaceSyncer: Failed to find sync for id=0
04-02 20:20:16.768 22342 22342 E SurfaceSyncer: Failed to find sync for id=1
04-02 20:20:16.768 22342 22342 E SurfaceSyncer: Failed to find sync for id=2
04-02 20:20:40.394 22394 22394 W sh      : type=1400 audit(0.0:1258): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:20:40.402 22394 22394 W sh      : type=1400 audit(0.0:1259): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:20:40.406 22394 22394 W sh      : type=1400 audit(0.0:1260): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:20:40.410 22394 22394 W sh      : type=1400 audit(0.0:1261): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:20:40.414 22394 22394 W sh      : type=1400 audit(0.0:1262): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:20:40.873 22342 22777 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
04-02 20:20:40.873 22342 22777 E flutter : #0      PatcherAPI.runPatcher (package:revanced_manager/services/patcher_api.dart:209)
04-02 20:20:40.873 22342 22777 E flutter : <asynchronous suspension>
04-02 20:20:40.873 22342 22777 E flutter : #1      InstallerViewModel.runPatcher (package:revanced_manager/ui/views/installer/installer_viewmodel.dart:130)
04-02 20:20:40.873 22342 22777 E flutter : <asynchronous suspension>
04-02 20:20:40.873 22342 22777 E flutter : #2      InstallerViewModel.initialize (package:revanced_manager/ui/views/installer/installer_viewmodel.dart:67)
04-02 20:20:40.873 22342 22777 E flutter : <asynchronous suspension>
04-02 20:20:40.873 22342 22777 E flutter : 
04-02 20:21:04.027 23334 23334 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
04-02 20:21:04.051 23334 23334 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
04-02 20:21:04.051 23334 23334 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
04-02 20:21:04.052 23334 23334 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
04-02 20:21:04.074 23334 23334 W manager.flutter: type=1400 audit(0.0:1279): avc: denied { read } for name="max_map_count" dev="proc" ino=299214 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: QUALCOMM build                   : db3d445dbc, Ia06b22fa1a
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: Build Date                       : 10/04/21
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: Local Branch                     : 
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: Remote Branch                    : 
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: Remote Branch                    : 
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: Reconstruct Branch               : 
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
04-02 20:21:04.080 23334 23334 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-02 20:21:04.083 23334 23334 I AdrenoGLES-0: PFP: 0x016dd093, ME: 0x00000000
04-02 20:21:04.141 23334 23352 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:21:04.181 23334 23357 I flutter : dynamic_color: Core palette detected.
04-02 20:21:04.210 23334 23358 I Gralloc4: Adding additional valid usage bits: 0x546c08202000
04-02 20:21:04.214 23381 23381 W sh      : type=1400 audit(0.0:1280): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:21:04.218 23381 23381 W sh      : type=1400 audit(0.0:1281): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:21:04.222 23381 23381 W sh      : type=1400 audit(0.0:1282): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:21:04.226 23381 23381 W sh      : type=1400 audit(0.0:1283): avc: denied { read } for name="/" dev="dm-2" ino=2 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-02 20:21:04.254 23334 23334 E SurfaceSyncer: Failed to find sync for id=0
04-02 20:21:04.254 23334 23334 E SurfaceSyncer: Failed to find sync for id=1
04-02 20:21:04.258 23334 23352 W Parcel  : Expecting binder but got null!
```

### Screenshots or videos

![photo_2023-04-02_13-46-50](https://user-images.githubusercontent.com/61022739/229371976-cbb30230-b1fd-47a9-9c83-b819311b4bfe.jpg)

### Solution

No solution

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Attach a recording.

**Comment by bozander** [comment]
> Attach a recording.

[Video](https://drive.google.com/file/d/1-1Wsi0_Y_RBXk18mQs70ngl7CAp2w-Vh/view?usp=drivesdk)

**Comment by oSumAtrIX** [comment]
Looks like you are using different patches than ReVanced, in that case please open an issue in the respective repository.

**Comment by bozander** [comment]
The fact is that when using Revanded patches, the problem persists.  I gave a screenshot with patches from inotia00 only as an example

**Comment by oSumAtrIX** [comment]
Create a new issue with the default settings of ReVanced Manager.
