### ISSUE TITLE
bug: Patcher Aborting <title>

### ISSUE THREAD

**Issue by goggato** [revanced/revanced-manager#788]
### Type

Error while running the manager

### Bug description

I can't apply the patches on youtube, when I try to apply them it first says "applying patches..." but after all patches are applied it starts aborting, everytime 

### Steps to reproduce

In this sequence:
1.Download Micro G from this site: https://www.apkmirror.com/apk/team-vanced/microg-youtube-vanced/microg-youtube-vanced-0-2-24-220220-release/vanced-microg-0-2-24-220220-android-apk-download/
2.Download Revanced Manager [v0.0.57](https://github.com/revanced/revanced-manager/releases/tag/v0.0.57) from this site: https://github.com/revanced/revanced-manager/releases
3.Download Youtube version 18.04.40 from this site: https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-05-40-release/youtube-18-05-40-2-android-apk-download/
4.Select "Storage" in the bottom right, give Revanced access to your storage
5.

### Android version

8.1.0

### Manager version

0.0.57

### Target package name

Youtube

### Target package version.

18.05.40

### Installation type

Non-root

### Patches selected.

(11 patches)
custom video url
custom branding
custom video speed
debugging
downloads
general ads
microg support
remember playback speed
return youtube dislike
theme
video ads

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied copy-video-url
Applied custom-branding
Applied custom-video-speed
Applied debugging
Applied downloads
Applied general-ads
Applied microg-support
Applied remember-playback-speed
Applied return-youtube-dislike
Applied theme
Applied video-ads
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-aw3kcC5m4dDdBBKaY69mMA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1535903168, --version-name, 18.05.40, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4088949057691807094.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:212)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:22)
	at java.lang.Thread.run(Thread.java:764)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-aw3kcC5m4dDdBBKaY69mMA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1535903168, --version-name, 18.05.40, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4088949057691807094.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied copy-video-url
Applied custom-branding
Applied custom-video-speed
Applied debugging
Applied downloads
Applied general-ads
Applied microg-support
Applied remember-playback-speed
Applied return-youtube-dislike
Applied theme
Applied video-ads
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-aw3kcC5m4dDdBBKaY69mMA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1535903168, --version-name, 18.05.40, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4088949057691807094.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:212)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:22)
	at java.lang.Thread.run(Thread.java:764)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-aw3kcC5m4dDdBBKaY69mMA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1535903168, --version-name, 18.05.40, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4088949057691807094.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VHVJQY/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Additional context

:( I tried following a lot of guides on how to download revanced but nothing worked, this is the guide I followed for this try: https://www.reddit.com/r/revancedapp/comments/xlcny9/revanced_manager_guide_for_dummies/

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by badawoll** [comment]
Hate to be that guy, but the acknowledgements are there for a reason - you should do what they say, not just tick the box.

>  I have searched the existing issues and this is a new and no duplicate or related to another open issue.

A quick search through the issues shows [quite](https://github.com/revanced/revanced-manager/issues/473) [a](https://github.com/revanced/revanced-manager/issues/480) [few](https://github.com/revanced/revanced-manager/issues/561) [identical](https://github.com/revanced/revanced-manager/issues/727) [issues](https://github.com/revanced/revanced-manager/issues/703) (that's 5, with a minute of searching).

ARMv7 is still not supported. And the solution is still the same, patch on a PC using `revanced-cli`, or another device which runs on ARM64. I get it that it's not immediately clear what's going on, but... try to actually search next time, not just tick the box saying that you did :slightly_smiling_face: 

Also join the [discord community](http://revanced.app/discord), it has the most comprehensive FAQ list out there.
