### ISSUE TITLE
bug: exiting error

### ISSUE THREAD

**Issue by BhasuShubh** [revanced/revanced-manager#823]
### Type

Error at runtime

### Bug description

All the steps are finished but then at the end it shows error in exiting the step

### Steps to reproduce

I don't know how this is happening 

### Android version

Android version 12

### Manager version

0.0.57

### Target package name

youtube 

### Target package version.

18.15.40

### Installation type

Non-root

### Patches selected.

custom branding
Custom video speed
hide watermark
old quality layout
remember video quality
return youtube dislike
sponsorblock
vanced microG support
video ads

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied custom-branding
Applied custom-video-speed
Applied hide-watermark
Applied old-quality-layout
Applied remember-video-quality
Applied return-youtube-dislike
Applied sponsorblock
Applied vanced-microg-support
Applied video-ads
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/~~Jez_gwKukFQZJckq-eVX1Q==/app.revanced.manager.flutter-_h8o8MMWVWGFOtG8oGfLiQ==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537213888, --version-name, 18.15.40, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4101734782577066029.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:212)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:22)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/~~Jez_gwKukFQZJckq-eVX1Q==/app.revanced.manager.flutter-_h8o8MMWVWGFOtG8oGfLiQ==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537213888, --version-name, 18.15.40, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4101734782577066029.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WEFLRQ/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Screenshots or videos

![Screenshot_20230428-160124](https://user-images.githubusercontent.com/78732766/235162455-36e8e7ac-7a35-4d72-89cb-62d716f2a699.jpg)
![Screenshot_20230428-134319](https://user-images.githubusercontent.com/78732766/235162471-5a446339-3b31-4998-9630-61bcaddf117d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
ARMv7 devices aren't supported, you'll have to patch on another device
