### ISSUE TITLE
bug: crash

### ISSUE THREAD

**Issue by lUjek-Sh** [revanced/revanced-manager#827]
### Type

Error at runtime

### Bug description

Apk crash after open

### Steps to reproduce

Install and open

### Android version

Android 11

### Manager version

0.0.57

### Target package name

no

### Target package version.

no

### Installation type

Non-root

### Patches selected.

no

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
04-28 23:51:57.102  6201  6201 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
04-28 23:51:57.144  6201  6201 I Perf    : Connecting to perf service.
04-28 23:51:57.151  6201  6201 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-28 23:51:57.151  6201  6201 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-28 23:51:57.206  6201  6201 W manager.flutter: type=1400 audit(0.0:90285): avc: denied { read } for name="max_map_count" dev="proc" ino=1321985 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: QUALCOMM build                   : d7ad79a, I2f86ca99a8
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: Build Date                       : 06/13/21
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.12
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: Local Branch                     : mybranchebcc171e-87ea-f17a-bb69-1458d0b52af0
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r127-rel
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: Remote Branch                    : NONE
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: Build Config                     : S L 10.0.7 AArch64
04-28 23:51:57.225  6201  6201 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-28 23:51:57.233  6201  6201 I AdrenoGLES-0: PFP: 0x005ff114, ME: 0x005ff066
04-28 23:51:57.256  6201  6201 I TetheringManager: registerTetheringEventCallback:app.revanced.manager.flutter
--------- beginning of system
04-28 23:51:57.300  6201  6201 V Activity: mLastPackageName-app.revanced.manager.flutter.MainActivity
04-28 23:51:57.330  6201  6201 D PureDisplay: package-app.revanced.manager.flutter DYNAMIC_ORIGINAL_MODE open
04-28 23:51:57.703  6201  6243 W SQLiteLog: (28) double-quoted string literal: "221F04DDCF86133E6D2E6344BA97034F"
04-28 23:51:57.703  6201  6243 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
04-28 23:51:57.734  6201  6201 I DynamiteModule: Considering local module com.google.android.gms.cronet_dynamite:0 and remote module com.google.android.gms.cronet_dynamite:2411
04-28 23:51:57.734  6201  6201 I DynamiteModule: Selected remote version of com.google.android.gms.cronet_dynamite, version >= 2411
04-28 23:51:57.734  6201  6201 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
04-28 23:51:57.742  6201  6201 W System  : ClassLoader referenced unknown path: 
04-28 23:51:57.793  6201  6201 W linker  : Warning: "/data/user_de/0/com.google.android.gms/app_chimera/m/00000069/CronetDynamite.apk!/lib/arm64-v8a/libcronet.111.0.5563.55.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
04-28 23:51:57.802  6201  6201 I cr_CronetLibraryLoader: Cronet version: 111.0.5563.55, arch: aarch64
04-28 23:51:58.146  6201  6228 I flutter : dynamic_color: Dynamic color not detected on this device.
04-28 23:51:58.179  6201  6229 I Gralloc4: mapper 4.x is not supported
04-28 23:51:58.179  6201  6229 W Gralloc3: mapper 3.x is not supported
04-28 23:51:58.181  6201  6243 W SQLiteLog: (28) double-quoted string literal: "129C81370C8C8A20B85E5575BDF12E85"
04-28 23:51:58.181  6201  6243 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
04-28 23:51:58.226  6277  6277 W sh      : type=1400 audit(0.0:90286): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:51:58.286  6277  6277 I chatty  : uid=10314(app.revanced.manager.flutter) /system/bin/sh identical 4 lines
04-28 23:51:58.306  6277  6277 W sh      : type=1400 audit(0.0:90291): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:51:58.366  6201  6228 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_500_ec3a64e46e2ee5f546845582e1d5409107780cef55bc43b052ee962f9807aee6.ttf'
04-28 23:51:58.378  6201  6228 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_regular_d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf'
04-28 23:51:58.417  6201  6228 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Inter_regular_ca30a452e6f1961d934a7c782130cbcba3bbb9b611aae1dac1279d396350b35e.ttf'
04-28 23:51:58.907  6201  6201 I Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
04-28 23:51:58.934  6201  6223 I OpenGLRenderer: Davey! duration=726ms; Flags=0, IntendedVsync=38273572656171, Vsync=38274255989477, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=38274272531388, AnimationStart=38274272534045, PerformTraversalsStart=38274272535295, DrawStart=38274273728576, SyncQueued=38274274099878, SyncStart=38274274421701, IssueDrawCommandsStart=38274275520503, SwapBuffers=38274298384878, FrameCompleted=38274299307378, DequeueBufferDuration=2128646, QueueBufferDuration=204479, GpuCompleted=12, 
04-28 23:51:59.266  6666  6666 W sh      : type=1400 audit(0.0:90325): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:51:59.296  6680  6680 W sh      : type=1400 audit(0.0:90326): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:51:59.326  6694  6694 W sh      : type=1400 audit(0.0:90327): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:51:59.356  6708  6708 W sh      : type=1400 audit(0.0:90328): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:51:59.386  6722  6722 W sh      : type=1400 audit(0.0:90329): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:00.451  6201  6201 V Activity: onStop mLastPackageResume = false app.revanced.manager.flutter.MainActivity@2378425
04-28 23:52:02.554  6849  6849 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
04-28 23:52:02.612  6849  6849 I Perf    : Connecting to perf service.
04-28 23:52:02.620  6849  6849 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-28 23:52:02.621  6849  6849 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-28 23:52:02.686  6849  6849 W manager.flutter: type=1400 audit(0.0:90336): avc: denied { read } for name="max_map_count" dev="proc" ino=1321985 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: QUALCOMM build                   : d7ad79a, I2f86ca99a8
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: Build Date                       : 06/13/21
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.12
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: Local Branch                     : mybranchebcc171e-87ea-f17a-bb69-1458d0b52af0
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r127-rel
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: Remote Branch                    : NONE
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: Build Config                     : S L 10.0.7 AArch64
04-28 23:52:02.714  6849  6849 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-28 23:52:02.725  6849  6849 I AdrenoGLES-0: PFP: 0x005ff114, ME: 0x005ff066
04-28 23:52:02.756  6849  6849 I TetheringManager: registerTetheringEventCallback:app.revanced.manager.flutter
04-28 23:52:02.815  6849  6849 D AndroidRuntime: Shutting down VM
--------- beginning of crash
04-28 23:52:02.827  6849  6849 E AndroidRuntime: FATAL EXCEPTION: main
04-28 23:52:02.827  6849  6849 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 6849
04-28 23:52:02.827  6849  6849 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4439)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4471)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7701)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5010)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4426)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	... 11 more
04-28 23:52:02.827  6849  6849 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8501)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5003)
04-28 23:52:02.827  6849  6849 E AndroidRuntime: 	... 12 more
04-28 23:52:02.851  6849  6849 I Process : Sending signal. PID: 6849 SIG: 9
04-28 23:52:06.458  6896  6896 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
04-28 23:52:06.500  6896  6896 I Perf    : Connecting to perf service.
04-28 23:52:06.506  6896  6896 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-28 23:52:06.506  6896  6896 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-28 23:52:06.546  6896  6896 W manager.flutter: type=1400 audit(0.0:90337): avc: denied { read } for name="max_map_count" dev="proc" ino=1321985 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: QUALCOMM build                   : d7ad79a, I2f86ca99a8
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: Build Date                       : 06/13/21
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.12
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: Local Branch                     : mybranchebcc171e-87ea-f17a-bb69-1458d0b52af0
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r127-rel
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: Remote Branch                    : NONE
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: Build Config                     : S L 10.0.7 AArch64
04-28 23:52:06.574  6896  6896 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-28 23:52:06.585  6896  6896 I AdrenoGLES-0: PFP: 0x005ff114, ME: 0x005ff066
04-28 23:52:06.604  6896  6896 I TetheringManager: registerTetheringEventCallback:app.revanced.manager.flutter
04-28 23:52:06.646  6896  6896 V Activity: mLastPackageName-app.revanced.manager.flutter.MainActivity
04-28 23:52:06.670  6896  6896 D PureDisplay: package-app.revanced.manager.flutter DYNAMIC_ORIGINAL_MODE open
04-28 23:52:06.756  6896  6937 W SQLiteLog: (28) double-quoted string literal: "221F04DDCF86133E6D2E6344BA97034F"
04-28 23:52:06.756  6896  6937 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
04-28 23:52:06.816  6896  6922 I flutter : dynamic_color: Dynamic color not detected on this device.
04-28 23:52:06.842  6896  6923 I Gralloc4: mapper 4.x is not supported
04-28 23:52:06.843  6896  6923 W Gralloc3: mapper 3.x is not supported
04-28 23:52:06.844  6896  6937 W SQLiteLog: (28) double-quoted string literal: "129C81370C8C8A20B85E5575BDF12E85"
04-28 23:52:06.844  6896  6937 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
04-28 23:52:06.896  6949  6949 W sh      : type=1400 audit(0.0:90338): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:06.926  6949  6949 I chatty  : uid=10314(app.revanced.manager.flutter) /system/bin/sh identical 2 lines
04-28 23:52:06.946  6949  6949 W sh      : type=1400 audit(0.0:90341): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:06.956  6949  6949 W sh      : type=1400 audit(0.0:90342): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:06.986  6949  6949 I chatty  : uid=10314(app.revanced.manager.flutter) /system/bin/sh identical 2 lines
04-28 23:52:07.006  6949  6949 W sh      : type=1400 audit(0.0:90345): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:07.549  6896  6896 I Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
04-28 23:52:07.581  6896  6916 I OpenGLRenderer: Davey! duration=723ms; Flags=1, IntendedVsync=38282222786983, Vsync=38282906120289, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=38282914949458, AnimationStart=38282914952219, PerformTraversalsStart=38282914953364, DrawStart=38282919537531, SyncQueued=38282919865448, SyncStart=38282920231177, IssueDrawCommandsStart=38282920550864, SwapBuffers=38282945295604, FrameCompleted=38282946621281, DequeueBufferDuration=2187864, QueueBufferDuration=267500, GpuCompleted=0, 
04-28 23:52:14.316  7240  7240 W sh      : type=1400 audit(0.0:90363): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:14.386  7240  7240 I chatty  : uid=10314(app.revanced.manager.flutter) /system/bin/sh identical 3 lines
04-28 23:52:14.416  7240  7240 W sh      : type=1400 audit(0.0:90367): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:15.051  6896  6896 I DynamiteModule: Considering local module com.google.android.gms.cronet_dynamite:0 and remote module com.google.android.gms.cronet_dynamite:2411
04-28 23:52:15.051  6896  6896 I DynamiteModule: Selected remote version of com.google.android.gms.cronet_dynamite, version >= 2411
04-28 23:52:15.051  6896  6896 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
04-28 23:52:15.062  6896  6896 W System  : ClassLoader referenced unknown path: 
04-28 23:52:15.123  6896  6896 W linker  : Warning: "/data/user_de/0/com.google.android.gms/app_chimera/m/00000069/CronetDynamite.apk!/lib/arm64-v8a/libcronet.111.0.5563.55.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
04-28 23:52:15.133  6896  6896 I cr_CronetLibraryLoader: Cronet version: 111.0.5563.55, arch: aarch64
04-28 23:52:19.836  7528  7528 W sh      : type=1400 audit(0.0:90388): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:19.906  7528  7528 I chatty  : uid=10314(app.revanced.manager.flutter) /system/bin/sh identical 3 lines
04-28 23:52:19.926  7528  7528 W sh      : type=1400 audit(0.0:90392): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:20.866  7764  7764 W sh      : type=1400 audit(0.0:90411): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:20.916  7778  7778 W sh      : type=1400 audit(0.0:90412): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:24.286  7798  7798 W sh      : type=1400 audit(0.0:90413): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:24.306  7798  7798 W sh      : type=1400 audit(0.0:90414): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:24.416  7798  7798 I chatty  : uid=10314(app.revanced.manager.flutter) /system/bin/sh identical 5 lines
04-28 23:52:24.446  7798  7798 W sh      : type=1400 audit(0.0:90420): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
04-28 23:52:25.366  8056  8056 W sh      : type=1400 audit(0.0:90437): avc: denied { read } for name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app:s0:c58,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by hieuck** [comment]
đây là bug hay tính năng?

Tôi có Samsung S9 Android 10 Rooted

Vấn đề gặp phải - các thao tác thực hiện:
khi có bán vá mới (ví dụ 18.16.37), tôi cài đè bản YouTube nguyên bản (CHƯA MỞ LÊN), tôi tiến hành vá trong ReVanced, cài đặt với quyền Root và mở lên thì sẽ bị crash

tôi tìm được ra cách là trước khi vá bản YouTube ReVanced mới tôi sẽ mở bản YouTube nguyên gốc lên trước sau đó vá bản YouTube ReVanced mới thì sẽ hoạt động

Is this a bug or a feature?

I have Samsung S9 Android 10 Rooted

The problem encountered - the operations performed:
when a new patch is available (eg 18.16.37), I overwrite the original YouTube version (NOT OPENED), I patch it in ReVanced, install with Root privileges and open it, it will crash

I found a way that before patching the new YouTube ReVanced I will open the original YouTube version first then patch the new YouTube ReVanced and it will work
