### ISSUE TITLE
Due to this patch, ReVanced Manager is giving error while compiling ReVanced Music.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [revanced/revanced-manager#849]
### Type

Error while running the manager

### Bug description

![Screenshot_2023-05-05-20-08-52-16_a85b47aaa863e3bc831e16d29c27a79c](https://user-images.githubusercontent.com/91815107/236491092-c3d3ac5b-49bf-4484-9742-0de60b9f6954.jpg)
Due to this newly released patch called "Custom Branding Music Name", the manager is giving error while compiling ReVanced Music.

### Steps to reproduce

Just select "Custom Branding Music Name" in ReVanced Manger and try to patch YT Music apk.

### Android version

Realme 7 Pro, running on Realme UI 3.0 (Android 12).

### Manager version

0.0.57

### Target package name

com.google.android.apps.youtube.music

### Target package version.

5.55.53

### Installation type

Non-root

### Patches selected.

All the recommended patches + Custom Branding Music Name.

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied amoled
Applied background-play
Applied bitrate-default-value
Applied custom-branding-music-name
Applied disable-auto-captions
Applied enable-black-navbar
Applied enable-color-match-player
Applied enable-force-minimized-player
Applied enable-force-shuffle
Applied enable-opus-codec
Applied exclusive-audio-playback
Applied hide-button-shelf
Applied hide-carousel-shelf
Applied hide-category-bar
Applied hide-get-premium
Applied hide-music-ads
Applied hide-music-cast-button
Applied hide-new-playlist
Applied hide-playlist-card
Applied hide-taste-builder
Applied hide-upgrade-button
Applied minimized-playback-music
Applied music-microg-support
Applied optimize-resource-music
Applied patch-options
Applied remember-video-quality
Applied share-button-hook
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Os8MNrpluRv412SKirECmA==/app.revanced.manager.flutter-NzwsFJq3Mq1TOeUo4WNMkQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:212)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:22)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Os8MNrpluRv412SKirECmA==/app.revanced.manager.flutter-NzwsFJq3Mq1TOeUo4WNMkQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Unofficial patches.

**Comment by Kobewaxman** [comment]
@Aryan-Chauhan the patch is not recommended.
