### ISSUE TITLE
bug: Cannot select APK from storage

### ISSUE THREAD

**Issue by rollingmoai** [revanced/revanced-manager#85]
### Type

Error at runtime

### Branch

flutter

### Bug description

Selecting the APK from storage doesn't work. It does not select the app and nothing happens.

### Steps to reproduce

1. Get Youtube APK
2. Select the APK from storage
3. See nothing happening

### Relevant log output

```shell
--------- beginning of crash
09-15 09:44:40.969  8076  8076 E AndroidRuntime: FATAL EXCEPTION: main
09-15 09:44:40.969  8076  8076 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 8076
09-15 09:44:40.969  8076  8076 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=209, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4822)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4860)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2350)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:264)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8312)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=209, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5439)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4805)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	... 11 more
09-15 09:44:40.969  8076  8076 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8469)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5432)
09-15 09:44:40.969  8076  8076 E AndroidRuntime: 	... 12 more
--------- beginning of system
09-15 11:06:49.259  8159  8159 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=864.0, y[0]=2051.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214222778, downTime=214222778, deviceId=3, source=0x1002, displayId=0 }
09-15 11:06:49.963  8159  8159 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=922.0, y[0]=1438.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214223481, downTime=214223481, deviceId=3, source=0x1002, displayId=0 }
09-15 11:06:50.261  8159  8159 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=943.0, y[0]=1284.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214223779, downTime=214223779, deviceId=3, source=0x1002, displayId=0 }
09-15 11:06:51.114  8159  8159 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=764.0, y[0]=1365.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214224632, downTime=214224632, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:10.161  2387  2387 D AppResolutionTuner: loadTunerAppList + 
09-15 11:07:10.162  2387  2387 D AppResolutionTuner: loadTunerAppList - 
09-15 11:07:10.174  2387  2387 D OplusInputMethodUtil: init DEBUG to false, update DEBUG_IME to false
09-15 11:07:10.220  2387  2387 D ColorViewRootUtil: initSwipState, isDisplayCompatApp false
09-15 11:07:10.220  2387  2387 D ColorViewRootUtil: mScreenHeight 2340, mScreenWidth 1080
09-15 11:07:10.339  2387  2387 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 2340 getDecorView.DecorView@f2900de[MainActivity]
09-15 11:07:11.662  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=866.0, y[0]=2130.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214245180, downTime=214245180, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:12.448  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=807.0, y[0]=1568.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214245966, downTime=214245966, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:15.154  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=920.0, y[0]=1069.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214248673, downTime=214248673, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:15.635  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=932.0, y[0]=1129.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214249153, downTime=214249153, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:17.182  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=846.0, y[0]=1617.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214250701, downTime=214250701, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:18.077  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=801.0, y[0]=1343.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214251595, downTime=214251595, deviceId=3, source=0x1002, displayId=0 }
--------- beginning of main
09-15 11:07:19.339  2387  2387 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@fdec819, this = DecorView@f2900de[MainActivity]
09-15 11:07:19.931  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=491.0, y[0]=2035.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214253449, downTime=214253449, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:19.931  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=491.0, y[0]=2035.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214253449, downTime=214253449, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:19.931  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=491.0, y[0]=2035.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214253449, downTime=214253449, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:19.955  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=491.0, y[0]=2035.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214253474, downTime=214253449, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:19.955  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=491.0, y[0]=2035.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214253474, downTime=214253449, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:21.163  2387  2421 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 15, oppidx_max 15, oppidx_min 0
09-15 11:07:21.169  2387  2387 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@fdec819, this = DecorView@f2900de[MainActivity]
09-15 11:07:22.932  2387  2387 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@fdec819, this = DecorView@f2900de[MainActivity]
09-15 11:07:22.942  2387  2387 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@fdec819, this = DecorView@f2900de[MainActivity]
09-15 11:07:22.968  2387  2430 E libEGL  : Invalid file path for libcolorx-loader.so
09-15 11:07:22.968  2387  2430 I chatty  : uid=10631(app.revanced.manager.flutter) 1.raster identical 1 line
09-15 11:07:22.968  2387  2430 E libEGL  : Invalid file path for libcolorx-loader.so
09-15 11:07:23.789  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=809.0, y[0]=539.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214257308, downTime=214257308, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:23.789  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=809.0, y[0]=539.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214257308, downTime=214257308, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:23.790  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=809.0, y[0]=539.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214257308, downTime=214257308, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:23.821  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=809.0, y[0]=539.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214257340, downTime=214257308, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:23.822  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=809.0, y[0]=539.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214257340, downTime=214257308, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:24.717  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=799.0, y[0]=2086.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214258235, downTime=214258235, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:24.717  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=799.0, y[0]=2086.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214258235, downTime=214258235, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:24.718  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=799.0, y[0]=2086.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214258235, downTime=214258235, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:24.766  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=799.0, y[0]=2086.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214258284, downTime=214258235, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:24.766  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=799.0, y[0]=2086.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214258284, downTime=214258235, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:24.778  2387  2387 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-15 11:07:24.781  2387  2387 D FilePickerDelegate: Selected type */*
09-15 11:07:26.969  2387  2387 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@fdec819, this = DecorView@f2900de[MainActivity]
09-15 11:07:26.989  2387  2421 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 15, oppidx_max 15, oppidx_min 0
09-15 11:07:31.470  2387  2387 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@fdec819, this = DecorView@f2900de[MainActivity]
09-15 11:07:31.481  2387  2387 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@fdec819, this = DecorView@f2900de[MainActivity]
09-15 11:07:31.483  2387  3756 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A32151
09-15 11:07:31.515  2387  2430 E libEGL  : Invalid file path for libcolorx-loader.so
09-15 11:07:31.515  2387  2430 I chatty  : uid=10631(app.revanced.manager.flutter) 1.raster identical 1 line
09-15 11:07:31.515  2387  2430 E libEGL  : Invalid file path for libcolorx-loader.so
09-15 11:07:31.717  2387  3756 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_17.33.42-1531188672_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
09-15 11:07:31.718  2387  3756 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@8e0afb0]
09-15 11:07:32.441  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=875.0, y[0]=2090.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214265958, downTime=214265958, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:32.441  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=875.0, y[0]=2090.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214265958, downTime=214265958, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:32.442  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=875.0, y[0]=2090.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214265958, downTime=214265958, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:32.455  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=875.0, y[0]=2090.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214265974, downTime=214265958, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:32.456  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=875.0, y[0]=2090.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214265974, downTime=214265958, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.135  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=885.0, y[0]=1682.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214266654, downTime=214266654, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.136  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=885.0, y[0]=1682.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214266654, downTime=214266654, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.136  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=885.0, y[0]=1682.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214266654, downTime=214266654, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.176  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=894.0, y[0]=1467.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214266695, downTime=214266654, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.177  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=894.0, y[0]=1467.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214266695, downTime=214266654, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.930  2387  2387 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=792.0, y[0]=1396.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214267448, downTime=214267448, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.930  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=792.0, y[0]=1396.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214267448, downTime=214267448, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.930  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=792.0, y[0]=1396.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214267448, downTime=214267448, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.945  2387  2387 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=792.0, y[0]=1396.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214267464, downTime=214267448, deviceId=3, source=0x1002, displayId=0 }
09-15 11:07:33.946  2387  2387 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=792.0, y[0]=1396.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=214267464, downTime=214267448, deviceId=3, source=0x1002, displayId=0 }
```

**Comment by SebiAi** [comment]
+1
About:
```
Version: 0.0.5
Model: A063
Android Version: 12
Arch: arm64-v8a
```

**Comment by MicrosoftDid911** [comment]
Also happening on android 10, version 0.0.5

**Comment by yavko** [comment]
Same on android 12 `0.0.5`

**Comment by EncryptedCicada** [comment]
I have the same behaviour on Android 12.

**Comment by KrystianQur** [comment]
i have the same problem on Android 12

**Comment by Aunali321** [comment]
Try using 0.0.3 and see if it fixes it.

**Comment by SpookieGames** [comment]
Same problem after the latest update 

Version: 0.0.5
Model: 2201116SG
Android Version: 12
Arch: arm64-v8a

**Comment by rollingmoai** [comment]
> Try using 0.0.3 and see if it fixes it.

@Aunali321 Thanks, 0.0.3 worked.

**Comment by Sherman-Liu** [comment]
Can confirm, v0.0.6 from several minutes ago doesn't work either.

**Comment by Aunali321** [comment]
@ponces is there an issue with 0.0.6 too?

**Comment by yavko** [comment]
It works for me now!

**Comment by Sherman-Liu** [comment]
> @ponces is there an issue with 0.0.6 too?

Unfortunately, for me, yes.

**Comment by SpookieGames** [comment]
Now it works for me after the 0.0.6 update

**Comment by Sherman-Liu** [comment]
v0.0.6 still not working for me even after clean install, would this log help?
[revanced-manager_logcat_20220915170220520789.log](https://github.com/revanced/revanced-manager/files/9573693/revanced-manager_logcat_20220915170220520789.log)

**Comment by rollingmoai** [comment]
Now it works for me in 0.0.6, closing this issue.
