### ISSUE TITLE
bug: 360º videos crash patched YouTube

### ISSUE THREAD

**Issue by Krutyi-4el** [revanced/revanced-manager#850]
### Type

Error at runtime

### Bug description

Firstly, I apologize for creating this issue here (looks like this is not the place for it), I kind of got lost in repositories.

The issue happens when I try to open any 360º video with patched YouTube app.

### Steps to reproduce

1. Patch YouTube
2. Try to open any 360º video. Searching for "3D video 360" and scrolling also produces the crash.

### Android version

Android 10, RROS 8.6.9

### Manager version

1.0.0

### Target package name

com.google.android.youtube

### Target package version.

18.16.34

### Installation type

Root

### Patches selected.

{"com.google.android.youtube":["client-spoof","custom-branding","disable-shorts-on-startup","disable-zoom-haptics","downloads","hide-cast-button","hide-player-buttons","hide-player-overlay","minimized-playback","premium-heading","theme","video-ads","enable-debugging","custom-video-buffer"]}

### Device logs (exported using Manager settings).

```shell
(Manager's settings did not provide relevant logs, but I've managed to capture it myself with logcat. Here it is:)

05-05 21:46:55.357  6998 29808 E Ads     : Failed to connect to https://googleads.g.doubleclick.net/pagead/drt/m?is_lat=0. No DSID retrieved.
05-05 21:46:55.893  1508  1643 E system_server: Invalid ID 0x00000000.
05-05 21:46:55.953 28377 28377 E android.youtub: Not starting debugger since process cannot load the jdwp agent.
05-05 21:46:56.035 28377 28377 E android.youtub: expected 8 dex files but found 6
05-05 21:46:58.802   657  4338 E ResolverController: No valid NAT64 prefix (118, <unspecified>/0)
05-05 21:46:59.723   657  4379 E ResolverController: No valid NAT64 prefix (118, <unspecified>/0)
05-05 21:46:59.757   657  4378 E ResolverController: No valid NAT64 prefix (118, <unspecified>/0)
05-05 21:46:59.858   657  4389 E ResolverController: No valid NAT64 prefix (118, <unspecified>/0)
05-05 21:47:00.112   657  4401 E ResolverController: No valid NAT64 prefix (118, <unspecified>/0)
05-05 21:47:00.113   657  4402 E ResolverController: No valid NAT64 prefix (118, <unspecified>/0)
05-05 21:47:00.854  1508  1660 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
05-05 21:47:01.362 28377 28377 E libc    : Access denied finding property "persist.sys.theme.accentcolor"
05-05 21:47:01.362 28377 28377 E libc    : Access denied finding property "persist.sys.theme.gradientcolor"
05-05 21:47:02.400 28377 28377 E android.youtub: Resource 7f0409bc is a complex map type.
05-05 21:47:02.449 28377 28377 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
05-05 21:47:02.450 28377 28377 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
05-05 21:47:02.398  1508  1660 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
05-05 21:47:02.781  1508  2549 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
05-05 21:47:02.968 28377 28377 E YT.mlplayer: MedialibPlayer.stopVideo(), STOPPAGE_REASON_UNKNOWN
05-05 21:47:02.977  4409  4409 E e.process.gapp: Not starting debugger since process cannot load the jdwp agent.
05-05 21:47:03.256   915  1088 E statsd  : Found dropped events: 1 error -19 last atom tag 83 from uid 10216
05-05 21:47:03.271  1508  1648 E system_server: expected 8 dex files but found 6
05-05 21:47:03.583 28377 28377 E YT.mlplayer: MedialibPlayer.loadVideo(cpn=hY6pZtR_w1vSxv2y playWhenReady=true positionMs=0 playerEvents=[86] videoId=scrubbed volume=1.0)
05-05 21:47:03.585 28377  4385 E YT.qoe  : Pinging https://s.youtube.com/api/stats/qoe?cat=spherical&cl=528939226&ei=JU9VZJePMcuMv_IPtNCj6AI&event=streamingstats&feature=youtu.be&ns=yt&plid=AAX69rby78SaBH29&cpn=hY6pZtR_w1vSxv2y&cplatform=mobile&cbr=com.google.android.youtube&cff=SMALL_FORM_FACTOR&c=android&cmodel=Redmi%20Note%208T&cos=Android&soc=qcom%3Atrinket&csdk=29&cbrver=18.16.34&cver=18.16.34&cosver=10&cbrand=Xiaomi&qclc=ChBoWTZwWnRSX3cxdlN4djJ5GgA%3D%0A&sur=0.061:1&vis=0.070:0&conn=0.010:3&bat=0.009:0.820:1,0.591:0.820:1&vps=0.000:N&ctmp=du:used.12350084.268435456;avail.37133078528.52552495104;;inst.simple&vc=1537332672&seq=1&docid=(scrubbed) 
05-05 21:47:03.585 28377  4385 E YT.qoe  : &fexp=1714244,23858057,23888716,23918597,23946420,23964928,23966208,23983296,23998056,24004644,24007246,24034168,24036948,24077241,24078649,24080738,24117491,24120819,24132305,24135310,24140247,24143331,24162920,24166867,24181174,24186125,24187043,24187377,24197450,24211178,24219713,24227054,24230811,24232551,24241378,24248955,24255165,24255543,24255545,24262346,24265964,24267170,24271689,24285788,24288664,24290971,24291857,24390371,24390675,24396565,24397985,24404640,24407191,24409417,24420425,24429094,24429652,24436800,24439483,24440132,24440518,24440520,24442764,24443595,24446348,24449004,24451319,24451437,24453872,24455284,24457383,24458317,24458324,24458329,24458684,24458839,24459436,24465011,24466371,24468691,24468724,24469429,24471752,24472328,24475157,24477512,24477815,24479945,24480226,24483503,24483944,24485239,24485421,24487287,24487842,24488188,24488210,24492688,24494584,24494741,24495060,24495838,24498024,24498300,24499799,24511563,24511798,24515366,24515424,24516017,24516176,24517427,24518452,24519102,24519143,24530334,24531153,24532514,24532855,24535631,24537200,24538438,24539048,24550812,24551738,24552606,24552995,24553360,24553456,24553663,24554138,24555242,24555609,24555874,24556101,24556888,24556906,24557784,24559406,24559542,24690661,24691333,24693160,24695331,39321511,39322730,39323028,39323074,39323604,39323606,39793172,39795385,39796638,39799259,39801102,39802389,39802465,39802571,39803206,39803434,39804611,39805006,39805380,39805721,39807013,39808889,39809646,39811456,39811979,39812297,39813030,39813446,39813480,39813705,39813747,39814090,39814239,39814383,39814385,39814575,39814648,39815213,39816027,39816190,39816399,39816834,39817301,39817474,39817483,39817918,39818224,39818233,39818271,39818407,39818488,39818591,39818906,39818933,39818977,39818997,39819017,39819084,39819111,39819376,39819409,39819562,39819582,39819748,39819839,39819967,39820119,39820121,39820135,39820147,39820194,39820226,39820235,39820514,39820549,39820803,39820836,39820844,39820854,39820856,39820932,39820967,39821052,39821098,39821101,39821105,39821259,39821347,39821398,39821462,39821482,48910082,48910144
05-05 21:47:03.766 28377 28377 E AndroidRuntime: FATAL EXCEPTION: main
05-05 21:47:03.766 28377 28377 E AndroidRuntime: Process: com.google.android.youtube, PID: 28377
05-05 21:47:03.766 28377 28377 E AndroidRuntime: android.view.InflateException: Binary XML file line #5 in com.google.android.youtube:layout/ui_layer: Binary XML file line #5 in com.google.android.youtube:layout/ui_layer: Error inflating class ImageButton
05-05 21:47:03.766 28377 28377 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #5 in com.google.android.youtube:layout/ui_layer: Error inflating class ImageButton
05-05 21:47:03.766 28377 28377 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.google.android.youtube:drawable/rippleable with resource ID #0x7f080af9
05-05 21:47:03.766 28377 28377 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File  from drawable resource ID #0x7f080af9
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:888)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:671)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:916)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1028)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:1003)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.View.<init>(View.java:5388)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:195)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.widget.ImageButton.<init>(ImageButton.java:86)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.widget.ImageButton.<init>(ImageButton.java:82)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageButton.<init>(PG:3)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageButton.<init>(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at fx.ab(PG:17)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at fx.onCreateView(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:242)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at asro.c(PG:3)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at asro.<init>(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrUiLayoutImpl.<init>(PG:4)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrUiLayoutImpl.<init>(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrLayoutImpl.init(PG:4)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrLayoutImpl.<init>(PG:5)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrLayoutImpl.<init>(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrLayoutFactory.createFromCurrentPackage(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrLayoutFactory.create(PG:4)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrLayout.init(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.ndk.base.GvrLayout.<init>(PG:4)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.sdk.base.CardboardViewNativeImpl.<init>(PG:9)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.sdk.base.ImplementationSelector.createCardboardViewApi(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.sdk.base.GvrView.init(PG:4)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.google.vr.sdk.base.GvrView.<init>(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at abqp.<init>(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at abrf.a(PG:5)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at abrl.<init>(PG:4)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at aagn.E(PG:3)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at aagn.q(PG:10)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at zvx.k(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at zvx.r(PG:38)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at zvn.K(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at zvp.H(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at zvp.M(PG:44)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at aaau.M(PG:6)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at aabf.M(PG:3)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at aaaz.M(PG:4)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at zsa.s(PG:14)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at actk.aU(PG:42)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at actk.bi(PG:13)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at actk.bh(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at actk.D(PG:67)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at actk.aR(PG:53)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at actk.B(PG:14)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at acow.d(PG:7)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at acot.d(PG:17)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at ukz.d(PG:1)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at aclt.k(PG:5)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at acow.a(PG:10)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at acjl.h(PG:8)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at acjk.d(PG:2)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at acau.run(PG:6)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at afvi.run(PG:3)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7398)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: Caused by: java.io.FileNotFoundException: 
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.AssetManager.nativeOpenNonAsset(Native Method)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.AssetManager.openNonAsset(AssetManager.java:943)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:877)
05-05 21:47:03.766 28377 28377 E AndroidRuntime: 	... 73 more
05-05 21:47:03.945  1508  2273 E InputDispatcher: channel '20ba9e com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Can not reproduce, please exclude patches until the error is gone, report back which one causes it.
