### ISSUE TITLE
ReVanced Manager Aborting

### ISSUE THREAD

**Issue by ligisten** [revanced/revanced-manager#912]
### Type

Error while running the manager

### Bug description

I cant patch youtube without it saying it is aborting.

### Steps to reproduce

Step 1. Download latest ReVanced Manager Version
Step 2. Download Latest Recommended YouTube APK
Step 3. Patch Downloaded YouTube APK From Storage

### Android version

Android 13

### Manager version

1.30

### Target package name

YouTube

### Target package version.

v18.17.43

### Installation type

Non-root

### Patches selected.

![Screenshot_20230531-100700](https://github.com/revanced/revanced-manager/assets/135107884/376af61a-af7a-4ec6-ab08-c748f2b9651d)

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred! Aborting
Error:
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/Iterable;Ljava/lang/Iterable;Ljava/lang/Iterable;Lkotlin/jvm/functions/Function1;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprint; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprint' appears in /data/app/~~_tzpZ9r4HI3Fm8kIyK5pPA==/app.revanced.manager.flutter-CUZAz99GMv1sFrKZN8Gyww==/base.apk)
	at app.revanced.patches.shared.patch.integrations.AbstractIntegrationsPatch$IntegrationsFingerprint.<init>(AbstractIntegrationsPatch.kt:32)
	at app.revanced.patches.shared.patch.integrations.AbstractIntegrationsPatch$IntegrationsFingerprint.<init>(AbstractIntegrationsPatch.kt:28)
	at app.revanced.patches.youtube.misc.integrations.fingerprints.InitFingerprint.<init>(InitFingerprint.kt:5)
	at app.revanced.patches.youtube.misc.integrations.fingerprints.InitFingerprint.<clinit>(Unknown Source:2)
	at app.revanced.patches.youtube.misc.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:15)
	... 13 more
```

### Screenshots or videos

![Screenshot_20230531-100021](https://github.com/revanced/revanced-manager/assets/135107884/c62ed7fb-3dde-4b6d-afa6-fe50d90b83bf)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Axelen123** [comment]
Use official patches.
