### ISSUE TITLE
bug: patch button isn't working

### ISSUE THREAD

**Issue by m4xx1m** [revanced/revanced-manager#927]
### Type

Error while running the manager

### Bug description

I'm updated to 1.3.1 and I can't patch yt

### Steps to reproduce

patch yt

### Android version

13

### Manager version

1.3.1

### Target package name

YouTube 

### Target package version.

18.19.35

### Installation type

Root

### Patches selected.

:\

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
06-09 11:12:29.400 15439 15456 E OpenGLRenderer: Unable to match the desired swap behavior.
06-09 11:12:29.402 15439 15439 E SurfaceSyncer: Failed to find sync for id=0
06-09 11:12:29.402 15439 15439 E SurfaceSyncer: Failed to find sync for id=1
06-09 11:12:29.402 15439 15439 E SurfaceSyncer: Failed to find sync for id=2
06-09 11:12:31.770 15439 15461 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'List<String>'
06-09 11:12:31.770 15439 15461 E flutter : #0      PatcherViewModel.showArmv7WarningDialog.<anonymous closure> (package:revanced_manager/ui/views/patcher/patcher_viewmodel.dart:90)
06-09 11:12:31.770 15439 15461 E flutter : <asynchronous suspension>
06-09 11:12:31.770 15439 15461 E flutter : #1      PatcherViewModel.showArmv7WarningDialog (package:revanced_manager/ui/views/patcher/patcher_viewmodel.dart:89)
06-09 11:12:31.770 15439 15461 E flutter : <asynchronous suspension>
06-09 11:12:31.770 15439 15461 E flutter : 
06-09 11:12:32.863 15439 15461 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'List<String>'
06-09 11:12:32.863 15439 15461 E flutter : #0      PatcherViewModel.showArmv7WarningDialog.<anonymous closure> (package:revanced_manager/ui/views/patcher/patcher_viewmodel.dart:90)
06-09 11:12:32.863 15439 15461 E flutter : <asynchronous suspension>
06-09 11:12:32.863 15439 15461 E flutter : #1      PatcherViewModel.showArmv7WarningDialog (package:revanced_manager/ui/views/patcher/patcher_viewmodel.dart:89)
06-09 11:12:32.863 15439 15461 E flutter : <asynchronous suspension>
06-09 11:12:32.863 15439 15461 E flutter : 
06-09 11:12:40.316 15439 15456 E OpenGLRenderer: Unable to match the desired swap behavior.
06-09 11:12:40.318 15439 15439 E SurfaceSyncer: Failed to find sync for id=0
06-09 11:12:40.318 15439 15439 E SurfaceSyncer: Failed to find sync for id=1
06-09 11:12:40.318 15439 15439 E SurfaceSyncer: Failed to find sync for id=2
06-09 11:12:40.318 15439 15439 E SurfaceSyncer: Failed to find sync for id=3
06-09 11:13:07.913 15439 15456 E OpenGLRenderer: Unable to match the desired swap behavior.
06-09 11:13:07.920 15439 15439 E SurfaceSyncer: Failed to find sync for id=0
06-09 11:13:07.920 15439 15439 E SurfaceSyncer: Failed to find sync for id=1
06-09 11:13:07.920 15439 15439 E SurfaceSyncer: Failed to find sync for id=2
06-09 11:13:07.921 15439 15439 E SurfaceSyncer: Failed to find sync for id=3
06-09 11:13:07.921 15439 15439 E SurfaceSyncer: Failed to find sync for id=4
```

### Screenshots or videos

https://github.com/revanced/revanced-manager/assets/59927482/2a6022e2-a38b-4dfb-b33a-cf602196a9b7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
@EvadeMaster Could this be related to your PR?

**Comment by Niniou911** [comment]
i have the same bug

**Comment by Ushie** [comment]
Resolved in 7f7b14b

Please report back after testing v1.3.2, it should be released within the next 15 minutes

**Comment by Ushie** [comment]
v1.3.2 Is released!

**Comment by Niniou911** [comment]
it works now thank you
