### ISSUE TITLE
Reddit Spoof Wifi Connexion Doesn't Work

### ISSUE THREAD

**Issue by JuJust123** [revanced/revanced-manager#960]
### Type

Error while running the manager

### Bug description

I don't understand why the manager won't patch my version of Reddit, yet it's a version marked as supported... 

### Steps to reproduce

Launch a patch of Reddit with only the Patch "Spoof Wifi Connection"

### Android version

Latest version of Android 12 I believe

### Manager version

0.0.57

### Target package name

Reddit

### Target package version.

Last Version

### Installation type

Non-root

### Patches selected.

Spoof Wifi Connexion

### Device logs (exported using Manager settings).

```shell
ABORTING ...


Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborting
Error:
java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/patcher/extensions/InstructionExtensions;
	at app.revanced.util.patch.IMethodCall$DefaultImpls.replaceInvokeVirtualWithIntegrations(MethodCall.kt:58)
	at app.revanced.patches.all.connectivity.wifi.spoof.patch.SpoofWifiPatch$MethodCall.replaceInvokeVirtualWithIntegrations(SpoofWifiPatch.kt:28)
	at app.revanced.patches.all.connectivity.wifi.spoof.patch.SpoofWifiPatch.transform(SpoofWifiPatch.kt:206)
	at app.revanced.patches.all.connectivity.wifi.spoof.patch.SpoofWifiPatch.transform(SpoofWifiPatch.kt:15)
	at app.revanced.util.patch.AbstractTransformInstructionsPatch.execute(AbstractTransformInstructionsPatch.kt:61)
	at app.revanced.util.patch.AbstractTransformInstructionsPatch.execute(AbstractTransformInstructionsPatch.kt:13)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:321)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:22)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.extensions.InstructionExtensions
	... 15 more
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
--------- beginning of system
06-21 01:45:14.496  2149  2149 I Quality : Skipped: false 1 cost 19.740416 refreshRate 11254460 bit true processName app.revanced.manager.flutter
06-21 01:45:24.321  2149  2149 I Quality : Skipped: false 1 cost 32.638847 refreshRate 16666666 bit true processName app.revanced.manager.flutter
--------- beginning of main
06-21 01:46:09.159  2149 12760 D VRI[MainActivity]: dispatchAppVisibility visible:false
06-21 01:46:09.165  2149  2149 I SurfaceView: 224593914 surfaceDestroyed
06-21 01:46:09.172  2149  5856 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#7(BLAST Consumer)7](id:86500000007,api:1,p:2149,c:2149) disconnect: api 1
06-21 01:46:09.176  2149  2149 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#7(BLAST Consumer)7](id:86500000007,api:0,p:-1,c:2149) disconnect: api -1
06-21 01:46:09.176  2149  2149 D BufferQueueConsumer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#7(BLAST Consumer)7](id:86500000007,api:0,p:-1,c:2149) disconnect
06-21 01:46:09.177  2149  5827 D SurfaceView: 29605905positionLost mSurfaceControl is null return;
06-21 01:46:09.182  2149  5827 D BufferQueueProducer: [VRI[MainActivity]#6(BLAST Consumer)6](id:86500000006,api:1,p:2149,c:2149) disconnect: api 1
06-21 01:46:09.191  2149  2149 D BufferQueueConsumer: [VRI[MainActivity]#6(BLAST Consumer)6](id:86500000006,api:0,p:-1,c:2149) disconnect
06-21 01:46:09.193  2149  2149 D VRI[MainActivity]: setWindowStopped stopped:true
06-21 01:47:03.123  2149 13669 D VRI[MainActivity]: dispatchAppVisibility visible:true
06-21 01:47:03.133  2149  2149 D VRI[MainActivity]: setWindowStopped stopped:false
06-21 01:47:03.173  2149  2149 I Quality : Skipped: false 2 cost 28.122969 refreshRate 11261485 bit true processName app.revanced.manager.flutter
06-21 01:47:03.197  2149  2149 D BufferQueueConsumer: [](id:86500000008,api:0,p:-1,c:2149) connect: controlledByApp=false
06-21 01:47:03.199  2149  2149 E IPCThreadState: attemptIncStrongHandle(58): Not supported
06-21 01:47:03.199  2149  2149 E IPCThreadState: attemptIncStrongHandle(64): Not supported
06-21 01:47:03.200  2149  5827 D BufferQueueProducer: [VRI[MainActivity]#8(BLAST Consumer)8](id:86500000008,api:1,p:2149,c:2149) connect: api=1 producerControlledByApp=true
06-21 01:47:03.203  2149  2149 D BufferQueueConsumer: [](id:86500000009,api:0,p:-1,c:2149) connect: controlledByApp=false
06-21 01:47:03.205  2149  2149 I SurfaceView: 224593914 visibleChanged -- surfaceCreated 
06-21 01:47:03.206  2149  5856 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#9(BLAST Consumer)9](id:86500000009,api:1,p:2149,c:2149) connect: api=1 producerControlledByApp=true
06-21 01:47:03.207  2149  2149 I SurfaceView: 224593914 surfaceChanged -- format=4 w=1080 h=2400
06-21 01:47:03.213  2149  2149 E SurfaceSyncer: Failed to find sync for id=0
06-21 01:47:03.213  2149  2149 E SurfaceSyncer: Failed to find sync for id=1
06-21 01:47:03.213  2149  2149 E SurfaceSyncer: Failed to find sync for id=2
06-21 01:47:03.213  2149  2149 E SurfaceSyncer: Failed to find sync for id=3
06-21 01:47:03.213  2149  2149 E SurfaceSyncer: Failed to find sync for id=4
06-21 01:47:03.213  2149  2149 E SurfaceSyncer: Failed to find sync for id=5
06-21 01:47:03.213  2149  2149 D VRI[MainActivity]: registerCallbacksForSync syncBuffer=false
06-21 01:47:03.221  2149  5827 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
06-21 01:47:03.222  2149  2149 D VRI[MainActivity]: draw finished.
06-21 01:47:03.238  2149  2149 D VRI[MainActivity]: onFocusEvent true
06-21 01:47:21.976  2149  2149 D VRI[MainActivity]: onFocusEvent false
06-21 01:47:22.310  2149 13669 D VRI[MainActivity]: dispatchAppVisibility visible:false
06-21 01:47:22.313  2149  2149 I SurfaceView: 224593914 surfaceDestroyed
06-21 01:47:22.315  2149  5856 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#9(BLAST Consumer)9](id:86500000009,api:1,p:2149,c:2149) disconnect: api 1
06-21 01:47:22.319  2149  2149 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#9(BLAST Consumer)9](id:86500000009,api:0,p:-1,c:2149) disconnect: api -1
06-21 01:47:22.319  2149  2149 D BufferQueueConsumer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#9(BLAST Consumer)9](id:86500000009,api:0,p:-1,c:2149) disconnect
06-21 01:47:22.321  2149  5827 D SurfaceView: 145538201positionLost mSurfaceControl is null return;
06-21 01:47:22.322  2149  5827 D BufferQueueProducer: [VRI[MainActivity]#8(BLAST Consumer)8](id:86500000008,api:1,p:2149,c:2149) disconnect: api 1
06-21 01:47:22.359  2149  2149 D BufferQueueConsumer: [VRI[MainActivity]#8(BLAST Consumer)8](id:86500000008,api:0,p:-1,c:2149) disconnect
06-21 01:47:22.372  2149  2149 D VRI[MainActivity]: setWindowStopped stopped:true
06-21 01:47:28.547  2149 12478 D VRI[MainActivity]: dispatchAppVisibility visible:true
06-21 01:47:28.555  2149  2149 D VRI[MainActivity]: setWindowStopped stopped:false
06-21 01:47:28.633  2149  2149 D BufferQueueConsumer: [](id:8650000000a,api:0,p:-1,c:2149) connect: controlledByApp=false
06-21 01:47:28.633  2149  2149 E IPCThreadState: attemptIncStrongHandle(57): Not supported
06-21 01:47:28.633  2149  2149 E IPCThreadState: attemptIncStrongHandle(69): Not supported
06-21 01:47:28.635  2149  5827 D BufferQueueProducer: [VRI[MainActivity]#10(BLAST Consumer)10](id:8650000000a,api:1,p:2149,c:2149) connect: api=1 producerControlledByApp=true
06-21 01:47:28.642  2149  2149 D BufferQueueConsumer: [](id:8650000000b,api:0,p:-1,c:2149) connect: controlledByApp=false
06-21 01:47:28.642  2149  2149 I SurfaceView: 224593914 visibleChanged -- surfaceCreated 
06-21 01:47:28.643  2149  5856 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#11(BLAST Consumer)11](id:8650000000b,api:1,p:2149,c:2149) connect: api=1 producerControlledByApp=true
06-21 01:47:28.647  2149  2149 I SurfaceView: 224593914 surfaceChanged -- format=4 w=1080 h=2400
06-21 01:47:28.649  2149  2149 E SurfaceSyncer: Failed to find sync for id=0
06-21 01:47:28.649  2149  2149 E SurfaceSyncer: Failed to find sync for id=1
06-21 01:47:28.649  2149  2149 E SurfaceSyncer: Failed to find sync for id=2
06-21 01:47:28.649  2149  2149 E SurfaceSyncer: Failed to find sync for id=3
06-21 01:47:28.649  2149  2149 E SurfaceSyncer: Failed to find sync for id=4
06-21 01:47:28.649  2149  2149 E SurfaceSyncer: Failed to find sync for id=5
06-21 01:47:28.649  2149  2149 E SurfaceSyncer: Failed to find sync for id=6
06-21 01:47:28.649  2149  2149 D VRI[MainActivity]: registerCallbacksForSync syncBuffer=false
06-21 01:47:28.655  2149  5827 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
06-21 01:47:28.656  2149  2149 D VRI[MainActivity]: draw finished.
06-21 01:47:28.682  2149  2149 D VRI[MainActivity]: onFocusEvent true
```

### Screenshots or videos

![Screenshot_2023-06-21-01-42-10-83_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/revanced/revanced-manager/assets/131188363/f3dc3593-9eb7-4a42-bf93-7225383983a6)
![Screenshot_2023-06-21-01-42-15-51_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/revanced/revanced-manager/assets/131188363/6db7db60-0716-4082-86c8-12552448f90c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Update ReVanced Manager
