### ISSUE TITLE
original.apk: The source file doesn't  exist.

### ISSUE THREAD

**Issue by noga-dev** [ReVanced/revanced-manager#975]
### Type

Error at runtime

### Bug description

Started after latest update?

### Steps to reproduce

No special steps

### Android version

13

### Manager version

1.3.6

### Target package name

YouTube

### Target package version.

18.19.35

### Installation type

Root

### Patches selected.

Hide Ads (v0.0.1)

Return Youtube Dislike (v0.0.1)

Sponsorblock (v0.0.1)

Swipe Controls (v0.0.3)

Video Ads (v0.0.1)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
07-01 03:30:39.211  9576  9576 I manager.flutter: Using CollectorTypeCC GC.
07-01 03:30:39.213  9576  9576 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
07-01 03:30:39.229  9576  9576 I MessageMonitor: Load libmiui_runtime
07-01 03:30:39.241  9576  9576 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10311; state: ENABLED
07-01 03:30:39.257  9576  9593 D AppScoutStateMachine: 9576-ScoutStateMachinecreated
07-01 03:30:39.258  9576  9576 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~vLng0IBhVSrTVykvhsDjsQ==/app.revanced.manager.flutter-4vm3YoeYZ1Sfko5lJQOBnA==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~vLng0IBhVSrTVykvhsDjsQ==/app.revanced.manager.flutter-4vm3YoeYZ1Sfko5lJQOBnA==/lib/arm64:/data/app/~~vLng0IBhVSrTVykvhsDjsQ==/app.revanced.manager.flutter-4vm3YoeYZ1Sfko5lJQOBnA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
07-01 03:30:39.264  9576  9576 I Perf    : Connecting to perf service.
07-01 03:30:39.268  9576  9576 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
07-01 03:30:39.270  9576  9576 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
07-01 03:30:39.270  9576  9576 V GraphicsEnvironment: Updatable production driver is not supported on the device.
07-01 03:30:39.274  9576  9576 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkAppConfig: null
07-01 03:30:39.275  9576  9576 D manager.flutter: JNI_OnLoad success
07-01 03:30:39.275  9576  9576 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
07-01 03:30:39.277  9576  9576 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-01 03:30:39.278  9576  9576 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-01 03:30:39.286  9576  9576 D MiuiMultiWindowAdapter: MiuiMultiWindowAdapter::getFreeformVideoWhiteListInSystem::LIST_ABOUT_SUPPORT_LANDSCAPE_VIDEO = [com.hunantv.imgo.activity, com.tencent.qqlive, com.qiyi.video, com.hunantv.imgo.activity.inter, com.tencent.qqlivei18n, com.iqiyi.i18n, tv.danmaku.bili]
07-01 03:30:39.298  9576  9576 W libc    : Access denied finding property "ro.vendor.df.effect.conflict"
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: QUALCOMM build                   : db3d445dbc, Ia06b22fa1a
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: Build Date                       : 10/04/21
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: Local Branch                     : 
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: Remote Branch                    : 
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: Remote Branch                    : 
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: Reconstruct Branch               : 
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
07-01 03:30:39.342  9576  9576 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-01 03:30:39.344  9576  9576 I AdrenoGLES-0: PFP: 0x016dd093, ME: 0x00000000
07-01 03:30:39.357  9576  9607 W libc    : Access denied finding property "vendor.migl.debug"
07-01 03:30:39.392  9576  9576 D IS_CTS_MODE: false
07-01 03:30:39.392  9576  9576 D MULTI_WINDOW_ENABLED: false
07-01 03:30:39.397  9576  9576 D DecorView[]: getWindowModeFromSystem  windowmode is 1
--------- beginning of system
07-01 03:30:39.412  9576  9576 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ec6f775, reason: AppDarkModeEnable
07-01 03:30:39.413  9576  9576 D DecorView[]: getWindowModeFromSystem  windowmode is 1
07-01 03:30:39.413  9576  9576 D DecorView[]: updateDecorCaptionStatus windowMode is 1
07-01 03:30:39.438  9576  9576 D SurfaceView: UPDATE null, mIsCastMode = false
07-01 03:30:39.444  9576  9598 E libEGL  : pre_cache appList: ,,
07-01 03:30:39.450  9576  9576 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x4cd8a10, mIsProjectionMode = false
07-01 03:30:39.450  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:30:39.451  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:30:39.451  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:30:40.222  9576  9605 I flutter : dynamic_color: Core palette detected.
07-01 03:30:40.259  9576  9576 D DecorView[]: getWindowModeFromSystem  windowmode is 1
07-01 03:30:40.259  9576  9576 D DecorView[]: updateDecorCaptionStatus windowMode is 1
07-01 03:30:40.275  9576  9576 E SurfaceSyncer: Failed to find sync for id=0
07-01 03:30:40.281  9576  9598 D manager.flutter: MiuiProcessManagerServiceStub setSchedFifo
07-01 03:30:40.281  9576  9598 I MiuiProcessManagerImpl: setSchedFifo pid:9576, mode:3
07-01 03:30:40.288  9576  9598 W Parcel  : Expecting binder but got null!
07-01 03:30:40.310  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus true
07-01 03:30:40.310  9576  9576 I HandWritingStubImpl: refreshLastKeyboardType: 1
07-01 03:30:40.310  9576  9576 I HandWritingStubImpl: getCurrentKeyboardType: 1
07-01 03:30:40.315  9576  9576 I HandWritingStubImpl: getCurrentKeyboardType: 1
07-01 03:30:40.519  9622  9622 W sh      : type=1400 audit(0.0:246047): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c55,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-01 03:30:40.527  9622  9622 W sh      : type=1400 audit(0.0:246048): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c55,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-01 03:30:40.531  9622  9622 W sh      : type=1400 audit(0.0:246049): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c55,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-01 03:30:40.539  9622  9622 W sh      : type=1400 audit(0.0:246050): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c55,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-01 03:30:40.543  9622  9622 W sh      : type=1400 audit(0.0:246051): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c55,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
07-01 03:30:40.604  9576  9605 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot add to a fixed-length list
07-01 03:30:40.604  9576  9605 E flutter : #0      FixedLengthListMixin.addAll (dart:_internal/list.dart:36)
07-01 03:30:40.604  9576  9605 E flutter : #1      RootAPI.getInstalledApps (package:revanced_manager/services/root_api.dart:84)
07-01 03:30:40.604  9576  9605 E flutter : <asynchronous suspension>
07-01 03:30:40.604  9576  9605 E flutter : #2      ManagerAPI.getUnsavedApps (package:revanced_manager/services/manager_api.dart:330)
07-01 03:30:40.604  9576  9605 E flutter : <asynchronous suspension>
07-01 03:30:40.604  9576  9605 E flutter : #3      ManagerAPI.reAssessSavedApps (package:revanced_manager/services/manager_api.dart:385)
07-01 03:30:40.604  9576  9605 E flutter : <asynchronous suspension>
07-01 03:30:40.604  9576  9605 E flutter : 
07-01 03:30:41.865  9576  9576 W MirrorManager: this model don't Support
07-01 03:31:49.806  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:31:50.317  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus true
07-01 03:31:50.317  9576  9576 I HandWritingStubImpl: refreshLastKeyboardType: 1
07-01 03:31:50.318  9576  9576 I HandWritingStubImpl: getCurrentKeyboardType: 1
07-01 03:31:51.060  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:31:51.543  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:32:17.605  9576  9576 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ec6f775, reason: AppDarkModeEnable
07-01 03:32:17.616  9576  9593 D AppScoutStateMachine: 9576-ScoutStateMachinecreated
07-01 03:32:17.647  9576  9576 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x9d0add2, mIsProjectionMode = false
07-01 03:32:17.648  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:32:17.648  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:32:17.648  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:32:17.648  9576  9576 E SurfaceSyncer: Failed to find sync for id=0
07-01 03:32:17.648  9576  9576 E SurfaceSyncer: Failed to find sync for id=1
07-01 03:32:17.673  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus true
07-01 03:32:17.673  9576  9576 I HandWritingStubImpl: refreshLastKeyboardType: 1
07-01 03:32:17.673  9576  9576 I HandWritingStubImpl: getCurrentKeyboardType: 1
07-01 03:32:28.934  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:32:29.437  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:32:34.471  9576  9588 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
07-01 03:33:10.847  9576  9576 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ec6f775, reason: AppDarkModeEnable
07-01 03:33:10.878  9576  9725 D AppScoutStateMachine: 9576-ScoutStateMachinecreated
07-01 03:33:10.916  9576  9576 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x369808a, mIsProjectionMode = false
07-01 03:33:10.916  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:33:10.916  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:33:10.916  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:33:10.916  9576  9576 E SurfaceSyncer: Failed to find sync for id=0
07-01 03:33:10.916  9576  9576 E SurfaceSyncer: Failed to find sync for id=1
07-01 03:33:10.916  9576  9576 E SurfaceSyncer: Failed to find sync for id=2
07-01 03:33:10.941  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus true
07-01 03:33:10.941  9576  9576 I HandWritingStubImpl: refreshLastKeyboardType: 1
07-01 03:33:10.941  9576  9576 I HandWritingStubImpl: getCurrentKeyboardType: 1
07-01 03:33:13.657  9576  9621 E LongScreenshotUtils: inLargeScreen false
07-01 03:33:13.658  9576  9621 I LongScreenshotUtils:  focus:true
07-01 03:33:13.658  9576  9621 I LongScreenshotUtils: current ratio width:1.0, height:1.0
07-01 03:33:14.326  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:33:14.994  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:34:04.018  9576  9576 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ec6f775, reason: AppDarkModeEnable
07-01 03:34:04.034  9576  9592 D AppScoutStateMachine: 9576-ScoutStateMachinecreated
07-01 03:34:04.068  9576  9576 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xe233248, mIsProjectionMode = false
07-01 03:34:04.068  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:34:04.068  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:34:04.069  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:34:04.069  9576  9576 E SurfaceSyncer: Failed to find sync for id=0
07-01 03:34:04.069  9576  9576 E SurfaceSyncer: Failed to find sync for id=1
07-01 03:34:04.069  9576  9576 E SurfaceSyncer: Failed to find sync for id=2
07-01 03:34:04.069  9576  9576 E SurfaceSyncer: Failed to find sync for id=3
07-01 03:34:04.096  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus true
07-01 03:34:04.096  9576  9576 I HandWritingStubImpl: refreshLastKeyboardType: 1
07-01 03:34:04.096  9576  9576 I HandWritingStubImpl: getCurrentKeyboardType: 1
07-01 03:34:07.000  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus false
07-01 03:34:28.841  9576  9576 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for app.revanced.manager.flutter.MainActivity@ec6f775, reason: AppDarkModeEnable
07-01 03:34:28.853  9576 11174 D AppScoutStateMachine: 9576-ScoutStateMachinecreated
07-01 03:34:28.901  9576  9576 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x164c390, mIsProjectionMode = false
07-01 03:34:28.901  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:34:28.902  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:34:28.902  9576  9576 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
07-01 03:34:28.902  9576  9576 E SurfaceSyncer: Failed to find sync for id=0
07-01 03:34:28.902  9576  9576 E SurfaceSyncer: Failed to find sync for id=1
07-01 03:34:28.902  9576  9576 E SurfaceSyncer: Failed to find sync for id=2
07-01 03:34:28.902  9576  9576 E SurfaceSyncer: Failed to find sync for id=3
07-01 03:34:28.902  9576  9576 E SurfaceSyncer: Failed to find sync for id=4
07-01 03:34:28.928  9576  9576 D DecorView[]: onWindowFocusChanged hasWindowFocus true
07-01 03:34:28.928  9576  9576 I HandWritingStubImpl: refreshLastKeyboardType: 1
07-01 03:34:28.928  9576  9576 I HandWritingStubImpl: getCurrentKeyboardType: 1
```

### Screenshots or videos

![Screenshot_2023-06-28-23-19-56-950_app revanced manager flutter](https://github.com/revanced/revanced-manager/assets/2067558/3563d4b4-4b66-4422-8efd-0dffe9ae06f2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheAabedKhan** [comment]
Is YouTube listed in the `Installed` section in the `Dashboard` page? If yes, can you unpatch it first and then try to patch it? If no, can you uninstall and reinstall the suggested version of YouTube?

**Comment by noga-dev** [comment]
Doesn't appear in the dashboard's installed section. Uninstalled and reinstalled, no go.

**Comment by noga-dev** [comment]
Found solution on discord. File original.apk needed to be delete from data/adb/revanced. Will leave this issue open as this should be handled by the manager.

**Comment by kenethc** [comment]
> Found solution on discord. File `original.apk` needs to be deleted from `data/adb/revanced`.
> 
> Will leave this issue open as this should be handled by the manager.

This resolves the issue.  But then almost immediately I have the same issue w/ base.apk as well which I had to also delete.

**Comment by 1bergonzi1** [comment]
> 

Thank you!
